### PR TITLE
Creating INSTALL component 'runtime' to enable installing binaries only

### LINKED ISSUE #6188: Request for adding support for installing only runtime targets
I maintain the HPX Conda package (https://anaconda.org/conda-forge/hpx). Conda packages get built for various platforms (https://github.com/conda-forge/hpx-feedstock). After being built, they are available for people to install in their Conda environment, for example to be able to build their own software that depends on HPX and which provides a Python API.

To be able to **build a Conda package** that depends on HPX, it is necessary that there is a HPX Conda package containing all the HPX headers, libraries, CMake scripts, etc.

To be able to **use a Conda package** that depends on HPX, it is useful that there is an HPX Conda package containing only the shared libraries and likely some other files (e.g. `hpxrun.py` is useful). This makes the package smaller. These users don't need the static libraries, header files, etc.

I am submitting this issue because I think it is currently not possible to install only the runtime targets of HPX. If this is indeed the case, is support for installing only runtime targets be something that the HPX team is willing to add?

Once I can create seperate development and runtime packages I will update the HPX Conda packaging logic to create a `hpx-dev` and `hpx` package.

### PR DESCRIPTION
**Pull request by hkaiser**
Fixes #6188

### CODE REVIEW

**Comment by hkaiser** [comment]
@kordejong could you please verify if this fixes the issue you reported? The installation component to use for this is `runtime`.

**Comment by kordejong** [comment]
> @kordejong could you please verify if this fixes the issue you reported? The installation component to use for this is `runtime`.

Thanks, yes, the `runtime` install target works. I did notice two remaining static libraries in de runtime install directory:
`./lib/libhpx_init.a`
`./lib/libhpx_wrap.a`
Other than that it looks good to me.

**Comment by hkaiser** [comment]
> > @kordejong could you please verify if this fixes the issue you reported? The installation component to use for this is `runtime`.
> 
> Thanks, yes, the `runtime` install target works. I did notice two remaining static libraries in de runtime install directory: `./lib/libhpx_init.a` `./lib/libhpx_wrap.a` Other than that it looks good to me.

Ok, good point. I will remove those from the 'runtime' target.

**Comment by hkaiser** [comment]
bors merge

**Pull request merged**
