### PR TITLE
Update LCI parcelport to LCI v1.7.1

### PR DESCRIPTION
**Pull request by JiakunYan**
Accommodate a breaking change in LCI v1.7.1, where FindFabric.cmake no longer exists.

LCI v1.7.1 removes all compilation warning messages.

The newly added LCI_USE_AVX option fixes a few segfaults when running Octotiger on Perlmutter.

Also add a new cmake variable, HPX_WITH_PARCELPORT_LCI_BACKEND, to replace the old LCI_SERVER.

### CODE REVIEW

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by hkaiser** [comment]
@JiakunYan, this is already your second PR to the HPX repository! As a 'thank you' we would like to offer a free STE||AR-Group t-shirt to you. If you are interested in receiving one, please get back to me directly so we can set up the delivery.

**Comment by JiakunYan** [comment]
@hkaiser I think this PR is ready to be merged.

**Comment by JiakunYan** [comment]
@hkaiser I think this PR is ready to be merged.

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by hkaiser** [comment]
bors merge

**Pull request merged**
