### PR TITLE
Fixing timed_executor specializations of customization points

### PR DESCRIPTION
**Pull request by hkaiser**
This is a leftover from #5331

### CODE REVIEW

**Comment by hkaiser** [comment]
retest lsu

**Review by msimberg — DISMISSED** [review]
Looks good to me! The thread executors files were just removed in #5356.

**Review by aurianer — APPROVED** [review]
LGTM thanks!

**Comment by hkaiser** [comment]
> The thread executors files were just removed in #5356.

I'll adapt this PR accordingly, thanks!

**Pull request merged**
