### PR TITLE
Fixing dangling reference in serialization of non-default constructible types

### LINKED ISSUE #5886: Segfault when serializing non default constructible class with stl containers data members
## Expected Behavior

Minimal working example trying to send class instances across nodes. The class is not default constructible and has stl containers data members such as a vector<int> and a string. The expected behavior is to provide the class instance as an argument to an action and return it.

## Actual Behavior

The class instance is successfully serialized  to the other node as printed out in the first 4 lines of the logs below, however, a segfault occurs within HPX at some point. The segfault only occurs when the type is not default constructible and has stl containers data members; if the serialized type is default constructible or has no stl containers, then there is no segfault.

```
Action executed on locality nid00171#0(0) with 64 threads. Event: evtid(6,4,6,9,2,7,1,10,10,3,5,3,5,5,9)
Action executed on locality nid00172#1(1) with 64 threads. Event: evtid(7,4,3,9,7,10,6,4,5,8,10,5,5,8,5)
Got result from future: evtid(6,4,6,9,2,7,1,10,10,3,5,3,5,5,9)
Got result from future: evtid(7,4,3,9,7,10,6,4,5,8,10,5,5,8,5)
{config}:
Core library:
  HPX_AGAS_LOCAL_CACHE_SIZE=4096
  HPX_HAVE_MALLOC=tcmalloc
  HPX_PARCEL_MAX_CONNECTIONS=512
  HPX_PARCEL_MAX_CONNECTIONS_PER_LOCALITY=4
  HPX_PREFIX (configured)=
  HPX_PREFIX=/global/common/software/atlas/hpx

  HPX_FILESYSTEM_WITH_BOOST_FILESYSTEM_COMPATIBILITY=OFF
  HPX_ITERATOR_SUPPORT_WITH_BOOST_ITERATOR_TRAVERSAL_TAG_COMPATIBILITY=OFF
  HPX_WITH_AGAS_DUMP_REFCNT_ENTRIES=OFF
  HPX_WITH_APEX=OFF
  HPX_WITH_ASYNC_MPI=OFF
  HPX_WITH_ATTACH_DEBUGGER_ON_TEST_FAILURE=OFF
  HPX_WITH_AUTOMATIC_SERIALIZATION_REGISTRATION=ON
  HPX_WITH_COROUTINE_COUNTERS=OFF
  HPX_WITH_DISTRIBUTED_RUNTIME=ON
  HPX_WITH_DYNAMIC_HPX_MAIN=ON
  HPX_WITH_IO_COUNTERS=ON
  HPX_WITH_IO_POOL=ON
  HPX_WITH_ITTNOTIFY=OFF
  HPX_WITH_LOGGING=ON
  HPX_WITH_NETWORKING=ON
  HPX_WITH_PAPI=OFF
  HPX_WITH_PARALLEL_TESTS_BIND_NONE=OFF
  HPX_WITH_PARCELPORT_ACTION_COUNTERS=OFF
  HPX_WITH_PARCELPORT_COUNTERS=OFF
  HPX_WITH_PARCELPORT_LCI=OFF
  HPX_WITH_PARCELPORT_LIBFABRIC=OFF
  HPX_WITH_PARCELPORT_MPI=ON
  HPX_WITH_PARCELPORT_MPI_MULTITHREADED=ON
  HPX_WITH_PARCELPORT_TCP=OFF
  HPX_WITH_PARCEL_COALESCING=ON
  HPX_WITH_PARCEL_PROFILING=OFF
  HPX_WITH_SANITIZERS=OFF
  HPX_WITH_SCHEDULER_LOCAL_STORAGE=OFF
  HPX_WITH_SPINLOCK_DEADLOCK_DETECTION=OFF
  HPX_WITH_STACKTRACES=ON
  HPX_WITH_STACKTRACES_DEMANGLE_SYMBOLS=ON
  HPX_WITH_STACKTRACES_STATIC_SYMBOLS=OFF
  HPX_WITH_TESTS_DEBUG_LOG=OFF
  HPX_WITH_THREAD_BACKTRACE_ON_SUSPENSION=OFF
  HPX_WITH_THREAD_CREATION_AND_CLEANUP_RATES=OFF
  HPX_WITH_THREAD_CUMULATIVE_COUNTS=ON
  HPX_WITH_THREAD_DEBUG_INFO=OFF
  HPX_WITH_THREAD_DESCRIPTION_FULL=OFF
  HPX_WITH_THREAD_GUARD_PAGE=ON
  HPX_WITH_THREAD_IDLE_RATES=OFF
  HPX_WITH_THREAD_LOCAL_STORAGE=OFF
  HPX_WITH_THREAD_MANAGER_IDLE_BACKOFF=ON
  HPX_WITH_THREAD_QUEUE_WAITTIME=OFF
  HPX_WITH_THREAD_STACK_MMAP=ON
  HPX_WITH_THREAD_STEALING_COUNTS=OFF
  HPX_WITH_THREAD_TARGET_ADDRESS=OFF
  HPX_WITH_TIMER_POOL=ON
  HPX_WITH_TUPLE_RVALUE_SWAP=ON
  HPX_WITH_VALGRIND=OFF
  HPX_WITH_VERIFY_LOCKS=OFF
  HPX_WITH_VERIFY_LOCKS_BACKTRACE=OFF

Module coroutines:
  HPX_COROUTINES_WITH_SWAP_CONTEXT_EMULATION=OFF

Module datastructures:
  HPX_DATASTRUCTURES_WITH_ADAPT_STD_TUPLE=ON

Module serialization:
  HPX_SERIALIZATION_WITH_ALLOW_CONST_TUPLE_MEMBERS=OFF
  HPX_SERIALIZATION_WITH_ALLOW_RAW_POINTER_SERIALIZATION=OFF
  HPX_SERIALIZATION_WITH_ALL_TYPES_ARE_BITWISE_SERIALIZABLE=OFF
  HPX_SERIALIZATION_WITH_BOOST_TYPES=OFF
  HPX_SERIALIZATION_WITH_SUPPORTS_ENDIANESS=OFF

Module topology:
  HPX_TOPOLOGY_WITH_ADDITIONAL_HWLOC_TESTING=OFF

{version}: V1.8.0-trunk (AGAS: V3.0), Git: unknown
{boost}: V1.79.0
{build-type}: release
{date}: May 11 2022 12:50:07
{platform}: linux
{compiler}: GNU C++ version 11.2.0 20210728 (Cray Inc.)
{stdlib}: GNU libstdc++ version 20210728

{stack-trace}: 19 frames:
0x155553400310  : /lib64/libpthread.so.0(+0x13310) [0x155553400310] in /lib64/libpthread.so.0
0x1555547d273c  : /global/common/software/atlas/hpx/lib/libtcmalloc_minimal.so.4(+0xe73c) [0x1555547d273c] in /global/common/software/atlas/hpx/lib/libtcmalloc_minimal.so.4
0x1555547d81c6  : tcmalloc::CentralFreeList::ReleaseListToSpans(void*) [0x26] in /global/common/software/atlas/hpx/lib/libtcmalloc_minimal.so.4
0x1555547d848b  : tcmalloc::CentralFreeList::InsertRange(void*, void*, int) [0x4b] in /global/common/software/atlas/hpx/lib/libtcmalloc_minimal.so.4
0x1555547dc2ca  : tcmalloc::ThreadCache::ReleaseToCentralCache(tcmalloc::ThreadCache::FreeList*, unsigned int, int) [0x12a] in /global/common/software/atlas/hpx/lib/libtcmalloc_minimal.so.4
0x1555547dc60c  : tcmalloc::ThreadCache::ListTooLong(tcmalloc::ThreadCache::FreeList*, unsigned int) [0x2c] in /global/common/software/atlas/hpx/lib/libtcmalloc_minimal.so.4
0x4109c7        : /global/u2/e/esseivaj/devel/HPXDemo/build/HPXSerializationDistributed() [0x4109c7] in /global/u2/e/esseivaj/devel/HPXDemo/build/HPXSerializationDistributed
0x204eaaf9      : hpx::parcelset::detail::parcel::~parcel() [0x9] in /global/common/software/atlas/hpx/lib64/libhpx.so.1
0x204f94fa      : hpx::parcelset::parcel::~parcel() [0x3a] in /global/common/software/atlas/hpx/lib64/libhpx.so.1
0x204d7a4c      : /global/common/software/atlas/hpx/lib64/libhpx.so.1() [0x204d7a4c] in /global/common/software/atlas/hpx/lib64/libhpx.so.1
0x155554cdac51  : hpx::util::detail::function_base::reset(hpx::util::detail::function_base_vtable const*) [0x11] in /global/common/software/atlas/hpx/lib64/libhpx_core.so
0x204d7e9f      : /global/common/software/atlas/hpx/lib64/libhpx.so.1() [0x204d7e9f] in /global/common/software/atlas/hpx/lib64/libhpx.so.1
0x204dfbae      : /global/common/software/atlas/hpx/lib64/libhpx.so.1() [0x204dfbae] in /global/common/software/atlas/hpx/lib64/libhpx.so.1
0x204e5ef4      : hpx::parcelset::parcelport_impl<hpx::parcelset::policies::mpi::parcelport>::send_pending_parcels(hpx::parcelset::locality const&, std::shared_ptr<hpx::parcelset::policies::mpi::sender_connection>, std::vector<hpx::parcelset::parcel, std::allocator<hpx::parcelset::parcel> >&&, std::vector<hpx::function<void (std::error_code const&, hpx::parcelset::parcel const&), false>, std::allocator<hpx::function<void (std::error_code const&, hpx::parcelset::parcel const&), false> > >&&) [0x6a4] in /global/common/software/atlas/hpx/lib64/libhpx.so.1
0x204d4e23      : /global/common/software/atlas/hpx/lib64/libhpx.so.1() [0x204d4e23] in /global/common/software/atlas/hpx/lib64/libhpx.so.1
0x204e63eb      : hpx::parcelset::parcelport_impl<hpx::parcelset::policies::mpi::parcelport>::do_background_work(unsigned long, hpx::parcelset::parcelport_background_mode) [0xab] in /global/common/software/atlas/hpx/lib64/libhpx.so.1
0x204ef187      : hpx::parcelset::parcelhandler::do_background_work(unsigned long, bool, hpx::parcelset::parcelport_background_mode) [0x57] in /global/common/software/atlas/hpx/lib64/libhpx.so.1
0x205ecb72      : /global/common/software/atlas/hpx/lib64/libhpx.so.1() [0x205ecb72] in /global/common/software/atlas/hpx/lib64/libhpx.so.1
0x155554dbdfef  : /global/common/software/atlas/hpx/lib64/libhpx_core.so(+0x2021efef) [0x155554dbdfef] in /global/common/software/atlas/hpx/lib64/libhpx_core.so
{what}: Segmentation fault
```

## Steps to Reproduce the Problem

1. Load modules listed under specifications.
2. Cmake command used to compile HPX: `cmake .. -DCMAKE_BUILD_TYPE=Release -DHPX_WITH_MALLOC=tcmalloc -DHPX_WITH_PARCELPORT_MPI=ON -DHPX_WITH_PARCELPORT_TCP=OFF -DCMAKE_INSTALL_PREFIX=... -DBOOST_ROOT=... -DHWLOC_ROOT=... -DTCMALLOC_ROOT=...`

main.cpp:

```cpp

#include <hpx/config.hpp>
#include <hpx/future.hpp>
#include <hpx/hpx_main.hpp>
#include <hpx/iostream.hpp>
#include <hpx/runtime.hpp>

#include "event.h"
#include <utility>
#include <vector>

Event print_event(Event evt) {
    std::size_t const os_threads = hpx::get_os_thread_count();
    hpx::cout << "Action executed on locality " << hpx::get_locality_name() << "("
              << hpx::get_locality_id() << ") with " << os_threads << " threads. Event: " << evt
              << std::endl;
    return evt;
}

HPX_PLAIN_ACTION(print_event, print_event_action);

int main() {
    std::vector<hpx::id_type> localities = hpx::find_all_localities();

    std::vector<hpx::future<Event>> futures;
    futures.reserve(localities.size());

    std::string name("evtid");
    for (auto& node : localities) {
        Event evt(name, 15);
        futures.push_back(hpx::dataflow<print_event_action>(node, evt));
    }
    hpx::wait_all(futures.begin(), futures.end());

    for (auto&& f : futures) {
        auto result = f.get();
        hpx::cout << "Got result from future: " << result << std::endl;
    }
    return 0;
}
```

event.h:

```cpp
#pragma once

// also includes hpx/serialization/vector.hpp and hpx/serialization/string.hpp
#include <hpx/modules/serialization.hpp>

class Event;

namespace hpx::serialization {

template <class Archive> inline void save_construct_data(Archive&, Event const*, unsigned int);
} // namespace hpx::serialization

class Event {
    std::vector<int> data;
    std::string name;
    template <class Archive> void serialize(Archive&, const unsigned int);

  public:
    Event() = delete;
    template <class Archive>
    friend void hpx::serialization::save_construct_data(Archive&, Event const*, unsigned int);
    Event(const std::string&, size_t);
    Event(const std::string&, const std::vector<int>&);

    friend std::ostream& operator<<(std::ostream&, const Event&);
    friend class hpx::serialization::access;
};

std::ostream& operator<<(std::ostream&, const Event&);

template <class Archive> void Event::serialize(Archive& ar, const unsigned int version) {
// nothing else to (de)serialize
}
namespace hpx::serialization {

template <class Archive>
inline void save_construct_data(Archive& ar, Event const* t, const unsigned int file_version) {
    ar & t->name & t->data;
}

template <class Archive>
inline void load_construct_data(Archive& ar, Event* t, const unsigned int file_version) {
    std::string name;
    std::vector<int> data;
    ar & name & data;
    ::new (t) Event(name, data);
}

} // namespace hpx::serialization
```

event.cpp:

```cpp
#include "event.h"
#include <random>

Event::Event(const std::string& name, size_t n_elem) : data(n_elem), name(name) {
    std::mt19937 gen(std::random_device{}());
    std::uniform_int_distribution<> distr(0, 10);
    for (auto it = data.begin(); it != data.end(); ++it) {
        *it = distr(gen);
    }
}

Event::Event(const std::string& name, const std::vector<int>& data) : data(data), name(name) {}

std::ostream& operator<<(std::ostream& os, const Event& e) {
    os << e.name << "(";
    for (auto it = e.data.cbegin(); it != e.data.cend(); ++it) {
        os << *it;
        if ((it + 1) != e.data.cend()) os << ",";
    }
    os << ")";
    return os;
}
```

## Specifications

  - HPX Version: 1.8.0-rc2 (also tested with HPX 1.7.1 which also results in segfault)
  - MPI Version: 3.1
  - Platform (compiler, OS): Running on Cori haswell partition with the following modules:
      - gcc/11.2.0
      - cray-mpich/7.7.19
      - PrgEnv-gnu/6.0.10

### PR DESCRIPTION
**Pull request by hkaiser**
Fixes #5886

### CODE REVIEW

**Comment by hkaiser** [comment]
@esseivaju please verify whether this patch fixes the issue you reported.

**Comment by esseivaju** [comment]
@hkaiser I just rebuilt hpx with the fix and I am still seeing a similar issue.

```
Action executed on locality nid00211#0(0) with 64 threads. Event: evtid(1,10,3,7,0,6,7,4,9,7,0,2,5,6,5)
{config}:
Core library:
  HPX_AGAS_LOCAL_CACHE_SIZE=4096
  HPX_HAVE_MALLOC=tcmalloc
  HPX_PARCEL_MAX_CONNECTIONS=512
  HPX_PARCEL_MAX_CONNECTIONS_PER_LOCALITY=4
  HPX_PREFIX (configured)=
  HPX_PREFIX=/global/common/software/atlas/hpx

  HPX_FILESYSTEM_WITH_BOOST_FILESYSTEM_COMPATIBILITY=OFF
  HPX_ITERATOR_SUPPORT_WITH_BOOST_ITERATOR_TRAVERSAL_TAG_COMPATIBILITY=OFF
  HPX_WITH_AGAS_DUMP_REFCNT_ENTRIES=OFF
  HPX_WITH_APEX=OFF
  HPX_WITH_ASYNC_MPI=OFF
  HPX_WITH_ATTACH_DEBUGGER_ON_TEST_FAILURE=OFF
  HPX_WITH_AUTOMATIC_SERIALIZATION_REGISTRATION=ON
  HPX_WITH_COROUTINE_COUNTERS=OFF
  HPX_WITH_DISTRIBUTED_RUNTIME=ON
  HPX_WITH_DYNAMIC_HPX_MAIN=ON
  HPX_WITH_IO_COUNTERS=ON
  HPX_WITH_IO_POOL=ON
  HPX_WITH_ITTNOTIFY=OFF
  HPX_WITH_LOGGING=ON
  HPX_WITH_NETWORKING=ON
  HPX_WITH_PAPI=OFF
  HPX_WITH_PARALLEL_TESTS_BIND_NONE=OFF
  HPX_WITH_PARCELPORT_ACTION_COUNTERS=OFF
  HPX_WITH_PARCELPORT_COUNTERS=OFF
  HPX_WITH_PARCELPORT_LCI=OFF
  HPX_WITH_PARCELPORT_LIBFABRIC=OFF
  HPX_WITH_PARCELPORT_MPI=ON
  HPX_WITH_PARCELPORT_MPI_MULTITHREADED=ON
  HPX_WITH_PARCELPORT_TCP=OFF
  HPX_WITH_PARCEL_COALESCING=ON
  HPX_WITH_PARCEL_PROFILING=OFF
  HPX_WITH_SANITIZERS=OFF
  HPX_WITH_SCHEDULER_LOCAL_STORAGE=OFF
  HPX_WITH_SPINLOCK_DEADLOCK_DETECTION=OFF
  HPX_WITH_STACKOVERFLOW_DETECTION=ON
  HPX_WITH_STACKTRACES=ON
  HPX_WITH_STACKTRACES_DEMANGLE_SYMBOLS=ON
  HPX_WITH_STACKTRACES_STATIC_SYMBOLS=OFF
  HPX_WITH_TESTS_DEBUG_LOG=OFF
  HPX_WITH_THREAD_BACKTRACE_ON_SUSPENSION=OFF
  HPX_WITH_THREAD_CREATION_AND_CLEANUP_RATES=OFF
  HPX_WITH_THREAD_CUMULATIVE_COUNTS=ON
  HPX_WITH_THREAD_DEBUG_INFO=OFF
  HPX_WITH_THREAD_DESCRIPTION_FULL=OFF
  HPX_WITH_THREAD_GUARD_PAGE=ON
  HPX_WITH_THREAD_IDLE_RATES=OFF
  HPX_WITH_THREAD_LOCAL_STORAGE=OFF
  HPX_WITH_THREAD_MANAGER_IDLE_BACKOFF=ON
  HPX_WITH_THREAD_QUEUE_WAITTIME=OFF
  HPX_WITH_THREAD_STACK_MMAP=ON
  HPX_WITH_THREAD_STEALING_COUNTS=OFF
  HPX_WITH_THREAD_TARGET_ADDRESS=OFF
  HPX_WITH_TIMER_POOL=ON
  HPX_WITH_TUPLE_RVALUE_SWAP=ON
  HPX_WITH_VALGRIND=OFF
  HPX_WITH_VERIFY_LOCKS=ON
  HPX_WITH_VERIFY_LOCKS_BACKTRACE=OFF

Module coroutines:
  HPX_COROUTINES_WITH_SWAP_CONTEXT_EMULATION=OFF

Module datastructures:
  HPX_DATASTRUCTURES_WITH_ADAPT_STD_TUPLE=ON

Module serialization:
  HPX_SERIALIZATION_WITH_ALLOW_CONST_TUPLE_MEMBERS=OFF
  HPX_SERIALIZATION_WITH_ALLOW_RAW_POINTER_SERIALIZATION=OFF
  HPX_SERIALIZATION_WITH_ALL_TYPES_ARE_BITWISE_SERIALIZABLE=OFF
  HPX_SERIALIZATION_WITH_BOOST_TYPES=OFF
  HPX_SERIALIZATION_WITH_SUPPORTS_ENDIANESS=OFF

Module topology:
  HPX_TOPOLOGY_WITH_ADDITIONAL_HWLOC_TESTING=OFF

{version}: V1.8.0-trunk (AGAS: V3.0), Git: 50677d8ea4
{boost}: V1.79.0
{build-type}: debug
{date}: May 16 2022 09:47:41
{platform}: linux
{compiler}: GNU C++ version 11.2.0 20210728 (Cray Inc.)
{stdlib}: GNU libstdc++ version 20210728

{stack-trace}: 19 frames:
0x155554aa5af1  : /global/common/software/atlas/hpx/lib64/libhpx_cored.so(+0x20368af1) [0x155554aa5af1] in /global/common/software/atlas/hpx/lib64/libhpx_cored.so
0x155552f9e310  : /lib64/libpthread.so.0(+0x13310) [0x155552f9e310] in /lib64/libpthread.so.0
0x155552d2dcba  : /lib64/libc.so.6(+0x15dcba) [0x155552d2dcba] in /lib64/libc.so.6
0x15555383f459  : std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&) [0xa9] in /opt/gcc/11.2.0/snos/lib64/libstdc++.so.6
0x43a9d8        : /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed() [0x43a9d8] in /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed
0x43aa18        : /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed() [0x43aa18] in /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed
0x439ae3        : /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed() [0x439ae3] in /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed
0x438d7d        : /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed() [0x438d7d] in /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed
0x437c2f        : /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed() [0x437c2f] in /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed
0x4375aa        : /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed() [0x4375aa] in /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed
0x4355ce        : /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed() [0x4355ce] in /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed
0x43242e        : /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed() [0x43242e] in /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed
0x431758        : /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed() [0x431758] in /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed
0x42f1f0        : /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed() [0x42f1f0] in /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed
0x42daad        : /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed() [0x42daad] in /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed
0x42c02e        : /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed() [0x42c02e] in /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed
0x427e31        : /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed() [0x427e31] in /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed
0x42332f        : /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed() [0x42332f] in /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed
0x4233e8        : /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed() [0x4233e8] in /global/u2/e/esseivaj/devel/HPXDemo/buildd/HPXSerializationDistributed
{what}: Segmentation fault
```

**Comment by esseivaju** [comment]
The test passed. It seems like the issue only occurs when serializing to a remote node so it might be related to parcel. Since we trigger UB, I don't always get the same stack-trace, which will sometimes include the ```parcel::load_schedule``` method:


```
{stack-trace}: 18 frames:
0x1555533fe310  : /lib64/libpthread.so.0(+0x13310) [0x1555533fe310] in /lib64/libpthread.so.0
0x15555318dcba  : /lib64/libc.so.6(+0x15dcba) [0x15555318dcba] in /lib64/libc.so.6
0x40cfc7        : /global/u2/e/esseivaj/devel/HPXDemo/build/HPXSerializationDistributed() [0x40cfc7] in /global/u2/e/esseivaj/devel/HPXDemo/build/HPXSerializationDistributed
0x41d8fc        : /global/u2/e/esseivaj/devel/HPXDemo/build/HPXSerializationDistributed() [0x41d8fc] in /global/u2/e/esseivaj/devel/HPXDemo/build/HPXSerializationDistributed
0x40d32b        : /global/u2/e/esseivaj/devel/HPXDemo/build/HPXSerializationDistributed() [0x40d32b] in /global/u2/e/esseivaj/devel/HPXDemo/build/HPXSerializationDistributed
0x204eae8a      : hpx::parcelset::detail::parcel::load_schedule(hpx::serialization::input_archive&, unsigned long, bool&) [0x7a] in /global/common/software/atlas/hpx/lib64/libhpx.so.1
0x204d3ca2      : /global/common/software/atlas/hpx/lib64/libhpx.so.1() [0x204d3ca2] in /global/common/software/atlas/hpx/lib64/libhpx.so.1
0x204d4498      : /global/common/software/atlas/hpx/lib64/libhpx.so.1() [0x204d4498] in /global/common/software/atlas/hpx/lib64/libhpx.so.1
0x204e3bb1      : /global/common/software/atlas/hpx/lib64/libhpx.so.1() [0x204e3bb1] in /global/common/software/atlas/hpx/lib64/libhpx.so.1
0x204e4021      : /global/common/software/atlas/hpx/lib64/libhpx.so.1() [0x204e4021] in /global/common/software/atlas/hpx/lib64/libhpx.so.1
0x204e5fec      : hpx::parcelset::parcelport_impl<hpx::parcelset::policies::mpi::parcelport>::do_background_work(unsigned long, hpx::parcelset::parcelport_background_mode) [0x11c] in /global/common/software/atlas/hpx/lib64/libhpx.so.1
0x204eecf7      : hpx::parcelset::parcelhandler::do_background_work(unsigned long, bool, hpx::parcelset::parcelport_background_mode) [0x57] in /global/common/software/atlas/hpx/lib64/libhpx.so.1
0x205ec2f2      : /global/common/software/atlas/hpx/lib64/libhpx.so.1() [0x205ec2f2] in /global/common/software/atlas/hpx/lib64/libhpx.so.1
0x155554dbe41f  : /global/common/software/atlas/hpx/lib64/libhpx_core.so(+0x2022141f) [0x155554dbe41f] in /global/common/software/atlas/hpx/lib64/libhpx_core.so
0x155554dbf87f  : /global/common/software/atlas/hpx/lib64/libhpx_core.so(+0x2022287f) [0x155554dbf87f] in /global/common/software/atlas/hpx/lib64/libhpx_core.so
0x155554cc0c97  : hpx::threads::coroutines::detail::coroutine_impl::operator()() [0xd7] in /global/common/software/atlas/hpx/lib64/libhpx_core.so
0x155554cc00f9  : /global/common/software/atlas/hpx/lib64/libhpx_core.so(+0x201230f9) [0x155554cc00f9] in /global/common/software/atlas/hpx/lib64/libhpx_core.so
{what}: Segmentation fault
```

**Comment by hkaiser** [comment]
> The test passed. It seems like the issue only occurs when serializing to a remote node so it might be related to parcel.

That's unlikely. The only difference between serialization as part of a parcel and the test is that there the type is embedded in a tuple and not stored in a vector. I'll play with it a bit more. Thanks!

**Comment by hkaiser** [comment]
@esseivaju I have added another test and another fix that seems to resolve the issue now. Please verify.

**Comment by esseivaju** [comment]
@hkaiser Thanks for the update. I just tried to run the regression test and the demo example, the issue should be fixed as it doesn't segfaults anymore.

**Comment by hkaiser** [comment]
bors merge

**Pull request merged**
