### PR TITLE
Use BUILD_INTERFACE generator expression to fix cmake flag exports

### LINKED ISSUE #3484: Phylanx fails with latest hpx
## Expected Behavior
Expect Phylanx to compile with latest HPX

## Actual Behavior
Phylanx Fails compilation with the following error listed below.  I can confirm that it works up to the following commit dbbb94662ba0818cc5d6120f52e4a7b330075709 ( Merge pull request #3476 from STEllAR-GROUP/hide_credentials ). It looks to me the changes that were made to CMAKE recently is causing the issue.
The buildbot link for the failing build is here:
http://ktau.nic.uoregon.edu:8020/#/builders/8/builds/215
```
[ 12%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/assert_condition.cpp.o
/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/src/execution_tree/patterns.cpp: In function ‘std::__cxx11::string phylanx::execution_tree::find_help(const string&)’:
/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/src/execution_tree/patterns.cpp:68:30: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
                 for(int i=0;i<p.size();i++) {
                             ~^~~~~~~~~
/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/src/execution_tree/compiler/compiler.cpp: In instantiation of ‘std::vector<phylanx::ast::expression> phylanx::execution_tree::compiler::compiler::extract_lambda_arguments(const std::pair<_FIter, _FIter>&, const phylanx::ast::tagged&) [with Iterator = std::_Rb_tree_iterator<std::pair<const std::__cxx11::basic_string<char>, phylanx::ast::expression> >]’:
/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/src/execution_tree/compiler/compiler.cpp:314:62:   required from here
/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/src/execution_tree/compiler/compiler.cpp:201:41: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
                 if (count != 0 && count != size-1 &&
                                   ~~~~~~^~~~~~~~~
/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/src/execution_tree/compiler/compiler.cpp: In instantiation of ‘std::vector<phylanx::ast::expression> phylanx::execution_tree::compiler::compiler::extract_define_arguments(const std::pair<_FIter, _FIter>&, const phylanx::ast::tagged&) [with Iterator = std::_Rb_tree_iterator<std::pair<const std::__cxx11::basic_string<char>, phylanx::ast::expression> >]’:
/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/src/execution_tree/compiler/compiler.cpp:336:62:   required from here
/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/src/execution_tree/compiler/compiler.cpp:160:41: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
                 if (count != 0 && count != size-1 &&
                                   ~~~~~~^~~~~~~~~
[ 12%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/base_primitive.cpp.o
[ 12%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/call_function.cpp.o
[ 12%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/console_output.cpp.o
In file included from /var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/src/ast/parser/expression.cpp:8:0:
/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/phylanx/ast/parser/expression_def.hpp: In instantiation of ‘phylanx::ast::parser::expression_base<Iterator>::expression_base(phylanx::ast::parser::error_handler<Iterator>&) [with Iterator = __gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> >]’:
/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/phylanx/ast/parser/expression_def.hpp:26:62:   required from ‘phylanx::ast::parser::expression<Iterator>::expression(phylanx::ast::parser::error_handler<Iterator>&) [with Iterator = __gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> >]’
/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/src/ast/parser/expression.cpp:13:39:   required from here
/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/phylanx/ast/parser/expression_def.hpp:126:28: error: suggest parentheses around comparison in operand of ‘|’ [-Werror=parentheses]
             |   '(' > expr > ')'
                 ~~~~~~~~~~~^~~~~
[ 14%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/debug_output.cpp.o
[ 14%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/define_variable.cpp.o
[ 14%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/enable_tracing.cpp.o
[ 14%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/format_string.cpp.o
[ 17%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/function.cpp.o
[ 17%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/lambda.cpp.o
[ 17%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/node_data_helpers.cpp.o
[ 17%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/primitive_component.cpp.o
[ 19%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/primitive_component_base.cpp.o
cc1plus: some warnings being treated as errors
make[2]: *** [src/CMakeFiles/phylanx_component.dir/execution_tree/patterns.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
cc1plus: some warnings being treated as errors
make[2]: *** [src/CMakeFiles/phylanx_component.dir/execution_tree/compiler/compiler.cpp.o] Error 1
/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/src/execution_tree/primitives/base_primitive.cpp:64:21: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
         static char const* const get_primitive_argument_type_name(std::size_t index)
                     ^~~~~
cc1plus: some warnings being treated as errors
make[2]: *** [src/CMakeFiles/phylanx_component.dir/ast/parser/expression.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/phylanx_component.dir/all] Error 2
make: *** [all] Error 2
program finished with exit code 2
elapsedTime=80.792626

```

## Steps to Reproduce the Problem
Build Phylanx against latest hpx

## Specifications
  - HPX Version: Master
  - Platform (compiler, OS): Ubuntu 18.04 / gcc 7.3

### PR DESCRIPTION
**Pull request by biddisco**
Fixes #3484 

## Proposed Changes
Use BUILD_INTERFACE generator expression to make flags only inherited by targets n the build tree

### CODE REVIEW

**Comment by sithhell** [comment]
I think that's not sufficient. I have a different solution here:
https://gist.github.com/sithhell/668c7f76f474980df00abde9af98ac00

**Comment by biddisco** [comment]
The BUILD_INTERFACE works fine. Can you explain what your patch does? I would like to move away from all the monolithic hpx_add_xxx macros that should not be necessary and instead migrate towards just `target_add_xxx` at the CMakeLists level.

**Comment by sithhell** [comment]
what it does is to declare certain compiler flags private and others public. As you wrote in #3484, your patch only works for an installation of HPX. When running off of a build directory, the problem remains and a lot of applications are affected by the warnings (and warnings as errors) that now turn up.

I agree with you that moving away from those properties should be the way to go. In the meantime, we should at least restore the behavior we had for the release (which my linked patch does).

**Comment by biddisco** [comment]
OK. understood. yes adding PUBLIC and PRIVATE options to the flags is a good idea - in the next step we can then just get rid of the macro altogether :) (when cleanup is done)

**Comment by biddisco** [comment]
Regarding your point that BUILD_INTERFACE isn't enough, and adding PUBLIC/PRIVATE attributes - if a flag is marked as PRIVATE then the tests will not pick up that flag. If it is PUBLIC they will, but so will users' code. Using BUILD_INTERFACE allows anything to be used in the project and it is only users building against the build dir will be affected. BUILD_INTERFACE solves the problem entirely for installed versions of HPX. Using PRIVATE will mean some tests are not getting all the flags. A combination of both would be a good idea.

**Comment by hkaiser** [comment]
@biddisco when will the issue (#3484) be fixed? If you anticipate for the fix to take a while I'd suggest rolling back the cmake changes committed by #3479.

**Comment by hkaiser** [comment]
@sithhell could you please fix this? We should get this PR in as quickly as possible. Alternatively, I suggest to go ahead and roll back #3479.

**Comment by biddisco** [comment]
@hkaiser I will fix it. Got sidetracked by the other PR.

**Comment by hkaiser** [comment]
@biddisco thanks a lot!

**Comment by sithhell** [comment]
Everything should be back to normal now. Not sure why the parallel algorithm test is constantly failing now :(

**Comment by hkaiser** [comment]
> Not sure why the parallel algorithm test is constantly failing now

@sithhell this is because circleci has significantly reduced the amount of memory available to the vm's they run the tests on.

**Comment by sithhell** [comment]
Phylanx is working fine again.

**Comment by hkaiser** [comment]
@sithhell Does this enforce the C++ mode onto dependent libraries/applications now? 

We are seeing the issue, that Phylanx does not compile with Blaze master. This is a combination of things, but it is exposed by us not being able to enforce compilation of Phylanx in C++14 mode (CircleCI) as the HPX base Docker image enforces C++17.

**Comment by sithhell** [comment]
That's strange. We always enforced the C++ mode to our consuming target.
Blaze is header only, there should be no problem with that. The only
potential issue might be with pybind11...

**Comment by hkaiser** [comment]
> That's strange. We always enforced the C++ mode to our consuming target.

Ok, then we will need to make sure HPX is compiled in C++14 mode on CircleCI.

**Pull request merged**
