### PR TITLE
Rename simdpar to par_simd

### LINKED ISSUE #5494: Rename `simdpar` execution policy to `par_simd`
This is for consistency with the `unseq` and `par_unseq` policies.

### PR DESCRIPTION
**Pull request by msimberg**
Fixes #5494. I just did a find-and-replace, hoping there are no surprises.

### CODE REVIEW

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by hkaiser** [comment]
@srinivasyadav18 could you please verify this doesn't break anything?

**Comment by msimberg** [comment]
Am I right in my understanding that if `HPX_WITH_CXX20_EXPERIMENTAL_SIMD` is detected then there should be tests for this? `gcc-newest` (i.e. GCC 11 with C++20) seems to be running some tests with `datapar` in their name.

**Comment by srinivasyadav18** [comment]
> Am I right in my understanding that if `HPX_WITH_CXX20_EXPERIMENTAL_SIMD` is detected then there should be tests for this? `gcc-newest` (i.e. GCC 11 with C++20) seems to be running some tests with `datapar` in their name.

Yup, we use the existing datapar tests defined [here](https://github.com/STEllAR-GROUP/hpx/blob/master/libs/parallelism/algorithms/tests/unit/datapar_algorithms/CMakeLists.txt#L9). As it works for both `Vc` backend and `std-simd` backend.

**Review by srinivasyadav18 — APPROVED** [review]
LGTM, thanks! ;-)

**Pull request merged**
