### PR TITLE
Move unordered_map out of parcelport into hpx/concurrent

### PR DESCRIPTION
**Pull request by biddisco**
Also move readers_writers_mutex into hpx/lcos/local

These classes are now stable enough to be used outside of just
the parcelport code

### CODE REVIEW

**Comment by hkaiser** [comment]
Do you have a test to go with this?

**Comment by biddisco** [comment]
An excellent question. The answer is no.

If I create a test - is there a canonical way to test that there are no race conditions? 
I can iterate of millions of items and do set/get operations and check none are incorrect but ....

**Comment by hkaiser** [comment]
There is no way to guarantee the absence of races. But you could run millions of tests, each time with different items and different number of items and over time we will gain confidence that the code is race free. At least that's what we do to 'ensure' there are no races in the rest of HPX.

**Comment by sithhell** [comment]
The `reader_writer_mutex` needs to be implemented platform independent, it currently relies on gcc intrinsics.

**Pull request closed without merging**
