### PR TITLE
Making sure object is pinned while executing actions, even if action returns a future

### LINKED ISSUE #3325: AGAS migrates components prematurely
## Expected Behavior

When migrating a component whose action itself returns a future, the component should be migrated after the future of the action returns.

## Actual Behavior

Currently, it seems that the component gets migrated as soon as the action returns. Thus, the future of the action will continue to compute on the original locality.

## Steps to Reproduce the Problem

As a test case, I have modified the `migrate_component` unit test from the library. See https://github.com/bremerm31/hpx_mwe/blob/v0.1/src/migrate_component.cpp

Now `busy_work` has been futurized, and the `busy_work_impl` function will also increment `data_` by one. Thus, after `busy_work` has `executed data_` should be 43. However, since migration will occur before `busy_work` returns `data_` is evaluated as 42, causing the error to be thrown.

One workaround discussed with @hkaiser was manually pinning the component. This is shown via comments on L47-L48 in https://github.com/bremerm31/hpx_mwe/blob/v0.1/src/migrate_component.cpp#L47 . If these are uncommented, the test works as expected.

## Specifications

  - HPX Version: https://github.com/STEllAR-GROUP/hpx/commit/f6ce7ea37472dba57ed20964d7dea27a781fbce0
  - Compiler
```
[max@walikar dgswemv2]$ g++ --version
g++ (GCC) 6.1.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
  - OS
```
[max@walikar dgswemv2]$ cat /etc/*-release
CentOS Linux release 7.4.1708 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.4.1708 (Core) 
CentOS Linux release 7.4.1708 (Core)
```

### PR DESCRIPTION
**Pull request by hkaiser**
- fix problem in traits::action_decorate_function when used with component type
- adding more test cases for migrating components that expose actions returning futures
- flyby: factor out pinning/unpinning into separate trait

This fixes #3325

### CODE REVIEW

**Comment by hkaiser** [comment]
@bremerm31 Could you please try running your application using this branch and report back if this solves your issues?

**Comment by bremerm31** [comment]
@hkaiser thanks for the quick turnaround!

I seem to be having trouble building the PR. I get errors of the sort
```
In file included from /workspace/bremer/hpx/hpx/lcos/server/latch.hpp:14:0,
                 from /workspace/bremer/hpx/hpx/lcos/latch.hpp:11,
                 from /workspace/bremer/hpx/src/runtime_impl.cpp:15:
/workspace/bremer/hpx/hpx/runtime/components/server/runtime_support.hpp:109:34: error: enclosing class of constexpr non-static member function ‘void hpx::components::server::runtime_support::finalize()’ is not a literal type
         HPX_CXX14_CONSTEXPR void finalize() {}
                                  ^~~~~~~~
/workspace/bremer/hpx/hpx/runtime/components/server/runtime_support.hpp:60:11: note: ‘hpx::components::server::runtime_support’ is not literal because:
     class runtime_support
           ^~~~~~~~~~~~~~~
/workspace/bremer/hpx/hpx/runtime/components/server/runtime_support.hpp:60:11: note:   ‘hpx::components::server::runtime_support’ has a non-trivial destructor
```
although it seems the Cmake test is passing, i.e.
```
-- Performing Test HPX_WITH_CXX14_CONSTEXPR - Success
```
I've attached my full [hpx build log](https://github.com/STEllAR-GROUP/hpx/files/2027677/hpx_build_log.txt)

**Comment by hkaiser** [comment]
@bremerm31 thanks, that should be fine now.

**Comment by bremerm31** [comment]
Ran the mini-app mentioned in #3325 . The app ran correctly 100/100 times.

**Comment by hkaiser** [comment]
@bremerm31 \o/ Thanks!

**Pull request merged**
