### PR TITLE
Fixing environment handling for FreeBSD

### LINKED ISSUE #5115: Don't expect hwloc to always report Cores
Hello

I am the main hwloc developer. We recently got a bug report through FreeBSD because hwloc returned 0 cores, causing HPX tests to fail. https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=252643 and open-mpi/hwloc#442

This was indeed a hwloc bug that I am going to fix, but I think HPX shouldn't fail in this case. There are platforms where we cannot detect the cores. Of course it doesn't happen on Linux. However some operating systems such as *BSD don't have any native topology information. In these cases, hwloc tries alternative detection methods such as x86 CPUID assembly, but this isn't always supported.

HPX should have a fallback that uses PU instead of Cores in such cases. PU are guaranteed to always exist in hwloc.

Note that I didn't dig into the HPX code at all, I don't know if the failure is in the core HPX or in some tests mentioned in the freebsd bug report.

Thanks

### PR DESCRIPTION
**Pull request by hkaiser**
- flyby: disable memory perf counters for FreeBSD

Fixes #5115

### CODE REVIEW

**Comment by zao** [comment]
```
/home/zao/stellar/hpx/libs/core/debugging/src/print.cpp:251:17: error: use of undeclared identifier 'gethostname'
                gethostname(hostname_, std::size_t(12));
                ^
/home/zao/stellar/hpx/libs/core/debugging/src/print.cpp:261:26: error: cannot initialize a variable of type 'const char **' with an lvalue of type 'char **'
            char const** env = freebsd_environ;
                         ^     ~~~~~~~~~~~~~~~
2 errors generated.
```

**Comment by hkaiser** [comment]
@zao should be fine now, thanks!

**Comment by hkaiser** [comment]
@zao reported that this PR works for him on FreeBSD when using a patched hwloc 2.4 : https://gist.github.com/zao/c826f73531fccb5029061e06df9b94de (i.e. the hwloc patch that fixes the issue @bgoglin mentioned here: https://github.com/STEllAR-GROUP/hpx/issues/5115)

**Comment by hkaiser** [comment]
@msimberg once the tests have cycled, this is good to go, I believe (I have fixed the cyclic dependency problem).

**Comment by msimberg** [comment]
> @msimberg once the tests have cycled this is good to go, I believe (I have fixed the cyclic dependency problem).

Just the cmake_format check that's unhappy... Please feel free to merge without waiting for CI after that's updated.

**Pull request merged**
