### PR TITLE
Fixing gather_there for used with lvalue reference argument

### PR DESCRIPTION
**Pull request by hkaiser**
Fixes issue reported here: https://github.com/STEllAR-GROUP/hpx/pull/4676#issuecomment-860999175

@khuck, please verify whether this fixes your problem.

### CODE REVIEW

**Comment by hkaiser** [comment]
@msimberg I'd appreciate it if this fix would go into V1.7, still.

**Comment by khuck** [comment]
@hkaiser building/testing it now...

**Comment by khuck** [comment]
@hkaiser That works, thanks!

**Comment by hkaiser** [comment]
retest lsu

**Pull request merged**
