### PR TITLE
Additional Check for Inspect Tool to detect Endline Whitespace

### PR DESCRIPTION
**Pull request by Bcorde5**
The commits are slightly off, however the product is a clean version of the Endline Whitespace Checker for the inspect tool.

### CODE REVIEW

**Comment by hkaiser** [comment]
LGTM! Thanks!

**Comment by Bcorde5** [comment]
I apologize for these seemingly confusing actions, this will be the final time I edit the pull request until instructed otherwise, but otherwise the main repository will lose work.

**Comment by K-ballo** [comment]
> otherwise the main repository will lose work.

How would the main repository lose work?

**Comment by Bcorde5** [comment]
The first merge added the recent changes from the main repository into my branch, in order to sync my pull request with the main branch.  However, when the test initially failed, I realized I made a mistake trying to update my branch, so I reverted the changes in my own branch.  However, that made this pull request take away changes made to the main branch, since reverting the changes removed the main branch files.  So with change da67742, not only does it include my initial pull request, but it also deletes some of the changes that were introduced into the master branch since I first opened the request.  So in order to keep those changes, I had to revert the reversion.

**Comment by hkaiser** [comment]
Before merging this, I'd like to ask everybody one last time whether there are objections to enforcing a 'no trailing whitespace' policy on our code. This addition was mainly meant as a introductory project for Brandon. Nevertheless I think this policy has some merit and at the same time would not impose too much trouble onto developers as almost every editor can be configured to remove trailing whitespace on every save operation (see also [editorconfig](http://editorconfig.org/) which is available for many editors as well).

**Comment by hkaiser** [comment]
Since there have not been any objections, I'll go ahead and merge this.

**Pull request merged**
