### PR TITLE
ci: bump docker image version to 13

### PR DESCRIPTION
**Pull request by bhumitattarde**
See https://github.com/STEllAR-GROUP/docker_build_env/pull/49 for context

### CODE REVIEW

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by hkaiser** [comment]
bors merge

**Comment by hkaiser** [comment]
@bhumitattarde this really fixes the pdf build, thanks again: https://hpx-docs.stellar-group.org/branches/master/pdf/HPX.pdf

**Comment by bhumitattarde** [comment]
> @bhumitattarde this really fixes the pdf build, thanks again: https://hpx-docs.stellar-group.org/branches/master/pdf/HPX.pdf

@hkaiser Great, thanks to you too! : )

**Pull request merged**
