### PR TITLE
Adds new feature: changing interval used in interval_timer (issue 3244)

### PR DESCRIPTION
**Pull request by xaguilar**
Adds the function change_interval in hpx::util::interval_timer. This function allows the user to change the interval (attribute microsecs_) used by an interval_timer, thereby, slowing it down or speeding it up.

### CODE REVIEW

**Comment by hkaiser** [comment]
May I ask you to remove the `speed_up` and `slow_down` functions while you're working on this? Those are not used anywhere, AFAIR.

**Comment by xaguilar** [comment]
Sure! I'll do it right now.

**Comment by xaguilar** [comment]
Done!

**Comment by xaguilar** [comment]
Glad to contribute!

**Pull request merged**
