### PR TITLE
Add `stopValue` in `Sentinel` struct instead of `Iterator`

### PR DESCRIPTION
**Pull request by gonidelis**
Add `stopValue` in `Sentinel` struct instead of `Iterator`

### CODE REVIEW

**Comment by gonidelis** [comment]
Sorry about that. Just fixed it.

**Comment by hkaiser** [comment]
The only thing I would ask for the future (we will merge this as it is for now) would be that you comply to the HPX naming scheme outlined here: https://github.com/STEllAR-GROUP/hpx/wiki/HPX-Source-Code-Structure-and-Coding-Standards#coding-standards
(I'm fully aware that those were not observed here to begin with).

**Comment by gonidelis** [comment]
@hkaiser Thank you very much. I will take that into consideration next time.

**Comment by aurianer** [comment]
Don't forget to `clang-format-9` your code (see [clang-format step failure](https://195189-4455628-gh.circle-artifacts.com/0/hpx/artifacts/modified_clang_format_files.txt)) ;)

**Comment by gonidelis** [comment]
@aurianer Sorry. Will fix it asap.

**Comment by msimberg** [comment]
> I'm not sure where the pycicle errors come from, but they seem to be unrelated to this PR.

They are 99% sure unrelated. I'm trying to fix things that regressed while pycicle was down in #4684.

**Comment by hkaiser** [comment]
Congratulations, your first PR to the HPX repository has just been merged! As a 'thank you' we offer a free STE||AR-Group t-shirt to all of our first time contributors. If you are interested in receiving one, please get back to me directly so we can set up the delivery.

**Comment by gonidelis** [comment]
> Congratulations, your first PR to the HPX repository has just been merged! As a 'thank you' we offer a free STE||AR-Group t-shirt to all of our first time contributors. If you are interested in receiving one, please get back to me directly so we can set up the delivery.

Thanks a lot!!!

**Pull request merged**
