### PR TITLE
1d stencil fix

### PR DESCRIPTION
**Pull request by hendrx**
When the results where printed, the inner for loop was iterating over the global number of partitions. 

As stepper_server::space const& s = solution[i]  we know s.size() = local_np and thus the inner for loop has to use the local number of partitions and not the global.

### CODE REVIEW

**Comment by hkaiser** [comment]
@hendrx I'm not sure if this patch is correct. The output loop (which has been patched) has to go over all partitions as it is run on locality zero only. Do I misunderstand the intent of you change?

**Comment by hendrx** [comment]
@hkaiser :  
step.do_work(...) basically works on several local partitions for each locality ( defined by local_np) returning  stepper_server::space.  

locality 0 then gathers the results and stores them in in  std::vector<stepper_server::space> solution. each of the stepper_server:spaces in solution has exactly as many partitions as the locality which computed the results had been given as local_np parameter to step.do_work(). thus if the inner for loop tries to iterate over s[] for  the global number of partitions it will segfault. atleast it did for me.

example: if you have 10 partitions globally, given by command line parameter "np"  and 2 localities, each locality works on 5 partitions. thats why stepper_server::space const& s is each local_np in size. 
so originally the inner for loop would try to acces s[j] where j > 4. 
by using "j != np/nl" this will not happen as now  the inne for loop will only try to access as many members as there are local partitions.

**Comment by hkaiser** [comment]
@hendrx Ok, I see your point now. Thanks for explaining it. In this case, shouldn't the loop use `s.size()` as its upper bound instead of `np/nl`? The localities could have a different amount of partitions after all.

**Comment by hendrx** [comment]
`step.do_work()` defines  how much partitions there are per locality :  
`for (space& s: U_) 
s.resize(local_np); ` .

So yeah, its probably more intuitive to write s.size(), but as long as `do_work` is called with `(np/nl,..)`, which is the case, `local_np = s.size() = np/nl`.

 i could only see this being a problem if a worker was started with a different `np` parameter passed then the locality 0. but right now it seems not really smart to do that anyway. ( f.e.: 2 localities, l=0 started with `np=10,nx=10` , l=1 started with `np=4, nx=10` locality 0 would then try to calculate a kernel of say 10*10 partitions, would itself do the first 5 partitions, but the  locality=1 would just do `np/nl=2`, so its not really a finished result.

**Comment by hkaiser** [comment]
@hendrx I'm confused. Are you saying it is a good thing to use `s.size()` as the upper bound or that it is not a good thing to do so? Generally, I don't see any reason not to use it, regardless of whether code in other places precludes `np/nl` from being wrong.

**Comment by hendrx** [comment]
Im saying its a good thing to use it and you were right to propose it.

The confusing part is just me trying   to explain why in this specific example not using it but using instead np/nl is also okay .

**Comment by hkaiser** [comment]
> Im saying its a good thing to use it and you were right to propose it.

Ok, pls change this PR accordingly, then.

**Comment by hendrx** [comment]
Will do :)

**Pull request merged**
