### PR TITLE
adding libcds-hpx tag to prepare for hpx1.5 release

### PR DESCRIPTION
**Pull request by weilewei**
Prepared tag `hpx-1.5` for use in hpx 1.5 release

### CODE REVIEW

**Comment by msimberg** [comment]
If the integration is ready for public use (meaning the basics work, even if experimental), could you please add `HPX_WITH_LIBCDS=ON` to the CircleCI configuration: https://github.com/STEllAR-GROUP/hpx/blob/dac11daccfef1c3d98734b668dc09a1d0fb217db/.circleci/config.yml#L199 and check that the benchmark runs correctly on CircleCI.

**Comment by weilewei** [comment]
> If the integration is ready for public use (meaning the basics work, even if experimental), could you please add `HPX_WITH_LIBCDS=ON` to the CircleCI configuration:
> 
> https://github.com/STEllAR-GROUP/hpx/blob/dac11daccfef1c3d98734b668dc09a1d0fb217db/.circleci/config.yml#L199
> 
> and check that the benchmark runs correctly on CircleCI.

Ok, done.

**Comment by msimberg** [comment]
@weilewei could you please run `cmake-format` on the CMake files? Specifically, this is the formatting change that would satisfy CI: https://213714-4455628-gh.circle-artifacts.com/0/hpx/artifacts/modified_cmake_format_files.txt.

**Comment by msimberg** [comment]
@weilewei I added `HPX_WITH_LIBCDS=ON` to one of the jenkins builds as well, since I realized we don't run performance tests on CircleCI (they take a long time and we have limited resources there).

**Comment by weilewei** [comment]
> @weilewei could you please run `cmake-format` on the CMake files? Specifically, this is the formatting change that would satisfy CI: https://213714-4455628-gh.circle-artifacts.com/0/hpx/artifacts/modified_cmake_format_files.txt.

Sure, done now.

**Pull request merged**
