### PR TITLE
Supporting generic context for boost >= 1.61

### PR DESCRIPTION
**Pull request by AntonBikineev**

### CODE REVIEW

**Comment by hkaiser** [comment]
@AntonBikineev: I had some work done for this here: https://github.com/STEllAR-GROUP/hpx/tree/fixing_2471, but it crashed for me if a hpx-thread was moved to a different core. Have you seen similar problems?

**Comment by AntonBikineev** [comment]
@hkaiser I don't know, tests seemed to work fine on my laptop :)

**Comment by AntonBikineev** [comment]
@hkaiser I hadn't seen your patch. I think this can be closed then

**Comment by hkaiser** [comment]
@AntonBikineev if your PR works we should go ahead with it. The branch I referred to does not properly work.

**Comment by AntonBikineev** [comment]
@hkaiser Do hpx tests cover the situation with moving hpx-threads?

**Comment by hkaiser** [comment]
@AntonBikineev we don't have explicit tests, but for me the problem showed up by just running `hello_world` with `--hpx::threads=N`, where N > 1.

Also, inspect does not like your PR: https://6607-4455628-gh.circle-artifacts.com/0/tmp/circle-artifacts.qtJDgAu/hpx_inspect_report.html

**Comment by AntonBikineev** [comment]
@hkaiser I haven't observed this problem neither on mac nor linux. Maybe it was fixed by some another PR...

**Comment by AntonBikineev** [comment]
@hkaiser BTW, can I setup CI to use a specific boost version?

**Comment by hkaiser** [comment]
> BTW, can I setup CI to use a specific boost version

Not easily...

**Comment by hkaiser** [comment]
> > BTW, can I setup CI to use a specific boost version
>
> Not easily...

I might have misunderstood. Did you mean on circleci? or on our buildbot?

**Comment by AntonBikineev** [comment]
hm, I don't know, on any of those :)

**Comment by hkaiser** [comment]
@AntonBikineev you might want to get in contact with @hapoo (Alireza), he can help setting something up on buildbot.

**Pull request merged**
