### PR TITLE
Fixing spelling errors 

### LINKED ISSUE #4940: Codespell report for "HPX" (on fossies.org)
The FOSS server https://fossies.org - since today also supporting "HPX" - offers a feature named "Source code misspelling reports":

 https://fossies.org/features.html#codespell

Such reports are normally only generated on request, but since I found in the tarball a file named `tools/.codespell_whitelist` as Fossies administrator I couldn't help forcing  nevertheless such a  [codespell](https://github.com/codespell-project/codespell) analysis for the new "HPX" release :

 https://fossies.org/linux/misc/hpx/codespell.html

That version-independent (not linked) URL should redirect always to the last report (if available), so currently to

 https://fossies.org/linux/misc/hpx-1.5.0.tar.gz/codespell.html

Ok, unsurprisingly only very few  misspellings and typos were found.

### PR DESCRIPTION
**Pull request by hkaiser**
...as reported by https://fossies.org/linux/test/hpx/codespell.html

Fixes #4940

Thanks @jschleus! One of the spelling problems can't be fixed, could you add the word to the whitelist, please (`'unitialized'`, here: https://github.com/STEllAR-GROUP/hpx/blob/master/docs/sphinx/releases/whats_new_1_1_0.rst)?

### CODE REVIEW

**Comment by jschleus** [comment]
@hkaiser Oops, the word `unitialized` as a mentioned previously corrected typo I have overseen (now as false positive in the whitelist).

**Review by aurianer — APPROVED** [review]
LGTM thanks!

**Comment by msimberg** [comment]
Thanks @hkaiser! These should've been caught by CI so I went looking into the builds and it looks like I essentially disabled the spellchecking in my last change to the spellchecking config. I'll try to fix that so we don't end up in this situation again.

**Comment by jschleus** [comment]
Great, Fossies resp. codespell  currently found no more spelling errors: https://fossies.org/linux/test/hpx/codespell.html

**Pull request merged**
