### PR TITLE
Fixing #2256

### PR DESCRIPTION
**Pull request by AntonBikineev**

### CODE REVIEW

**Comment by hkaiser** [comment]
@AntonBikineev Good thinking, thanks! However, wouldn't it be sufficient to force instantiate the `register_class_name<>` template in this case?

**Comment by AntonBikineev** [comment]
@hkaiser Now I'm not sure that it makes more sense. Instead of
```
+    namespace hpx { namespace actions {                                       \
+        template struct transfer_action<action>;                              \
+    }}            
```
it would be
```
+    namespace hpx { namespace actions {                                       \
+        template struct register_class_name<                                     \
+            ::hpx::actions::transfer_action<action> >;                           \
+    }}                                                                                                      \
```
which anyways would require instantiation of transfer_action

**Comment by sithhell** [comment]
I think you need to export the explicit instantiations.

**Comment by AntonBikineev** [comment]
@hkaiser that was my initial idea, I still think that it makes dealing with actions too complicated..

**Comment by hkaiser** [comment]
@AntonBikineev I agree, it's not nice. Nevertheless, I'd suggest to do it this way for now until we have a better idea. Normally the user will not need this as the stack-size macros etc. are not used too often.

**Comment by AntonBikineev** [comment]
@hkaiser, okay, lgtm

**Pull request merged**
