### PR TITLE
Add support of std::array to hpx::util::tuple_size and tuple_element

### PR DESCRIPTION
**Pull request by Naios**
Didn't run the test suite on it yet, let's see how it goes.

### CODE REVIEW

**Comment by Naios** [comment]
I was asking myself whether we still need `HPX_HAVE_CXX11_STD_ARRAY`, since it should be theoretically supported on all required platforms.

**Comment by K-ballo** [comment]
I'd suggest we mark support for `std::array` as required in cmake (which will in turn no longer emit the `HAVE` macro), and drop support for `boost::array` in the process.

**Comment by Naios** [comment]
@K-ballo do you prefer the changes you mentioned above over this PR, or can those be applied after this PR was merged?

**Comment by K-ballo** [comment]
> @K-ballo do you prefer the changes you mentioned above over this PR, or can those be applied after this PR was merged?

@Naios I don't particularly care in which way the changes make it into master, as long as they do.

**Comment by Naios** [comment]
@K-ballo I will take care about this later during my GSoC project, it would be good, if we could merge this PR meanwhile, because it's required by #2687.

**Pull request merged**
