### PR TITLE
Segmented algorithms

### PR DESCRIPTION
**Pull request by hkaiser**
This recreates the patch that was proposed by #2859

### CODE REVIEW

**Comment by hkaiser** [comment]
@ghost, @mcopik would you have the time to verify that I properly reproduced the PR submitted earlier (#2859)?

**Comment by msimberg** [comment]
I'd rather wait with this one until after 1.2 so I've moved this to the next release. This could be unrelated, but it smells very related to this PR: http://cdash.cscs.ch//testDetails.php?test=4055606&build=24062.

**Comment by sithhell** [comment]
The segmented algorithm tests fail.
For example here:
http://rostam.cct.lsu.edu/builders/hpx_clang_3_8_boost_1_59_centos_x86_64_release/builds/191/steps/run_unit_tests/logs/tests.unit.parallel.segmented_algorithms.distributed.mpi.partitioned_vector_adjacent_difference1%20%28Timeout%29
Or here:
https://gitlab.com/stellar-group/hpx/-/jobs/152622270

**Comment by hkaiser** [comment]
@sithhell Thanks, will fix.

**Pull request merged**
