### PR TITLE
Remove most of Boost.MPL, Boost.EnableIf and Boost.TypeTraits

### PR DESCRIPTION
**Pull request by sithhell**

### CODE REVIEW

**Comment by K-ballo** [comment]
LGTM

**Comment by hkaiser** [comment]
We should consider to guard the use of `alignof()` with a feature test.

**Comment by hkaiser** [comment]
Other things to consider (could be separate PR):

- [ ] add inspect check for `boost::is*`, `boost::add_*`, `boost::remove_*`, etc. to flag the use of those as deprecated
- [ ] add inspect check for `<type_traits>` being included whenever `std::is_`, `std::add_*`, or `std::remove_*` are used
- [ ] require support for `std::ref` (change feature test) and remove guards `HPX_HAVE_CXX11_STD_REFERENCE_WRAPPER` from code (see #2260)

**Comment by hkaiser** [comment]
@sithhell Do you plan to add the `alignof()` feature test? Any idea whether `alignof()` can be made mandatory?

**Comment by K-ballo** [comment]
`alignof()` will not work on VS2013, but `std::alignment_of` will.

**Comment by sithhell** [comment]
alignof has been replaced with the std:: alignment_of

Am 26.07.2016 3:36 nachm. schrieb "Agustín Bergé" <notifications@github.com

**Comment by hkaiser** [comment]
LGTM, thanks! Could you create a ticket for the open suggestion above, please (adding deprecated Boost type traits to inspect)?

**Comment by sithhell** [comment]
See #2267.

**Pull request merged**
