### PR TITLE
Cleaning up the build system

### PR DESCRIPTION
**Pull request by chinz07**
## Proposed Changes

- Remove some dead or obsolete code (hpx_is_target and SubProject.cmake)
- Replace most macros with functions

The remaining macros can not be replaced easily without an extensive rewrite. Since the PR is already rather large, I will submit these changes as a separate PR.

To verify that the behavior of the build system has not changed, I have compared the generated compiler invocations and the hashes of every object file with their old values. The modified build system produces bit-for-bit identical results for all files (except version.cpp.o) if the default settings are used.

This PR is the first step towards resolving issue #3474. As part of a followup PR I will start to replace the deprecated directory-based commands (add_compile_options, ...).

### CODE REVIEW

**Comment by chinz07** [comment]
I am unable to reproduce the failures on CircleCI. Even if I use the `stellargroup/build_env:debian_clang` Docker image and work through the steps specified in the config file, all tests succeed on my machine. Judging from other runs of the test suite on CircleCI these tests do timeout occasionally. Are these failures expected?

The failures on daint are related to #3506?

Any help would be appreciated.

**Comment by msimberg** [comment]
Hi @chinz07, you're right that those failures are unrelated. The CircleCI failure is this one: #3257, and the daint one is related to but not caused by #3506. Sorry about that. This PR is looking really good and much appreciated! For now you're mostly safe to assume that errors that are not build-related are not caused by your PR.

**Comment by msimberg** [comment]
> > and the daint one is related to but not caused by #3506.
> 
> Could you please elaborate on that. What's a related fail, I had a wuick look on cdash but couldn't spot anything obvious

@biddisco I might've looked too quickly. It looks like a plain old hang in HPX whereas your PR is about slurm timeouts. So not related.

**Comment by chinz07** [comment]
@msimberg Thanks for the quick reply. Since the produced binaries were bit-for-bit identical, I anticipated that much. But better safe than sorry. ODR violations due to missing flags and preprocessor definitions can cause quite a pain.

If the failures are unrelated, the PR is ready to be merged.

**Comment by chinz07** [comment]
@msimberg Agreed. That's what I intended anyway. Sorry for not mentioning it explicitly. In the meantime, I will continue to prepare the follow-up PRs. Hopefully, we can merge those as fast as possible after the release so everybody can properly test the refactored build system.

**Pull request merged**
