### PR TITLE
Rename tag_invoke and related facilities to tag_dispatch

### PR DESCRIPTION
**Pull request by hkaiser**
In the light of the recent discussions (see #5344) this proposes to rename `tag_invoke` and friends to `tag_dispatch`, mainly to avoid potential conflicts with a possible future `std::tag_invoke` and to prevent users from misunderstanding the concepts they represent. I think we should make this change now (as in as quickly as possible) to avoid breaking code that users may write in the future. 

This PR is really a proposal and I'm open to discussions (and bike-shedding).

### CODE REVIEW

**Comment by hkaiser** [comment]
The quicker we get this merged, the better, I think.

**Review by aurianer — DISMISSED** [review]
LGTM thanks!
Should we also rename the `tag_invoke_*_calls` or `tag_invoke_*_called` in the sender receivers unit tests?

**Comment by msimberg** [comment]
> > LGTM thanks!
> > Should we also rename the `tag_invoke_*_calls` or `tag_invoke_*_called` in the sender receivers unit tests?
> 
> In general we should leave `tag_invoke` wherever we want for a future `std::tag_invoke` to be usable with our functions.

I'm not sure I understand this comment. Have you left any `tag_invoke` overloads unchanged? I think @aurianer's question was simply about the variable names we use in the tests. I think it makes sense to rename them as well as long as we call our "thing" `tag_dispatch` and not `tag_invoke`. Am I missing something?

**Comment by hkaiser** [comment]
> I'm not sure I understand this comment. Have you left any `tag_invoke` overloads unchanged? I think @aurianer's question was simply about the variable names we use in the tests. I think it makes sense to rename them as well as long as we call our "thing" `tag_dispatch` and not `tag_invoke`.

Apparently I misunderstood, sorry. I will make the change.

**Comment by hkaiser** [comment]
@aurianer I have now renamed the uses of `tag_invoke_...` in the tests as well. @msimberg This should be good to go.

**Comment by hkaiser** [comment]
> Thanks @hkaiser. What about the discussion from yesterday about keeping the `tag_invoke` name for the main facility? Did you get some clarity on that?

I think now that we should rename `tag_invoke` as well. The rationale is that if we renamed `tag_fallback_invoke` (and friends) only, then we would have to implement base functionalities by overloading `tag_fallback_dispatch` but specializations for the same DPO would have to be done using `tag_invoke`. That doesn't sound too appealing to me and would be difficult to explain.

**Comment by msimberg** [comment]
> I think now that we should rename `tag_invoke` as well. The rationale is that if we renamed `tag_fallback_invoke` (and friends) only, then we would have to implement base functionalities by overloading `tag_fallback_dispatch` but specializations for the same DPO would have to be done using `tag_invoke`. That doesn't sound too appealing to me and would be difficult to explain.

Good point, and agreed that the names should be consistent if possible. I suppose the question was more about why we need to rename `tag_invoke`, but as I said I don't fully understand the issue, so let's go ahead with this if you think it's the right thing to do.

**Comment by hkaiser** [comment]
> > I think now that we should rename `tag_invoke` as well. The rationale is that if we renamed `tag_fallback_invoke` (and friends) only, then we would have to implement base functionalities by overloading `tag_fallback_dispatch` but specializations for the same DPO would have to be done using `tag_invoke`. That doesn't sound too appealing to me and would be difficult to explain.
> 
> Good point, and agreed that the names should be consistent if possible. I suppose the question was more about why we need to rename `tag_invoke`, but as I said I don't fully understand the issue, so let's go ahead with this if you think it's the right thing to do.

It does not hurt... , at least I can't see it getting in the way.

**Comment by msimberg** [comment]
> It does not hurt... , at least I can't see it getting in the way.

Yes, the only potential downside is that we'd have rename things back if we get a std::tag_invoke and we want to make things work with that. However, that's far off in the future, if it ever happens. Let's do this. This just needs a formatting round as well, but let's merge it once that's done.

**Comment by msimberg** [comment]
Thanks @hkaiser for updating this as well. Since this, #5341, and #5347 will conflict (or will at least need changes) after one of them is merged, I'll let you merge them in whichever order you see as easiest.

**Pull request merged**
