### PR TITLE
Minor docs fixes

### PR DESCRIPTION
**Pull request by tapaswenipathak**
## Proposed Changes
Minor rst formatting fixes.

## Any background context you want to provide?
GSoD'19 applicant.

### CODE REVIEW

**Comment by msimberg** [comment]
Could you give some more background for this? Did you have problems with getting the images to show up? The leading slash makes sphinx look in the docs root for the images (and they do show up in our generated docs, e.g. [here](https://stellar-group.github.io/hpx/docs/sphinx/branches/master/html/examples/fibonacci_local.html)).

**Comment by tapaswenipathak** [comment]
Can you see any file on GitHub? How does the `.png` looks?

**Comment by msimberg** [comment]
@tapaswenipathak I'm not sure I understand your question. The corresponding image (to the link I posted) is [here](https://github.com/STEllAR-GROUP/hpx/blob/master/docs/sphinx/_static/images/future_schematics.png) in the repository.

**Comment by tapaswenipathak** [comment]
Screen Shot 2019-06-18 at 5 37 02 AM

**Comment by msimberg** [comment]
Sorry for not replying earlier. I see now what you mean. I would *really* encourage users to read the generated documentation and not on GitHub. There are many other things that don't show up correctly at all when reading on GitHub. But this is a very small change so it definitely won't hurt to do this. There's one more of these that need to be changed in https://github.com/STEllAR-GROUP/hpx/blob/master/docs/sphinx/examples/1d_stencil.rst.

**Comment by tapaswenipathak** [comment]
@msimberg do you think I can enhance anything else in this PR?

**Pull request merged**
