### PR TITLE
Adapted parallel::{all_of|any_of|none_of} for Ranges TS (see #1668)

### PR DESCRIPTION
**Pull request by brjsp**
- Add projection function to all_of, any_of, none_of
- Add range version of the above functions (#1668)
- corresponding tests

### CODE REVIEW

**Comment by hkaiser** [comment]
@brjsp our circleci testing infrastructure reports errors from the newly added tests, would you mind fixing those (https://circleci.com/gh/STEllAR-GROUP/hpx/8551)?

**Comment by brjsp** [comment]
should be OK now

**Comment by hkaiser** [comment]
@brjsp sadly it's not ok yet. Would you mind to have a look again?

**Comment by brjsp** [comment]
should be ok now

**Comment by hkaiser** [comment]
@brjsp yes, compilation errors are gone now, however inspect is still unhappy: https://8587-4455628-gh.circle-artifacts.com/0/tmp/circle-artifacts.6IoAkhH/hpx_inspect_report.html

**Comment by aserio** [comment]
Congrats @brjsp on your first pull request! Are you interested in receiving a STE||AR Group T-Shirt?

**Pull request merged**
