### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by diehlpk**
` HPX is has been funded by`

Should read

`HPX has been funded by`

### CODE REVIEW

**Review by msimberg — DISMISSED** [review]
Looks good to me, but I don't know if any of those are still active (i.e. if it should be is or has been).

**Review by aurianer — DISMISSED** [review]
Thanks!

**Comment by hkaiser** [comment]
> Looks good to me, but I don't know if any of those are still active (i.e. if it should be is or has been).

We should change this to simply refer to: https://hpx.stellar-group.org/funding-acknowledgements/

**Comment by msimberg** [comment]
@diehlpk sorry for hijacking your PR. I changed the README and the docs to point to the funding page on hpx.stellar-group.org. I also added a users section to the docs, which simply points to the users page on hpx.stellar-group.org.

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by diehlpk** [comment]
@msimberg No worries, I have too much on my plate and could not do it soonish.

**Review by aurianer — APPROVED** [review]
Thanks!

**Pull request merged**
