### PR TITLE
Restore compatibility for old (now deprecated) copy algorithms

### PR DESCRIPTION
**Pull request by hkaiser**
This was accidentally left in #4821.

### CODE REVIEW

**Comment by gonidelis** [comment]
Looks good to me now :)

**Comment by msimberg** [comment]
retest

**Comment by msimberg** [comment]
Sorry @hkaiser, I accidentally configured the CSCS jenkins instance to use the LSU configuration (which is not there obviously). Testing should restart soon.

**Comment by msimberg** [comment]
retest

**Comment by msimberg** [comment]
> Sorry @hkaiser, I accidentally configured the CSCS jenkins instance to use the LSU configuration (which is not there obviously). Testing should restart soon.

It's unrelated to that in fact. I'm talking to CSCS admins about the issue.

**Pull request merged**
