### PR TITLE
Move documentation from `README.rst` to `index.rst` files under `libs` directory

### PR DESCRIPTION
**Pull request by dimitraka**
Towards resolving issue #6214

For all the `README.rst` files that used to contain information, this information was moved to the corresponding `index.rst` file.

### CODE REVIEW

**Comment by hkaiser** [comment]
@dimitraka can we merge this now?

**Comment by dimitraka** [comment]
> @dimitraka can we merge this now?

yes, I have made the final changes. thank you!

**Comment by hkaiser** [comment]
bors merge

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
