### PR TITLE
Fix #1423

### LINKED ISSUE #1423: Remove HPX_STD_UNIQUE_PTR
All our compilers are able to use std::unique_ptr. HPX_STD_UNIQUE_PTR is not required anymore.

### PR DESCRIPTION
**Pull request by mcopik**
I replaced the HPX macro for unique and auto pointers with unique pointer from standard library.

### CODE REVIEW

**Comment by sithhell** [comment]
Would be nice if the CMake test here: https://github.com/STEllAR-GROUP/hpx/blob/master/CMakeLists.txt#L938 would fail if `std::unique_ptr` is not part of the stdlib. In a similar fashion than the C++11 rvalue references check.

**Comment by mcopik** [comment]
I changed the compiler check in CMake files. Should I test it against some older version of GCC or is it fine without additional check?

**Comment by sithhell** [comment]
LGTM!

**Comment by sithhell** [comment]
Thanks!

**Pull request merged**
