### PR TITLE
Raw ptr untracking

### PR DESCRIPTION
**Pull request by AntonBikineev**
This PR is based on another one, so look only at lastt commit. Sorry my badness at git.

### CODE REVIEW

**Comment by K-ballo** [comment]
Could you include some rationale here on why you think raw pointer serialization should be untracked? It seems to be defeating the goal of supporting raw pointer serialization to begin with.

**Comment by hkaiser** [comment]
@K-ballo raw pointers shouldn't ever be tracked as you wouldn't know which of the pointer copies you receive are owning the memory.

**Comment by K-ballo** [comment]
The semantics of pointer serialization are well defined and they depend on tracking. Tracking is what makes pointer serialization useful and interesting, without tracking we are giving pointer serializations the semantics of something else (optional? by value something). These semantics do demand that the user knows what he is doing, so we have agreed to support it only via an explicit mechanism. This change effectively overrules that decision, and I'd rather see it be completely removed that turned into something that is not. The intention already is that people who don't know what this does does not use it after all.

**Comment by hkaiser** [comment]
> The semantics of pointer serialization are well defined and they depend on tracking

Would you mind elaborating on what you believe to be 'well defined pointer serialization semantics'? I have the impression we're talking about different things here.

**Comment by K-ballo** [comment]
> The semantics of pointer serialization are well defined and they depend on tracking
> 
> Would you mind elaborating on what you believe to be 'well defined pointer serialization semantics'? I have the impression we're talking about different things here.

I'll try but it boils down to tracking. Pointer serialization semantics preserve identities rather than values. If a group of pointers all refer to the same object while saving, they still refer to that same single one object when loading. This is, pointer serialization is stable with regard to relationships.

Consider as a basic example two nodes in a directional graph forming a cycle, saving those nodes should not trigger infinite recursion, loading those nodes should give out two nodes in a directional graph forming a cycle. This is what the literature (that I can remember) describes and what libraries (like Boost.Serialization and Cereal) implement. Neither of the pointer involved own any memory, memory is owned by the graph (relation) as a whole.

Serialization does not add any new trickery or gotcha to the list of already existing ones that raw pointers already have. Nor is necessary to go to extreme situations like cycles, raw pointers participate in relationships without stating ownership, while smart dumb pointers like `observer_ptr` participate in relationships explicitly stating that they do not participate in ownership.

Pointer serialization is all about preserving relationships (ownership is orthogonal), while my understanding of "untracked" serialization is that relationships are severed.

**Comment by hkaiser** [comment]
Thanks. What if we make tracking/not tracking explicit by not only having `raw_ptr(p)` but also `tracked_ptr(p)`. I don't think that the graph example you provide is the only use case of pointer serialization. You can easily think of some use case where the pointer actually owns the memory in which case tracking would lead to problems.

**Comment by K-ballo** [comment]
Untracked pointer serialization makes absolutely no sense to me at all, and given that I was the only proponent of raw pointer serialization support I'd rather not see any of it than see such oxymoron. That should address whatever concerns started this PR, which I believe to be related to ownership instead. If and when the need for raw pointer serialization arises, there's a chance I won't have to be the one making a case for it.

**Comment by hkaiser** [comment]
@K-ballo I'm not sure what  you're trying to say. Remove raw pointer serialization altogether?

**Comment by K-ballo** [comment]
> @K-ballo I'm not sure what you're trying to say. Remove raw pointer serialization altogether?

Indeed. I have asked what the rationale for this PR is, and I assume is out of ownership concerns. If that's the case then this PR is a mistake, but in order to address those concerns I'd be ok with raw pointer serialization being removed altogether since it isn't needed right now. Chances are it will eventually be needed, and will come back in proper form then.

**Comment by hkaiser** [comment]
Ok, I'm fine with removing raw pointer serialization altogether.

**Comment by sithhell** [comment]
On Thursday, May 07, 2015 19:31:34 Agustín Bergé wrote:
> > @K-ballo I'm not sure what you're trying to say. Remove raw pointer
> > serialization altogether?
> Indeed. I have asked what the rationale for this PR is, and I assume is out
> of ownership concerns. If that's the case then this PR is a mistake, but in
> order to address those concerns I'd be ok with raw pointer serialization
> being removed altogether since it isn't needed right now. Chances are it
> will eventually be needed, and will come back in proper form then.

It was indeed about ownership concerns. I have to agree with you that raw 
pointer serialization isn't about ownership, thanks for bringing that up, I 
haven't thought about it that way.

**Comment by hkaiser** [comment]
This has been superseded by #1548

**Pull request closed without merging**
