### PR TITLE
Replace boost::chrono with std::chrono in interfaces

### PR DESCRIPTION
**Pull request by K-ballo**

### CODE REVIEW

**Comment by K-ballo** [comment]
This is a breaking change as it disables dual support for `boost::chrono`. For the short term, the old behavior can be brought back via `HPX_WITH_BOOST_CHRONO_COMPATIBILITY`.

**Comment by hkaiser** [comment]
Could this be (conditionally) removed now as well: https://github.com/STEllAR-GROUP/hpx/blob/master/cmake/HPX_SetupBoost.cmake#L26?

**Comment by K-ballo** [comment]
> Could this be (conditionally) removed now as well: https://github.com/STEllAR-GROUP/hpx/blob/master/cmake/HPX_SetupBoost.cmake#L26?

I believe not because Boost.Thread still links against it, but I'm not sure. Will give it a try...

**Comment by hkaiser** [comment]
@K-ballo could you rebase this branch, please?

**Pull request merged**
