### PR TITLE
refactor: convert `counter_status` enum to enum class

### PR DESCRIPTION
**Pull request by bhumitattarde**
Towards #4702

## Proposed Changes

  - converted `counter_status` enum to enum class.
  - added clang's `.cache` & cmake-tools's `cmake-build` directory to `.gitignore`. These are some of the most widely used extensions for C++ development using VSCode.
  - formatted `server/papi.cpp` (since this file was getting touched as a part of this change).

## Any background context you want to provide?

This change can probably be improved by making `ostream` overload print enum name strings instead of enum int values. Thoughts? 

## Checklist

Not all points below apply to all pull requests.

- [ ] I have added a new feature and have added tests to go along with it.
- [ ] I have fixed a bug and have added a regression test.
- [ ] I have added a test using random numbers; I have made sure it uses a seed, and that random numbers generated are valid inputs for the tests.

### CODE REVIEW

**Comment by hkaiser** [comment]
@bhumitattarde thanks for this. Unfortunately, this seems to be a duplicate of #5857.

**Comment by bhumitattarde** [comment]
@hkaiser Aah, I did not see that. My apologies. I'll close this PR.

**Comment by hkaiser** [comment]
> @hkaiser Aah, I did not see that. My apologies. I'll close this PR.

No reason to apologize. We really appreciate your initiative. Let's talk about things before you start working on something to avoid these situations.

**Comment by bhumitattarde** [comment]
> > @hkaiser Aah, I did not see that. My apologies. I'll close this PR.
> 
> No reason to apologize. We really appreciate your initiative. Let's talk about things before you start working on something to avoid these situations.

Thank you. I'll definitely keep that in mind next time. : )

**Pull request closed without merging**
