### PR TITLE
Move algorithms to tag_fallback_invoke

### PR DESCRIPTION
**Pull request by toktarev**
Fixes #

## Proposed Changes

Move algorithms to tag_fallback_invoke
  
## Any background context you want to provide?

Issue: https://github.com/STEllAR-GROUP/hpx/issues/5204

### CODE REVIEW

**Comment by hkaiser** [comment]
@toktarev any  reason you closed this PR?

**Comment by toktarev** [comment]
@hkaiser I am sorry, I see some conflict with master
Will have to fix it and re-open

**Comment by toktarev** [comment]
@hkaiser 

I am sorry again for this confusion (I see that you've made some work with labels here).

**Comment by hkaiser** [comment]
Feel free to leave it open. Just rebase against master, that should take care of the conflicts.

**Comment by toktarev** [comment]
The problem is that I've already created the same one (https://github.com/STEllAR-GROUP/hpx/pull/5288).

And @msimberg  made there some work (review).

**Comment by toktarev** [comment]
ReOpen option is disabled here

**Pull request closed without merging**
