### PR TITLE
Adding a check for end line whitespace

### PR DESCRIPTION
**Pull request by Bcorde5**
The two new files check whether or not files have white space in the end of the line, while the edits to the inspect.cpp file allow the other two files to work.

### CODE REVIEW

**Comment by hkaiser** [comment]
Have you run inspect on your source code yet? I'm sure it would raise several issues (at least using tabs and missing newline at the end of a file).

**Comment by Bcorde5** [comment]
Going to run it today, and make changes to all of my local files accordingly.

**Comment by hkaiser** [comment]
The new checker seems to run [fine](https://circle-artifacts.com/gh/STEllAR-GROUP/hpx/655/artifacts/0/tmp/circle-artifacts.KiAoioq/hpx_inspect_report.html)

LGTM.

**Comment by Bcorde5** [comment]
I did not mean to add these new changes to the pull request, how do I undo this, and create a new pull request?

**Comment by zao** [comment]
The state of the pull request is whatever state the branch you made it currently is at.
I tend to make separate branches for each pull request I make, so that when requirements change and feedback comes in, I can rewrite and force push my branch to make the PR contain exactly what I want.

I don't know if Github allows you to change what branch a PR is based from. If not, it's probably easiest to make a fresh named branch and a new PR with that branch.

See one of mine for how it'd look -- https://github.com/STEllAR-GROUP/hpx/pull/1044

**Comment by Bcorde5** [comment]
Thanks for the information, I guess this pull request might have to be as is, but in the future I guess I can make separate branches to create new pull requests.

**Comment by hkaiser** [comment]
I'd like to ask you to separate those changes into different PRs. We can close this PR and start over by creating separate ones for each of the checkers.

**Comment by Bcorde5** [comment]
Good idea, I will do it right now

**Comment by Bcorde5** [comment]
Tomorrow, I will do separate PRs

**Pull request closed without merging**
