### PR TITLE
Remove old compatibility bases from make_action

### PR DESCRIPTION
**Pull request by K-ballo**

### CODE REVIEW

**Comment by K-ballo** [comment]
> We should now be able to remove the specialization of the extract_action trait as well.

Was that specialization there only for handling cases of `extract_action<make_action<...>>`?

**Comment by hkaiser** [comment]
@K-ballo looks like I was wrong when I said we can remove the extract_action trait (https://circleci.com/gh/STEllAR-GROUP/hpx/94660)

**Comment by K-ballo** [comment]
> @K-ballo looks like I was wrong when I said we can remove the extract_action trait (https://circleci.com/gh/STEllAR-GROUP/hpx/94660)

Those actually break with just the base change too.

We'll have to start with only deprecating those bases, fixing the examples, and tightening `extract_action` to specialize only for the `make_action` traits.

**Comment by hkaiser** [comment]
> Those actually break with just the base change too.

Not sure about this...

> We'll have to start with only deprecating those bases, fixing the examples, and tightening extract_action to specialize only for the make_action traits.

I fully agree. Let's do it in stages.

**Comment by hkaiser** [comment]
@msimberg I think this is good to go. Please review and/or merge at your leasure.

**Pull request merged**
