### PR TITLE
Fix typos reported by fossies codespell report

### LINKED ISSUE #4940: Codespell report for "HPX" (on fossies.org)
The FOSS server https://fossies.org - since today also supporting "HPX" - offers a feature named "Source code misspelling reports":

 https://fossies.org/features.html#codespell

Such reports are normally only generated on request, but since I found in the tarball a file named `tools/.codespell_whitelist` as Fossies administrator I couldn't help forcing  nevertheless such a  [codespell](https://github.com/codespell-project/codespell) analysis for the new "HPX" release :

 https://fossies.org/linux/misc/hpx/codespell.html

That version-independent (not linked) URL should redirect always to the last report (if available), so currently to

 https://fossies.org/linux/misc/hpx-1.5.0.tar.gz/codespell.html

Ok, unsurprisingly only very few  misspellings and typos were found.

### PR DESCRIPTION
**Pull request by msimberg**
Fixes #4940. I've left typos that come from an external source (mainly PR titles).

### CODE REVIEW

**Review by aurianer — APPROVED** [review]
For the PRs title I think correcting them doesn't change the link to the PR right?

**Comment by hkaiser** [comment]
> For the PRs title I think correcting them doesn't change the link to the PR right?

No, changing the title doesn't change the link.

**Review by hkaiser — APPROVED** [review]
Thanks a lot for doing this!

**Comment by msimberg** [comment]
> > For the PRs title I think correcting them doesn't change the link to the PR right?
> 
> No, changing the title doesn't change the link.

Indeed. We can of course go back and edit titles of issues and PRs as well, but I didn't have the patience for that. Would you like me to do that as well?

**Comment by hkaiser** [comment]
> Indeed. We can of course go back and edit titles of issues and PRs as well, but I didn't have the patience for that. Would you like me to do that as well?

I don't think this is necessary.

**Pull request merged**
