### PR TITLE
working issue with MPI_CC / CC conflict in automake

### PR DESCRIPTION
**Pull request by ct-clmsn**
Fixes #

An issue with MPI_CC/CC conflict with gasnet-conduit-mpi autotools (autoconf in gasnet).

## Proposed Changes

  - set MPI_CC to the user set CMAKE_C_COMPILER
  - set ENV{MPI_CC} to CMAKE_C_COMPILER
  - set MPI_C_COMPILER to CMAKE_C_COMPILER
  
## Any background context you want to provide?

When gasnet compiles it automatically detects for mpi. If it finds MPI then MPI_CC is set. If MPI_CC is set to a compiler that does not match the CMAKE_C_COMPILER set by a user to compile gasnet, then a runtime exception happens during gasnet's build.

## Checklist

Not all points below apply to all pull requests.

- [ ] I have added a new feature and have added tests to go along with it.
- [ ] I have fixed a bug and have added a regression test.
- [ ] I have added a test using random numbers; I have made sure it uses a seed, and that random numbers generated are valid inputs for the tests.

### CODE REVIEW

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by ct-clmsn** [comment]
@hkaiser all should be good now

**Review by hkaiser — APPROVED** [review]

**Comment by hkaiser** [comment]
> @hkaiser all should be good now

Let's get this merged.

**Comment by hkaiser** [comment]
bors merge

**Pull request merged**
