### PR TITLE
Adding example demonstrating a possible safe-object implementation

### PR DESCRIPTION
**Pull request by hkaiser**

### CODE REVIEW

**Comment by hkaiser** [comment]
@zkhatami88 This should be useful to you.

**Comment by sithhell** [comment]
Why did you merge out twice? Shouldn't it be enough to merge it once?
Am 05.11.2015 1:39 vorm. schrieb "Hartmut Kaiser" <notifications@github.com

**Comment by hkaiser** [comment]
The PR against master did exist already. I thought I'd merge it instead of closing it. Later on we would have pushed the very same commit to master (via merging from release) anyways.

**Comment by sithhell** [comment]
Am 05.11.2015 1:44 nachm. schrieb "Hartmut Kaiser" <notifications@github.com
>:
>
> The PR against master did exist already. I thought I'd merge it instead
of closing it. Later on we would have pushed the very same commit to master
(via merging from release) anyways.

Yes sure, saves just one merge commit :p
I guess I would have closed it as duplicate...

**Pull request merged**
