### PR TITLE
Deprecating get_gid(), add get_id() and get_unmanaged_id()

### PR DESCRIPTION
**Pull request by hkaiser**
Deprecating component_base::get_gid(), add get_id() and get_unmanag_id()

This in a breaking change, for backwards compatibility, enable `HPX_WITH_COMPONENT_GET_GID_COMPATIBILITY` (default: ON).

### CODE REVIEW

**Comment by hkaiser** [comment]
This fixes #1624.

**Comment by hkaiser** [comment]
@koonschi This should solve your problem, please report back to us whether it does. 

Please note that you need to change your code to take advantage of the fix. Instead of calling `get_gid()`, please use` get_id()` on the server-side.

**Comment by Finomnis** [comment]
one important question though:

given a component with an component action test_action, then:

```c++
// implementation of test_action
void component::test(){
    // does hpx keep the component_id alive during execution of test_action?
    
    // otherwise, this:
    hpx::id_type new_id = get_id();
    // results in undefined behaviour.
}

/* ... */

void main(){
    // ...
    {
        hpx::id_type component_id;

        typedef component::test_acton action;
        apply<action>(component_id);
        //end of scope, component_id gets destroyed
    }
    // ...
}
```

so, question: does apply keep the current component id alive until after the action execution finished? if yes, everything is fine.

just as a side note to prevent future errors.

**Comment by hkaiser** [comment]
@Finomnis Do you have a failing test case? Otherwise I'll go ahead and merge this.

**Comment by Finomnis** [comment]
@hkaiser go ahead :)

**Pull request merged**
