### PR TITLE
Revert "Adding fedora docs"

### PR DESCRIPTION
**Pull request by sithhell**
This PR should be reverted. I see a couple of problems with this patch:
In general, I would like to avoid to have each linux distribution documented separately, this creates a maintenance nightmare in the end, I think a more appropriate place for information like this would be the Wiki. We already state the prerequisites in the docs. Installing those from the package manager should not require additional documentation from our end.
More specifically with this patch, the packages that get installed doesn't match the cmake configuration line, that is, there are some superfluous packages (the documentation toolchain, libsodium, hdf5 and openmpi).

### CODE REVIEW

**Comment by sithhell** [comment]
I would rather suggest to merge the information regarding what packages need to get installed on what distribution for which feature in the prerequisites page.

**Comment by hkaiser** [comment]
> I would rather suggest to merge the information regarding what packages need to get installed on what distribution for which feature in the prerequisites page.

I'd be fine with that. Will you add this to this PR?

**Comment by sithhell** [comment]
On 05/02/2016 02:03 PM, Hartmut Kaiser wrote:
>     I would rather suggest to merge the information regarding what
>     packages need to get installed on what distribution for which
>     feature in the prerequisites page.
> 
> I'd be fine with that. Will you add this to this PR?

I can do that when I find the time. But it's on a very low priority.

**Comment by hkaiser** [comment]
> I can do that when I find the time. But it's on a very low priority.

Why is removing the fedora docs very high-priority, then?

**Comment by sithhell** [comment]
well, I want to have my complaints documented.

**Comment by hkaiser** [comment]
> well, I want to have my complaints documented.

That would have been better documented as a ticket, then. As stated before, long living PRs are a maintenance nightmare, I'd rather close any PRs as quickly as possible.

**Comment by sithhell** [comment]
Am 02.05.2016 2:29 nachm. schrieb "Hartmut Kaiser" <notifications@github.com
>:
>>
>> well, I want to have my complaints documented.
>
> That would have been better documented as a ticket, then. As stated
before, long living PRs are a maintenance nightmare, I'd rather close any
PRs as quickly as possible.
>

So we are discussing the process now? Are there any technical issues with
what I proposed?
Regarding the process, I don't think that this particular set of changes
creates any conflicts. As did the original PR, but whatever. Will turn it
into an issue.

**Comment by sithhell** [comment]
Moving this to #2140

**Pull request closed without merging**
