### PR TITLE
lexicographic_compare accepts different iterator types (#3646)

### PR DESCRIPTION
**Pull request by wteiwewte**

### CODE REVIEW

**Comment by msimberg** [comment]
@wteiwewte you might want to check either the implementation or the test: https://circleci.com/gh/STEllAR-GROUP/hpx/85740 ;)

**Comment by wteiwewte** [comment]
I checked tests and didn't find any bugs. On my fork those tests are passing. What factors can contribute to different execution on ci ?

**Comment by hkaiser** [comment]
@weilewei the clang compiler on CircleCI has vectorization enabled by default (even for Debug builds). I'm not saying that this is the reason for the issues we're seeing, we just ran into this in different contexts before...

**Comment by msimberg** [comment]
@wteiwewte what compiler are you using? I see from our CI that the test fails with clang 4, clang 8, and gcc 9, but not with gcc 5. Is it possible that you're using some version of gcc older than 9? You could also use the docker image we use on CircleCI to get the exact same environment (`docker run -it stellargroup/build_env:ubuntu`).

**Pull request closed without merging**
