### PR TITLE
Separate segmented algorithms for transform

### PR DESCRIPTION
**Pull request by Jedi18**
Seperate segmented algorithms for transform
Replace tag_invoke with tag_fallback_invoke

## Any background context you want to provide?
Issue #5156 
Issue #5204

### CODE REVIEW

**Comment by msimberg** [comment]
retest

**Review by aurianer — DISMISSED** [review]
LGTM thanks a lot!

**Comment by aurianer** [comment]
retest

**Comment by Jedi18** [comment]
Thanks! I've rebased it onto master so it should be able to merge now

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by hkaiser** [comment]
retest

**Pull request merged**
