### PR TITLE
Moving some action tests to modules

### PR DESCRIPTION
**Pull request by hkaiser**
- flyby adding test for invoking apply for an action accepting an rvalue

### CODE REVIEW

**Comment by msimberg** [comment]
retest

**Comment by hkaiser** [comment]
Note, this is not ready by a long shot. More changes are needed.

**Comment by hkaiser** [comment]
This is ready for review now

**Review by msimberg — DISMISSED** [review]
Looks good to me, thanks! I'd like to still wait for the results from Rostam (which seems to not be up at the moment...).

**Comment by hkaiser** [comment]
retest lsu

**Comment by hkaiser** [comment]
The LSU tests are fine now as well, merging...

**Pull request merged**
