### PR TITLE
Tune lsu perf-test parameters to reduce inconsistency

### PR DESCRIPTION
**Pull request by Pansysk75**
After investigation, tuned parameters of the automated lsu performance tests, so that the measurements are more consistent between benchmark runs.

More details here:
https://gist.github.com/Pansysk75/fed0ba2a22dd09040b5cf0510fd6c4ae

### CODE REVIEW

**Comment by Pansysk75** [comment]
retest lsu

**Comment by Pansysk75** [comment]
@hkaiser It seems to behave as intended now. Let's hope this fix lasts a while. Feel free to merge if there are no objections.

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by hkaiser** [comment]
bors merge

**Pull request merged**
