### PR TITLE
Disable throttling scheduler if HWLOC is not found/used

### LINKED ISSUE #2807: Difficulty building with `HPX_WITH_HWLOC=Off`
I was trying to build HPX with `HPX_WITH_HWLOC=Off`

However, I get the following [make error](https://gist.github.com/bremerm31/f673068d51e088a24539526920a19de2)

zao in the IRC channel recommended just building with hwloc, which I will do. However, it might be nice to either deprecate the flag (if hwloc is truly a required dependency) or fix the include.

### PR DESCRIPTION
**Pull request by hkaiser**
- this is necessary as this scheduler directly uses HWLOC.
- this fixes #2807

### CODE REVIEW

**Comment by hkaiser** [comment]
@bremerm31 this should fix the issue you reported, please verify.

**Comment by bremerm31** [comment]
I'm getting the following error when trying to build: 

https://gist.github.com/bremerm31/63d03bc7c528ff76e336c79a513ab776

**Comment by hkaiser** [comment]
Ok, so there is more to it then I thought. Let me investigate one more time.

**Comment by hkaiser** [comment]
@bremerm31 what about now? Thanks!

**Pull request merged**
