### PR TITLE
Mind map

### PR DESCRIPTION
**Pull request by shoshijak**
Mind map of certain parts of the HPX source code, the API, hierarchy of classes etc. that I made during my internship at CSCS (March - June 2017) and could be useful for other people new to HPX (interns, students, GSoC, etc.).

### CODE REVIEW

**Comment by Praveenv98** [comment]
@shoshijak Thank you very much. It will be a huge help for beginners!

**Comment by hkaiser** [comment]
@shoshijak I assume this is generated somehow using some tools. Wouldn't it be better if we added a build step to the documentation tool chain which generates this on demand and uploads this as part of the documentation (http://stellar-group.github.io/hpx/docs/html/)? Otherwise the mind-map will become outdated very quickly...

**Comment by hkaiser** [comment]
@shoshijak: how did you generate this?

**Comment by mcopik** [comment]
@shoshijak I don't think that adding hundreds of images to the repository is a good idea. It might be generated during build but it should not be shipped with the source code.

**Comment by hkaiser** [comment]
Closing this as this needs build system integration and automation instead of dropping in a snapshot of things.

**Pull request closed without merging**
