### PR TITLE
Fix build of future_overhead when networking disabled

### PR DESCRIPTION
**Pull request by biddisco**
Changes to actions broke the benchmark

### CODE REVIEW

**Comment by msimberg** [comment]
When did this break? This passed just yesterday (https://cdash.cscs.ch/viewConfigure.php?buildid=105758 and https://cdash.cscs.ch/testDetails.php?test=20975245&build=105758).

**Comment by biddisco** [comment]
might just be another stale cache problem...

**Comment by biddisco** [comment]
Today's master 
```
[6/7] Building CXX object tests/performance/local/CMakeFiles/future_overhead_test.dir/future_overhead.cpp.o
FAILED: tests/performance/local/CMakeFiles/future_overhead_test.dir/future_overhead.cpp.o 
/usr/bin/g++  -DBOOST_DISABLE_ASSERTS -DHPX_APPLICATION_EXPORTS -DHPX_APPLICATION_NAME=future_overhead_test -DHPX_APPLICATION_NAME_DEFAULT=future_overhead_test -DHPX_APPLICATION_STRING=\"future_overhead_test\" -DHPX_DISABLE_ASSERTS -DHPX_PREFIX=\"/home/biddisco/build/hpx-release\" -DHPX_PREFIX_DEFAULT=\"/usr/local\" -D_GNU_SOURCE -I/home/biddisco/src/hpx -I. -I/home/biddisco/src/hpx/libs/affinity/include -Ilibs/affinity/include -I/home/biddisco/src/hpx/libs/affinity/include_compatibility -I/home/biddisco/src/hpx/libs/algorithms/include -Ilibs/algorithms/include -I/home/biddisco/src/hpx/libs/algorithms/include_compatibility -I/home/biddisco/src/hpx/libs/allocator_support/include -Ilibs/allocator_support/include -I/home/biddisco/src/hpx/libs/allocator_support/include_compatibility -I/home/biddisco/src/hpx/libs/asio/include -Ilibs/asio/include -I/home/biddisco/src/hpx/libs/asio/include_compatibility -I/home/biddisco/src/hpx/libs/assertion/include -Ilibs/assertion/include -I/home/biddisco/src/hpx/libs/assertion/include_compatibility -I/home/biddisco/src/hpx/libs/async/include -Ilibs/async/include -I/home/biddisco/src/hpx/libs/async/include_compatibility -I/home/biddisco/src/hpx/libs/async_base/include -Ilibs/async_base/include -I/home/biddisco/src/hpx/libs/async_combinators/include -Ilibs/async_combinators/include -I/home/biddisco/src/hpx/libs/async_combinators/include_compatibility -I/home/biddisco/src/hpx/libs/basic_execution/include -Ilibs/basic_execution/include -I/home/biddisco/src/hpx/libs/basic_execution/include_compatibility -I/home/biddisco/src/hpx/libs/batch_environments/include -Ilibs/batch_environments/include -I/home/biddisco/src/hpx/libs/batch_environments/include_compatibility -I/home/biddisco/src/hpx/libs/cache/include -Ilibs/cache/include -I/home/biddisco/src/hpx/libs/cache/include_compatibility -I/home/biddisco/src/hpx/libs/checkpoint/include -Ilibs/checkpoint/include -I/home/biddisco/src/hpx/libs/checkpoint/include_compatibility -I/home/biddisco/src/hpx/libs/collectives/include -Ilibs/collectives/include -I/home/biddisco/src/hpx/libs/collectives/include_compatibility -I/home/biddisco/src/hpx/libs/command_line_handling/include -Ilibs/command_line_handling/include -I/home/biddisco/src/hpx/libs/command_line_handling/include_compatibility -I/home/biddisco/src/hpx/libs/compute/include -Ilibs/compute/include -I/home/biddisco/src/hpx/libs/compute/include_compatibility -I/home/biddisco/src/hpx/libs/compute_cuda/include -Ilibs/compute_cuda/include -I/home/biddisco/src/hpx/libs/concepts/include -Ilibs/concepts/include -I/home/biddisco/src/hpx/libs/concepts/include_compatibility -I/home/biddisco/src/hpx/libs/concurrency/include -Ilibs/concurrency/include -I/home/biddisco/src/hpx/libs/concurrency/include_compatibility -I/home/biddisco/src/hpx/libs/config/include -Ilibs/config/include -I/home/biddisco/src/hpx/libs/coroutines/include -Ilibs/coroutines/include -I/home/biddisco/src/hpx/libs/coroutines/include_compatibility -I/home/biddisco/src/hpx/libs/datastructures/include -Ilibs/datastructures/include -I/home/biddisco/src/hpx/libs/datastructures/include_compatibility -I/home/biddisco/src/hpx/libs/debugging/include -Ilibs/debugging/include -I/home/biddisco/src/hpx/libs/debugging/include_compatibility -I/home/biddisco/src/hpx/libs/distributed_executors/include -Ilibs/distributed_executors/include -I/home/biddisco/src/hpx/libs/distributed_executors/include_compatibility -I/home/biddisco/src/hpx/libs/errors/include -Ilibs/errors/include -I/home/biddisco/src/hpx/libs/errors/include_compatibility -I/home/biddisco/src/hpx/libs/execution/include -Ilibs/execution/include -I/home/biddisco/src/hpx/libs/execution/include_compatibility -I/home/biddisco/src/hpx/libs/filesystem/include -Ilibs/filesystem/include -I/home/biddisco/src/hpx/libs/format/include -Ilibs/format/include -I/home/biddisco/src/hpx/libs/format/include_compatibility -I/home/biddisco/src/hpx/libs/functional/include -Ilibs/functional/include -I/home/biddisco/src/hpx/libs/functional/include_compatibility -I/home/biddisco/src/hpx/libs/hardware/include -Ilibs/hardware/include -I/home/biddisco/src/hpx/libs/hardware/include_compatibility -I/home/biddisco/src/hpx/libs/hashing/include -Ilibs/hashing/include -I/home/biddisco/src/hpx/libs/hashing/include_compatibility -I/home/biddisco/src/hpx/libs/include/include -Ilibs/include/include -I/home/biddisco/src/hpx/libs/io_service/include -Ilibs/io_service/include -I/home/biddisco/src/hpx/libs/io_service/include_compatibility -I/home/biddisco/src/hpx/libs/iterator_support/include -Ilibs/iterator_support/include -I/home/biddisco/src/hpx/libs/iterator_support/include_compatibility -I/home/biddisco/src/hpx/libs/local_async/include -Ilibs/local_async/include -I/home/biddisco/src/hpx/libs/local_lcos/include -Ilibs/local_lcos/include -I/home/biddisco/src/hpx/libs/local_lcos/include_compatibility -I/home/biddisco/src/hpx/libs/logging/include -Ilibs/logging/include -I/home/biddisco/src/hpx/libs/logging/include_compatibility -I/home/biddisco/src/hpx/libs/memory/include -Ilibs/memory/include -I/home/biddisco/src/hpx/libs/naming_base/include -Ilibs/naming_base/include -I/home/biddisco/src/hpx/libs/pack_traversal/include -Ilibs/pack_traversal/include -I/home/biddisco/src/hpx/libs/pack_traversal/include_compatibility -I/home/biddisco/src/hpx/libs/performance_counters/include -Ilibs/performance_counters/include -I/home/biddisco/src/hpx/libs/plugin/include -Ilibs/plugin/include -I/home/biddisco/src/hpx/libs/plugin/include_compatibility -I/home/biddisco/src/hpx/libs/prefix/include -Ilibs/prefix/include -I/home/biddisco/src/hpx/libs/prefix/include_compatibility -I/home/biddisco/src/hpx/libs/preprocessor/include -Ilibs/preprocessor/include -I/home/biddisco/src/hpx/libs/preprocessor/include_compatibility -I/home/biddisco/src/hpx/libs/program_options/include -Ilibs/program_options/include -I/home/biddisco/src/hpx/libs/resiliency/include -Ilibs/resiliency/include -I/home/biddisco/src/hpx/libs/resource_partitioner/include -Ilibs/resource_partitioner/include -I/home/biddisco/src/hpx/libs/resource_partitioner/include_compatibility -I/home/biddisco/src/hpx/libs/runtime_configuration/include -Ilibs/runtime_configuration/include -I/home/biddisco/src/hpx/libs/runtime_configuration/include_compatibility -I/home/biddisco/src/hpx/libs/schedulers/include -Ilibs/schedulers/include -I/home/biddisco/src/hpx/libs/schedulers/include_compatibility -I/home/biddisco/src/hpx/libs/segmented_algorithms/include -Ilibs/segmented_algorithms/include -I/home/biddisco/src/hpx/libs/segmented_algorithms/include_compatibility -I/home/biddisco/src/hpx/libs/serialization/include -Ilibs/serialization/include -I/home/biddisco/src/hpx/libs/serialization/include_compatibility -I/home/biddisco/src/hpx/libs/static_reinit/include -Ilibs/static_reinit/include -I/home/biddisco/src/hpx/libs/static_reinit/include_compatibility -I/home/biddisco/src/hpx/libs/statistics/include -Ilibs/statistics/include -I/home/biddisco/src/hpx/libs/statistics/include_compatibility -I/home/biddisco/src/hpx/libs/string_util/include -Ilibs/string_util/include -I/home/biddisco/src/hpx/libs/synchronization/include -Ilibs/synchronization/include -I/home/biddisco/src/hpx/libs/synchronization/include_compatibility -I/home/biddisco/src/hpx/libs/testing/include -Ilibs/testing/include -I/home/biddisco/src/hpx/libs/testing/include_compatibility -I/home/biddisco/src/hpx/libs/thread_executors/include -Ilibs/thread_executors/include -I/home/biddisco/src/hpx/libs/thread_executors/include_compatibility -I/home/biddisco/src/hpx/libs/thread_pools/include -Ilibs/thread_pools/include -I/home/biddisco/src/hpx/libs/thread_pools/include_compatibility -I/home/biddisco/src/hpx/libs/thread_support/include -Ilibs/thread_support/include -I/home/biddisco/src/hpx/libs/thread_support/include_compatibility -I/home/biddisco/src/hpx/libs/threading/include -Ilibs/threading/include -I/home/biddisco/src/hpx/libs/threading/include_compatibility -I/home/biddisco/src/hpx/libs/threading_base/include -Ilibs/threading_base/include -I/home/biddisco/src/hpx/libs/threading_base/include_compatibility -I/home/biddisco/src/hpx/libs/threadmanager/include -Ilibs/threadmanager/include -I/home/biddisco/src/hpx/libs/threadmanager/include_compatibility -I/home/biddisco/src/hpx/libs/timing/include -Ilibs/timing/include -I/home/biddisco/src/hpx/libs/timing/include_compatibility -I/home/biddisco/src/hpx/libs/topology/include -Ilibs/topology/include -I/home/biddisco/src/hpx/libs/topology/include_compatibility -I/home/biddisco/src/hpx/libs/type_support/include -Ilibs/type_support/include -I/home/biddisco/src/hpx/libs/type_support/include_compatibility -I/home/biddisco/src/hpx/libs/util/include -Ilibs/util/include -I/home/biddisco/src/hpx/libs/util/include_compatibility -I/home/biddisco/src/hpx/libs/version/include -Ilibs/version/include -I/home/biddisco/src/hpx/init/include -Iinit/include -I/home/biddisco/src/hpx/components/iostreams/include -isystem /home/biddisco/apps/cxx17/boost/1.69.0/include -isystem /home/biddisco/apps/jemalloc/5.2.1/include -isystem /home/biddisco/apps/hwloc/2.1.0/include -fPIC -march=native -mtune=native -ffast-math -std=c++17 -O3 -DNDEBUG   -pthread -Wall -Wextra -Wno-unused-local-typedefs -Wno-strict-aliasing -Wno-sign-promo -Wno-attributes -Wno-cast-align -Wno-noexcept-type -Wno-unused-parameter -Wformat=2 -Wno-format-nonliteral -Winit-self -Wdouble-promotion -Wcast-qual -Wcast-align -Werror=trampolines -Werror=parentheses -Werror=reorder -Werror=return-type -Werror=sequence-point -Werror=uninitialized -Werror=format -Werror=missing-braces -Werror=sign-compare -fdiagnostics-show-option -Werror=vla -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-maybe-uninitialized -Wno-sync-nand -Wno-delete-non-virtual-dtor -fvisibility=hidden -MD -MT tests/performance/local/CMakeFiles/future_overhead_test.dir/future_overhead.cpp.o -MF tests/performance/local/CMakeFiles/future_overhead_test.dir/future_overhead.cpp.o.d -o tests/performance/local/CMakeFiles/future_overhead_test.dir/future_overhead.cpp.o -c /home/biddisco/src/hpx/tests/performance/local/future_overhead.cpp
In file included from /home/biddisco/src/hpx/hpx/lcos/base_lco.hpp:11,
                 from /home/biddisco/src/hpx/hpx/lcos/base_lco_with_value.hpp:13,
                 from /home/biddisco/src/hpx/hpx/runtime/agas/server/primary_namespace.hpp:15,
                 from /home/biddisco/src/hpx/libs/async/include/hpx/async/applier/detail/apply_colocated.hpp:19,
                 from /home/biddisco/src/hpx/libs/include/include/hpx/include/apply.hpp:10,
                 from /home/biddisco/src/hpx/tests/performance/local/future_overhead.cpp:11:
/home/biddisco/src/hpx/hpx/runtime/actions/basic_action.hpp: In instantiation of ‘struct hpx::actions::make_action<double (*)() noexcept, null_function, null_action>’:
/home/biddisco/src/hpx/tests/performance/local/future_overhead.cpp:134:1:   required from here
/home/biddisco/src/hpx/hpx/runtime/actions/basic_action.hpp:560:12: error: invalid use of incomplete type ‘struct hpx::actions::action<double (*)() noexcept, null_function, null_action>’
  560 |     struct make_action
      |            ^~~~~~~~~~~
/home/biddisco/src/hpx/hpx/runtime/actions/basic_action.hpp:530:12: note: declaration of ‘struct hpx::actions::action<double (*)() noexcept, null_function, null_action>’
  530 |     struct action;
      |            ^~~~~~
In file included from /home/biddisco/src/hpx/libs/errors/include/hpx/errors/throw_exception.hpp:18,
                 from /home/biddisco/src/hpx/libs/errors/include/hpx/errors/exception_fwd.hpp:69,
                 from /home/biddisco/src/hpx/libs/errors/include/hpx/errors/error_code.hpp:15,
                 from libs/errors/include/hpx/errors.hpp:16,
                 from /home/biddisco/src/hpx/hpx/hpx_finalize.hpp:13,
                 from /home/biddisco/src/hpx/hpx/hpx_init.hpp:16,
                 from /home/biddisco/src/hpx/tests/performance/local/future_overhead.cpp:10:
/home/biddisco/src/hpx/hpx/runtime/actions/plain_action.hpp:223:40: error: invalid use of incomplete type ‘using type = struct hpx::actions::action<double (*)() noexcept, null_function, null_action>’ {aka ‘struct hpx::actions::action<double (*)() noexcept, null_function, null_action>’}
  223 |         decltype(&func), &func, name>::type {}                                \
      |                                        ^~~~
/home/biddisco/src/hpx/libs/preprocessor/include/hpx/preprocessor/expand.hpp:24:26: note: in definition of macro ‘HPX_PP_EXPAND’
   24 | #define HPX_PP_EXPAND(X) X
      |                          ^
/home/biddisco/src/hpx/hpx/runtime/actions/plain_action.hpp:198:5: note: in expansion of macro ‘HPX_PP_EXPAND’
  198 |     HPX_PP_EXPAND(HPX_PP_CAT(                                                 \
      |     ^~~~~~~~~~~~~
/home/biddisco/src/hpx/libs/preprocessor/include/hpx/preprocessor/cat.hpp:37:28: note: in expansion of macro ‘HPX_DEFINE_PLAIN_ACTION_2’
   37 | #define HPX_PP_CAT_I(a, b) a##b
      |                            ^
/home/biddisco/src/hpx/libs/preprocessor/include/hpx/preprocessor/cat.hpp:29:26: note: in expansion of macro ‘HPX_PP_CAT_I’
   29 | #define HPX_PP_CAT(a, b) HPX_PP_CAT_I(a, b)
      |                          ^~~~~~~~~~~~
/home/biddisco/src/hpx/hpx/runtime/actions/plain_action.hpp:198:19: note: in expansion of macro ‘HPX_PP_CAT’
  198 |     HPX_PP_EXPAND(HPX_PP_CAT(                                                 \
      |                   ^~~~~~~~~~
/home/biddisco/src/hpx/hpx/runtime/actions/plain_action.hpp:188:5: note: in expansion of macro ‘HPX_DEFINE_PLAIN_ACTION_’
  188 |     HPX_DEFINE_PLAIN_ACTION_(__VA_ARGS__)                                     \
      |     ^~~~~~~~~~~~~~~~~~~~~~~~
/home/biddisco/src/hpx/hpx/runtime/actions/plain_action.hpp:365:5: note: in expansion of macro ‘HPX_DEFINE_PLAIN_ACTION’
  365 |     HPX_DEFINE_PLAIN_ACTION(func, name);                                      \
      |     ^~~~~~~~~~~~~~~~~~~~~~~
/home/biddisco/src/hpx/libs/preprocessor/include/hpx/preprocessor/cat.hpp:37:28: note: in expansion of macro ‘HPX_PLAIN_ACTION_2’
   37 | #define HPX_PP_CAT_I(a, b) a##b
      |                            ^
/home/biddisco/src/hpx/libs/preprocessor/include/hpx/preprocessor/cat.hpp:29:26: note: in expansion of macro ‘HPX_PP_CAT_I’
   29 | #define HPX_PP_CAT(a, b) HPX_PP_CAT_I(a, b)
      |                          ^~~~~~~~~~~~
/home/biddisco/src/hpx/hpx/runtime/actions/plain_action.hpp:360:19: note: in expansion of macro ‘HPX_PP_CAT’
  360 |     HPX_PP_EXPAND(HPX_PP_CAT(                                                 \
      |                   ^~~~~~~~~~
/home/biddisco/src/hpx/hpx/runtime/actions/plain_action.hpp:293:5: note: in expansion of macro ‘HPX_PLAIN_ACTION_’
  293 |     HPX_PLAIN_ACTION_(__VA_ARGS__)                                            \
      |     ^~~~~~~~~~~~~~~~~
/home/biddisco/src/hpx/tests/performance/local/future_overhead.cpp:134:1: note: in expansion of macro ‘HPX_PLAIN_ACTION’
  134 | HPX_PLAIN_ACTION(null_function, null_action)
      | ^~~~~~~~~~~~~~~~
In file included from /home/biddisco/src/hpx/hpx/lcos/base_lco.hpp:11,
                 from /home/biddisco/src/hpx/hpx/lcos/base_lco_with_value.hpp:13,
                 from /home/biddisco/src/hpx/hpx/runtime/agas/server/primary_namespace.hpp:15,
                 from /home/biddisco/src/hpx/libs/async/include/hpx/async/applier/detail/apply_colocated.hpp:19,
                 from /home/biddisco/src/hpx/libs/include/include/hpx/include/apply.hpp:10,
                 from /home/biddisco/src/hpx/tests/performance/local/future_overhead.cpp:11:
/home/biddisco/src/hpx/hpx/runtime/actions/basic_action.hpp:530:12: note: declaration of ‘using type = struct hpx::actions::action<double (*)() noexcept, null_function, null_action>’ {aka ‘struct hpx::actions::action<double (*)() noexcept, null_function, null_action>’}
  530 |     struct action;
      |            ^~~~~~
In file included from /home/biddisco/src/hpx/hpx/traits/action_continuation.hpp:10,
                 from /home/biddisco/src/hpx/libs/async/include/hpx/async/applier/apply_helper.hpp:19,
                 from /home/biddisco/src/hpx/libs/async/include/hpx/async/applier/apply.hpp:13,
                 from /home/biddisco/src/hpx/libs/async/include/hpx/async/applier/apply_continue.hpp:12,
                 from /home/biddisco/src/hpx/libs/async/include/hpx/async/applier/detail/apply_colocated.hpp:13,
                 from /home/biddisco/src/hpx/libs/include/include/hpx/include/apply.hpp:10,
                 from /home/biddisco/src/hpx/tests/performance/local/future_overhead.cpp:11:
/home/biddisco/src/hpx/hpx/traits/extract_action.hpp: In instantiation of ‘struct hpx::traits::extract_action<null_action, void>’:
/home/biddisco/src/hpx/libs/async/include/hpx/async/async.hpp:129:9:   required from ‘struct hpx::detail::async_action_dispatch<null_action, hpx::naming::id_type, void>’
/home/biddisco/src/hpx/libs/async/include/hpx/async/async_fwd.hpp:31:49:   required by substitution of ‘template<class Action, class F, class ... Ts> decltype (hpx::detail::async_action_dispatch<Action, typename hpx::util::decay<T>::type>::call(forward<F>(f), (forward<Ts>)(hpx::async::ts)...)) hpx::async(F&&, Ts&& ...) [with Action = null_action; F = const hpx::naming::id_type&; Ts = {}]’
/home/biddisco/src/hpx/tests/performance/local/future_overhead.cpp:154:50:   required from here
/home/biddisco/src/hpx/hpx/traits/extract_action.hpp:17:15: error: no type named ‘derived_type’ in ‘struct null_action’
   17 |         using type = typename Action::derived_type;
      |               ^~~~
/home/biddisco/src/hpx/tests/performance/local/future_overhead.cpp: In function ‘void measure_action_futures_wait_each(uint64_t, bool)’:
/home/biddisco/src/hpx/tests/performance/local/future_overhead.cpp:154:50: error: no matching function for call to ‘async<null_action>(const hpx::naming::id_type&)’
  154 |         futures.push_back(async<null_action>(here));
      |                                                  ^
In file included from /home/biddisco/src/hpx/libs/async/include/hpx/async.hpp:11,
                 from /home/biddisco/src/hpx/libs/include/include/hpx/include/async.hpp:10,
                 from /home/biddisco/src/hpx/tests/performance/local/future_overhead.cpp:12:
/home/biddisco/src/hpx/libs/async/include/hpx/async/async.hpp:196:26: note: candidate: ‘template<class Action, class F, class ... Ts> decltype (hpx::detail::async_action_dispatch<Action, typename hpx::util::decay<T>::type>::call(forward<F>(f), (forward<Ts>)(hpx::async::ts)...)) hpx::async(F&&, Ts&& ...)’
  196 |     HPX_FORCEINLINE auto async(F&& f, Ts&&... ts)
      |                          ^~~~~
/home/biddisco/src/hpx/libs/async/include/hpx/async/async.hpp:196:26: note:   substitution of deduced template arguments resulted in errors seen above
In file included from /home/biddisco/src/hpx/libs/local_async/include/hpx/local_async/async.hpp:11,
                 from /home/biddisco/src/hpx/libs/async/include/hpx/async/async_fwd.hpp:13,
                 from /home/biddisco/src/hpx/hpx/runtime/actions/action_priority.hpp:11,
                 from /home/biddisco/src/hpx/libs/async/include/hpx/async/applier/apply.hpp:17,
                 from /home/biddisco/src/hpx/libs/async/include/hpx/async/applier/apply_continue.hpp:12,
                 from /home/biddisco/src/hpx/libs/async/include/hpx/async/applier/detail/apply_colocated.hpp:13,
                 from /home/biddisco/src/hpx/libs/include/include/hpx/include/apply.hpp:10,
                 from /home/biddisco/src/hpx/tests/performance/local/future_overhead.cpp:11:
/home/biddisco/src/hpx/libs/async_base/include/hpx/async_base/async.hpp:23:26: note: candidate: ‘template<class F, class ... Ts> decltype (hpx::detail::async_dispatch<typename hpx::util::decay<Action>::type>::call(forward<F>(f), (forward<Ts>)(hpx::async::ts)...)) hpx::async(F&&, Ts&& ...)’
   23 |     HPX_FORCEINLINE auto async(F&& f, Ts&&... ts)
      |                          ^~~~~
/home/biddisco/src/hpx/libs/async_base/include/hpx/async_base/async.hpp:23:26: note:   template argument deduction/substitution failed:
/home/biddisco/src/hpx/tests/performance/local/future_overhead.cpp:154:46: note:   cannot convert ‘here’ (type ‘const hpx::naming::id_type’) to type ‘null_action&&’
  154 |         futures.push_back(async<null_action>(here));
      |                                              ^~~~
/home/biddisco/src/hpx/tests/performance/local/future_overhead.cpp: In function ‘void measure_action_futures_wait_all(uint64_t, bool)’:
/home/biddisco/src/hpx/tests/performance/local/future_overhead.cpp:172:50: error: no matching function for call to ‘async<null_action>(const hpx::naming::id_type&)’
  172 |         futures.push_back(async<null_action>(here));
      |                                                  ^
In file included from /home/biddisco/src/hpx/libs/async/include/hpx/async.hpp:11,
                 from /home/biddisco/src/hpx/libs/include/include/hpx/include/async.hpp:10,
                 from /home/biddisco/src/hpx/tests/performance/local/future_overhead.cpp:12:
/home/biddisco/src/hpx/libs/async/include/hpx/async/async.hpp:196:26: note: candidate: ‘template<class Action, class F, class ... Ts> decltype (hpx::detail::async_action_dispatch<Action, typename hpx::util::decay<T>::type>::call(forward<F>(f), (forward<Ts>)(hpx::async::ts)...)) hpx::async(F&&, Ts&& ...)’
  196 |     HPX_FORCEINLINE auto async(F&& f, Ts&&... ts)
      |                          ^~~~~
/home/biddisco/src/hpx/libs/async/include/hpx/async/async.hpp:196:26: note:   template argument deduction/substitution failed:
In file included from /home/biddisco/src/hpx/hpx/runtime/actions/action_priority.hpp:11,
                 from /home/biddisco/src/hpx/libs/async/include/hpx/async/applier/apply.hpp:17,
                 from /home/biddisco/src/hpx/libs/async/include/hpx/async/applier/apply_continue.hpp:12,
                 from /home/biddisco/src/hpx/libs/async/include/hpx/async/applier/detail/apply_colocated.hpp:13,
                 from /home/biddisco/src/hpx/libs/include/include/hpx/include/apply.hpp:10,
                 from /home/biddisco/src/hpx/tests/performance/local/future_overhead.cpp:11:
/home/biddisco/src/hpx/libs/async/include/hpx/async/async_fwd.hpp: In substitution of ‘template<class Action, class F, class ... Ts> decltype (hpx::detail::async_action_dispatch<Action, typename hpx::util::decay<T>::type>::call(forward<F>(f), (forward<Ts>)(hpx::async::ts)...)) hpx::async(F&&, Ts&& ...) [with Action = null_action; F = const hpx::naming::id_type&; Ts = {}]’:
/home/biddisco/src/hpx/tests/performance/local/future_overhead.cpp:172:50:   required from here
/home/biddisco/src/hpx/libs/async/include/hpx/async/async_fwd.hpp:31:49: error: ‘call’ is not a member of ‘hpx::detail::async_action_dispatch<null_action, hpx::naming::id_type, void>’
   30 |         -> decltype(detail::async_action_dispatch<Action,
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   31 |             typename util::decay<F>::type>::call(std::forward<F>(f),
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
   32 |             std::forward<Ts>(ts)...));
      |             ~~~~~~~~~~~~~~~~~~~~~~~~             
In file included from /home/biddisco/src/hpx/libs/local_async/include/hpx/local_async/async.hpp:11,
                 from /home/biddisco/src/hpx/libs/async/include/hpx/async/async_fwd.hpp:13,
                 from /home/biddisco/src/hpx/hpx/runtime/actions/action_priority.hpp:11,
                 from /home/biddisco/src/hpx/libs/async/include/hpx/async/applier/apply.hpp:17,
                 from /home/biddisco/src/hpx/libs/async/include/hpx/async/applier/apply_continue.hpp:12,
                 from /home/biddisco/src/hpx/libs/async/include/hpx/async/applier/detail/apply_colocated.hpp:13,
                 from /home/biddisco/src/hpx/libs/include/include/hpx/include/apply.hpp:10,
                 from /home/biddisco/src/hpx/tests/performance/local/future_overhead.cpp:11:
/home/biddisco/src/hpx/libs/async_base/include/hpx/async_base/async.hpp:23:26: note: candidate: ‘template<class F, class ... Ts> decltype (hpx::detail::async_dispatch<typename hpx::util::decay<Action>::type>::call(forward<F>(f), (forward<Ts>)(hpx::async::ts)...)) hpx::async(F&&, Ts&& ...)’
   23 |     HPX_FORCEINLINE auto async(F&& f, Ts&&... ts)
      |                          ^~~~~
/home/biddisco/src/hpx/libs/async_base/include/hpx/async_base/async.hpp:23:26: note:   template argument deduction/substitution failed:
/home/biddisco/src/hpx/tests/performance/local/future_overhead.cpp:172:46: note:   cannot convert ‘here’ (type ‘const hpx::naming::id_type’) to type ‘null_action&&’
  172 |         futures.push_back(async<null_action>(here));
      |                                              ^~~~
In file included from /home/biddisco/src/hpx/hpx/lcos/base_lco.hpp:11,
                 from /home/biddisco/src/hpx/hpx/lcos/base_lco_with_value.hpp:13,
                 from /home/biddisco/src/hpx/hpx/runtime/agas/server/primary_namespace.hpp:15,
                 from /home/biddisco/src/hpx/libs/async/include/hpx/async/applier/detail/apply_colocated.hpp:19,
                 from /home/biddisco/src/hpx/libs/include/include/hpx/include/apply.hpp:10,
                 from /home/biddisco/src/hpx/tests/performance/local/future_overhead.cpp:11:
/home/biddisco/src/hpx/hpx/runtime/actions/basic_action.hpp: In instantiation of ‘void hpx::actions::detail::register_local_action_invocation_count(hpx::actions::detail::invocation_count_registry&) [with Action = null_action]’:
/home/biddisco/src/hpx/hpx/runtime/actions/detail/invocation_count_registry.hpp:79:59:   required from ‘hpx::actions::detail::register_action_invocation_count<Action>::register_action_invocation_count() [with Action = null_action]’
/home/biddisco/src/hpx/hpx/runtime/actions/detail/invocation_count_registry.hpp:93:9:   required from ‘hpx::actions::detail::register_action_invocation_count<null_action> hpx::actions::detail::register_action_invocation_count<null_action>::instance’
/home/biddisco/src/hpx/tests/performance/local/future_overhead.cpp:134:1:   required from here
/home/biddisco/src/hpx/hpx/runtime/actions/basic_action.hpp:503:17: error: ‘get_invocation_count’ is not a member of ‘null_action’
  503 |                 &Action::get_invocation_count
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
```

**Comment by biddisco** [comment]
I just assumed that since local and dsitributed runtime were being separated, this must have broken the actions. Not sure what the right fix is to be honest.

**Comment by msimberg** [comment]
@biddisco what commit and cmake configuration do you have? I just built `future_overhead_test` successfully on 54ed1bbf82e9658c22d239561c6b53dd4b9bbf5b with `cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DHPX_WITH_MALLOC=system -DHPX_WITH_NETWORKING=OFF`.

**Comment by biddisco** [comment]
`commit 54ed1bbf82e9658c22d239561c6b53dd4b9bbf5b`
```
rm -rf * 
cmake       -DCMAKE_BUILD_TYPE=Debug       -DBOOST_ROOT=$BOOST_ROOT       -DHWLOC_ROOT=$INSTALL_ROOT/hwloc/$HWLOC_VER       -DHPX_WITH_MALLOC=JEMALLOC       -DJEMALLOC_ROOT=$INSTALL_ROOT/jemalloc/$JEMALLOC_VER       -DHPX_WITH_NETWORKING:BOOL=OFF ~/src/hpx
```
`make future_overhead_test`
```
In file included from /home/biddisco/src/hpx/hpx/lcos/base_lco.hpp:11,
                 from /home/biddisco/src/hpx/hpx/lcos/base_lco_with_value.hpp:13,
                 from /home/biddisco/src/hpx/hpx/runtime/agas/server/primary_namespace.hpp:15,
                 from /home/biddisco/src/hpx/libs/async/include/hpx/async/applier/detail/apply_colocated.hpp:19,
                 from /home/biddisco/src/hpx/libs/include/include/hpx/include/apply.hpp:10,
                 from /home/biddisco/src/hpx/tests/performance/local/future_overhead.cpp:11:
/home/biddisco/src/hpx/hpx/runtime/actions/basic_action.hpp: In instantiation of ‘struct hpx::actions::make_action<double (*)() noexcept, null_function, null_action>’:
/home/biddisco/src/hpx/tests/performance/local/future_overhead.cpp:134:1:   required from here
/home/biddisco/src/hpx/hpx/runtime/actions/basic_action.hpp:560:12: error: invalid use of incomplete type ‘struct hpx::actions::action<double (*)() noexcept, null_function, null_action>’
  560 |     struct make_action
```

**Comment by biddisco** [comment]
Note - above build was using c++17 settings

**Comment by msimberg** [comment]
Can you try removing `noexcept` from `null_function`?

**Comment by hkaiser** [comment]
> Note - above build was using c++17 settings

How did you specify that? Your cmake line above doesn't have that. Also, what compiler version is this?

Also, please post the full cmake output.

**Comment by biddisco** [comment]
ok, seems there was a mismatch between my env vars asking for c++17 flags and c++17 boost but hpx choosing c++14. build is ok if I add `HPX_WITH_CXX17=ON`

**Pull request closed without merging**
