### PR TITLE
Fix partitioned vector include in partitioned_vector_find tests

### PR DESCRIPTION
**Pull request by msimberg**
Fixes failures like [these](http://rostam.cct.lsu.edu/builders/hpx_clang_3_9_boost_1_62_centos_x86_64_release/builds/10/steps/run_unit_tests/logs/tests.unit.parallel.segmented_algorithms.distributed.tcp.partitioned_vector_find%20%280.78%20sec%29).

### CODE REVIEW

**Comment by msimberg** [comment]
The `move` that `clang_tidy` is complaining about looks intentional. Is it?

**Comment by hkaiser** [comment]
> The move that clang_tidy is complaining about looks intentional. Is it?

This is a genuine bug, should be using `std::forward` instead.

**Comment by msimberg** [comment]
Thanks @hkaiser, changed it.

**Comment by hkaiser** [comment]
Thanks @msimberg, much appreciated!

**Pull request merged**
