### PR TITLE
Fixing the output formatting for id_types

### PR DESCRIPTION
**Pull request by hkaiser**
This fixes the wrong output reported here: https://gist.github.com/severinstrobl/bfba712aa4a03454e5fbab65bd70046e

### CODE REVIEW

**Comment by severinstrobl** [comment]
Thanks, with this change i get the expected output, where different IDs in the format `{0000000x00000000, 0000000000000000}` are printed.

**Review by msimberg — DISMISSED** [review]
Thanks @hkaiser. Would a regression test for this be possible? I suppose we don't expect to at least be all zeros?

**Review by aurianer — DISMISSED** [review]
LGTM thanks!

**Comment by hkaiser** [comment]
@msimberg I have added the test now.

**Pull request merged**
