### PR TITLE
Adding timestamp option for S390x platform

### LINKED ISSUE #3511: Build on s390x fails
## Expected Behavior

Builds

## Actual Behavior

Fails:
```
[  676s] [ 12%] Building CXX object src/CMakeFiles/hpx.dir/runtime/threads/coroutines/swapcontext.cpp.o
[  676s] cd /home/abuild/rpmbuild/BUILD/hpx-1.2.0-rc1/build/src && /usr/bin/c++  -DBOOST_DISABLE_ASSERTS -DHPX_COMPONENT_NAME=hpx -DHPX_DISABLE_ASSERTS -DHPX_ENABLE_ASSERT_HANDLER -DHPX_EXPORTS -D_GNU_SOURCE -Dhpx_EXPORTS -I/home/abuild/rpmbuild/BUILD/hpx-1.2.0-rc1 -I/home/abuild/rpmbuild/BUILD/hpx-1.2.0-rc1/build  -O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -DNDEBUG -O2 -g -DNDEBUG -fPIC   -pthread -Wall -Wextra -Wno-unused-local-typedefs -Wno-strict-aliasing -Wno-sign-promo -Wno-attributes -Wno-cast-align -Wno-unused-parameter -Wformat=2 -Wno-format-nonliteral -Winit-self -Wdouble-promotion -Wcast-qual -Wcast-align -Werror=trampolines -Werror=parentheses -Werror=reorder -Werror=return-type -Werror=sequence-point -Werror=uninitialized -Werror=format -Werror=missing-braces -Werror=sign-compare -fdiagnostics-show-option -Werror=vla -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-maybe-uninitialized -Wno-sync-nand -Wno-delete-non-virtual-dtor -fvisibility=hidden -std=c++17 -o CMakeFiles/hpx.dir/runtime/threads/coroutines/swapcontext.cpp.o -c /home/abuild/rpmbuild/BUILD/hpx-1.2.0-rc1/src/runtime/threads/coroutines/swapcontext.cpp
[  676s] /home/abuild/rpmbuild/BUILD/hpx-1.2.0-rc1/src/runtime/threads/coroutines/swapcontext.cpp:19:2: error: #error Unsupported platform
[  676s]  #error Unsupported platform
[  676s]   ^~~~~
[  676s] make[2]: *** [src/CMakeFiles/hpx.dir/build.make:1028: src/CMakeFiles/hpx.dir/runtime/threads/coroutines/swapcontext.cpp.o] Error 1
```

## Steps to Reproduce the Problem

Build on s390x, details [here](https://github.com/STEllAR-GROUP/hpx/files/2531946/build_s390x.txt)

## Specifications

  - HPX Version: 1.2.0-rc1
  - Platform (compiler, OS): gcc-8.2.1, OpenSuse

### PR DESCRIPTION
**Pull request by hkaiser**
Fixes #3511

### CODE REVIEW

**Comment by hkaiser** [comment]
@msimberg FWIW, I added this to the 1.2.1 milestone. We should consider having it in the point release

**Comment by msimberg** [comment]
> Somehow boost_context is not provided on this arch and I could not compile hpx and test this pr.

Looks relevant: https://github.com/openmainframeproject/tsc/blob/master/proposed_projects/Boost%20Context.md. I think we can live without s390x for now.

**Comment by hkaiser** [comment]
@diehlpk I think we just miss a `!defined(__s390x__)` here: https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/runtime/threads/coroutines/detail/context_impl.hpp#L116 and a `defined(__s390x__)` here: https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/runtime/threads/coroutines/detail/context_impl.hpp#L125. Also you shouldn't try to compile on that platform using the Boost context library.

**Comment by hkaiser** [comment]
@diehlpk could you trigger a new build, please? Please also remove the `-DHPX_WITH_GENERIC_CONTEXT_COROUTINES=On` for this platform.

**Comment by diehlpk** [comment]
@hkaiser Still some unsupported plattform error https://koji.fedoraproject.org/koji/watchlogs?taskID=32537060

**Comment by diehlpk** [comment]
@hkaiser Your latest commit compiles, but does not link 

https://kojipkgs.fedoraproject.org//work/tasks/8921/32538921/build.log

**Comment by diehlpk** [comment]
@hkaiser The latest commit resolves in 

```
BUILDSTDERR: /builddir/build/BUILD/hpx_1.2.1/src/runtime/threads/coroutines/swapcontext.cpp:19:2: error: #error Unsupported platform
BUILDSTDERR:    19 | #error Unsupported platform
```
on s390x, arm64, and arm7. 

https://koji.fedoraproject.org/koji/taskinfo?taskID=32541821

**Comment by diehlpk** [comment]
@hkaiser Could you revert the last commit, there is some special behaviour on fedora on s390x and I could resolve it, but not using your latest commit.

**Comment by diehlpk** [comment]
Somehow arm7 fails now not due to memory consumption, it fails because of 

```
/BUILD/hpx_1.2.1/src/runtime/threads/coroutines/swapcontext.cpp
BUILDSTDERR: /builddir/build/BUILD/hpx_1.2.1/src/runtime/threads/coroutines/swapcontext.cpp:19:2: error: #error Unsupported platform
BUILDSTDERR:    19 | #error Unsupported platform
BUILDSTDERR:       |  ^~~~~
BUILDSTDERR: make[2]: *** [src/CMakeFiles/hpx.dir/build.make:1002: src/CMakeFiles/hpx.dir/runtime/threads/coroutines/swapcontext.cpp.o] Error 1
```

https://kojipkgs.fedoraproject.org//work/tasks/4907/32544907/build.log

**Comment by hkaiser** [comment]
@diehlpk On ARM architectures we do need the Boost context library, please add `-DHPX_WITH_GENERIC_CONTEXT_COROUTINES=On` for that platform.

> Could you revert the last commit, there is some special behaviour on fedora on s390x and I could resolve it, but not using your latest commit.

Feel free to push to this branch with any changes you have to apply.

**Comment by diehlpk** [comment]
@hkaiser I already used this flag to build on arm for f28 and f29, but somehow it is not working anymore
```

%build
# use generic context for these archs
%ifarch aarch64 armv7hl
%define cmake_opts -DHPX_WITH_GENERIC_CONTEXT_COROUTINES=ON
%endif
```

**Comment by hkaiser** [comment]
@diehlpk from the logs you linked above I see:
```
+ /usr/bin/cmake -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG \
    -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG \
    -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG \
    -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
    -DCMAKE_INSTALL_PREFIX:PATH=/usr \
    -DINCLUDE_INSTALL_DIR:PATH=/usr/include \
    -DLIB_INSTALL_DIR:PATH=/usr/lib \
    -DSYSCONF_INSTALL_DIR:PATH=/etc \
    -DSHARE_INSTALL_PREFIX:PATH=/usr/share \
    -DBUILD_SHARED_LIBS:BOOL=ON \
    -DLIB=lib \
    -DCMAKE_CXX_FLAGS=-O2 -g -pipe -Wall -Werror=format-security \
    -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS \
    -fexceptions -fstack-protector-strong -grecord-gcc-switches \
    -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 \
    -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 \
    -march=armv7-a -mfpu=vfpv3-d16 -mtune=generic-armv7-a \
    -mabi=aapcs-linux -mfloat-abi=hard -O1
```
which tells me that the flag is not passed down to the cmake invocation...

**Comment by hkaiser** [comment]
Also, somehow the build still reports HPX V1.2.0 I think you're missing some of @msimberg's patches.

**Comment by hkaiser** [comment]
> It seems that the HPX version is not updated in the 1.2.1-rc candidate

@msimberg ping?

**Comment by msimberg** [comment]
> > It seems that the HPX version is not updated in the 1.2.1-rc candidate
> 
> @msimberg ping?

I've just fixed that on the release branch. I'll make a PR to generate the version header based on the values in `CMakeLists.txt`, this is a bit too error prone...

**Pull request merged**
