### PR TITLE
fix returning non default constructable objects from action

### PR DESCRIPTION
**Pull request by kleinhenz**
Refixes #2847

## Proposed Changes

The ability to return a non default constructable object from an action was broken by ba7153c7fcc9cb63b9d8398314595a00cf6a6991 because of a missing negation of `std::is_default_constructible<T>`.
This wasn't caught by CI because the current test doesn't actually attempt to save or load any construction data.

## Checklist
- [x] I have fixed a bug and have added a regression test.

### CODE REVIEW

**Comment by kleinhenz** [comment]
This looks like it was fixed on master by 23c910c08ee616394f4adeed639462deb2691a55 but opening this to fix the 1.7.X branch.

**Comment by hkaiser** [comment]
@kleinhenz We do not plan to make a point release for V1.7 at this point. How important is that fix for you for this version? We plan to release V1.8 soon, would that be sufficient for you?

**Comment by kleinhenz** [comment]
ok I will close if there won't be another point release. I can wait for 1.8.

**Comment by hkaiser** [comment]
@kleinhenz thanks for submitting the patch in any case! Much appreciated.

**Pull request closed without merging**
