### PR TITLE
Moving files to (distributed) runtime module

### PR DESCRIPTION
**Pull request by hkaiser**
- moving related files to their respective modules
- removing leftover files from previous module refactorings

### CODE REVIEW

**Comment by hkaiser** [comment]
@msimberg this is ready for review now. I don't understand why the spellcheck is complaining about a word that is in the spellcheck whitelist, any ideas?

**Comment by msimberg** [comment]
> @msimberg this is ready for review now. I don't understand why the spellcheck is complaining about a word that is in the spellcheck whitelist, any ideas?

That's strange behaviour from codespell. Please see https://github.com/STEllAR-GROUP/hpx/pull/5227.

**Review by msimberg — DISMISSED** [review]
Looks good to me!

**Comment by msimberg** [comment]
This just needs another clang-format round, but please feel free to merge after that!

**Pull request merged**
