### PR TITLE
Add rotate and rotate_copy sender overloads

### PR DESCRIPTION
**Pull request by hcq9102**
Add sender overloads to parallel algorithms.

### CODE REVIEW

**Review by hkaiser — APPROVED** [review]
Wow, that was quick! LGTM, thanks!

**Comment by msimberg** [comment]
Thanks @hcq9102. The CircleCI run failed spectacularly, but I'm not sure it's due to this PR (I very much doubt it). I've restarted the builds there and hopefully they'll come back clean.

**Comment by hcq9102** [comment]
> Thanks @hcq9102. The CircleCI run failed spectacularly, but I'm not sure it's due to this PR (I very much doubt it). 
yes, I checked the result of **build_and_test**, can not figure out why. 

> I've restarted the builds there and hopefully they'll come back clean.
Thanks for your work and time.

**Comment by hcq9102** [comment]
> Thanks @hcq9102. The CircleCI run failed spectacularly, but I'm not sure it's due to this PR (I very much doubt it). 

yes, I noticed that and checked the failed details of build_and_test, can not figure out why.

> I've restarted the builds there and hopefully they'll come back clean.

Thanks for your work and time.

**Comment by msimberg** [comment]
One more try... it actually looks like the errors might be triggered by the changes here, though I've no clue how yet.

**Comment by hkaiser** [comment]
> One more try... it actually looks like the errors might be triggered by the changes here, though I've no clue how yet.

This is really strange. I don't understand what's going on either.

**Comment by hcq9102** [comment]
> > One more try... it actually looks like the errors might be triggered by the changes here, though I've no clue how yet.
> 
> This is really strange. I don't understand what's going on either.

Thanks for your time. @hkaiser  @msimberg 

I tried to look at it and found one thing might lead to these test failure.
When I recompiled after making this "Add sender overloads to parallel algorithms" changes, the compiler complains like [https://gist.github.com/hcq9102/fc1e95481df78c7965681d56139f4617](https://gist.github.com/hcq9102/fc1e95481df78c7965681d56139f4617)
it points out my current workstation lacks  _.../hpx/parallel/util/detail/sender_util.hpp_ file. 
 I realized that I didn't **git pull** the updated hpx into my local station. 
then I updated my local files.  
doing compile and the test, they are all fine as before.

So do you think is this mistake(didn't update files) leads to the tests failed spectacularly?  I doubt my local files lacks will lead to this, but I am not sure about this.

**Comment by msimberg** [comment]
> So do you think is this mistake(didn't update files) leads to the tests failed spectacularly? I doubt that, but I am not sure about this.

It would be weird, but not impossible. CircleCI doesn't merge/rebase with master before running the tests, so the build should in fact fail there if your branch isn't up to date (it should just ideally not fail like this). Please rebase on master and let's see if the failures remain.

**Comment by hcq9102** [comment]
> > So do you think is this mistake(didn't update files) leads to the tests failed spectacularly? I doubt that, but I am not sure about this.
> 
> It would be weird, but not impossible. CircleCI doesn't merge/rebase with master before running the tests, so the build should in fact fail there if your branch isn't up to date (it should just ideally not fail like this). Please rebase on master and let's see if the failures remain.

Got it, will try. Thanks a lot.

**Pull request closed without merging**
