### PR TITLE
Add non-contiguous index queue and use it in thread_pool_bulk_scheduler

### PR DESCRIPTION
**Pull request by hkaiser**
This changes the sequence of partitions scheduled on the same core.

@hcq9102 Could you please run your performance scripts for the S/R executor using PR to see if this behaves differently for larger numbers of cores?

### CODE REVIEW

**Comment by hkaiser** [comment]
Closing this as the change makes things worse, performance-wise.

**Comment by hkaiser** [comment]
Re-opening this as after all this might have some uses (for instance for find() and friends).

**Comment by hkaiser** [comment]
@Pansysk75 this PR enables controlling the placement strategies (breadth-first or depth-first) in the scheduler (currently supported for S/R only). A couple of algorithms are being adapted to take advantage of breadth-first placement. This also enables using S/R with `hpx::find`.

So what this already could be used for is to see whether `hpx::find` performance really improves when changing the placement strategies.

**Comment by Pansysk75** [comment]
> @Pansysk75 this PR enables controlling the placement strategies (breadth-first or depth-first) in the scheduler (currently supported for S/R only). A couple of algorithms are being adapted to take advantage of breadth-first placement. This also enables using S/R with `hpx::find`.

I'll check it out, nice! Just a quick thought:
I made a list of algorithms that are expected to benefit from this scheduling (find, mismatch, search, etc. that return an iterator to the first occurance). 
I would not expect algorithms that return a bool (all_of, equal, etc.) to benefit from this scheduling, since for these we don't care about "first occurance" of something, so we aren't as pressed to immediately schedule the first chunks of the container. Those should cancel as soon as there's any "match", anywhere.

**Comment by hkaiser** [comment]
@Pansysk75 There is also `find_end` (and similar) that would require scheduling things backwards as we're interested in finding the last occurence...

**Comment by hkaiser** [comment]
bors merge

**Pull request merged**
