### PR TITLE
Attempting to fix hangs in distributed barrier

### PR DESCRIPTION
**Pull request by hkaiser**
@biddisco could you please try whether this improves the situation?

### CODE REVIEW

**Comment by biddisco** [comment]
> @biddisco could you please try whether this improves the situation?

Out of 72, 19 completed correctly, so I would say that this patch made no difference. I see that the branch has been force pushed overnight, so I will run again with `-DHPX_WITH_THREAD_DEBUG_INFO=On` using this version.

**Comment by biddisco** [comment]
https://cloud.cscs.ch/owncloud/index.php/s/lmrMKszQANOv2E8 
contains some log data from a new run, but it does not look terribly interesting.

**Comment by hkaiser** [comment]
> https://cloud.cscs.ch/owncloud/index.php/s/lmrMKszQANOv2E8 contains some log data from a new run, but it does not look terribly interesting.

Thanks John! Would it be possible to collect another set of logs using `--hpx:0:debug-hpx-log` and `--hpx:debug-app-log` (don't restrict the latter for locality zero, please) and with `-DHPX_WITH_THREAD_DEBUG_INFO=On`?

**Comment by biddisco** [comment]
https://cloud.cscs.ch/owncloud/index.php/s/yHCfKOZj6dh8AY8
contains new trace with settings as requested

**Comment by hkaiser** [comment]
@biddisco thanks for the logs. Also, after merging #5773 it might be worth trying master again as this PR completely replaces the barrier implementation (amongst other things). We can be almost sure that it's not the barrier that is causing the problems if we still see the same hangs now.

**Pull request merged**
