### PR TITLE
Add missing header for std::intmax_t

### PR DESCRIPTION
**Pull request by jwakely**

### CODE REVIEW

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by hkaiser** [comment]
bors merge

**Comment by hkaiser** [comment]
@jwakely Congratulations, your first PR to the HPX repository has just been merged! As a 'thank you' we offer a free STE||AR-Group t-shirt to all of our first-time contributors. If you are interested in receiving one, please get back to me directly so we can set up the delivery.

**Comment by jwakely** [comment]
Thanks, but I have too many t-shirts already!

**Pull request merged**
