### PR TITLE
Fix macOS test exceptions

### PR DESCRIPTION
**Pull request by aacirino**
Fixes an exception in `hpx::any` due to type mismatch in the definition and use of command options.

## Proposed Changes

Use the same type, `std::size_t`, in the definition and use of the command options.

### CODE REVIEW

**Review by hkaiser — DISMISSED** [review]
LGTM, thanks!

**Review by hkaiser — CHANGES_REQUESTED** [review]
@aacirino thanks for your work on this! May I suggest to separate the MacOS fix for the thraed binding into its own PR?

**Comment by msimberg** [comment]
Thanks @aacirino. May I ask what exact problem you encountered on macOS to trigger that change? I ask because while handling command line options we warn about using `--hpx:use-process-mask` and disable it: https://github.com/STEllAR-GROUP/hpx/blob/acc57413f3bb734b742d2cea12bfd4b54cf2828d/libs/full/command_line_handling/src/command_line_handling.cpp#L746-L755. I'm guessing either that doesn't work correctly or you are using parts of HPX without the command line handling?

**Comment by aacirino** [comment]
Sure, but I don't know why Github added my last commit to my fork to this PR. I intended to open another pull request since I have not yet finished working in the thread binding issue.

> @aacirino thanks for your work on this! May I suggest to separate the MacOS fix for the thraed binding into its own PR?

**Comment by aacirino** [comment]
The issue is an exception raised due to lack of full macOS support by hwloc and it happens in a test with no command line option `--hpx:use-process-mask`. I was not aware of this option and am still learning HPX. Currently my application is in a very early stage where HPX isn't yet used. I am just using the unit and regression tests that fail in macOS to try to help the project.

> Thanks @aacirino. May I ask what exact problem you encountered on macOS to trigger that change? I ask because while handling command line options we warn about using `--hpx:use-process-mask` and disable it: https://github.com/STEllAR-GROUP/hpx/blob/acc57413f3bb734b742d2cea12bfd4b54cf2828d/libs/full/command_line_handling/src/command_line_handling.cpp#L746-L755. I'm guessing either that doesn't work correctly or you are using parts of HPX without the command line handling?

**Comment by msimberg** [comment]
> The issue is an exception raised due to lack of full macOS support by hwloc and it happens in a test with no command line option `--hpx:use-process-mask`. I was not aware of this option and am still learning HPX. Currently my application is in a very early stage where HPX isn't yet used. I am just using the unit and regression tests that fail in macOS to try to help the project.
> 
> > Thanks @aacirino. May I ask what exact problem you encountered on macOS to trigger that change? I ask because while handling command line options we warn about using `--hpx:use-process-mask` and disable it: https://github.com/STEllAR-GROUP/hpx/blob/acc57413f3bb734b742d2cea12bfd4b54cf2828d/libs/full/command_line_handling/src/command_line_handling.cpp#L746-L755
> > . I'm guessing either that doesn't work correctly or you are using parts of HPX without the command line handling?

Ah, is it `standalone_thread_pool_executor` by any chance? It does not use the command line handling and uses the `affinity_data` struct directly. It would fit your fixes...

**Comment by aacirino** [comment]
> > The issue is an exception raised due to lack of full macOS support by hwloc and it happens in a test with no command line option `--hpx:use-process-mask`. I was not aware of this option and am still learning HPX. Currently my application is in a very early stage where HPX isn't yet used. I am just using the unit and regression tests that fail in macOS to try to help the project.
> 
> > 
> 
> > > Thanks @aacirino. May I ask what exact problem you encountered on macOS to trigger that change? I ask because while handling command line options we warn about using `--hpx:use-process-mask` and disable it: https://github.com/STEllAR-GROUP/hpx/blob/acc57413f3bb734b742d2cea12bfd4b54cf2828d/libs/full/command_line_handling/src/command_line_handling.cpp#L746-L755
> 
> > > . I'm guessing either that doesn't work correctly or you are using parts of HPX without the command line handling?
> 
> 
> 
> Ah, is it `standalone_thread_pool_executor` by any chance? It does not use the command line handling and uses the `affinity_data` struct directly. It would fit your fixes...

It is indeed `standalone_thread_pool_executor`. I see the use of the `___APPLE___` compile-time serving two purposes: a way to circumvent the issue with hwloc and as a marker so that we know where to change code when hwloc implements the functionality. For me using the compile-time flag `___APPLE___` is better than adding a command line option to the test execution.

**Comment by msimberg** [comment]
@aacirino what's the status of these changes? @hkaiser would you still like to see this split up into two PRs?

**Comment by aacirino** [comment]
> @aacirino what's the status of these changes? @hkaiser would you still like to see this split up into two PRs?

It is OK for me to keep one pull request. As a matter of fact I would like this PR to be closed ASAP because I have a commit to make that does not need to be included in the PR. I hope someday there will be an easy way to add commits to a fork without including the changes in an upstream open PR.

**Comment by msimberg** [comment]
> I hope someday there will be an easy way to add commits to a fork without including the changes in an upstream open PR.

The easiest way to do that is to create a separate branch. PRs are branch-specific, not fork-specific.

**Comment by msimberg** [comment]
bors merge

**Review by msimberg — APPROVED** [review]

**Comment by msimberg** [comment]
bors merge

**Pull request merged**
