### PR TITLE
Moving LCO related files to modules

### PR DESCRIPTION
**Pull request by hkaiser**

### CODE REVIEW

**Comment by hkaiser** [comment]
@aurianer could this failure be related to the recent changes to the base image: https://app.circleci.com/pipelines/github/STEllAR-GROUP/hpx/6946/workflows/397303e6-e791-42f4-aff3-910373d7f5d9/jobs/241472?

**Comment by aurianer** [comment]
Possibly the code coverage PR also modified the way we installed cmake, will have a look

**Comment by aurianer** [comment]
Actually it was an old leftover, for the checkout and install step we were still using the image 1, @msimberg has a PR on its way :)

**Comment by msimberg** [comment]
> Actually it was an old leftover, for the checkout and install step we were still using the image 1, @msimberg has a PR on its way :)

See #5226.

**Review by msimberg — APPROVED** [review]
Looks good, thanks!

Edit: except for the circular dependency (and cmake formatting) :/

**Comment by msimberg** [comment]
retest lsu

**Pull request merged**
