### PR TITLE
Fixing datapar

### PR DESCRIPTION
**Pull request by srinivasyadav18**
Fixes #

## Proposed Changes

  - Format datapar/transform_loop.hpp
  - Fix in_in_out_result
  - Fix tests/datapar_algorithms

## Any background context you want to provide?
https://github.com/STEllAR-GROUP/hpx/pull/5235#issuecomment-803026630

### CODE REVIEW

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by msimberg** [comment]
Can we please combine this with #5235 (I don't mind which one to keep)? I'd like to see circleci build successfully with the datapar option enabled (which #5235 enables) before merging. If there are independent refactorings/optimizations those can go in a separate PR.

**Comment by hkaiser** [comment]
> Can we please combine this with #5235 (I don't mind which one to keep)? I'd like to see circleci build successfully with the datapar option enabled (which #5235 enables) before merging. If there are independent refactorings/optimizations those can go in a separate PR.

@msimberg this is a PR against #5235. I'm planning to finalize that first and then merge this PR over before merging everything to master,

**Comment by msimberg** [comment]
> > Can we please combine this with #5235 (I don't mind which one to keep)? I'd like to see circleci build successfully with the datapar option enabled (which #5235 enables) before merging. If there are independent refactorings/optimizations those can go in a separate PR.
> 
> @msimberg this is a PR against #5235. I'm planning to finalize that first and then merge this PR over before merging everything to master,

Sorry for the noise, I missed that it wasn't against master!

**Pull request merged**
