### PR TITLE
Improve integration of futures and senders

### PR DESCRIPTION
**Pull request by hkaiser**
Relies on #5413

### CODE REVIEW

**Review by msimberg — DISMISSED** [review]
Thanks, looks good to me!

For some reason this seems to have the commits from #5406 in the diff, but perhaps that'll go away with a rebase...

**Comment by msimberg** [comment]
retest

**Comment by hkaiser** [comment]
> For some reason this seems to have the commits from #5406 in the diff, but perhaps that'll go away with a rebase...

I'll rebase once #5413 has been merged.

**Comment by hkaiser** [comment]
> > For some reason this seems to have the commits from #5406 in the diff, but perhaps that'll go away with a rebase...
> 
> I'll rebase once #5413 has been merged.

@msimberg this should be fine now.

**Comment by msimberg** [comment]
Pushed some cosmetic changes. Otherwise this still looks good.

**Comment by hkaiser** [comment]
> Pushed some cosmetic changes. Otherwise this still looks good.

Thanks!

**Comment by msimberg** [comment]
launch perftests

**Comment by hkaiser** [comment]
retest lsu

**Pull request merged**
