### PR TITLE
Adapt lexicographical_compare to C++20

### PR DESCRIPTION
**Pull request by Jedi18**
Adapted lexicographical_compare to C++ 20 and added container overloads. (range and sentinel)

## Any background context you want to provide?
Issue #4822
Issue #3646
Issue #1668

### CODE REVIEW

**Comment by hkaiser** [comment]
add to whitelist

**Comment by hkaiser** [comment]
@Jedi18 The newly added test fails compiling: https://app.circleci.com/pipelines/github/STEllAR-GROUP/hpx/7708/workflows/3673147f-437e-43bc-9448-64f158db2bc2/jobs/251639/steps. Could you please have a look?

**Comment by Jedi18** [comment]
@hkaiser Sure ok done, sorry for the delay in fixing that

**Comment by hkaiser** [comment]
@Jedi18 please note that with #5348 we will rename our `tag_invoke` facilities. That might affect your work. Please have an eye out for this.

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
