### PR TITLE
Cublas demo

### PR DESCRIPTION
**Pull request by biddisco**
Demonstrates how to mix calls to CUDA cublas with hpx futures

### CODE REVIEW

**Comment by hkaiser** [comment]
@biddisco Thanks a lot! Does this now work with Boost V1.63 as well?

Also, could you please configure clang-format such that it does not align assignments and variable declarations?

**Comment by biddisco** [comment]
I added an #ifdef xxx_CUDA_ALLOCATOR around all the code that used the cuda::allocator and replaced the allocation and parallel::copy with  cudaMalloc and cudaMemcpy - this means we can use the c++ compiler and everything compiles fine with any boost etc. When using the allocator, I was not able to get the nvcc compiler to work and did not want to remove all lambdas, so currently it will only compile (for me) using the non allocator version. My collaborators assure me that they will never use the allocators/copy/compute/etc that hpx provides and just need a demo that shows how to mix cublas and futures.

**Comment by biddisco** [comment]
I "align assignments and variable declarations" by hand because I like it. Are you telling me to stop?

**Comment by hkaiser** [comment]
> I "align assignments and variable declarations" by hand because I like it. Are you telling me to stop?

We don't align variables or assignments anywhere else. But we don't enforce any particular style, only encourage authors not to change formatting in existing files. We also encourage authors to keep formatting of changed lines in existing files consistent with the existing style.

**Comment by biddisco** [comment]
I have put the indentations/alignments I changed back the way they were.

**Pull request merged**
