### PR TITLE
Basename registration

### PR DESCRIPTION
**Pull request by hkaiser**
- Rename register_id_with_basename --> register_with_basename
- Rename find_id[s]_from_basename --> find_from_basename
- Rename find_all_ids_from_basename --> find_all_from_basename
- Rename unregister_id_with_basename --> unregister_with_basename
- Added equivalent functions taking/returning client objects instead of ids/futures to ids

### CODE REVIEW

**Comment by hkaiser** [comment]
@quantomb if this gets merged it will break the parquet code. But it will also allow simplify and streamline the code you have as the new API now accepts `future<id_type>` in addition to where the old API was expecting just an `id_type`.

**Comment by quantomb** [comment]
@hkaiser Thank you. These changes won't take much modification to the code as is. Thanks for the heads up.

**Comment by sithhell** [comment]
It's a breaking change to anyone using that api. I suggest to inform the ML
before going ahead with merging it.

**Comment by hkaiser** [comment]
>  I suggest to inform the ML before going ahead with merging it.

Done (http://thread.gmane.org/gmane.comp.lib.hpx.devel/296)

**Pull request merged**
