### PR TITLE
Fix #3124

### LINKED ISSUE #3124: Add hello_world_component to CI builds
hello_world_component is deliberately excluded from the cmake build as it is intended to illustrate building by command line. It should be explicitly added to CI builds, to prevent it from accidentally breaking.

### PR DESCRIPTION
**Pull request by NK-Nikunj**
Fixes #3124 

## Proposed Changes

  - Added CMakeLists.txt in examples/hello_world_component specific only to external builds. This CMakeLists.txt will not be executed while running cmake for building hpx.
  - Added cmake script in circle.yml to integrate the hello_world_component into CI build.

### Edit
  - Fixed a typo in documentation for "using_hpx_pkgconfig".

### CODE REVIEW

**Comment by hkaiser** [comment]
@NK-Nikunj This PR contains the same changes as #3176. Should we close that other one without merging or will you remove that commit from this one?

**Comment by NK-Nikunj** [comment]
@hkaiser I forgot to see that commit to #3176 is also added here. Since this commit has been added to this one as well, I feel you can close #3176. I will edit the proposed changes above to include the changes done in #3176 as well.

**Comment by msimberg** [comment]
@NK-Nikunj The hello world component is failing during cmake configuration (you can see the output by clicking on details on the circleci entry). I believe you need to change `HPX_DIR` to `../build/lib/cmake/HPX` in order for HPX to be found correctly ([see docs](https://stellar-group.github.io/hpx/docs/html/hpx.html#hpx.manual.build_system.using_hpx.using_hpx_cmake)).

**Comment by hkaiser** [comment]
@NK-Nikunj have you deleted all of the actual code now? Also, please note that if you rely on pkg-config, this has to be enabled for Linux systems only (or if pkg-config was found by cmake).

**Comment by NK-Nikunj** [comment]
@hkaiser, @sithhell told me to build hello_world_component to test pkg-config instead of the test code that was given in the src. That's why I deleted the src folder.

**Comment by hkaiser** [comment]
To re-iterate: the purpose of the original example was to demonstrate how an external program depending on HPX can be built. We ran into issues as at some point the example was not compiling anymore. #3124 proposed to solve this by adding the code to the CI system, ensuing that any future changes wouldn't break the example. 

Now, this PR proposes not only proposes to build another example, it also proposes to remove the original example source code (sorry if I misunderstand things). Could you please explain your rationale in more detail?

**Comment by NK-Nikunj** [comment]
@hkaiser I think you have misunderstood what I have proposed. When I asked @sithhell for implementation, he told me that the previous example was being built externally. He told me to build the hello_world_component from that build. The example is 

What I have done is simply redirect the tests/unit/build/CMakelists.txt to invoke examples/hello_world_component/CMakelists.txt instead of the tests/unit/build/src/CMakelists.txt. Also, I have changed the Makefile accordingly so that hello_world_client can be built. The hello_world_component cmake can also be invoked by a user if he wishes to build hello_world_component by also passing HPX_DIR into cmake command.

**Pull request merged**
