### PR TITLE
Fixing 1763

### PR DESCRIPTION
**Pull request by AntonBikineev**

### CODE REVIEW

**Comment by AntonBikineev** [comment]
operator new(size_t) is useless because when calling new thread_data lookup doesn't go to outmost namespaces and overload resolution says no, no overload

**Comment by K-ballo** [comment]
The "won't be called" stuff that actually "might be called" makes me uneasy. If those certainly won't be called, and given that's a requirement for the program to be well-formed, why not enforcing that requirement by the design?

**Comment by AntonBikineev** [comment]
@K-ballo ugh, the first point is absolutely correct, thanks.
In what scenarios that operator new(size_t) "might be called"? What do you suggest? I personally don't like those run-time assertions and would rather prefer having it deleted to cause link-time error.

**Comment by hkaiser** [comment]
@AntonBikineev can we close this now?

**Comment by AntonBikineev** [comment]
@hkaiser think so

**Pull request closed without merging**
