### PR TITLE
Fix check for pu-step in single-core case

### LINKED ISSUE #5358: HPX init fails for single-core environments
## Expected Behavior

It should be possible to launch a HPX application on systems with only one CPU core/PU available.

## Actual Behavior

The initialization of HPX fails with:
> hpx::init: std::exception caught: Invalid command line option --hpx:pu-step, value must be non-zero and smaller than number of available processing units.

## Steps to Reproduce the Problem

The problem can be reproduced by launching a HPX application after taking all but one CPU offline or by limiting the number of PUs in an batch environment, which is how I encountered the issue in the first place. I used the `os_thread_num` example in conjunction with `srun -N 1 -n 1 -c 1` to reproduce the issue.

## Specifications

  - HPX Version: 1.7.0/master
  - Platform (compiler, OS): GCC 9.3, Linux, SLURM

### PR DESCRIPTION
**Pull request by severinstrobl**
Fixes #5358

### CODE REVIEW

**Review by hkaiser — DISMISSED** [review]
LGTM, thanks!

**Comment by hkaiser** [comment]
add to whitelist

**Comment by hkaiser** [comment]
@severinstrobl Thanks a lot!

**Comment by hkaiser** [comment]
@severinstrobl could you please apply the same fix here as well: https://github.com/STEllAR-GROUP/hpx/blob/master/libs/full/command_line_handling_local/src/command_line_handling_local.cpp#L425

**Comment by severinstrobl** [comment]
@hkaiser Certainly, I completely missed that.

**Review by hkaiser — APPROVED** [review]
LGTM, thanks! This is good to go now - this time for sure.

**Pull request merged**
