### PR TITLE
Add GCC 11 builder to jenkins

### PR DESCRIPTION
**Pull request by msimberg**
This also triggered the error reported in https://github.com/STEllAR-GROUP/hpx/issues/5275. I've simply made the conversion explicit, but I don't know if there's a more proper fix for the issue.

### CODE REVIEW

**Review by aurianer — DISMISSED** [review]
LGTM thanks!

**Comment by hkaiser** [comment]
> This also triggered the error reported in #5275. I've simply made the conversion explicit, but I don't know if there's a more proper fix for the issue.

That works as well. Thanks!

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by msimberg** [comment]
Sigh... one more try. This was missing the slurm constraint for `gcc-10`.

**Pull request merged**
