### PR TITLE
Applying quick fix for hwloc-2.0

### LINKED ISSUE #3221: HPX on Mac OS X with HWLoc 2.0.0 fails to run
## Expected Behavior

```
$ ./build/bin/hello_world_exe
hello world from OS-thread 5 on locality 0
hello world from OS-thread 6 on locality 0
hello world from OS-thread 7 on locality 0
hello world from OS-thread 0 on locality 0
hello world from OS-thread 1 on locality 0
hello world from OS-thread 3 on locality 0
hello world from OS-thread 4 on locality 0
hello world from OS-thread 2 on locality 0
```

## Actual Behavior

```
$ ./build/bin/hello_world_exe
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: partitioner::setup_pools: Default pool default has no threads assigned. Please rerun with --hpx:threads=X and check the pool thread assignment
Abort trap: 6
```

## Steps to Reproduce the Problem

  1. OS X 10.13.3 with hwloc 2.0.0 (installed by home-brew)
  1. Build HPX either in Release or Debug version
  1. Run hello_world_exe

```bash
brew install hwloc
mkdir build
cd build

cmake /Users/svanzwam/coding/hpx1.1/repo \
      -GNinja \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=/Users/svanzwam/coding/hpx1.1/install

ninja hello_world_exe
```
## Specifications

  - HPX Version: 1.1
  - Platform (compiler, OS): OS X 10.13.3, compiler:
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Missing packages mostly installed through home-brew.

### PR DESCRIPTION
**Pull request by AntonBikineev**
Fixes #3221 

Not sure that the fix is correct and generic though.

### CODE REVIEW

**Comment by hkaiser** [comment]
@AntonBikineev we traverse the system hierarchy with hwloc in several places. Are you sure you got all of them fixed with this patch (not saying you didn't...)?

**Comment by AntonBikineev** [comment]
@hkaiser no, it's not enough. the same has to be done at least for PU as well. Will do that tomorrow :)

**Comment by hkaiser** [comment]
@AntonBikineev thanks for your work on this! Please let us know once you're done with your changes.

**Comment by AntonBikineev** [comment]
@hkaiser, Sorry for taking sp long to respond - I just missed the github notification. Yes, I think that's it for the changes. Please let me know f you think there are some more places the fix should go to. BTW, it would be also nice to have hwloc-2.0 configuration on buildbot.

**Comment by hkaiser** [comment]
Thanks @AntonBikineev, we have set up a buildbot builder for hwloc, let's see how it goes.

**Comment by hapoo** [comment]
I added hwloc-2.0 to buildbot, right now gcc 7.3.0 and clang 6.0.0 use hwloc-2.0.
forcing build for this branch on buildbot all the tests passed except one: `tests.regressions.util.set_config_entry_deadlock` see [here](http://rostam.cct.lsu.edu/builders/hpx_gcc_7_boost_1_66_centos_x86_64_debug/builds/107/steps/run_regression_tests/logs/tests.regressions.util.set_config_entry_deadlock%20%280.52%20sec%29)

This test also fails with hwloc-1.11.2 on [gcc 6](http://rostam.cct.lsu.edu/builders/hpx_gcc_6_boost_1_64_centos_x86_64_debug/builds/233/steps/run_regression_tests/logs/tests.regressions.util.set_config_entry_deadlock%20%280.40%20sec%29) with same error, so I don't think they are related to hwloc-2.0

**Comment by msimberg** [comment]
@hapoo Thanks for setting up the builders. It looks like this was branched off from master at a time when that test was failing, so should be unrelated. Also thanks to @AntonBikineev for getting this done!

**Pull request merged**
