### PR TITLE
Update the MPI cmake setup

### LINKED ISSUE #4484: Use CMake targets provided by FindMPI

### PR DESCRIPTION
**Pull request by aurianer**
Fixes #4484

### CODE REVIEW

**Review by msimberg — DISMISSED** [review]
A very welcome simplification, thanks! Let's wait for rostam to be back before merging though.

**Comment by hkaiser** [comment]
> A very welcome simplification, thanks! Let's wait for rostam to be back before merging though.

I agree, this is a nice change. I would like to make sure this still works on Windows, though. I believe to remember that especially the Intel MPI libraries were always a bit special on that platform...

**Comment by gonidelis** [comment]
What is the status of this PR?

**Comment by hkaiser** [comment]
> What is the status of this PR?

This needs a rebase and then should be merged.

**Comment by gonidelis** [comment]
> > What is the status of this PR?
> 
> This needs a rebase and then should be merged.

Ok sure. Should I go for it or should I wait for @aurianer ?

**Comment by hkaiser** [comment]
> > > What is the status of this PR?
> > 
> > 
> > This needs a rebase and then should be merged.
> 
> Ok sure. Should I go for it or should I wait for @aurianer ?

@gonidelis please go for it if you have the time.

**Comment by msimberg** [comment]
> > > > What is the status of this PR?
> > > 
> > > 
> > > This needs a rebase and then should be merged.
> > 
> > 
> > Ok sure. Should I go for it or should I wait for @aurianer ?

This seemed to work just fine on Linux. The only open question was @hkaiser's comment regarding windows.

**Review by hkaiser — APPROVED** [review]
Everything works on Windows as well. LGTM, thanks!

**Comment by hkaiser** [comment]
bors merge

**Pull request merged**
