### PR TITLE
Make the compatilibility headers macro conditional

### LINKED ISSUE #4709: Make deprecation warnings overridable in dependent projects
Allow overriding `HPX_<module_name>_HAVE_DEPRECATION_WARNINGS` in dependent projects, meaning the definition of `HPX_<module_name>_HAVE_DEPRECATION_WARNINGS` should be guarded with an `#ifndef`.

### PR DESCRIPTION
**Pull request by aurianer**
Fixes #4709
- Define a default value to 1 for the `HPX_<MODULE>_HAVE_DEPRECATION_WARNINGS` if not already defined
- Remove the unused macro `HPX_<MODULE>_HAVE_COMPATIBILITY_HEADERS`

### CODE REVIEW

**Comment by msimberg** [comment]
Ah, it seems like we crossed paths a bit... #4711. I'll close mine since you cleaned things up better. However, it looks like not all compatibility headers got their `#if defined` changed in this PR. Let's go with this PR but I'd wait until #4710 is merged before applying this one. #4710 will add some more compatibility headers.

**Comment by aurianer** [comment]
> Ah, it seems like we crossed paths a bit... #4711. I'll close mine since you cleaned things up better. However, it looks like not all compatibility headers got their `#if defined` changed in this PR. Let's go with this PR but I'd wait until #4710 is merged before applying this one. #4710 will add some more compatibility headers.

Sorry I didn't see your PR :/
I'll add the new compatibility headers !

**Comment by aurianer** [comment]
All the compatibility headers should be modified now, sorry I had a typo in my script..

**Comment by msimberg** [comment]
Thanks @aurianer! The `clang-oldest` failure is again unrelated.

**Pull request merged**
