### PR TITLE
Don't pollute CMAKE_CXX_FLAGS through find_package()

### PR DESCRIPTION
**Pull request by gentryx**
In its current form a call to find_package(HPX) in CMake will add "-std=c++11" (or 14) to the consumer's C++ flags, no matter if HPX was found or not. That's bad, because it breaks 3rd party code on builds totally unrelated to HPX.

In my case find_package(HPX) is not successful if I compile LibGeoDecomp with g++ 4..4.7 (compiler version mismatch). But "-std=c++14" gets added anyway, so somewhere below a test for OpenMP will fail (CMake tests for OpenMP-flags. Compilation of the test source uses a valid source file and OpenMP-flag, but g++ 4.4.7 stumbles upon the "-std=c++14".

### CODE REVIEW

**Comment by gentryx** [comment]
Oh, the downside of this PR is obviously that users now have to manually add HPX_FLAGS to their CMAKE_CXX_FLAGS, but this is standard behavior for other packages as well (e.g. MPI). It also allows users to compose this with CUDA.

**Comment by sithhell** [comment]
I guess the proper fix would be to move the setting of that variable after the compatibility checks.

**Comment by gentryx** [comment]
@sithhell that would be one possibility. But then again this doesn't address the problem that e.g. CUDA will still be missing that flag.

**Comment by sithhell** [comment]
which flag is CUDA missing then?

**Comment by gentryx** [comment]
You have to populate CUDA_NVCC_FLAGS

**Comment by gentryx** [comment]
circleci is failing, but I don't see how this is related to my PR. any clues?

**Comment by gentryx** [comment]
ping

**Comment by hkaiser** [comment]
pong

**Comment by gentryx** [comment]
;-) 

Seriously though: is there a reason not to merge this?

**Comment by hkaiser** [comment]
> Seriously though: is there a reason not to merge this?

Apparently this patch causes the errors. Looks like the compilation for the failing test misses the `-std=C++11` command line option.

**Comment by gentryx** [comment]
@hkaiser Sorry for being dense. My fault, I'll fix it.

**Comment by biddisco** [comment]
LGTM

**Comment by hkaiser** [comment]
@gentryx Could you recreate this PR against the release branch, please? I'll merge it asap once that's done.

**Comment by sithhell** [comment]
This has been superseeded by #1854.

**Pull request closed without merging**
