### PR TITLE
Rename `annotate_function` to `scoped_annotation`

### LINKED ISSUE #5686: Rename `annotate_function`
The distinction between `annotate_function` and `annotated_function` is often confusing to users. I think the current `annotate_function` could be renamed e.g. `scoped_annotation` as it

1. clearly distinguishes it from `annotated_function` and
2. at least in my opinion describes its purpose much better than `annotate_function`

I'm sure there would be other alternative names as well so feel free to suggest some if you can think of any. The main reason for opening this issue is that I think it should be renamed.

Bonus change that I'm adding as a reminder:
- move `annotate(d)_function` from `hpx::util` to `hpx`

### PR DESCRIPTION
**Pull request by msimberg**
Fixes #5686. Also moves the utilities to the top-level `hpx` namespace. Adds them to the public API list.

Open question: which header should provide these? I've now added both to `hpx/local/functional.hpp` (and by extension `hpx/functional.hpp`). `scoped_annotation` could also fit in `hpx/local/execution.hpp` in my opinion (`annotated_function` could sort of also fit there). 

Some (in my opinion worse) alternative names:

- `annotation`
- `annotate_scope`
- `annotation_scoped`
- `raii_annotation`

### CODE REVIEW

**Comment by hkaiser** [comment]
`scoped_annotation` is fine, thanks!

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by msimberg** [comment]
The codacy warning is a false positive...

**Comment by msimberg** [comment]
bors merge

**Pull request merged**
