### PR TITLE
Change project name to HPX

### PR DESCRIPTION
**Pull request by biddisco**
Lots of CMake changes:
  Use HPX_PACKAGE_NAME for install paths where appropriate
  Replace hpx_SOURCE_DIR with PROJECT_SOURCE_DIR
  Replace hpx_BINARY_DIR with PROJECT_BINARY_DIR

This should allow one to change the project name and have most
install/find rules remain working.

A number of hardcoded filenames of type hpx_XXXX have been left unchanged

### CODE REVIEW

**Comment by hkaiser** [comment]
LGTM

**Comment by hkaiser** [comment]
Should we add an inspect checker tool which verifies that hpx_SOURCE_DIR is not being used anywhere to avoid these things in the future? What other automatic checks can we add?

**Comment by sithhell** [comment]
On 07/22/2015 03:11 PM, Hartmut Kaiser wrote:
> LGTM

It is a potential breaking change for scripts that set HPX_DIR directly
as this change shows:
https://github.com/STEllAR-GROUP/hpx/pull/1682/files#diff-1ed9c08b4b0fc0a38337121a476fc7ceL92

It would be interesting if we can avoid the
`/lib/cmake/${HPX_PACKAGE_NAME}` prefix entirely to prevent details like
these leaking to the user.

> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/STEllAR-GROUP/hpx/pull/1682#issuecomment-123715042
> 


-- 
Thomas Heller
Friedrich-Alexander-Universität Erlangen-Nürnberg
Department Informatik - Lehrstuhl Rechnerarchitektur
Martensstr. 3
91058 Erlangen
Tel.: 09131/85-27018
Fax:  09131/85-27912
Email: thomas.heller@cs.fau.de

**Comment by biddisco** [comment]
I don't think you need to check for hpx_SOURCE_DIR, I did a full search/replace in the tree and if anyone used it, it would resolve to an empty string and be noticed immediately.

As for HPX_DIR, I have posted an email to the user list with instructions on what to do.
Using CMAKE_PREFIX_PATH one can avoid the lib/cmake/HPX issue. Most projects just put the HPXConfig.cmake files directly in the root of the build dir and not in lib/cmake/HPX as in the install dir.

**Comment by hkaiser** [comment]
I think that even it is a breaking change, we should go ahead with this. The only remark I have is that we need a note about this in the docs (see: https://github.com/STEllAR-GROUP/hpx/blob/master/docs/whats_new.qbk#L55). Could you please add that?

**Comment by sithhell** [comment]
Am 22.07.2015 6:17 nachm. schrieb "Hartmut Kaiser" <notifications@github.com
>:
>
> I think that even it is a breaking change, we should go ahead with this.
The only remark I have is that we need a note about this in the docs (see:
https://github.com/STEllAR-GROUP/hpx/blob/master/docs/whats_new.qbk#L55).
Could you please add that?

And adapt the docs to advocate CMAKE_PREFIX_PATH

**Comment by hkaiser** [comment]
> And adapt the docs to advocate CMAKE_PREFIX_PATH

Where in the docs should that go?

**Comment by biddisco** [comment]
I've updated the docs (though I'm not sure about the markup/formatting, so apologies if it looks wrong)

**Pull request merged**
