### PR TITLE
Adding split_future

### LINKED ISSUE #2239: Create a new facility lcos::split_all
Several people have been asking for a facility which allows to convert a future storing a tuple of values into a tuple of futures, each storing one of the elements of the original tuple:

    tuple<future<T>...> split_all(future<tuple<T...>> &&);

Other possible names discussed were `unfuse()` or `split_fused()`.

Other things to add:

- [x] support for `shared_future` (#2246)
- [x] support for `std::pair` (#2246)
- [x] support for `std::array` (#2246)

### PR DESCRIPTION
**Pull request by hkaiser**
This implements a first version of the `split_future` facility.

Still missing:
- [x] support for `shared_future`
- [x] MSVC12 fails compiling this (I gave up trying to make it work for this compiler, instead I disabled the feature alltogether)

This fixes #2239

### CODE REVIEW

**Comment by biddisco** [comment]
I have had a good look through this and it seems to be exactly what we need. I have not been able to test it yet as the existing code needs some redesign to integrate `split_future` in.

On thing that troubles me is that the code makes use of `future_data`, `acquire_future`, `acquire_shared_state`, `future_access`, `future_traits` and other internals that are undocumented. Reading through this code I had to go into all the other headers and 'discover' what the other functions were doing and verify them mentally by working through the code. If each of these had a short comment section at the start of the header explaining what the purpose of each of the classes/structs/traits were for, then it would be much easier to learn from examples like `split_future` and move towards implementing other features without assistance.

**Comment by hkaiser** [comment]
> On thing that troubles me is that the code makes use of  `future_data`,  `acquire_future`,  `acquire_shared_state`,  `future_access`,  `future_traits` and other internals that are undocumented. Reading through this code I had to go into all the other headers and 'discover' what the other functions were doing and verify them mentally by working through the code. If each of these had a short comment section at the start of the header explaining what the purpose of each of the classes/structs/traits were for, then it would be much easier to learn from examples like  `split_future`  and move towards implementing other features without assistance.

Fair point. We have not formally documented our customization points (yet), but we should do so. I think this could look very much like the documentation of the [customization points for Boost Spirit](http://www.boost.org/doc/libs/1_61_0/libs/spirit/doc/html/spirit/advanced/customize.html).

I will try to add comments over time, at least. However, if you have learnt something specific which was not obvious right away, feel free to add that information as a comment to any of those facilities as well.

**Comment by dcbdan** [comment]
The following code snippet printed the wrong output for me. This was printed
```
Printing map: 
Printing set: 0 1 10 100 101 2000 
```
not
```
Printing map: (6, 43556) (123, 321) (999, 999) 
Printing set: 0 1 10 100 101 2000 
```
 
```
#include <hpx/hpx_init.hpp>
#include <hpx/hpx.hpp>

#include <iostream>
#include <utility>
#include <vector>

///////////////////////////////////////////////////////////////////////////////
int hpx_main(int argc, char* argv[])
{
    using pair_type     = std::pair<std::map<int, int>, std::set<int> >;
    using pair_fut_type = std::pair<hpx::future<std::map<int, int> >,
                              hpx::future<std::set<int> > >;

    std::map<int, int> mm;
    // fill mm with arbitrary values
    mm[123] = 321;
    mm[999] = 999;
    mm[6]   = 43556;

    // fill ss awith arbitrary values
    std::set<int> ss{0, 1, 10, 100, 101, 2000};

    pair_type p = std::make_pair(mm, ss);
    hpx::future<pair_type> f_pair = hpx::make_ready_future(p);

    // given a future of a pair, get a pair of futures

    // Doesn't work, needs to receive r value
    // pair_fut_type pair_f = hpx::split_future(f_pair);

    // Fine, take your r value
    pair_fut_type pair_f = hpx::split_future(std::move(f_pair));

    // see if the values of mm2 and ss2 are the same
    std::map<int, int> mm2 = pair_f.first.get();
    std::cout << "Printing map: ";
    for(auto val: mm2)
        std::cout << "(" << val.first << ", " << val.second << ") ";
    std::cout << std::endl;

    std::set<int> ss2 = pair_f.second.get();
    std::cout << "Printing set: ";
    for(auto val: ss2)
        std::cout << val << " ";
    std::cout << std::endl;

    return hpx::finalize();
}

int main(int argc, char* argv[])
{
    return hpx::init(argc, argv);
}
```

**Comment by hkaiser** [comment]
@dcbdan Thanks for providing the test revealing a data move-problem. This has been fixed now.

**Comment by hkaiser** [comment]
This PR is ready to be merged now

**Comment by sithhell** [comment]
LGTM!

**Pull request merged**
