### PR TITLE
Blind attempt to fix warnings issued by gcc V9

### LINKED ISSUE #3643: Warnings when compiling HPX 1.2.1 with gcc 9
## Expected Behavior

... Please describe the behavior you would have expected.

## Actual Behavior

```
BUILDSTDERR: /builddir/build/BUILD/hpx_1.2.1/hpx/lcos/detail/future_data.hpp:720:74:   required from 'hpx::lcos::detail::timed_future_data<Result>::timed_future_data(const time_point&, Result_&&) [with Result_ = const hpx::util::unused_type&; Result = void; std::chrono::_V2::steady_clock::time_point = std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >]'
BUILDSTDERR: /builddir/build/BUILD/hpx_1.2.1/hpx/lcos/future.hpp:1740:65:   required from here
BUILDSTDERR: /builddir/build/BUILD/hpx_1.2.1/hpx/lcos/detail/future_data.hpp:721:17: warning: implicitly-declared 'constexpr hpx::util::unused_type::unused_type(const hpx::util::unused_type&)' is deprecated [-Wdeprecated-copy]
```
Full log: https://kojipkgs.fedoraproject.org//work/tasks/9834/32429834/build.log

## Steps to Reproduce the Problem

  1. Compile hpx 1.2.1 with gcc 9 and boost 1.69. Maybe, the boost version is not relevant for these warnings

## Specifications

... Please describe your environment

  - HPX Version: 1.2.1
  - Platform (compiler, OS): gcc 9, Fedora 30

### PR DESCRIPTION
**Pull request by hkaiser**
Fixes #3643

@diehlpk Could you check whether this fixes the warnings you reported in #3643, please?

### CODE REVIEW

**Comment by hkaiser** [comment]
@msimberg FWIW, I added this to the 1.2.1 milestone. We should consider having it in the point release

**Comment by diehlpk** [comment]
@hkaiser It seems that the one I reported vanished, but there are more of these 

```
make[2]: Leaving directory '/builddir/build/BUILD/hpx_1.2.1/serial'
BUILDSTDERR: /builddir/build/BUILD/hpx_1.2.1/src/runtime/agas/server/route.cpp: In member function 'void hpx::agas::server::primary_namespace::route(hpx::parcelset::parcel&&)':
BUILDSTDERR: /builddir/build/BUILD/hpx_1.2.1/src/runtime/agas/server/route.cpp:49:25: warning: implicitly-declared 'hpx::error_code::error_code(const hpx::error_code&)' is deprecated [-Wdeprecated-copy]
BUILDSTDERR:    49 |         error_code ec = throws;
BUILDSTDERR:       |                         ^~~~~~
BUILDSTDERR: In file included from /builddir/build/BUILD/hpx_1.2.1/hpx/lcos/future.hpp:11,
BUILDSTDERR:                  from /builddir/build/BUILD/hpx_1.2.1/hpx/runtime/agas/interface.hpp:15,
BUILDSTDERR:                  from /builddir/build/BUILD/hpx_1.2.1/hpx/runtime/applier/apply.hpp:12,
BUILDSTDERR:                  from /builddir/build/BUILD/hpx_1.2.1/src/runtime/agas/server/route.cpp:8:
BUILDSTDERR: /builddir/build/BUILD/hpx_1.2.1/hpx/error_code.hpp:222:32: note: because 'hpx::error_code' has user-provided 'hpx::error_code& hpx::error_code::operator=(const hpx::error_code&)'
BUILDSTDERR:   222 |         HPX_EXPORT error_code& operator=(error_code const& rhs);
BUILDSTDERR: 
```
```
BUILDSTDERR: /builddir/build/BUILD/hpx_1.2.1/src/runtime/agas/server/primary_namespace_server.cpp: In member function 'hpx::naming::gid_type hpx::agas::server::primary_namespace::statistics_counter(const string&)':
BUILDSTDERR: /builddir/build/BUILD/hpx_1.2.1/src/runtime/agas/server/primary_namespace_server.cpp:1268:31: warning: implicitly-declared 'hpx::error_code::error_code(const hpx::error_code&)' is deprecated [-Wdeprecated-copy]
BUILDSTDERR:  1268 |     hpx::error_code ec = hpx::throws;
BUILDSTDERR:       |                               ^~~~~~
BUILDSTDERR: In file included from /builddir/build/BUILD/hpx_1.2.1/hpx/lcos/future.hpp:11,
BUILDSTDERR:                  from /builddir/build/BUILD/hpx_1.2.1/hpx/async_launch_policy_dispatch.hpp:11,
BUILDSTDERR:                  from /builddir/build/BUILD/hpx_1.2.1/hpx/async.hpp:10,
BUILDSTDERR:                  from /builddir/build/BUILD/hpx_1.2.1/src/runtime/agas/server/primary_namespace_server.cpp:11:
BUILDSTDERR: /builddir/build/BUILD/hpx_1.2.1/hpx/error_code.hpp:222:32: note: because 'hpx::error_code' has user-provided 'hpx::error_code& hpx::error_code::operator=(const hpx::error_code&)'
BUILDSTDERR:   222 |         HPX_EXPORT error_code& operator=(error_code const& rhs);
BUILDSTDERR: 
```      |                                ^~~~~~~~

**Comment by diehlpk** [comment]
Fore more details https://kojipkgs.fedoraproject.org//work/tasks/2067/32522067/build.log

**Comment by hkaiser** [comment]
@diehlpk I fixed two more warnings. The attribute warnings should have been fixed by #3505, no idea why they still show up - @sithhell?

**Comment by msimberg** [comment]
The attribute warnings were and are a mystery to me. Seems to be very much compiler and configuration dependent. Perhaps our defines are not doing what they should be doing. This is most worrying:

```
BUILDSTDERR: /builddir/build/BUILD/hpx_1.2.1/hpx/runtime/actions/basic_action.hpp:861:43: warning: type attributes ignored after type is already defined [-Wattributes]
BUILDSTDERR:   861 |         template struct HPX_ALWAYS_EXPORT transfer_action< action>;   
```
Line 861 is within an `#if defined(HPX_MSVC) || defined(HPX_MINGW)` block, which should not be happening... I'll have a look.

**Comment by hkaiser** [comment]
@msimberg should we add that patch to V1.2.1?

**Comment by msimberg** [comment]
@hkaiser yes, it's already on the release branch (although I forgot to push it before leaving work, it'll be there tomorrow).

**Pull request merged**
