### PR TITLE
Implement parallel::unique.

### PR DESCRIPTION
**Pull request by taeguk**
It is related to #1141, #2804.

Check Box
---------------
- [x] Implementation of parallel::unique using temporary storage. (https://github.com/STEllAR-GROUP/hpx/pull/2867/commits/eecac2c1)
- [x] Implementation of parallel::unique using sequentially performed f3. (The lastest commit)
- [x] Unit tests.
- [x] Benchmark codes. (with various data type)
- [x] Adapt to Ranges TS. (Container version)
- [x] Some modifications of parallel::util::scan_partitioner.

Issues
-------------
1. What way should we select between the two ways to implement parallel::unique discussed in #2804?
  -> I implemented both ways and benchmarked them. In conclusion, using the way to perform f3 sequentially is better. So, I choosed that.

Note for future
---------------------
1. The performance of parallel::unique is bad. The performance is different depending on the situation, but it is slightly faster than the sequential version, and sometimes it is slower than the sequential version. There is need to improve this algorithm if we can find the better way.

### CODE REVIEW

**Comment by taeguk** [comment]
https://github.com/taeguk/hpx/blob/da7fd5d7dd38ca0074c579d248ef7ea916c200bf/hpx/parallel/util/scan_partitioner.hpp#L284-L289
@hkaiser I used explicit waiting like above.
But, you said "Prefer ```dataflow``` rather than explicit waiting".
https://github.com/taeguk/hpx/blob/da7fd5d7dd38ca0074c579d248ef7ea916c200bf/hpx/parallel/util/scan_partitioner.hpp#L304
Yes, I agree. But, if we want to use ```dataflow``` instead of explicit waiting, we should change the type of ```finalitems``` from ```std::vector<hpx::future<Result2>>``` to ```std::vector<hpx::shared_future<Result2>>``` because final item should be passed to both 'f3 on next partition' and 'f4'. And, the interface of f3 should be also changed. These changes should be also applied even if ```ScanPartTag``` is ```scan_partitioner_normal_tag``` because maybe it is better for same template to have same interface. So, f3 of existed codes using ```scan_partitioner``` should be a little modified.

How do you think about it? Keep using current explicit waiting? Or use ```dataflow``` with changing the interface of f3 in scan_partitioner.

**Comment by hkaiser** [comment]
Please fix the conflicts, otherwise this can't go ahead.

**Comment by taeguk** [comment]
@hkaiser I'm ready to be reviewed and merged.

**Comment by hkaiser** [comment]
@taeguk Please fix the conflicts for this to be merged. And sorry for the long delay ...

**Comment by taeguk** [comment]
@hkaiser I resolved conflicts. And I did somethings related to #2908, too.
I'm ready to be merged :)

**Comment by hkaiser** [comment]
@taeguk: thanks a lot for your continued work on this! Just a heads up - there are still problems reported by inspect.

**Pull request merged**
