### PR TITLE
Fixing 2000

### LINKED ISSUE #2000: Undefined reference to hpx::assertion_failed
Building commit 6c08935c5d9158031bbdee01872283e2dd8b0ceb with GCC 5.3 and RelWithDebInfo as the build type fails due to an undefined reference to `hpx::assertion_failed`.

After examining the compiler output, it seems that all calls of assertion_failed are inlined. Afterwards the dead function is eliminated by the compiler and the reference in assert.hpp can not subsequently be resolved by the linker.

The reason for this behavior seems to be the contradicting declaration of this function in exception.hpp (as an inline function) and in assert.hpp (as a non-inline function).

As far as I know an inline function must be defined in every translation unit where it is called. In addition, an inline function with external linkage must be declared inline in every translation unit. Both rules are (possibly) violated in this case.

I was able to fix the issue by moving the definition into exception.cpp

assertion_failed_msg should be affected by the same issue.

### PR DESCRIPTION
**Pull request by chinz07**
This fixes #2000

### CODE REVIEW

**Comment by chinz07** [comment]
Since assertion_failed/assertion_failed_msg never returns and the compiler can not infer this fact anymore it might be a good idea to mark the function with HPX_ATTRIBUTE_NORETURN. Any objections?

**Comment by hkaiser** [comment]
> Since assertion_failed/assertion_failed_msg never returns and the compiler can not infer this fact anymore it might be a good idea to mark the function with HPX_ATTRIBUTE_NORETURN. Any objections?

No objections.

**Comment by chinz07** [comment]
@hkaiser Could you please merge this PR?

**Comment by hkaiser** [comment]
@chinz07 I was assuming you'd add the HPX_ATTRIBUTE_NORETURN first, were you pallning to do that?

**Comment by chinz07** [comment]
@hkaiser I have marked the functions in commit f0553bc7f39a235ddb15675fd214b2a766df497d.

**Comment by hkaiser** [comment]
Ok, I'll merge it once buildbot has cycled later today

**Pull request merged**
