### PR TITLE
Fix sync traversals of containers passed as r-value

### PR DESCRIPTION
**Pull request by Naios**
## Proposed Changes

  - This fixes the reference correctness of `traverse_pack` when traversing a container passed as rvalue

### CODE REVIEW

**Comment by hkaiser** [comment]
@Naios could you please fix the remaining inspect check errors (https://9740-4455628-gh.circle-artifacts.com/0/tmp/circle-artifacts.pTMGwoc/hpx_inspect_report.html)? We can't move ahead with merging otherwise. Thanks!

**Comment by Naios** [comment]
@hkaiser I corrected the outstanding issue

**Comment by hkaiser** [comment]
@Naios you can ignore the AppVeyor problem (this is unrelated to your work), but could you please look into the errors reported by our pycicle CI system?

**Comment by Naios** [comment]
@hkaiser I took a look into the error, this is a greater bug with which affects the whole GCC (6.x) family.
I could reproduce it on one of my remote machines using GCC 6.3.
Currently I don't have the resources to reproduce it (currently I'm missing time to do it and also I don't have an environment for debugging GCC properly).

**Pull request closed without merging**
