### PR TITLE
Change discover counters mode enum to enum class

### PR DESCRIPTION
**Pull request by gonidelis**
Final enum to enum class conversion for performance counters module (`discover_counter_mode`). It's minimal and couldn't find any local fails so I will let CI guide me. I would hope for these PRs to go to 1.9.

### CODE REVIEW

**Comment by gonidelis** [comment]
@hkaiser I am trying to reproduce the failed test errors. I copied the CMake flags and recompiled with gcc11 on rostam. When I try to compile [tests.unit.modules.actions.distributed.lci.thread_stacksize](https://cdash.cscs.ch/test/12951711) make cannot locate the target. Any ideas?

Same applies for #5857.

**Comment by hkaiser** [comment]
@gonidelis could you please rebase this PR onto master and resolve the conflicts? Once that's done we can merge.

**Comment by hkaiser** [comment]
bors merge

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
