### PR TITLE
More fixes to enable for all types to be assumed to be bitwise copyable

### PR DESCRIPTION
**Pull request by hkaiser**
These changes are needed to make the changes from #5435 actually work.

@msimberg I hate to ask, but would it be possible for this to still get into V1.7? We discovered this issue just now. Nan will test it on her side today and report back asap. I think this would be a very low risk change as it doesn't touch on code that is used for normal operation.

### CODE REVIEW

**Comment by hkaiser** [comment]
@msimberg I take it back. No need to rush this PR as there are a lot more changes I need to apply. Sorry for the noise.

**Comment by hkaiser** [comment]
retest

**Comment by msimberg** [comment]
retest

**Comment by msimberg** [comment]
@hkaiser this one looks like it genuinely needs a bit of work still. The `not_bitwise_serializable` test seems to be failing on all configurations: https://cdash.cscs.ch/testDetails.php?test=48557292&build=173851.

**Comment by hkaiser** [comment]
@msimberg this looks good now. Please feel free to merge if you don't have more comments.

**Pull request merged**
