### PR TITLE
Use of shared_ptr in io_service_pool changed to unique_ptr

### PR DESCRIPTION
**Pull request by AntonBikineev**

### CODE REVIEW

**Comment by hkaiser** [comment]
IIRC,this will only work on gcc >= 4.8 as stdlibc++ does not have emplace_back, etc. Unfortunately, we might have to leave the old code in place for `#if defined(HPX_GCC_VERSION) && HPX_GCC_VERSION < 408000`.

**Comment by AntonBikineev** [comment]
@hkaiser I"m not sure, but I suppose there was only a problem with map<>::emplace function in older versions of gcc (we saw it in some of polymorphic_factory headers), not with vector<>::emplace_back

**Comment by hkaiser** [comment]
@AntonBikineev You're right. However, the buildbot is failing for the gcc 4.6 builders (see for instance:  http://hermione.cct.lsu.edu/builders/hpx_gcc_4_6_boost_1_49_debian_x86_64_debug/builds/470/steps/build_core/logs/stdio). Intel13 fails as well: http://hermione.cct.lsu.edu/builders/hpx_intel_13_gcc44_boost_1_54_debian_x86_64_debug/builds/128/steps/build_core/logs/stdio.

**Comment by hkaiser** [comment]
@AntonBikineev ping?

**Comment by AntonBikineev** [comment]
@hkaiser from what I can see, those version of libstdc++ (<= 4.6) require type to be assignable in order for it to be emplace_backable and push_backable, but asio::work has explicitly declared private operator=. We can either wrap problematical sections into macros and use old version of the code for them or just refuse PR.

**Comment by hkaiser** [comment]
@AntonBikineev By no means I'm suggesting to reject your PR, I really think we should try to integrate it. I can't answer the question whether just to wrap the critical pieces into macros or have both versions. This entirely depends on how much code would have to wrapped into macros. if it's almost all of it we can go with both versions, if it's just a small section I'd prefer to have those wrapped instead. In any case we should try to use compiler feature-based macros (as detected during configuration) instead of compiler versions, if possible.

**Comment by AntonBikineev** [comment]
@hkaiser the problem is that there is no feature-macro which would be able to know whether push_back/emplace_back requires operator= underneath. Which macro do we use to specify version of libstdc++?

**Comment by AntonBikineev** [comment]
it turns out there may be problems related to non-noexcept move-ctor of boost::thread, which seems to be non-noexcept up until boost-1.56...

**Comment by hkaiser** [comment]
All tests looks fine now.

**Comment by hkaiser** [comment]
> it turns out there may be problems related to non-noexcept move-ctor of boost::thread, which seems to be non-noexcept up until boost-1.56... 

What problems would you anticipate?

**Comment by AntonBikineev** [comment]
@hkaiser how do I run tests on hermione with, say, boost-1.49.0, g++-4.7 and debian?

**Comment by hkaiser** [comment]
@AntonBikineev:
```
cmake \
    -DCMAKE_BUILD_TYPE=Debug 
    -DHPX_WITH_EXAMPLES=On \
    -DCMAKE_C_COMPILER=/usr/bin/gcc-4.7 \
    -DCMAKE_CXX_COMPILER=/usr/bin/g++-4.7 \
    -DBOOST_ROOT=/opt/boost/1.49.0-debug \
    -DCMAKE_INSTALL_PREFIX:PATH=<install_dir> \
    -DHPX_WITH_MALLOC=tcmalloc 
    <hpx_source_dir>
```

**Comment by AntonBikineev** [comment]
@hkaiser: no, I meant some specific command, which I could run on IRC

**Comment by hkaiser** [comment]
>  I meant some specific command, which I could run on IRC

try `HermioneBot: help`

The available builders are listed here: http://hermione.cct.lsu.edu/builders

**Comment by AntonBikineev** [comment]
hkaiser: I have a compilation error when compiling with options mentioned above, let me try handling this please

**Comment by hkaiser** [comment]
Well, it's merged already, let's see what happens.

**Pull request merged**
