### PR TITLE
Add future example on existing presentation material

### PR DESCRIPTION
**Pull request by tapaswenipathak**
## Proposed Changes

Adds future tutorial in sphinx documentation

## Any background context you want to provide?

GSoD'19 task.

### CODE REVIEW

**Comment by msimberg** [comment]
Thanks @tapaswenipathak for taking the time to put this together. As it stands I'm not sure this is ready to go in to master for two reasons:

1. Since this was originally a presentation it's lacking quite a few things which would normally be said by the presenter. It's more of a list of bullet points rather than fluent text.
2. These are not really examples or tutorials, in the same vein as the other sections under "Examples", so another section might be more appropriate.

Here are a few suggestions how we could improve this:

1. Actually document our `future`s. There's an old issue for this (#985) which would be great to see resolved. The content you've added is mostly documentation of futures (and related functionality).
2. Link to the presentations more prominently and differently. You might have found this page: https://stellar-group.github.io/hpx/docs/sphinx/branches/master/html/additional_material.html which links to the presentations. We could in addition to linking to the full tutorials repo link to selected workshops and sections within those. We could also add a link to that section in the intro.
3. Expand this and your other PRs into a section in the manual about writing task based programs. The quick start has the very basics, but doesn't go into detail. The manual ("Writing single-node HPX applications") goes into more detail but also lacks a bit of structure (and content). A nicely explained example is usually best, but it could take other forms as well.

I'm commenting on this PR but most of this applies to the other PRs as well.

**Comment by tapaswenipathak** [comment]
hi @msimberg, I think all these docs should go in https://github.com/STEllAR-GROUP/tutorials, should I close this PR as I will create a PR against tutorials repository for these docs?

**Comment by msimberg** [comment]
@tapaswenipathak what do you have in mind? Much of this already comes *from* the tutorials repo. Having them in our real documentation rather than slides would still be useful.

**Comment by msimberg** [comment]
Closing this for now to avoid unnecessary CI builds. @tapaswenipathak this doesn't mean we're not interested in the content of the PR. Feel free to reopen if you get the time to continue this at some point in the future!

**Pull request closed without merging**
