### PR TITLE
Fixing #1620

### PR DESCRIPTION
**Pull request by sithhell**
This patch makes sure that the id of a promise can be retrieved multiple times
keeping the promise alive long enough.

### CODE REVIEW

**Comment by sithhell** [comment]
All tests pass.

**Comment by hkaiser** [comment]
This PR will cause for the promise to be never free'd as the credits left behind by the split operation will keep it alive. There is no way for those credits to be given back at any point.

**Comment by sithhell** [comment]
Am 29.10.2015 4:16 nachm. schrieb "Hartmut Kaiser" <notifications@github.com
>:
>
> This PR will cause for the promise to be never free'd as the credits left
behind by the split operation will keep it alive. There is no way for those
credits to be given back at any point.

The test checking for that passes:
https://github.com/STEllAR-GROUP/hpx/blob/master/tests/regressions/lcos/promise_leak_996.cpp

This patch only splits the credit when get_id is called, when the promise
goes out of scope, the remaining credits are being decremented.

I'm not sure how the promise is never freed then.

**Comment by hkaiser** [comment]
The test you're referring to does not call `get_id()` on the promise, so it will not trigger the id-split. 

The follwoing code would expose the leak, though (which is roughly what we do for any async on actions):

```
    struct test
    {
        test() { ++count; }
        test(test const & t) { ++count; }
        test& operator=(test const & t) { ++count; return *this; }
        ~test() { --count; }

        static int count;
    };

    test call() { return test(); }
    HPX_PLAIN_ACTION(call);

    void test_leak()
    {
        {
            hpx::lcos::promise<test> p;
            hpx::apply_c<call_action>(p.get_id(), hpx::find_here());
            hpx::future<test> f = p.get_future();
            f.get();
        }

        hpx::agas::garbage_collect();
        hpx::this_thread::yield();
        hpx::agas::garbage_collect();
        HPX_TEST_EQ(test::count, 0);
    }
```

**Comment by sithhell** [comment]
I added and ran the leak test, it passes just fine.

**Pull request merged**
