### PR TITLE
hpx::partitioned_vector serializer

### PR DESCRIPTION
**Pull request by ct-clmsn**
PR for issue #1645

### CODE REVIEW

**Comment by ct-clmsn** [comment]
@hkaiser @sithhell libhpx_partitioned_vector isn't correctly linked by cmake into the serialized partitioned_vector unit test. The unit test can be built manually using hpxcxx without error. I've reviewed the partitioned_vector unit tests and haven't been able to sort out what needs to be added into cmake to fix the linking issue - do ya'll have any tips or suggestions?

**Comment by hkaiser** [comment]
@ct-clmsn In theory it is sufficient to declare the partitioned_vector_component as a dependency, but that has been done. I have no idea right away, but I'll have a look.

**Comment by ct-clmsn** [comment]
@hkaiser thanks!

**Comment by hkaiser** [comment]
@ct-clmsn There was a problem in the segmented parallel::fill implementation which was causing your liker errors. I added a commit to your branch here: https://github.com/STEllAR-GROUP/hpx/commit/e1cc39c01227284cc4632c34bcfd1a7d3dad4e18. If this goers through now we can merge things from that branch. Thanks for you patience!

**Comment by hkaiser** [comment]
@ct-clmsn I have updated the commit mentioned above (see https://github.com/STEllAR-GROUP/hpx/commit/a5b25d0f5c9ed0b72a9f1235c96bc66991b1d282). I hope you don't mind me slightly simplifying your implementation... Things should be ready for merging now.

**Comment by ct-clmsn** [comment]
@hkaiser apologies for unnecessary complexity! i had concerns the most straight forward implementation might lack nuance.

**Comment by hkaiser** [comment]
@ct-clmsn No apologies needed. Sometimes the simplest solution turns out to be the best in the end... The main issue was that bug in `parallel::fill` we had - this probably has thrown you off. Thanks again for your contributions!

**Pull request merged**
