### PR TITLE
Fixing memory leak

### PR DESCRIPTION
**Pull request by sithhell**

### CODE REVIEW

**Comment by hkaiser** [comment]
LGTM, thanks!

**Comment by hkaiser** [comment]
It's just strange that this PR includes half of #1942

**Comment by sithhell** [comment]
Yup ... I should have cherry picked the commit instead of checking out ... stupid git ... let's merge #1942 first...

**Comment by hkaiser** [comment]
>  let's merge #1942 first...

Sure, if #1942 looks good to you, pls go ahead.

**Pull request merged**
