### PR TITLE
Modernize modules of level 21, 22

### PR DESCRIPTION
**Pull request by hkaiser**
working towards https://github.com/STEllAR-GROUP/hpx/issues/5497

Modules:
- core/async_combinators
- core/execution

### CODE REVIEW

**Comment by hkaiser** [comment]
@srinivasyadav18 could you please have a look at this remaining error: https://app.circleci.com/pipelines/github/STEllAR-GROUP/hpx/12926/workflows/2bac9104-5e08-43f4-9ad3-bca1aa5980ed/jobs/326724/steps? Please note, that this could be a compiler issue. We might have to remove the `constexpr` from this variable.

**Comment by hkaiser** [comment]
@srinivasyadav18 one of the datapar tests is still failing here: https://github.com/STEllAR-GROUP/hpx/actions/runs/3863061252/jobs/6585015799. Would you have the time to check?

**Comment by srinivasyadav18** [comment]
> @srinivasyadav18 one of the datapar tests is still failing here: https://github.com/STEllAR-GROUP/hpx/actions/runs/3863061252/jobs/6585015799. Would you have the time to check?

@hkaiser yes. I will look into it and make the changes.

**Comment by hkaiser** [comment]
retest LSU

**Pull request merged**
