### PR TITLE
Executor parameters

### PR DESCRIPTION
**Pull request by hkaiser**
- moving execution_policy::get_chunk_size into separate executor parameters trait
- moving get_static_chunk_size() into auto_chunk_size executor parameters type
- adding dynamic_chunk_size, static_chunk_size, and guided_chunk_size as simple
  executor parameter types
- adding test
- adding documentation

The bottom line is that it is now possible to attach an executor parameter object to the execution policy, very similar to attaching an executor:

    local_priority_queue_executor exec(4);   // use 4 cores
    guided_chunk_size gcs(100);              // use GUIDED scheduling with min-chunk-size = 100
    for_each(par.on(exec).with(gcs), ...);

### CODE REVIEW

**Comment by dcbdan** [comment]
The following code fails to compile, asserting on line 966 of execution_policy.hpp. For some reason, calling is_executor_parameters::value is false for static_chunk_size and auto_chunk_size executor_parameters. 

```
#include <hpx/config.hpp>
#include <hpx/hpx.hpp>
#include <hpx/hpx_start.hpp>

#include <hpx/include/parallel_algorithm.hpp>
#include <hpx/include/parallel_executors.hpp>
#include <hpx/include/parallel_executor_parameters.hpp>
#include <hpx/include/parallel_execution_policy.hpp>

using hpx::parallel::par;

using hpx::parallel::static_chunk_size;
using hpx::parallel::dynamic_chunk_size;
using hpx::parallel::auto_chunk_size;
using hpx::parallel::guided_chunk_size;

template <typename Iter>
void test_static_chunk_size(std::size_t, Iter first, Iter last)
{
    static_chunk_size cs();
    hpx::parallel::for_each(par.with(cs), first, last, [](int){});
}

template <typename Iter>
void test_dynamic_chunk_size(std::size_t c, Iter first, Iter last)
{
    dynamic_chunk_size cs(c);
    hpx::parallel::for_each(par.with(cs), first, last, [](int){});
}

template <typename Iter>
void test_auto_chunk_size(std::size_t, Iter first, Iter last)
{
    auto_chunk_size cs();
    hpx::parallel::for_each(par.with(cs), first, last, [](int){});
}

template <typename Iter>
void test_guided_chunk_size(std::size_t c, Iter first, Iter last)
{
    guided_chunk_size cs(c);
    hpx::parallel::for_each(par.with(cs), first, last, [](int){});
}

int hpx_main(int argc, char* argv[])
{
    std::size_t chunk_size = 50;
    std::vector<int> v(123);

    auto first = v.begin();
    auto last  = v.end();
    std::iota(first, last, 0);

//    test_static_chunk_size(chunk_size, first, last);    // does not compile

    test_dynamic_chunk_size(chunk_size, first, last);   // compiles

//    test_auto_chunk_size(chunk_size, first, last);      // does not compile

    test_guided_chunk_size(chunk_size, first, last);    // compiles

    return hpx::finalize();
}

int main(int argc, char* argv[])
{
    // initialize HPX, run hpx_main.
    hpx::start(argc, argv);

    // wait for hpx::finalize to be called.
    return hpx::stop();
}
```

**Comment by dcbdan** [comment]
The file compiled when I changed cs() to cs. How come? 

I deduced that the type of `cs` in `static_chunk_size cs` evaluated to `hpx::parallel::v3::static_chunk_size` and the type of `cs` in `static_chunk_size cs()` evaluated to `hpx::parallel::v3::static_chunk_size()` but I'm not sure what that difference comes from.

**Comment by zao** [comment]
`T x()` is a function declaration, not a variable definition, thanks to hysterical legacy behaviour.

**Comment by dcbdan** [comment]
Ahh, thank you.. *facepalm

**Pull request merged**
