### PR TITLE
Fix and simplify make_ready_future overload sets

### PR DESCRIPTION
**Pull request by K-ballo**

### CODE REVIEW

**Comment by hkaiser** [comment]
Should we use the new (global) `init_no_addref` for `id_type` as well (see https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/runtime/naming/name.hpp#L806)?

**Comment by K-ballo** [comment]
> Should we use the new (global) `init_no_addref` for `id_type` as well (see https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/runtime/naming/name.hpp#L806)?

Possibly yes, but then it would have to graduate from `lcos::detail` to `util` or something like that.

**Comment by hkaiser** [comment]
>> Should we use the new (global) `init_no_addref` for `id_type` as well (see https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/runtime/naming/name.hpp#L806)?
>
> Possibly yes, but then it would have to graduate from `lcos::detail` to `util` or something like that.

@K-ballo Let's leave that for a separate PR. 
@msimberg this is good to go.

**Comment by K-ballo** [comment]
Removed `init_no_addref` changes from this PR.

**Comment by hkaiser** [comment]
Let's go ahead and get this in.

**Pull request merged**
