### PR TITLE
Fix GCC 10 release builds

### PR DESCRIPTION
**Pull request by msimberg**
"Fixes" #5035. I know this isn't the way it should be since this leads to circular includes (which nonetheless work). The first change, `apply_implementations_fwd.hpp` to `apply_implementations.hpp` seems legit, as the `apply_impl` definitions are needed by the corresponding file (there are also other files that use `apply_impl` which should probably include the non-forwarding header). With this include the first error is gone, and what remains is undefined references to `apply_l_p` and `apply_r_p` which the second include "solves". I'm guessing maybe the proper fix would be to move some of the definitions from `apply.hpp` to `detail/apply_implementations.hpp`? The `apply_x_p` declarations are in `detail/apply_implementations_fwd.hpp`... @hkaiser let me know if you can take it from here or if I should try something else out.

### CODE REVIEW

**Comment by hkaiser** [comment]
FWIW, this compiles for me.

**Comment by msimberg** [comment]
> FWIW, this compiles for me.

Right, it does for me too ;) If you're not worried about the circular includes for the moment (they are at least within a module) we can go ahead with this.

**Comment by hkaiser** [comment]
@msimberg can we merge this? I think it solves the issue for us.

**Review by aurianer — DISMISSED** [review]
Thanks!

**Comment by aurianer** [comment]
`test.headers` and `clang-format` CI failing though

**Comment by msimberg** [comment]
> @msimberg can we merge this? I think it solves the issue for us.

> `test.headers` and `clang-format` CI failing though

I think that makes it a no... The header tests are most likely failing because of the circular includes.

**Comment by msimberg** [comment]
@hkaiser I'd appreciate if you could look at this. My attempts at moving things around lead to the same problems with the header tests and I don't know them well enough to be able to say where things are going wrong. As for the original linker errors I think the main problem is simply that the full template function definitions should come before their use, and not just the forward declarations. It seems like some compilers are less strict about this though...

**Comment by hkaiser** [comment]
@msimberg I believe this is ready for review now.

**Review by msimberg — COMMENTED** [review]
It's not very pretty, but it does work, so let's go ahead with this. Thanks @hkaiser for doing this! (I can't approve this since I opened the PR.)

**Pull request merged**
