### PR TITLE
Slight optimization for avoiding binding of nullary functions by deferred_call()

### PR DESCRIPTION
**Pull request by hkaiser**

### CODE REVIEW

**Comment by K-ballo** [comment]
What's the rationale for this change?

**Comment by hkaiser** [comment]
> What's the rationale for this change?

This avoids wrapping nullary functions twice. I recently came across the situation, that a bound function was wrapped again (executors call `async` underneath, and the emulation of bulk-asynchrony in the `executor_trait` wraps the function as well).

**Comment by K-ballo** [comment]
I worry this breaks generality, because despite it being an implementation detail we are forced to rely on it in a few places to avoid extra moves (that potentially copy). Nevertheless, LGTM.

**Comment by hkaiser** [comment]
Using std::forward() instead of the explicit cast for the return value might be even better (to 'cast away' constness, if needed).

**Comment by K-ballo** [comment]
LGTM

**Pull request merged**
