### PR TITLE
This fixes referencing stale iterators during the execution of binary mismatch

### PR DESCRIPTION
**Pull request by hkaiser**
- flyby: modernize the implementation of mismatch
- flyby: modernize `advance_to_sentinel`, `algorithm_result`

for more details, see https://github.com/STEllAR-GROUP/hpx/pull/5410#issuecomment-911790179

@Jedi18 please verify whether this fixes the issues you were seeing.

### CODE REVIEW

**Comment by hkaiser** [comment]
@Jedi18 while working on this I realized that the non-binary version of `mismatch` has not been adapted to sentinels yet. Would you be able to look into that?

**Comment by Jedi18** [comment]
@hkaiser Yes it does fix it, thanks a lot! Oh ok sure, I'll adapt mismatch to sentinels.

**Comment by msimberg** [comment]
@hkaiser could you please describe the problem in more detail and why this fixes it? Can we do something more with our tests to catch similar problems in the future?

**Comment by hkaiser** [comment]
> @hkaiser could you please describe the problem in more detail and why this fixes it? Can we do something more with our tests to catch similar problems in the future?

Certainly, sorry for being skimpy with information. Debug builds with MSVC use a special version of the standard library that tracks iterator validity. We were seeing debug failures from this iterator validation during destruction of the function objects that are executed by the threads that make ready the futures that represent the chunk execution. At the point of destruction of said function objects the iterators that are being captured by the lambdas went dangling as the sequences they referred to did already go out of scope.

My fix makes ensure that the futures are released earlier, which releases the iterators that are bound to the associated function objects (thread functions).

Please note that I have added a second commit to this PR that applies a similar fix to all other algorithms, where needed.

**Review by msimberg — APPROVED** [review]

**Comment by msimberg** [comment]
This is unhappy for some reason: https://cdash.cscs.ch/viewBuildError.php?buildid=178740. Not sure why...

**Comment by msimberg** [comment]
> > This is unhappy for some reason: https://cdash.cscs.ch/viewBuildError.php?buildid=178740. Not sure why...
> 
> I think I've encountered this before, this happens when using HPX_INVOKE instead of hpx::util::invoke with projections for some reason.

Did you find a workaround when you saw this before?

**Comment by hkaiser** [comment]
> > > This is unhappy for some reason: https://cdash.cscs.ch/viewBuildError.php?buildid=178740. Not sure why...
> > 
> > 
> > I think I've encountered this before, this happens when using HPX_INVOKE instead of hpx::util::invoke with projections for some reason.
> 
> Did you find a workaround when you saw this before?

I now have changed the capture mode for that lambda, let's see if it helps. This is definitely a compiler problem.

**Comment by Jedi18** [comment]
> > > This is unhappy for some reason: https://cdash.cscs.ch/viewBuildError.php?buildid=178740. Not sure why...
> > 
> > 
> > I think I've encountered this before, this happens when using HPX_INVOKE instead of hpx::util::invoke with projections for some reason.
> 
> Did you find a workaround when you saw this before?

Nope, I just changed it back to hpx::util::invoke

**Comment by hkaiser** [comment]
> > > > This is unhappy for some reason: https://cdash.cscs.ch/viewBuildError.php?buildid=178740. Not sure why...
> > > 
> > > 
> > > I think I've encountered this before, this happens when using HPX_INVOKE instead of hpx::util::invoke with projections for some reason.
> > 
> > 
> > Did you find a workaround when you saw this before?
> 
> I now have changed the capture mode for that lambda, let's see if it helps. This is definitely a compiler problem.

Looks like changing the capture mode fixed this.

**Pull request merged**
