### PR TITLE
Remove serialization to functional module dependency

### PR DESCRIPTION
**Pull request by msimberg**
Extracts the change from #4955.

### CODE REVIEW

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by K-ballo** [comment]
We should probably be using `std::function` in all our user-facing interfaces, and use `hpx::function_nonser` for any internal erasure for a user-facing generic parameters.

**Comment by msimberg** [comment]
> We should probably be using `std::function` in all our user-facing interfaces, and use `hpx::function_nonser` for any internal erasure for a user-facing generic parameters.

Good idea. I think the only "officially" public interface that would require a change in that case is for `hpx::init/start`. Luckily that's not even a breaking change.

**Comment by hkaiser** [comment]
> > We should probably be using `std::function` in all our user-facing interfaces, and use `hpx::function_nonser` for any internal erasure for a user-facing generic parameters.
> 
> Good idea. I think the only "officially" public interface that would require a change in that case is for `hpx::init/start`. Luckily that's not even a breaking change.

There are also the APIs related to registering startup/shutdown functions...

**Pull request merged**
