### PR TITLE
Making sure VERIFY_LOCKS stays disabled if not defined

### PR DESCRIPTION
**Pull request by hkaiser**

### CODE REVIEW

**Comment by hkaiser** [comment]
> This patch disables the lock detection by default for every build type. Shouldn't we enable it for debug builds via CMake?

Good point. I'll change that.

**Comment by hkaiser** [comment]
>> This patch disables the lock detection by default for every build type. Shouldn't we enable it for debug builds via CMake?
>
> Good point. I'll change that.

After trying to do this, I have no idea how to change that. @sithhell any input would be welcome.

**Comment by sithhell** [comment]
My suggestion would be to leave everything as is and keep the lock detection forced in debug mode.

**Comment by hkaiser** [comment]
@biddisco You were the one complaining that the current behavior was unexpected. Care to comment?

**Comment by hkaiser** [comment]
@biddisco ping?

**Comment by biddisco** [comment]
@sithhell wrote "This patch disables the lock detection by default for every build type. Shouldn't we enable it for debug builds via CMake?" 
This is not correct. If the user enables lock detection, then cmake adds a #define for HPX_HAVE_VERIFY_LOCKS, the patch just removes the override that turns it back on in debug mode.
In my view this patch is fine.
If the user enables lock checks, (here https://github.com/STEllAR-GROUP/hpx/blob/9da883ca05c6709374a6b84764de90e75a78c70b/CMakeLists.txt#L664) they get lock checking, if they don't enable it, then they don't

**Comment by sithhell** [comment]
What we loose here is that it is enabled by default on debug builds. One way to fix that would be to not have the define as part of the generated config defines header, but the target specific compiler flags, which is able to use generator expressions, which would allow to enable it for debug builds by default.
If the premise is to only have it enabled if explicitly asked for, then this change is fine. In the past however, we caught more bugs with it being enabled than false-positives.

**Comment by sithhell** [comment]
What should we do with this PR now?

**Comment by hkaiser** [comment]
@biddisco, @sithhell What should be done with this? Can we simply close it?

**Comment by hkaiser** [comment]
I'm going to close this as there is no obvious way to achieve what you asked for. The PR here is not a correct solution in any case.

**Pull request closed without merging**
