### PR TITLE
Switching to CircleCI 2.0

### PR DESCRIPTION
**Pull request by msimberg**
As prepared by @sithhell. This should have very high priority in order to get tests running on PRs.

### CODE REVIEW

**Comment by sithhell** [comment]
Thanks for pushing that!

One thing we have to be aware of is that now, the circle checks will be flagged as failing, since we have lots of failing tests overall. But I think this is a good thing as it detects failures in PRs more easily and hopefully forces us to fix out tests.

**Comment by sithhell** [comment]
The other thing is, there will only be a new docker image once all tests pass ;)

**Comment by hkaiser** [comment]
@msimberg the existing CircleCI test do run the header tests and I wouldn't like to lose that.

**Comment by msimberg** [comment]
@hkaiser Sorry, you're right. In that case that we should try to keep them running on circleci.

**Comment by msimberg** [comment]
Putting this for reference here: CircleCI 1.0 will not be supported anymore after August 31st, 2018.

**Comment by msimberg** [comment]
I played around a bit more and changed the following:
- the header tests depend on the `hpx` target, so the header tests workflow steps now depend on the `core` step (the header tests were all rebuilding `hpx` from scratch)
- for some inexplicable reason `ninja` caused the problems with "cannot allocate memory" and `make` had no problems, so I've changed the generator to `Unix Makefiles` (if someone has ideas on what `ninja` could possibly be doing differently I'd love to hear it)
- (currently being tested) build all parallel algorithms even if the partitioned vector tests fail

**Comment by msimberg** [comment]
Any remaining concerns over this one?

@NK-Nikunj have I understood #3124 correctly that building the hello world component doesn't require any extra build steps now, and is part of tests/unit/build? I don't want to clobber your changes and end up with not building the hello world component again.

The only thing which fails now is building the partitioned vector tests which will show up red until they're fixed, but that we can live with.

**Comment by NK-Nikunj** [comment]
@msimberg yes, you have understood perfectly. The hello world component builds with tests.unit.build.

**Comment by msimberg** [comment]
I'm going to go ahead with this as we'll need this eventually. We can adjust it later on if needed.

**Pull request merged**
