### PR TITLE
Remove compute_cuda module

### LINKED ISSUE #5647: [User input needed] Remove (CUDA) compute functionality?
The CUDA builds are currently broken again (or rather the tests fail). The CUDA compute functionality (not the low-level futures integration) has been in maintenance mode for quite some time and is unlikely to see improvements in the future. We've kept it alive in case there are users relying on it. We have two options for the 1.8.0 release:

- Fix it again.
- Just remove it finally.

The latter seems even more appealing if we consider we are not planning to make further improvements to it.

If any users happen to see this, and you're relying on the CUDA functionality, please let us know which parts of it, and how important it is for your use cases.

I'm marking this for 1.8.0 as we should do one or the other before 1.8.0.

### PR DESCRIPTION
**Pull request by msimberg**
Also remove related CMake options `HPX_WITH_COMPUTE_CUDA` and `HPX_WITH_ASYNC_CUDA` (since the latter is equivalent to `HPX_WITH_CUDA `now).

Fixes #5647.

### CODE REVIEW

**Comment by hkaiser** [comment]
@G-071 Gregor, could you please check whether OctoTiger relies on any of the functionalities that are being proposed for removal?

**Comment by G-071** [comment]
Looks good to me!

With a few changes within Octo-Tiger for c++17/HPX master, I managed to get a working Octo-Tiger build using this PR that passed all the CUDA tests! Generally, as long as the async_cuda functionality still works (especially the CUDA executors in  ```hpx/async_cuda/cuda_executor.hpp```) everything should be fine.

**Comment by hkaiser** [comment]
@G-071: thanks Gregor!

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Review by aurianer — APPROVED** [review]
LGTM thanks!

**Comment by msimberg** [comment]
bors merge

**Pull request merged**
