### PR TITLE
Make sure promise::get_gid() can be called more than once

### PR DESCRIPTION
**Pull request by hkaiser**

### CODE REVIEW

**Comment by hkaiser** [comment]
@Finomnis This should fix your problem, please verify

**Comment by hkaiser** [comment]
@Finomnis can this be merged now?

**Comment by Finomnis** [comment]
Hey :) my work cluster is/was down, so I wasn't able to verify. But if the
test succeeds, it should work :)

**Comment by hkaiser** [comment]
@Finomnis Please let us know once you've tested it.

**Comment by Finomnis** [comment]
Confirmed. Fixed my problem.

**Comment by Finomnis** [comment]
I think we should revert this change. I can prove that there is no scenario where this would not cause an out-of-scope problem.
If someone _needs_ to request a second id_type directly from a promise, this means that the first id_type he requested is out-of-reach for the person requesting it, and it can not be guaranteed that it did not get released yet.

example (pseudocode):
```c++
promise p;
function_one(p.get_gid());
function_two(p.get_gid()); // UNSAFE - function_one could have release its id_type already
```

this code can get re-arranged in different ways, but it always comes back to the problem that you need to keep a copy of the previous id_type to _ensure_ that it does not get out of scope. like this:
```c++
promise p;
id_type id1 = p.get_gid();
function_one(id1);
id_type id2 = p.get_gid();
function_two(id2); // SAVE - id1 is still alive and ensures that agas did not delete the object yet
```

but this _always_ leads to the scenario, that the caller still has a copy of the id_type, which he can simple reuse instead of querying a new one:
```c++
promise p;
id_type id1 = p.get_gid();
function_one(id1);
function_two(id1); // SAVE
```

Therefore, I think we should revert this change as every single use-case it is actually needed _does_ introduce a systematic error.

**Pull request merged**
