### PR TITLE
Investigate builder gasnet failure

### PR DESCRIPTION
**Pull request by Pansysk75**

### CODE REVIEW

**Comment by Pansysk75** [comment]
This is what causes the failure (its deep inside some gasnet makefile):
```bash
sed -e /###NOINSTALL###/d -e s@###INSTALL_INCLUDE###@/work/jenkins/workspace/HPX@6/hpx/build/clang-13-debug/_deps/gasnet-src/install/include@g
```
"@" is used as a separator for the `sed` command, but it's also a character in the install path (".../HPX@6/..")
Let's see if I can change the Jenkins configuration, a path without special characters might save us from future trouble.

**Comment by Pansysk75** [comment]
@hkaiser Looks like it would need to be changed when Jenkins is launched by passing a `hudson.slaves.WorkspaceList` parameter, as described here:
https://stackoverflow.com/questions/52860584/change-jenkins-concurrent-job-workspace-naming
I could not find where Jenkins is (I assume automatically on startup) launched on Rostam. Would you mind helping out?

**Comment by hkaiser** [comment]
> @hkaiser Looks like it would need to be changed when Jenkins is launched by passing a `hudson.slaves.WorkspaceList` parameter, as described here: https://stackoverflow.com/questions/52860584/change-jenkins-concurrent-job-workspace-naming However, I could not find how Jenkins is launched on Rostam (I assume it is automatically launched on startup). Would you mind helping out?

@Pansysk75 this has to be done by @akheir, he owns the admin side of things.

**Comment by hkaiser** [comment]
> > @hkaiser Looks like it would need to be changed when Jenkins is launched by passing a `hudson.slaves.WorkspaceList` parameter, as described here: https://stackoverflow.com/questions/52860584/change-jenkins-concurrent-job-workspace-naming However, I could not find how Jenkins is launched on Rostam (I assume it is automatically launched on startup). Would you mind helping out?
> 
> @Pansysk75 this has to be done by @akheir, he owns the admin side of things.

Needless to say, thanks for figuring this out, Dr. Watson!

**Comment by akheir** [comment]
I added `-Dhudson.slaves.WorkspaceList=A` to Jenkin startup

`/usr/bin/java -Djava.awt.headless=true -Dhudson.slaves.WorkspaceList=A -jar /usr/share/java/jenkins.war --webroot=/var/cache/jenkins/war --httpPort=8080 --prefix=/jenkins
`

**Comment by Pansysk75** [comment]
> I added `-Dhudson.slaves.WorkspaceList=A` to Jenkin startup
> 
> `/usr/bin/java -Djava.awt.headless=true -Dhudson.slaves.WorkspaceList=A -jar /usr/share/java/jenkins.war --webroot=/var/cache/jenkins/war --httpPort=8080 --prefix=/jenkins `

@hkaiser  @akheir This change seems to have been reverted in the last few days. There is a "@" symbol in the CI path again, which causes the same problem breaking some tests like before. Any ideas?

**Comment by akheir** [comment]
The new update for Jenkins totally remodeled the startup scripts. I tried to pass the arguments through systemctl, let's check again

**Comment by Pansysk75** [comment]
> @Pansysk75 Done it differently this time through the systemctl. I hope this will fix it.

The fix worked! Thanks a lot for figuring it out.

**Pull request closed without merging**
