### PR TITLE
[WIP] shift_left && shift_right algorithms

### LINKED ISSUE #3706: Add shift_left and shift_right algorithms
P0769 was accepted for C++20 (http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0769r2.pdf). This adds the `shift_left` and `shift_right` algorithms. We should implement those as part of our parallel algorithm module (see #1141).

See also for an exemplar (sequential) implementation of those here: https://github.com/danra/shift_proposal.

### PR DESCRIPTION
**Pull request by shikharvashistha**
Fixes #3706 

## Proposed Changes

  - Motive of this PR is to implement shift_right && shift_left algorithm.
  - A very basic Idea based on exemplar (sequential) implementation provided in same issue mentioned above.
  

## Any background context you want to provide?

Please share suggestions, ideas, guidance regarding the same.

### CODE REVIEW

**Comment by hkaiser** [comment]
@rainmaker6 thanks for working on this. In order to proceed, first of all please

- (clang-)format the new files
- add real tests for the functionalities implemented.

**Comment by msimberg** [comment]
retest

**Comment by hkaiser** [comment]
@rainmaker6 could you please use the `.clang-format` file that is located in the root of our repository (here: https://github.com/STEllAR-GROUP/hpx/blob/master/.clang-format)?

**Comment by msimberg** [comment]
retest

**Comment by hkaiser** [comment]
@rainmaker6 this is still a draft, do you plan to move this forward?

**Comment by rainmaker6** [comment]
> @rainmaker6 this is still a draft, do you plan to move this forward?

Sir,
I would like to bring to your kind notice that this is the project I've submitted GSoC proposal for this year. 

I would like to know from you that-is it possible to continue on the same project this week(was unwell), as more than 40% of work is already completed by me.

I'll change it from draft to final if approved by you.

Regards
Shikhar Vashistha

**Comment by msimberg** [comment]
retest

**Comment by msimberg** [comment]
@shikharvashistha do you still plan to work on this?

**Comment by hkaiser** [comment]
> @shikharvashistha do you still plan to work on this?

I think we can close this PR here. @Jedi18 is currently working on implementing the algorithms.

**Pull request closed without merging**
