### PR TITLE
Adding HPX dependency tool (adapted from Boostdep tool)

### PR DESCRIPTION
**Pull request by hkaiser**
Adding a tool that helps generating various dependency reports, for an example see: https://hpx.stellar-group.org/files/report/.

This tool was adapted from @pdimov's Boostdep tool (https://github.com/pdimov/boostdep-report).

- adding target to build dependency report
- flyby: fixing circular dependency between config and preprocessor,
  and between hashing and serialization
- flyby: generate config_registry only if needed

### CODE REVIEW

**Comment by hkaiser** [comment]
@msimberg could you please have a look at why all of the cscs debug builders fail to report results here?

**Comment by msimberg** [comment]
test cscs

**Comment by msimberg** [comment]
retest cscs

**Comment by hkaiser** [comment]
This can be merged once the clang 14 issue has been resolved (see #5864)

**Pull request merged**
