### PR TITLE
Simplify allocator rebinding in pack traversal

### PR DESCRIPTION
**Pull request by K-ballo**
Workaround for #2904, broken build for Intel compilers

### CODE REVIEW

**Comment by hkaiser** [comment]
Thanks @K-ballo, let's go ahead and merge this as a stop-gap measure. 

@Naios would you have time to change the original code at some point? I think we could try replacing the offending `decltype()` with a 

    typname std::allocator_traits<Allocator>::template rebind_alloc<NewType>

which might already solve the problem.

**Comment by Naios** [comment]
In my opinion it would be better to conditionally disable the stateful allocator rebinding through the preprocessor if the intel compiler is used, instead of outcommenting the code for every toolchain.

@K-ballo could you try to apply the possible workaround proposed by @hkaiser please?
Currently I don't have a working environment with an Intel compiler.

Let me know if I can help more on this.

**Comment by K-ballo** [comment]
> Currently I don't have a working environment with an Intel compiler.

@Naios Rostam has a working Intel compiler. You should probably already have access there, if not we can get you an account.

**Comment by K-ballo** [comment]
> @K-ballo could you try to apply the possible workaround proposed by @hkaiser please?

@Naios the proposed workaround allows Intel to build core HPX, but it causes it to fail while building the `pack_traversal` unit tests. In particular, touching up on the container remapping logic seems to be causing the tuple remapping logic to fail, as those are the cases from the unit test that stop compiling after the change. Other compilers remain unaffected.

**Comment by hkaiser** [comment]
@K-ballo circleci is not happy with this... it might not be possible to simply use the allocator_traits after all.

**Comment by K-ballo** [comment]
@hkaiser That was caused by my latest commit. Removing and trying again...

**Pull request merged**
