### PR TITLE
Fixing when_xxx and wait_xxx for MSVC12

### PR DESCRIPTION
**Pull request by hkaiser**

### CODE REVIEW

**Comment by sithhell** [comment]
Is msvc having problems with std::enable_if?

**Comment by hkaiser** [comment]
> Is msvc having problems with std::enable_if?

No we just have not consistently switched from `boost::enable_if` to `std::enable_if`. We should probably slowly phase out `boost::enable_if`, though.

**Comment by K-ballo** [comment]
Is this due to lack of C++14 SFINAE-friendly `std::iterator_traits`?

**Comment by hkaiser** [comment]
> Is this due to lack of C++14 SFINAE-friendly  std::iterator_traits

Partially yes, also because of lacking SFINAE on the defaulted function template argument.

**Comment by sithhell** [comment]
LGTM now!

**Pull request merged**
