### PR TITLE
Fixing 2996

### LINKED ISSUE #2996: Build fails with HPX_WITH_HWLOC=OFF
```
> make hello_world_exe
[  0%] Building CXX object src/CMakeFiles/hpx.dir/runtime.cpp.o
In file included from /home/simbergm/src/hpx/hpx/runtime/serialization/detail/polymorphic_nonintrusive_factory.hpp:23:0,
                 from /home/simbergm/src/hpx/hpx/lcos/future.hpp:15,
                 from /home/simbergm/src/hpx/hpx/performance_counters/counters.hpp:10,
                 from /home/simbergm/src/hpx/hpx/performance_counters/counter_creators.hpp:11,
                 from /home/simbergm/src/hpx/src/runtime.cpp:10:
/home/simbergm/src/hpx/hpx/util/static.hpp: In instantiation of ‘static T& hpx::util::static_<T, Tag>::get_reference() [with T = hpx::threads::noop_topology; Tag = hpx::threads::noop_topology::noop_topology_tag; hpx::util::static_<T, Tag>::reference = hpx::threads::noop_topology&]’:
/home/simbergm/src/hpx/hpx/util/static.hpp:50:26:   required from ‘hpx::util::static_<T, Tag>::static_() [with T = hpx::threads::noop_topology; Tag = hpx::threads::noop_topology::noop_topology_tag]’
/home/simbergm/src/hpx/hpx/runtime/threads/policies/noop_topology.hpp:243:68:   required from here
/home/simbergm/src/hpx/hpx/util/static.hpp:76:22: error: cannot declare variable ‘t’ to be of abstract type ‘hpx::threads::noop_topology’
             static T t;
                      ^
In file included from /home/simbergm/src/hpx/hpx/runtime/threads/policies/topology.hpp:12:0,
                 from /home/simbergm/src/hpx/src/runtime.cpp:25:
/home/simbergm/src/hpx/hpx/runtime/threads/policies/noop_topology.hpp:32:8: note:   because the following virtual functions are pure within ‘hpx::threads::noop_topology’:
 struct noop_topology : topology
        ^
In file included from /home/simbergm/src/hpx/hpx/runtime/threads/thread_executor.hpp:14:0,
                 from /home/simbergm/src/hpx/hpx/lcos/detail/future_data.hpp:16,
                 from /home/simbergm/src/hpx/hpx/lcos/future.hpp:12,
                 from /home/simbergm/src/hpx/hpx/performance_counters/counters.hpp:10,
                 from /home/simbergm/src/hpx/hpx/performance_counters/counter_creators.hpp:11,
                 from /home/simbergm/src/hpx/src/runtime.cpp:10:
/home/simbergm/src/hpx/hpx/runtime/threads/topology.hpp:195:34: note:   virtual hpx::threads::hwloc_bitmap_ptr hpx::threads::topology::cpuset_to_nodeset(hpx::threads::mask_cref_type) const
         virtual hwloc_bitmap_ptr cpuset_to_nodeset(
                                  ^
/home/simbergm/src/hpx/hpx/runtime/threads/topology.hpp:206:23: note:   virtual void* hpx::threads::topology::allocate_membind(std::size_t, hpx::threads::hwloc_bitmap_ptr, hpx::threads::hpx_hwloc_membind_policy, int) const
         virtual void* allocate_membind(std::size_t len,
                       ^
/home/simbergm/src/hpx/hpx/runtime/threads/topology.hpp:210:36: note:   virtual hpx::threads::mask_type hpx::threads::topology::get_area_membind_nodeset(const void*, std::size_t, void*) const
         virtual threads::mask_type get_area_membind_nodeset(
                                    ^
/home/simbergm/src/hpx/hpx/runtime/threads/topology.hpp:213:22: note:   virtual bool hpx::threads::topology::set_area_membind_nodeset(const void*, std::size_t, void*) const
         virtual bool set_area_membind_nodeset(
                      ^
/home/simbergm/src/hpx/hpx/runtime/threads/topology.hpp:216:21: note:   virtual int hpx::threads::topology::get_numa_domain(const void*, void*) const
         virtual int get_numa_domain(const void *addr, void *nodeset) const = 0;
                     ^
src/CMakeFiles/hpx.dir/build.make:206: recipe for target 'src/CMakeFiles/hpx.dir/runtime.cpp.o' failed
make[3]: *** [src/CMakeFiles/hpx.dir/runtime.cpp.o] Error 1
CMakeFiles/Makefile2:1353: recipe for target 'src/CMakeFiles/hpx.dir/all' failed
make[2]: *** [src/CMakeFiles/hpx.dir/all] Error 2
CMakeFiles/Makefile2:6713: recipe for target 'examples/quickstart/CMakeFiles/hello_world_exe.dir/rule' failed
make[1]: *** [examples/quickstart/CMakeFiles/hello_world_exe.dir/rule] Error 2
Makefile:2279: recipe for target 'hello_world_exe' failed
make: *** [hello_world_exe] Error 2
```

Relevant issue: #2977

@biddisco

### PR DESCRIPTION
**Pull request by biddisco**
fix #2996

### CODE REVIEW

**Comment by sithhell** [comment]
It turns out that you run into this runtime problem with this change if hwloc is disabled:
```
[11:53:22] <jbjnr> apparently not. terminate called after throwing an instance of 'std::length_error'
[11:53:22] <jbjnr>   what():  vector::reserve
[11:53:35] <jbjnr> but that has nothing to do with my changes.
```

This seems to be closely related to the resource partitioner requiring hwloc.

**Comment by biddisco** [comment]
- option 1 Fix it so it works without hwloc (probably can't be made completely RP safe, but should work with anything that doesn't have RP in user code),  and leave next release with hwloc optional.
- option 2 move forward with making hwloc compulsory and get compulsory status into the next release

**Comment by hkaiser** [comment]
@biddisco either way is fine for me.

**Comment by biddisco** [comment]
If nobody is too concerned about dropping hwloc optional status, then I will move forward with making hwloc compulsory and cleaning the noop topology away and promoting hwloc_topology

**Comment by hkaiser** [comment]
> If nobody is too concerned about dropping hwloc optional status, then I will move forward with making hwloc compulsory and cleaning the noop topology away and promoting hwloc_topology.

Ok, cool. Please don't make hwloc 2.0 compulsory, though.

**Comment by msimberg** [comment]
Should we close this if we go with #2977 instead? Especially as this PR only fixes compilation but still fails at runtime.

**Comment by hkaiser** [comment]
We can close this once #2977 has been fixed, yes.

**Comment by msimberg** [comment]
Closing because of #3133.

**Pull request closed without merging**
