### PR TITLE
Module datastructures

### PR DESCRIPTION
**Pull request by hkaiser**
This PR fixes the include directory for traits headers related to the datastructures module. It also adds missing compatibility headers for those traits files.

Most importantly, this patch proposes a `moveonly_any` that is capable of storing move-only data types.

### CODE REVIEW

**Comment by hkaiser** [comment]
@msimberg, @sithhell I think this is good to go now. Please review. I have no idea why the clang-oldest builder is unhappy...

**Comment by msimberg** [comment]
This doesn't answer your question but the error message is definitely related to this PR: https://cdash.cscs.ch//viewBuildError.php?buildid=75704. @sithhell any ideas?

**Comment by hkaiser** [comment]
> This doesn't answer your question but the error message is definitely related to this PR

I know :/ I think this version of clang does not properly implement `std::is_void<>` (unlikely, but a possible reason, see: https://github.com/STEllAR-GROUP/hpx/pull/4113/files#diff-9a4d5912ff0cdb713bd9aa5930718dc3R599-R603). Possibly it could be the `enable_if` applied to a forward declaration... Not sure.

**Comment by hkaiser** [comment]
@msimberg I have modified the implementation to get away without the SFINAE'd forwarding declaration. Let's see if this changes things for this compiler.

**Comment by hkaiser** [comment]
@msimberg things are better now: https://cdash.cscs.ch//buildSummary.php?buildid=75954

**Comment by sithhell** [comment]
Hmm, too bad. I don't like the name `moveonly_any`. I would have proposed `unique_any` to go along with `unique_function`.

**Comment by msimberg** [comment]
@sithhell sorry, I didn't realize there was still an ongoing discussion about naming. I have no opinion on this so feel free to rename it if you come to a concensus on it.

**Comment by hkaiser** [comment]
I'm fine with any name, so `unique_any` sounds good to me.

**Pull request merged**
