### PR TITLE
Adopt format in more places

### PR DESCRIPTION
**Pull request by K-ballo**

### CODE REVIEW

**Review by hkaiser — DISMISSED** [review]
Very nice, thanks!

**Comment by hkaiser** [comment]
@K-ballo please let us know f this is ready to go.

**Comment by K-ballo** [comment]
> @K-ballo please let us know f this is ready to go.

I'm not planning any more changes, if the failing checks are expected then it's ready to go.

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by hkaiser** [comment]
There are still the clang-format problems as reported here: https://app.circleci.com/pipelines/github/STEllAR-GROUP/hpx/7282/workflows/c8dc6e25-f7f9-42e8-bf22-81c2743b301e/jobs/245925

**Pull request merged**
