### PR TITLE
Fixing context switching

### PR DESCRIPTION
**Pull request by hkaiser**
- windows: add saving vector registers
- linux: add saving FP state registers

### CODE REVIEW

**Comment by sithhell** [comment]
Do we know that the missing floating point state switch is the culprit? IIRC, the generic context does this already as well as the posix one should do that already, so it should be easily verified if this is really needed.

**Comment by hkaiser** [comment]
> Do we know that the missing floating point state switch is the culprit? IIRC, the generic context does this already as well as the posix one should do that already, so it should be easily verified if this is really needed.

That was exactly the problem. Our posix context switch did not touch the floating point registers before. This patch rectifies this situation.

**Comment by sithhell** [comment]
Our special linux based context switching doesn't save the FP state registers. the one based on the posix routines should though. as well as the one based on boost.context.

**Comment by hkaiser** [comment]
> Our special linux based context switching doesn't save the FP state registers. the one based on the posix routines should though. as well as the one based on boost.context.

@sithhell: isn't that what this PR is all about?

**Pull request merged**
