### PR TITLE
Handle exceptions thrown during initialization of parcel handler

### PR DESCRIPTION
**Pull request by hkaiser**
Fixes unexpected behavior if during initialization one of the parcel-ports throws an exception

### CODE REVIEW

**Comment by diehlpk** [comment]
@hkaiser and @khuck While testing this patch, I encountered a new error with current hpx master

```
pdiehl@daint104:/scratch/snx3000/pdiehl> /scratch/snx3000/pdiehl/Octo-Tiger-mpi/build/hpx/bin/hello_world_distributed
terminate called after throwing an instance of 'hpx::detail::exception_with_info<hpx::exception>'
  what():  failed to insert update_agas_cache_action into typename to id registry.: HPX(invalid_status)
```

**Comment by hkaiser** [comment]
> @hkaiser and @khuck While testing this patch, I encountered a new error with current hpx master
> 
> ```
> pdiehl@daint104:/scratch/snx3000/pdiehl> /scratch/snx3000/pdiehl/Octo-Tiger-mpi/build/hpx/bin/hello_world_distributed
> terminate called after throwing an instance of 'hpx::detail::exception_with_info<hpx::exception>'
>   what():  failed to insert update_agas_cache_action into typename to id registry.: HPX(invalid_status)
> ```

I think that this is unrelated to the issue at hand.

**Comment by diehlpk** [comment]
@hkaiser The new error messages is much better

```
{locality-id}: 96
{hostname}: [ (mpi:96) (tcp:148.187.41.27:8006) ]
{process-id}: 1344
{os-thread}: <unknown>
{thread-description}: <unknown>
{state}: state_initialized
{auxinfo}: 
{file}: /scratch/snx3000/pdiehl/Octo-Tiger-mpi/src/hpx/plugins/parcelport/tcp/connection_handler_tcp.cpp
{line}: 82
{function}: virtual hpx::parcelset::policies::tcp::connection_handler::~connection_handler()
{what}: Assertion 'acceptor_ == nullptr' failed: HPX(assertion_failure)
```

**Comment by hkaiser** [comment]
> @hkaiser The new error messages is much better
> 
> ```
> {locality-id}: 96
> {hostname}: [ (mpi:96) (tcp:148.187.41.27:8006) ]
> {process-id}: 1344
> {os-thread}: <unknown>
> {thread-description}: <unknown>
> {state}: state_initialized
> {auxinfo}: 
> {file}: /scratch/snx3000/pdiehl/Octo-Tiger-mpi/src/hpx/plugins/parcelport/tcp/connection_handler_tcp.cpp
> {line}: 82
> {function}: virtual hpx::parcelset::policies::tcp::connection_handler::~connection_handler()
> {what}: Assertion 'acceptor_ == nullptr' failed: HPX(assertion_failure)
> ```

I'd say that this is a follow-on error. I'll have a look.

**Comment by hkaiser** [comment]
> > @hkaiser The new error messages is much better
> > ```
> > {locality-id}: 96
> > {hostname}: [ (mpi:96) (tcp:148.187.41.27:8006) ]
> > {process-id}: 1344
> > {os-thread}: <unknown>
> > {thread-description}: <unknown>
> > {state}: state_initialized
> > {auxinfo}: 
> > {file}: /scratch/snx3000/pdiehl/Octo-Tiger-mpi/src/hpx/plugins/parcelport/tcp/connection_handler_tcp.cpp
> > {line}: 82
> > {function}: virtual hpx::parcelset::policies::tcp::connection_handler::~connection_handler()
> > {what}: Assertion 'acceptor_ == nullptr' failed: HPX(assertion_failure)
> > ```
> 
> I'd say that this is a follow-on error. I'll have a look.

@diehlpk this should be fine now as well. If one (or more) parcelports fail during initialization, we now print a message and try continuing execution (after disabling the parcelports that failed).

**Pull request merged**
