### PR TITLE
Solving #2402 and #2403

### LINKED ISSUE #2402: datapar algorithm instantiated with wrong type
Hi,

I'm trying to compile a simple datapar example with HPX and Vc. The lambda should be compiled in two versions: One with the Vc vector-type and one with the Vc scalar-type. But the error I get from my compiler indicates that it is also compiled with 'double &' as its type.

```#include <hpx/include/datapar.hpp>
#include <hpx/include/parallel_for_each.hpp>

#include <boost/range/functions.hpp>

int main(int argc, char **argv) {
  std::vector<double> large(64);
  
  auto zip_it_begin = hpx::util::make_zip_iterator(boost::begin(large));
  auto zip_it_end = hpx::util::make_zip_iterator(boost::end(large));
  
  hpx::parallel::for_each(hpx::parallel::datapar_execution, zip_it_begin, zip_it_end, [](auto t) {
      using comp_type = typename hpx::util::tuple_element<0, decltype(t)>::type;
      using var_type = typename hpx::util::decay<comp_type>::type;

      var_type mass_density = 0.0;
      mass_density(mass_density > 0.0) = 7.0;
    });
  return 0;
}
```

Compiler message, note the second line:
```
g++-6 -o debug/wrong_type.o -c -std=c++14 -fopenmp -Wall -Wno-ignored-attributes -Wno-unused-local-typedefs -O0 -g -fno-omit-frame-pointer -DHPX_DEBUG -DHPX_APPLICATION_EXPORTS -DHPX_ENABLE_ASSERT_HANDLER -Ihpx_install_debug/include -Ihpx_install_debug/include/hpx/external -IVc_install_debug/include -Iboost_1_62_0_install_debug/include wrong_type.cpp
wrong_type.cpp: In instantiation of ‘main(int, char**)::<lambda(auto:1)> [with auto:1 = hpx::util::tuple<double&>]’:
hpx_install_debug/include/hpx/util/result_of.hpp:43:39:   required by substitution of ‘template<class F, class ... Ts> decltype (declval<F>()((declval<Ts>)()...)) hpx::util::detail::result_of_function_object_impl::invoke(F&&, Ts&& ...) [with F = main(int, char**)::<lambda(auto:1)>; Ts = {hpx::util::tuple<double&>}]’
hpx_install_debug/include/hpx/util/result_of.hpp:52:72:   required from ‘struct hpx::util::detail::result_of_function_object_impl::result_of_invoke<main(int, char**)::<lambda(auto:1)>(hpx::util::tuple<double&>&&)>’
hpx_install_debug/include/hpx/util/result_of.hpp:151:16:   required from ‘struct hpx::util::detail::result_of_impl<main(int, char**)::<lambda(auto:1)>, main(int, char**)::<lambda(auto:1)>(hpx::util::tuple<double&>&&)>’
hpx_install_debug/include/hpx/util/result_of.hpp:182:12:   required from ‘struct hpx::util::result_of<main(int, char**)::<lambda(auto:1)>(hpx::util::tuple<double&>&&)>’
hpx_install_debug/include/hpx/traits/is_callable.hpp:47:12:   required from ‘struct hpx::traits::is_callable<main(int, char**)::<lambda(auto:1)>(hpx::util::tuple<double&>&&), void>’
hpx_install_debug/include/hpx/parallel/traits/projected.hpp:138:16:   required from ‘struct hpx::parallel::traits::detail::is_indirect_callable_impl<main(int, char**)::<lambda(auto:1)>, hpx::util::tuple<double&>&&>’
hpx_install_debug/include/hpx/parallel/traits/projected.hpp:148:16:   required from ‘struct hpx::parallel::traits::detail::is_indirect_callable<main(int, char**)::<lambda(auto:1)>, hpx::util::detail::pack<hpx::parallel::traits::projected<hpx::parallel::util::projection_identity, hpx::util::zip_iterator<__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > > > > >, void>’
hpx_install_debug/include/hpx/parallel/traits/projected.hpp:160:12:   required from ‘struct hpx::parallel::traits::is_indirect_callable<main(int, char**)::<lambda(auto:1)>, hpx::parallel::traits::projected<hpx::parallel::util::projection_identity, hpx::util::zip_iterator<__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > > > > >’
hpx_install_debug/include/hpx/parallel/algorithms/for_each.hpp:408:5:   required by substitution of ‘template<class ExPolicy, class InIter, class F, class Proj, int _concept_requires_414, typename std::enable_if<((_concept_requires_414 == 43) || (((hpx::parallel::v1::is_execution_policy<T>::value && hpx::traits::is_iterator<Iter>::value) && hpx::parallel::traits::is_projected<Proj, InIter>::value) && hpx::parallel::traits::is_indirect_callable<F, hpx::parallel::traits::projected<Proj, InIter> >::value)), int>::type _concept_check_414> typename hpx::parallel::util::detail::algorithm_result<ExPolicy, T>::type hpx::parallel::v1::for_each(ExPolicy&&, InIter, InIter, F&&, Proj&&) [with ExPolicy = const hpx::parallel::v1::datapar_execution_policy&; InIter = hpx::util::zip_iterator<__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > > >; F = main(int, char**)::<lambda(auto:1)>; Proj = hpx::parallel::util::projection_identity; int _concept_requires_414 = 42; typename std::enable_if<((_concept_requires_414 == 43) || (((hpx::parallel::v1::is_execution_policy<T>::value && hpx::traits::is_iterator<Iter>::value) && hpx::parallel::traits::is_projected<Proj, InIter>::value) && hpx::parallel::traits::is_indirect_callable<F, hpx::parallel::traits::projected<Proj, InIter> >::value)), int>::type _concept_check_414 = <missing>]’
wrong_type.cpp:18:6:   required from here
wrong_type.cpp:17:19: error: ‘mass_density’ cannot be used as a function
       mass_density(mass_density > 0.0) = 7.0;
       ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by hkaiser**
This fixes #2402 and #2403

### CODE REVIEW

**Comment by hkaiser** [comment]
@DavidPfander-UniStuttgart This patch should solve the issue (for now). It adds a workaround disabling the concept checking for the case when a zip_iterator is used with a vector pack execution policy. This is not the best of all solutions but the only one I was able to come up with for now. We can revisit this issue once we better understand how this could be solved 'properly'. Please verify whether your problem is solved now.

**Comment by hkaiser** [comment]
@DavidPfander-UniStuttgart This is now fixing both of your problems: #2402 and #2403. Please verify.

**Comment by DavidPfander-UniStuttgart** [comment]
I think this still doesn't compile the example I provided. Does it compile for you?

**Comment by hkaiser** [comment]
I added the examples as tests and those seem to compile. Which one does not compile for you?

**Comment by hkaiser** [comment]
@DavidPfander-UniStuttgart Things should be fine now.

**Pull request merged**
