### PR TITLE
build(doxy): don't extract private members

### PR DESCRIPTION
**Pull request by bhumitattarde**

### CODE REVIEW

**Review by hkaiser — DISMISSED** [review]
LGTM, thanks!

**Comment by hkaiser** [comment]
@bhumitattarde could you please rebase onto master to resolve the conflict?

**Comment by bhumitattarde** [comment]
@hkaiser check now?

**Comment by hkaiser** [comment]
The doc build is failing now: https://app.circleci.com/pipelines/github/STEllAR-GROUP/hpx/12199/workflows/6d6973e0-bb86-40f7-bdde-17d23233610f/jobs/315745

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by hkaiser** [comment]
bors merge

**Pull request merged**
