### PR TITLE
added logic to detect riscv compiler configured for 64 bit target

### PR DESCRIPTION
**Pull request by ct-clmsn**
## Fixes #

Modification to cmake target detection script. Enforces 64-bit target constraint on risc-v builds.

## Proposed Changes

  - cmake/TargetArch.cmake has 1 modification

## Any background context you want to provide?

Current risc-v support does not check to see if the compiler is configured for the 32 bit or 64 bit build target. This PR enforces a check, in cmake, making sure the 64-bit build target is configured in the compiler.

## Checklist

Not all points below apply to all pull requests.

- [x] I have added a new feature and have added tests to go along with it.
- [ ] I have fixed a bug and have added a regression test.
- [ ] I have added a test using random numbers; I have made sure it uses a seed, and that random numbers generated are valid inputs for the tests.

### CODE REVIEW

**Comment by hkaiser** [comment]
@ct-clmsn do you expect more changes for this?

**Comment by ct-clmsn** [comment]
@hkaiser yeah, is it cool if I continue to push on this branch for the context switching implementation or would ya'll prefer a new branch?

**Comment by hkaiser** [comment]
> @hkaiser is it cool if I continue to push on this branch for the context switching implementation or would ya'll prefer a new branch? as for cmake scripts, this will be the last modification.

As you prefer... there is no problem in doing it either way. 

What difference will a new context switching implementation do compared to the one based on Boost.Context?

**Comment by ct-clmsn** [comment]
@hkaiser, great question! This is probably a misunderstanding on my part; figured you all had a need/preference for a non-boost implementation.

**Comment by hkaiser** [comment]
> @hkaiser, great question! This is probably a misunderstanding on my part; figured you all had a need/preference for both boost and non-boost implementations.

So far, we have relied on the Boost.Context implementation for platforms for which we don't have a 'native' implementation (those were created long before Boost.Context existed, and we have kept them). The only advantage of not using the Boost.Context version is that it removes one external dependency. 

That said, if you feel that you would like to create a 'native' one (independent of Boost) because that might be beneficial in one way or another (or just because you like the challenge), please go ahead.

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by ct-clmsn** [comment]
@hkaiser fair enough! In that case, I'm good with closing this branch and PR out with this update.

**Comment by hkaiser** [comment]
This can go in now, thanks again!

**Comment by hkaiser** [comment]
bors merge

**Pull request merged**
