### PR TITLE
Introduced default (main) template implementation for ignore_while_checking

### LINKED ISSUE #1485: `ignore_while_locked` doesn't support all Lockable types
The current implementation of `ignore_while_locked` only supports locks. This gets problematic when it is used in places where anything *Lockable* can be used, for example `condtion_variable::wait`. If a unsupported *Lockable* is passed we get a compile error. This change was introduced with b6d4e0ca5a62a66422419990de4fd319a6f50bb0. Before that we just silently ignored unsupported lockables leading to runtime failures when lock detection is turned on.

A suggestion to fix that situation would a default template that merely tries to have the passed ignored.

### PR DESCRIPTION
**Pull request by hkaiser**
This patch fixes #1485

### CODE REVIEW

**Comment by hkaiser** [comment]
This implements what we agreed on after some discussions on the list. Is there any reason not to go ahead with merging it?

**Comment by K-ballo** [comment]
I feel uneasy about this change. I do not think it actually solves #1485, but I am not familiar enough with the lock registering mechanism to review this PR. The address of a lock does not reliably guarantee mutex identity, and I do not think a general solution exist. However, that would mean that this PR leaves us in the same state that we were initially, which presumably leads to hard to debug runtime errors.

**Comment by hkaiser** [comment]
@K-ballo the main template proposed by this patch does not aim at using the address of a lock but the address of the mutex itself for identification (this corresponds to the practice we've employed so far, as we've always used the mutex itself for this). It essentially allows to use the address of the mutex to tell the lock checking what it should ignore. 

If the user passes something which is not identifying a mutex, it may not be ignored while performing lock checking. So in the worst case the user sees false positives.

**Comment by hkaiser** [comment]
For the record: @K-ballo suggested to build CV and the other synchronization primitives using `spinlock_no_backoff` for the internal synchronization needs. This would allow to drop the `ignore_lock_detection` dance altogether.

**Comment by sithhell** [comment]
On Thursday, May 07, 2015 06:34:32 Hartmut Kaiser wrote:
> For the record: @K-ballo suggested to build CV and the other synchronization
> primitives using `spinlock_no_backoff` for the internal synchronization
> needs. This would allow to drop the `ignore_lock_detection` dance
> altogether.

We discussed this on IRC last night. I am not particularly happy about that 
either. The two main reasons:
1) It still doesn't solve the issue, at it will probably come back at us again 
at some later point
2) `spinlock_no_backoff` is only a good idea when we know that the lock is not 
very contended (for performance reasons)

A consensus we came up with was to have something like a 
`ignore_all_held_locks` which would just ignore all currently held locks, this 
would solve the issue of not being able to generically detect any Lockable in 
`ignore_while_checking`

**Comment by sithhell** [comment]
LGTM!

**Pull request merged**
