### PR TITLE
Add spdx license and check

### LINKED ISSUE #4100: Add SPDX identifier to all files
Software Package Data Exchange® (SPDX®) is an open standard for communicating software bill of material information (including components, licenses, copyrights, and security references). See https://spdx.org/ for more information.

We should start adding the SPDX license identifier to our files:
```
// SPDX-License-Identifier: BSL-1.0
```
(prefixed with the appropriate comment tag depending on the filetype.

This can probably be done with a script and is a one-time change. We should also change the inspect license check to verify the existance of this tag in each file.

### PR DESCRIPTION
**Pull request by aurianer**
Fixes #4100

### CODE REVIEW

**Comment by aurianer** [comment]
Sorry for force pushing so much, my script left over some files, that should be good now

**Comment by hkaiser** [comment]
> I don't know why codacy is not running at all :/

I poked it, let's see.

**Comment by hkaiser** [comment]
@aurianer it went through now: https://app.codacy.com/manual/STEllAR-GROUP/hpx/pullRequest?prid=4200943. GitHub is confused and refers to the wrong project as there were two integrations with codacy installed here. I have removed one of the integrations, in the future things should be reported correctly.

**Comment by aurianer** [comment]
Thank you @hkaiser !

**Pull request merged**
