### PR TITLE
Fixing cyclic dependencies in naming and agas modules

### PR DESCRIPTION
**Pull request by hkaiser**
@zao this should fix the linker errors you were seeing

### CODE REVIEW

**Comment by zao** [comment]
Ran a build with this PR and `-k 0` to find any other failing examples. A common error for many of them is the following:
```
[120/264] Linking CXX executable bin/1d_stencil_1
FAILED: bin/1d_stencil_1
: && /usr/bin/c++ -O2 -g -DNDEBUG -pthread -Wl,-z,defs -fvisibility=hidden examples/1d_stencil/CMakeFiles/1d_stencil_1.dir/1d_stencil_1.cpp.o -o bin/1d_stencil_1  -Wl,-rpath,:::::::::::::::::::::::::::::::  lib/libhpx_wrap.a  lib/libhpx_init.a  lib/libhpx.a  lib/libhpx_checkpoint.a  lib/libhpx_executors_distributed.a  lib/libhpx_include.a  lib/libhpx_compute.a  lib/libhpx_init_runtime.a  lib/libhpx_collectives.a  lib/libhpx_lcos_distributed.a  lib/libhpx_parcelport_tcp.a  lib/libhpx_resiliency_distributed.a  lib/libhpx_runtime_distributed.a  lib/libhpx_segmented_algorithms.a  lib/libhpx_distribution_policies.a  lib/libhpx_performance_counters.a  lib/libhpx_runtime_components.a  lib/libhpx_agas.a  lib/libhpx_async_colocated.a  lib/libhpx_agas_base.a  lib/libhpx_async_distributed.a  lib/libhpx_parcelset.a  lib/libhpx_actions.a  lib/libhpx_naming.a  lib/libhpx_checkpoint_base.a  lib/libhpx_plugin_factories.a  lib/libhpx_command_line_handling.a  lib/libhpx_components.a  lib/libhpx_actions_base.a  lib/libhpx_components_base.a  lib/libhpx_parcelset_base.a  lib/libhpx_naming_base.a  lib/libhpx_statistics.a  lib/libhpx_core.a  -Wl,--whole-archive  -Wl,--no-whole-archive  lib/libhpx_batch_environments.a  lib/libhpx_cache.a  lib/libhpx_include_local.a  lib/libhpx_compute_local.a  lib/libhpx_init_runtime_local.a  lib/libhpx_algorithms.a  lib/libhpx_lcos_local.a  lib/libhpx_resiliency.a  lib/libhpx_runtime_local.a  lib/libhpx_command_line_handling_local.a  lib/libhpx_asio.a  lib/libhpx_static_reinit.a  lib/libhpx_testing.a  lib/libhpx_threadmanager.a  lib/libhpx_thread_pool_util.a  lib/libhpx_async_local.a  lib/libhpx_timed_execution.a  lib/libhpx_executors.a  lib/libhpx_execution.a  lib/libhpx_async_combinators.a  lib/libhpx_pack_traversal.a  lib/libhpx_io_service.a  lib/libhpx_properties.a  lib/libhpx_resource_partitioner.a  lib/libhpx_runtime_configuration.a  lib/libhpx_ini.a  lib/libhpx_program_options.a  lib/libhpx_thread_pools.a  lib/libhpx_schedulers.a  lib/libhpx_threading.a  lib/libhpx_futures.a  lib/libhpx_synchronization.a  lib/libhpx_threading_base.a  lib/libhpx_affinity.a  lib/libhpx_topology.a  lib/libhpx_async_base.a  lib/libhpx_coroutines.a  lib/libhpx_memory.a  lib/libhpx_concurrency.a  lib/libhpx_allocator_support.a  lib/libhpx_execution_base.a  lib/libhpx_hashing.a  lib/libhpx_lock_registration.a  lib/libhpx_util.a  lib/libhpx_version.a  lib/libhpx_prefix.a  lib/libhpx_plugin.a  lib/libhpx_string_util.a  lib/libhpx_iterator_support.a  lib/libhpx_functional.a  lib/libhpx_datastructures.a  lib/libhpx_itt_notify.a  lib/libhpx_tag_invoke.a  lib/libhpx_serialization.a  lib/libhpx_debugging.a  lib/libhpx_errors.a  lib/libhpx_logging.a  lib/libhpx_filesystem.a  lib/libhpx_timing.a  lib/libhpx_hardware.a  lib/libhpx_thread_support.a  lib/libhpx_type_support.a  lib/libhpx_assertion.a  lib/libhpx_format.a  lib/libhpx_concepts.a  lib/libhpx_config.a  lib/libhpx_preprocessor.a  lib/libhpx_config_registry.a  /usr/lib64/libtcmalloc_minimal.so  /usr/lib64/libhwloc.so  -ldl  -lrt  -Wl,-wrap=main && :                                                  /usr/bin/ld: lib/libhpx_parcelset.a(parcelhandler.cpp.o): in function `hpx::parcelset::init_static_parcelport_factories(std::vector<hpx::plugins::parcelport_factory_base*, std::allocator<hpx::plugins::parcelport_factory_base*> >&)':                                                                                                                /mnt/stellar/builds/hpx-git/libs/full/parcelset/include/hpx/parcelset/static_parcelports.hpp:25: undefined reference to `parcelport_tcp_factory_init(std::vector<hpx::plugins::parcelport_factory_base*, std::allocator<hpx::plugins::parcelport_factory_base*> >&)'
/usr/bin/ld: /mnt/stellar/builds/hpx-git/libs/full/parcelset/include/hpx/parcelset/static_parcelports.hpp:25: undefined reference to `parcelport_tcp_factory_init(std::vector<hpx::plugins::parcelport_factory_base*, std::allocator<hpx::plugins::parcelport_factory_base*> >&)'
collect2: error: ld returned 1 exit status
```
It's always missing `parcelport_tcp_factory_init(std::vector<hpx::plugins::parcelport_factory_base*, std::allocator<hpx::plugins::parcelport_factory_base*> >&)`. This seems to be used in `libhpx_parcelset.a` and defined in `libhpx_parcelport_tcp.a`.

**Comment by zao** [comment]
Quite some additional failures linking tests, not sure if they belong in the same PR or separate issues: https://gist.github.com/zao/d1775a0ac8a28584033c229818704c43
Notable mention is that `libatomic` rears its head again there.

**Comment by hkaiser** [comment]
> Quite some additional failures linking tests, not sure if they belong in the same PR or separate issues: https://gist.github.com/zao/d1775a0ac8a28584033c229818704c43 Notable mention is that `libatomic` rears its head again there.

@zao would you have by any chance the cmake log as well?

**Comment by hkaiser** [comment]
retest lsu

**Comment by hkaiser** [comment]
retest lsu

**Comment by hkaiser** [comment]
bors merge

**Pull request merged**
