### PR TITLE
Add sender overloads to rotate/rotate_copy

### PR DESCRIPTION
**Pull request by hcq9102**
Add sender overloads to parallel algorithms.

#5513 PR was closed by accident.

### CODE REVIEW

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by hkaiser** [comment]
The problems we've had with #5513 seem to be resolved now, thanks!

**Comment by hcq9102** [comment]
> The problems we've had with #5513 seem to be resolved now, thanks!

Yes. Thank you!

**Comment by msimberg** [comment]
Thanks @hcq9102! Just for your information for the future, you can reopen closed pull requests. You just need to push to the same branch.

**Comment by hcq9102** [comment]
> Thanks @hcq9102! Just for your information for the future, you can reopen closed pull requests. You just need to push to the same branch.

Got it! Thanks a lot@msimberg .

**Pull request merged**
