### PR TITLE
Run CI inspect checks before building

### PR DESCRIPTION
**Pull request by K-ballo**

### CODE REVIEW

**Comment by hkaiser** [comment]
CircleCI is still failing, not sure why...

**Comment by K-ballo** [comment]
`master` is in a bad state:

**Comment by K-ballo** [comment]
`master` is in a bad state:

    /hpx\parallel\executors\execution.hpp: *Endline Whitespace*: 184
    /hpx\parallel\executors\execution_fwd.hpp: *Line length limit*: 380

...and the new location of inspect within the CI script must be causing its artifacts to be ignored. I'll look into it.

**Comment by K-ballo** [comment]
It seems circle-ci won't even look at generated artifacts when the build fails :/

**Comment by K-ballo** [comment]
Abandoning, as circle-ci won't collect artifacts for a failed build.

**Comment by hkaiser** [comment]
This may be a thing again after we've moved to CircleCI V2.

**Comment by sithhell** [comment]
It's already implemented there. See #3036.

**Pull request closed without merging**
