### PR TITLE
Fix API, troubleshooting & people

### PR DESCRIPTION
**Pull request by dimitraka**
The following changes are included:
- Fix copyright date
- Add mails to About HPX-People
- Fix and enrich troubleshooting
- Split Full API to multiple pages (rst files)

### CODE REVIEW

**Comment by gonidelis** [comment]
@dimitraka By chance, do you mind if you add my email to the static images too cause it's missing?

**Comment by dimitraka** [comment]
> @dimitraka By chance, do you mind if you add my email to the static images too cause it's missing? (the hotmail domain one)

Sure!

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by hkaiser** [comment]
bors merge

**Pull request merged**
