### PR TITLE
Fixing task annotations for actions

### LINKED ISSUE #4652: How to fix distributed action annotation
## Expected Behavior

In the past, distributed actions were annotated correctly.  Now, all localities other than 0 get just `<anonymous task>` tasks.

## Actual Behavior

I think the fix (or at least the problem) is in here:
https://github.com/STEllAR-GROUP/hpx/blob/9b9392a24c3406237fae4f04c68a2081c1e04ae8/libs/async/include/hpx/async/applier/apply.hpp#L388-L409

I am not sure how using a default `threads::thread_init_data`is supposed to do anything useful - it just creates a thread_description with the name `<anonymous task>`, from the default constructor.  The actual action is in the Action and/or Continuation objects, from what I can see in gdb - but I have no idea how to get a valid thread_description out of those objects.

## Steps to Reproduce the Problem

... Please be as specific as possible while describing how to reproduce your problem.

  1.  Configure HPX with APEX
  1.  `export APEX_CSV_OUTPUT=1` before running
  1.  Run a distributed test like:
```
mpirun -np 2 ./bin/fibonacci_futures_distributed --n-value 10 -t 1 -Ihpx.stacks.use_guard_pages=0 --distribute-at 9
```
  1. Then see the apex.1.csv file and the `<anonymous task>` timers should have been `fibonacci_future_action` instead.

## Specifications

... Please describe your environment

  - HPX Version:  current master
  - Platform (compiler, OS):  gcc 7.3 on RHEL

### PR DESCRIPTION
**Pull request by hkaiser**
- flyby: simplify hello_world_distributed

Fixes #4652

### CODE REVIEW

**Comment by hkaiser** [comment]
@khuck could you please check whether this fixes the issue for you?

**Comment by khuck** [comment]
testing it now...

**Comment by khuck** [comment]
> @khuck could you please check whether this fixes the issue for you?

Yes, works great!  Thanks!

**Comment by khuck** [comment]
Looks like I have some labeling issues in APEX, but the profiling is working...

**Pull request merged**
