### PR TITLE
Correcting target ids for symbol_namespace::iterate

### PR DESCRIPTION
**Pull request by hkaiser**
Fixes: https://github.com/STEllAR-GROUP/phylanx/issues/1321

### CODE REVIEW

**Comment by taless474** [comment]
Thank you @hkaiser. It resolved the issue.

**Comment by msimberg** [comment]
Thanks @hkaiser, this looks good. I'm going to retrigger the tests because of what I think was a problem on Piz Daint, but it's unlikely that will uncover something that the other builders didn't find.

**Comment by msimberg** [comment]
retest

**Review by aurianer — APPROVED** [review]
Thanks!

**Pull request merged**
