### PR TITLE
Enhance the formatting of the documentation 

### PR DESCRIPTION
**Pull request by dimitraka**
- Change the font color of the code text
- Add an extension for the copy button. The copy button appears at the top-right of a code block.

### CODE REVIEW

**Comment by hkaiser** [comment]
@dimitraka I have updated the version of our docker image after your changes. Could you please change the following spots to `stellargroup/build_env:14` so this PR will pick up the new Python configuration:

- https://github.com/STEllAR-GROUP/hpx/blob/master/.circleci/config.yml#L13 
- https://github.com/STEllAR-GROUP/hpx/blob/master/.github/workflows/linux_bors.yml#L19
- https://github.com/STEllAR-GROUP/hpx/blob/master/.github/workflows/linux_debug.yml#L14
- https://github.com/STEllAR-GROUP/hpx/blob/master/.github/workflows/linux_release_fetchcontent.yml#L14
- https://github.com/STEllAR-GROUP/hpx/blob/master/.github/workflows/linux_sanitizers.yml#L14

**Comment by hkaiser** [comment]
@dimitraka Please add a copyright, a Boost license, and an SPDX statement to the new file you have added: https://github.com/dimitraka/hpx/blob/doc_updates/docs/sphinx/_static/custom.css. E.g. something like
```css
/* Copyright (c) 2022 Dimitra Karatza */
/* SPDX-License-Identifier: BSL-1.0 */
/* Distributed under the Boost Software License, Version 1.0. (See accompanying */
/* file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt) */
```

**Comment by hkaiser** [comment]
@dimitraka inspect is still complaining about the css file not being linked from anywhere (`https://output.circle-artifacts.com/output/job/750a6397-657c-4f87-a08d-d6f7fde995ca/artifacts/0/hpx_inspect_report.html`). We can suppress this by adding an empty file named `hpx-no-inspect` to the directory `docs/sphinx/_static/`. This will cause inspect not to look at files in that directory.

Otherwise, the change seems to work as expected (e.g.: https://output.circle-artifacts.com/output/job/6e751fe9-2294-45a9-b334-990b25019898/artifacts/0/hpx/build/share/hpx/docs/html/examples/fibonacci_local.html#setup). Great, thanks!

**Comment by dimitraka** [comment]
> @dimitraka inspect is still complaining about the css file not being linked from anywhere (`https://output.circle-artifacts.com/output/job/750a6397-657c-4f87-a08d-d6f7fde995ca/artifacts/0/hpx_inspect_report.html`). We can suppress this by adding an empty file named `hpx-no-inspect` to the directory `docs/sphinx/_static/`. This will cause inspect not to look at files in that directory.
> 
> Otherwise, the change seems to work as expected (e.g.: https://output.circle-artifacts.com/output/job/6e751fe9-2294-45a9-b334-990b25019898/artifacts/0/hpx/build/share/hpx/docs/html/examples/fibonacci_local.html#setup). Great, thanks!

I fixed that by adding a proper comment to the `custom.css` file. Now, `inspect` is happy again.

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by hkaiser** [comment]
bors merge

**Pull request merged**
