### PR TITLE
Replace spirit.qi with x3

### PR DESCRIPTION
**Pull request by K-ballo**

### CODE REVIEW

**Review by hkaiser — APPROVED** [review]
Wow! Many thanks!

**Comment by K-ballo** [comment]
This is tripping over an unfortunate regression in Boost 1.70 (https://github.com/boostorg/spirit/issues/511)

**Comment by K-ballo** [comment]
There doesn't appear to be a workaround for the 1.70 regression that doesn't involve duplicating the entire grammar. We may have to defer adopting X3 until we no longer support 1.70, or we could migrate only the other parsers not affected by the bug.

**Comment by hkaiser** [comment]
> There doesn't appear to be a workaround for the 1.70 regression that doesn't involve duplicating the entire grammar. We may have to defer adopting X3 until we no longer support 1.70, or we could migrate only the other parsers not affected by the bug.

Could we duplicate the grammar for V1.70 only?

**Comment by K-ballo** [comment]
> Could we duplicate the grammar for V1.70 only?

That would require three grammar definitions, a normal one and 2 specific for 1.70.0

**Comment by msimberg** [comment]
@K-ballo is this unrelated to the issues you mention above: https://cdash.cscs.ch/viewBuildError.php?buildid=139019? That's with Boost 1.65.0. Would it help if we bump the minimum version again?

**Comment by K-ballo** [comment]
> @K-ballo is this unrelated to the issues you mention above: https://cdash.cscs.ch/viewBuildError.php?buildid=139019?

That seems unrelated.

In order to move on with this I'll have to test again each of the 10 supported Boost versions.

**Comment by msimberg** [comment]
> > @K-ballo is this unrelated to the issues you mention above: https://cdash.cscs.ch/viewBuildError.php?buildid=139019?
> 
> That seems unrelated.
> 
> In order to move on with this I'll have to test again each of the 10 supported Boost versions.

Unless you feel like doing that manually we can wait for rostam to be back up. It'll test most, if not all, of the remaining Boost versions.

**Comment by msimberg** [comment]
> > > @K-ballo is this unrelated to the issues you mention above: https://cdash.cscs.ch/viewBuildError.php?buildid=139019?
> > 
> > 
> > That seems unrelated.
> > In order to move on with this I'll have to test again each of the 10 supported Boost versions.
> 
> Unless you feel like doing that manually we can wait for rostam to be back up. It'll test most, if not all, of the remaining Boost versions.

I suppose I wasn't thinking when I wrote that comment. That log *is* from rostam (from before it went down). In any case, that means that 1.65 is known broken from the CI. 1.69, 1.71, 1.72, 1.73, and 1.75 are ok on CI. That leaves 1.66, 1.67, 1.68, 1.70, and 1.74, currently untested. For 1.6.0 we can bump the minimum at least to 1.66 in any case. I'll do some updates to CI to test more of those missing versions. Feel free to wait for those to be in place before doing any changes.

**Comment by msimberg** [comment]
@K-ballo see #5100 for updated Boost versions. We still have to wait for some Boost versions to be installed on Rostam before that PR is useful for you.

**Comment by msimberg** [comment]
@K-ballo after updating the CI configurations it looks like https://cdash.cscs.ch/viewBuildError.php?buildid=141181 is indeed only a problem on Boost 1.66 (both GCC and clang).

**Comment by hkaiser** [comment]
retest lsu

**Comment by msimberg** [comment]
How do we feel about bumping the minimum Boost version to 1.71 in one go? It's a very big jump compared to what we've done before, but if it makes things easier for this PR it might be worth it.

**Comment by hkaiser** [comment]
> How do we feel about bumping the minimum Boost version to 1.71 in one go? It's a very big jump compared to what we've done before, but if it makes things easier for this PR it might be worth it.

Yes, I think supporting the five latest versions of Boost is more than sufficient.

**Comment by hkaiser** [comment]
retest

**Comment by hkaiser** [comment]
retest lsu

**Comment by msimberg** [comment]
Is this ready to go in terms of changes? The CI looks good (the two missing builds are ok on CDash).

**Comment by hkaiser** [comment]
> Is this ready to go in terms of changes? The CI looks good (the two missing builds are ok on CDash).

Yes, this is ready to go.

**Comment by msimberg** [comment]
> Yes, this is ready to go.

Thank you @K-ballo and @hkaiser for making the changes!

**Pull request merged**
