### PR TITLE
Fixing compilation issues with external example

### LINKED ISSUE #2011: Compilation error while running sample hello_world_component code
Multiple compilation errors while running the code for example in the documentation. (http://stellar-group.github.io/hpx/docs/html/hpx/manual/build_system/using_hpx/pkgconfig.html)
Code located at hpx/examples/hello_world_component.

### PR DESCRIPTION
**Pull request by hkaiser**
- also: fix documentation (remove stubs, remove mentioning of ini files)
- this fixes #2011 and #2009

### CODE REVIEW

**Comment by hkaiser** [comment]
@satyaki3794: Could you please verify whether this fixes your problem?

**Comment by satyaki3794** [comment]
The directory hpx/examples/hello_world_component has hello.sh which contains the commands needed to build and run this example. I am not sure about this but I think some of the commands in that file are wrong (some typos). Compilation fails at the first step, while generating the .so file, which can be fixed by adding the -fPIC flag.

After that has been fixed, when I run ./hello.sh, I get the following compilation errors. http://pastebin.com/crgQsFwy.


Maybe, like this issue (https://github.com/STEllAR-GROUP/hpx/issues/2009), the pkgconfig order in the .pc file is incorrect here too. I tried permuting the order of binaries like zao had done in the above case but to no avail.

**Comment by hkaiser** [comment]
> Compilation fails at the first step, while generating the .so file, which can be fixed by adding the -fPIC flag.

I now added the -fPIC to the pkgcfg options. I also tried to compile it again, seems to work now.

**Comment by satyaki3794** [comment]
I built the 'fixing_2011' branch and ran hello.sh in hpx/examples/hello_world_component. I got the same compilations yet again (http://pastebin.com/C5HeFxtB). As the errors were regarding undefined references (to hpx::cout, write_async() etc.). I searched online and found a similar issue (https://github.com/STEllAR-GROUP/hpx/issues/268).


The c++ command to run hello_world_client.cpp after generating the .so file, has the -lhpx_iostreams flag, and my LD_LIBRARY_PATH environment variable points to $HPX_INSTALL_LOCATION/lib. I am on Ubuntu 14.04 with gcc 4.8.2.
I tried moving around the -lhpx_iostreams flag in the command but wasn't aboe to resolve it.

**Comment by hkaiser** [comment]
@satyaki3794 I changed the pkgcfg files such that the HPX libraries are referenced by full file name. As outlined in #2009, this should at least fix that first issue you reported. I'm still not clear why you see those hpx::cout et.al. as missing symbols. They should be defined in `libhpx_iostreams.so` (could you verify whether they are defined there?).

**Comment by satyaki3794** [comment]
Please move the -lhpx_iostreams flag to the end of the command while compiling hello_world_client.cpp. It resolves the compilation errors.

**Comment by satyaki3794** [comment]
I built and tested the changes. Everything is working as expected.

**Pull request merged**
