### PR TITLE
Scalable barrier

### PR DESCRIPTION
**Pull request by hkaiser**
The barrier was implemented using a K-ary tree approach with the algorithm
as presented here: http://www.cs.fsu.edu/~asriniva/papers/HiPC15.pdf

The arity is configurable through hpx.lcos.collectives.arity and the cut off when
to switch to the tree based algorithm is hpx.lcos.collectives.cut_off.

### CODE REVIEW

**Comment by hkaiser** [comment]
The config settings need to be added to the docs, still.

**Comment by sithhell** [comment]
Can anyone review this please?

**Comment by hkaiser** [comment]
It was not clear to me that the changed boundaries would fix the issue. I think there should be some code checking pre-conditions if the barrier breaks with boundaries set too low.

**Comment by sithhell** [comment]
What do you mean? Which boundaries? The code is fine, the arity and cut off were chosen experimentally to get the best performance. Every value here should work

**Comment by hkaiser** [comment]
Sure. I trust the values used as a default now are fine. What I meant was that those values could be changed by the user and as we have seen, providing bad values not only could slow down the execution (I wouldn't care about this case, the user is not supposed to play with those values), but could break the barrier altogether (as the failing test has shown). So what I'd suggest is to add tests verifying that the selected values don't break the barrier functionally.

**Comment by sithhell** [comment]
On Mittwoch, 5. Oktober 2016 11:25:33 CEST Hartmut Kaiser wrote:
> Sure. I trust the values used as a default now are fine. What I meant was
> that those values could be changed by the user and as we have seen,
> providing bad values not only could slow down the execution (I wouldn't
> care about this case, the user is not supposed to play with those values),
> but could break the barrier altogether (as the failing test has shown). So
> what I'd suggest is to add tests verifying that the selected values don't
> break the barrier functionally.

The failing test was due to a bug in the algorithm which has been fixed.
The values have been determined only after the algorithm was fixed and the unit 
test ran successfully. Did you encounter problems when testing this branch?

**Comment by hkaiser** [comment]
> The failing test was due to a bug in the algorithm which has been fixed. The values have been determined only after the algorithm was fixed and the unit test ran successfully. Did you encounter problems when testing this branch?

Ok. This was a misunderstanding on my end, then. 

LGTM, please go ahead and merge it (after resolving the conflicts, that is).

**Comment by sithhell** [comment]
The remaining problem has been fixed.

**Pull request merged**
