### PR TITLE
Fixing SLURM environment parsing

### PR DESCRIPTION
**Pull request by sithhell**
This patch fixes parsing of the slurm environment in the presence of running
different SLURM steps with different number of tasks and nodes.

### CODE REVIEW

**Comment by hkaiser** [comment]
IIUC, there are situations where the `SLURM_STEP_...` are not set (depending whether `salloc` or `srun` have been used, possibly other criteria..., see [here](https://groups.google.com/forum/#!topic/slurm-devel/3tLPgShGM9A)). I think we should always check the `SLURM_...` env variables if the `SLURM_STEP_...` variable is not set.

**Comment by sithhell** [comment]
Am 11.09.2017 5:28 nachm. schrieb "Hartmut Kaiser" <notifications@github.com
>:

IIUC, there are situations where the SLURM_STEP_... are not set (depending
whether salloc or srun have been used, possibly other criteria..., see here
<https://groups.google.com/forum/#!topic/slurm-devel/3tLPgShGM9A>). I think
we should always check the SLURM_... env variables if the SLURM_STEP_...
variable is not set.


On the slurm installations I checked, they are both set. The post you
linked to concerns the `SLURM_JOB` variables, which seem to be the same as
the ones without `_JOB`.

http://rostam.cct.lsu.edu/builders/hpx_gcc_7_boost_1_65_centos_x86_64_debug/builds/19
Shows that the assertion which was a symptom of the bug seems to be gone.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/STEllAR-GROUP/hpx/pull/2895#issuecomment-328565680>,
or mute
the thread

**Comment by hkaiser** [comment]
> IIUC, there are situations where the SLURM_STEP_... are not set (depending whether salloc 
> or srun have been used, possibly other criteria..., see here). I think we should always check 
> the SLURM_... env variables if the SLURM_STEP_... variable is not set.

On the slurm installations I checked, they are both set. The post you
linked to concerns the `SLURM_JOB` variables, which seem to be the same as
the ones without `_JOB`.

The link is related to the `_JOB_` variables, yes - but if you read it you'll see that for the same job the `_STEP_` variables are not always present depending on the way things are run. 

Would it be a problem to play it safe and to allow for a fallback in case the `_STEP_` variables are not present?

> http://rostam.cct.lsu.edu/builders/hpx_gcc_7_boost_1_65_centos_x86_64_debug/builds/19 
> Shows that the assertion which was a symptom of the bug seems to be gone.

I don't doubt that for our setup things work now. Other environments may still break.

**Comment by sithhell** [comment]
No, shouldn't be a problem to add it as fallback to be on the safe side.

**Comment by sithhell** [comment]
Am 11.09.2017 6:49 nachm. schrieb "Thomas Heller" <thom.heller@gmail.com>:

No, shouldn't be a problem to add it as fallback to be on the safe side.


Reading through the post again I think what we have now is correct. The
occasions where there is no `_STEP_` variable set is when you have an
allocation, but not actually started the actual parallel application. I
think what's missing is the detection of that case and a proper diagnostic
and single locality fallback.

**Comment by sithhell** [comment]
I just checked the SLURM environments I have access to again. Having the fallback as you suggested would lead to similar failures. The PR is correct as is.

**Pull request merged**
