### PR TITLE
Replace PMR based version of small_vector

### PR DESCRIPTION
**Pull request by hkaiser**
- this significantly improves its performance

This is a follow-up to #5769

### CODE REVIEW

**Comment by msimberg** [comment]
@hkaiser I pushed the updated references for two of the tests. Unsure if the stream reference also needs updating (it was slower on the second run until now), so leaving that out for now. Let me know if the new references are no good.

**Comment by hkaiser** [comment]
retest cscs

**Comment by hkaiser** [comment]
The HIP and CUDA failures are caused by configuration problems on rostam and will be fixed separately.

**Comment by hkaiser** [comment]
bors merge

**Pull request merged**
