### PR TITLE
Update performance test references for Piz Daint

### PR DESCRIPTION
**Pull request by msimberg**
I picked a set of runs where it looked like there was a consistent performance increase, but this should be run a few times to see how many false positives it triggers.

### CODE REVIEW

**Comment by hkaiser** [comment]
Thanks Mikael, much appreciated!

**Comment by msimberg** [comment]
Updated the `future_overhead` and `stream` references again.

**Comment by msimberg** [comment]
launch perftests

**Comment by msimberg** [comment]
launch perftests

**Comment by msimberg** [comment]
launch perftests

**Comment by msimberg** [comment]
@hkaiser I think the latest update seems to be quite a good reference.

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by hkaiser** [comment]
bors merge

**Pull request merged**
