### PR TITLE
Adapting thread_queue_mc to behave even if no 128bit atomics are available

### PR DESCRIPTION
**Pull request by hkaiser**
@biddisco please verify that this does not break anything on your end.

### CODE REVIEW

**Comment by biddisco** [comment]
remove the template defaults will not break anything

**Comment by hkaiser** [comment]
> removing the template defaults will not break anything

Thanks @biddisco! I was more worried about (arbitrarily) choosing `PendingQueuing` as the third template argument for the `thread_queue_mc` here: https://github.com/STEllAR-GROUP/hpx/pull/4083/files#diff-6cd28becc08171d26d3f09c07c085302R73. Is that what you had in mind?

**Comment by biddisco** [comment]
I wouldn't worry too much. the latest changes (incoming) to thread_queue_mc have substantially hanged the class and I'll absorb any of your changes into it when I do my PR

**Comment by hkaiser** [comment]
@rtohid: this should fix your issues you're having with building FLeCSI.

**Pull request merged**
