### PR TITLE
Fix attribute warning for gcc

### PR DESCRIPTION
**Pull request by hkaiser**
- flyby: remove IB-Verbs and IPC from HPXConfig.cmake.in

### CODE REVIEW

**Comment by hkaiser** [comment]
This addresses a comment we received for #2109.

**Comment by sithhell** [comment]
This only fixes warnings for `thread` there are still a lot of others lingering around.

**Comment by hkaiser** [comment]
@sithhell Fixing it for `thread` was the purpose of this PR. What's wrong with it?

**Comment by sithhell** [comment]
On Dienstag, 20. Dezember 2016 02:34:34 CET Hartmut Kaiser wrote:
> @sithhell Fixing it for `thread` was the purpose of this PR. What's wrong
> with it?

I was under the assumption that the intention was to fix all the attribute 
warnings reported in the original issue.

**Comment by hkaiser** [comment]
@sithhell Give me a list of warnings and I can try doing this. My compiler does not report those.

**Comment by sithhell** [comment]
@hkaiser sorry, I misread the issue. I was seeing several warnings like these when using ICC, didn't realize the linked issue was closed some time ago. Indeed, the new comment only mentions threads.

**Comment by hkaiser** [comment]
@sithhell Could you review this PR, please?

**Pull request merged**
