### PR TITLE
Moving traits files to actions_base

### PR DESCRIPTION
**Pull request by hkaiser**
- flyby: moving a traits file to algorithms

### CODE REVIEW

**Comment by hkaiser** [comment]
This is a next (small) step in taking apart the actions/components/agas hairball. @msimberg I think this is ready to go now.

**Comment by hkaiser** [comment]
@msimberg this looks like to be good to go, please review.

**Review by msimberg — COMMENTED** [review]
Thanks @hkaiser, this looks good to me. Sorry about the conflicts. They should only be a result of the device code guards. You may need to add guards to the newly added files.

**Review by aurianer — APPROVED** [review]
LGTM, sorry for all the conflicts :grimacing:
You might have to add the following guard in some of the new files you added, but hipcc jenkins CI should complain about this anyway
```
#include <hpx/config.hpp>
#if defined(HPX_COMPUTE_DEVICE_CODE)
...
#endif
```

**Comment by hkaiser** [comment]
@aurianer I think I have resolved all the conflicts and this is good to go.

**Comment by msimberg** [comment]
@hkaiser this still remains: https://cdash.cscs.ch/viewBuildError.php?buildid=134514. That particular builder has networking off (but distributed runtime on), so it's most likely related to that. There are also suspiciously many test failures, but those look like they might be unrelated to the actual changes here. I'll restart the builds to see if they remain.

**Comment by msimberg** [comment]
retest lsu

**Comment by msimberg** [comment]
retest lsu

**Comment by msimberg** [comment]
retest lsu

**Comment by msimberg** [comment]
This still seems to be a problem: https://cdash.cscs.ch/viewBuildError.php?buildid=139882. However, that's with clang 6.0.1. clang 7 looks ok (though the result is not reported here). If it makes life easier I'd be ok with dropping support for clang 6.

**Comment by hkaiser** [comment]
> This still seems to be a problem: https://cdash.cscs.ch/viewBuildError.php?buildid=139882. However, that's with clang 6.0.1. clang 7 looks ok (though the result is not reported here). If it makes life easier I'd be ok with dropping support for clang 6.

I'm still planning to work on this and I hope to still be able to get it done before the release.

**Comment by hkaiser** [comment]
retest lsu

**Comment by hkaiser** [comment]
> > This still seems to be a problem: https://cdash.cscs.ch/viewBuildError.php?buildid=139882. However, that's with clang 6.0.1. clang 7 looks ok (though the result is not reported here). If it makes life easier I'd be ok with dropping support for clang 6.
> 
> I'm still planning to work on this and I hope to still be able to get it done before the release.

Let's go ahead with ditching clang 6. I have no idea what's wrong here :/

**Comment by hkaiser** [comment]
@msimberg once the tests have cycled this is good to go, I believe.

**Comment by msimberg** [comment]
> @msimberg once the tests have cycled this is good to go, I believe. I'm not sure what the HIP issue is about: https://cdash.cscs.ch/viewBuildError.php?buildid=142738, any ideas?

Unrelated, but also no ideas. It might be linking to the wrong standard library or just mismatched boost build types. I've been ignoring that error as long as we don't know what's wrong otherwise on the AMD nodes...

**Pull request merged**
