### PR TITLE
Relax constraints on `execution::when_all`

### PR DESCRIPTION
**Pull request by msimberg**
## Proposed Changes

Previously `execution::when_all` required all predecessors to send exactly one variant with exactly one type. This relaxes it to allow exactly one variant with any number of types (including zero). This brings it in line with P2300 and makes it much closer to `dataflow` (and much more useful).

## Checklist

Not all points below apply to all pull requests.

- [x] I have added a new feature and have added tests to go along with it.
- [ ] I have fixed a bug and have added a regression test.
- [ ] I have added a test using random numbers; I have made sure it uses a seed, and that random numbers generated are valid inputs for the tests.

### CODE REVIEW

**Review by hkaiser — DISMISSED** [review]
LGTM, thanks!

**Comment by msimberg** [comment]
I had to add a workaround for clang. And in the process I introduced a new bug. This time this should actually be ready, but let's see if I've messed up something else.

**Comment by msimberg** [comment]
bors merge

**Comment by msimberg** [comment]
bors merge

**Pull request merged**
