### PR TITLE
Fixing compilation if HPX_WITH_THREAD_BACKTRACE_ON_SUSPENSION=On

### LINKED ISSUE #4555: HPX_HAVE_THREAD_BACKTRACE_ON_SUSPENSION compilation error
Build fails when using `cmake -DHPX_HAVE_THREAD_BACKTRACE_ON_SUSPENSION=ON`. 

I am working on a fix. I enabled it to diagnose dashboard test errors with the lock held when suspending exception.

### PR DESCRIPTION
**Pull request by hkaiser**
Fixes #4555

### CODE REVIEW

**Comment by msimberg** [comment]
> The works fine thanks.
> 
> I added locally in my code an automatic dump of suspended thread stacktraces when register_locks decides to throw a lock held exception. This makes it slightly easier (but not much) to begin the debugging of this kind of problem.
> 
> To make it compile, I have to add
> 
> ```
>     hpx_coroutines
>     hpx_threading_base
> ```
> 
> to the dependencies of basic_execution
> 
> I'm not sure of the state of circular dependencies etc. Would these be reasonable additions or are they a problem? Just curious - I'm happy with this PR as is.

That would currently not work. In similar situations we've added callbacks/handlers that can be registered for this kind of functionality.

**Comment by biddisco** [comment]
Looks like a problem has cropped up here - I tested with backtraces enabled, but when I compile master after this merge with them disabled - I get 
```
In file included from libs/debugging/include/hpx/debugging.hpp:17,
                 from /home/biddisco/src/hpx/libs/serialization/include/hpx/serialization/detail/polymorphic_intrusive_factory.hpp:13,
                 from /home/biddisco/src/hpx/libs/functional/include/hpx/functional/serialization/detail/vtable/serializable_function_vtable.hpp:17,
                 from /home/biddisco/src/hpx/libs/functional/include/hpx/functional/serialization/detail/serializable_basic_function.hpp:18,
                 from /home/biddisco/src/hpx/libs/functional/include/hpx/functional/serialization/serializable_function.hpp:14,
                 from libs/functional/include/hpx/functional.hpp:29,
                 from /home/biddisco/src/hpx/libs/runtime_configuration/include/hpx/runtime_configuration/ini.hpp:14,
                 from /home/biddisco/src/hpx/libs/command_line_handling/include/hpx/command_line_handling/parse_command_line.hpp:11,
                 from /home/biddisco/src/hpx/libs/command_line_handling/src/parse_command_line.cpp:7:
/home/biddisco/src/hpx/libs/debugging/include/hpx/debugging/backtrace/backtrace.hpp:32:11: error: redefinition of ‘class hpx::util::backtrace’
   32 |     class backtrace
      |           ^~~~~~~~~
```

**Comment by hkaiser** [comment]
@biddisco Hmm. The master branch compiles for me regardless whether `HPX_WITH_THREAD_BACKTRACE_ON_SUSPENSION` is on or off. CircleCI seems to be happy with current master as well...

Could I see the full error message for this, please?

**Comment by biddisco** [comment]
Looks like a cache proble. Closed it again. Sorry for time wasting

**Pull request merged**
