### PR TITLE
Update ICC module name on Piz Daint Jenkins configuration

### PR DESCRIPTION
**Pull request by msimberg**

### CODE REVIEW

**Comment by msimberg** [comment]
So the icc builds on Piz Daint were based on a lie... Which is hopefully fixed now. The intel module was unloaded because of later modules, meaning the builds were done with gcc. Now the build actually uses icc. @NK-Nikunj I've had to disable some resiliency examples because of what seems to be a dumb icc (and they're disabled only with icc). Just letting you know in case you ever bump into someone asking about using the resiliency stuff with icc.

**Comment by NK-Nikunj** [comment]
@msimberg really curious what's breaking them on icc? Thanks for the heads up btw.

**Comment by msimberg** [comment]
> @msimberg really curious what's breaking them on icc? Thanks for the heads up btw.

It claims there are no matching overloads of `std::forward` for the function pointers passed to `dataflow_replay/validate`. I did not look further into if it's fixable, but I'm pretty sure it's icc that is wrong, and not the other compilers. It could also be that it's fixed in newer iccs. This was with 19.1.

**Comment by NK-Nikunj** [comment]
I see. Yeah, there's nothing much we can do about it there.

**Comment by msimberg** [comment]
retest cscs

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by msimberg** [comment]
The ICC configuration now successfully runs with `HPX_WITH_NETWORKING=OFF`. It's not perfect, but better than before. Any comments on this?

**Pull request merged**
