### PR TITLE
Module cache

### PR DESCRIPTION
**Pull request by aurianer**
Add `cache` module. Depends on #3832 config module.

### CODE REVIEW

**Comment by hkaiser** [comment]
@aurianer is this ready now?

**Comment by aurianer** [comment]
As far as I concerned yes, but I'm not sure as some picycle tests failed due to socket timeout, what do you think ?

**Comment by hkaiser** [comment]
@aurianer the pycicle problems seem to be unrelated, however @msimberg might know better.

**Comment by aurianer** [comment]
Thanks !

**Pull request merged**
