### PR TITLE
Assorted fixes for CUDA

### PR DESCRIPTION
**Pull request by gentryx**
Fixes #2911

### CODE REVIEW

**Comment by hkaiser** [comment]
Why is adding an `else` case solving a compiler warning? I don't get that.

**Comment by gentryx** [comment]
NVCC was complaining that the trailing return statements were unreachable. I guess this is because nvcc is a little over zealous for analyzing const expressions? I agree that it doesn't make much sense, it doesn't hurt either, though.

**Comment by gentryx** [comment]
Huh, any idea why CircleCI would fail? This particular issue (docker login failing) doesn't seem to be related to my change.

**Comment by hkaiser** [comment]
@gentryx it decided to run on your circleci account (no idea why), so it can't access our (CI) environment variables (like the docker credentials).

**Comment by msimberg** [comment]
I don't mind merging this, but it does undo some clang-tidy warnings that were fixed in #3154, which will come back next time someone decides to run clang-tidy. Being able to successfully compile is more important than being clang-tidy though.

What version of NVCC were you using? How much of HPX did you try to compile?

**Comment by gentryx** [comment]
Necessary for compilation is only the change to hpx/runtime/components/server/managed_component_base.hpp.

The other changes are just to make nvcc compile without issuing tons of warnings. So, I should be good if someone ran clang-tidy in the future. :-)

**Comment by gentryx** [comment]
I'm using CUDA 9.1.85, I was compiling from HPX only what's required by LibGeoDecomp. Not sure which parts that are exactly.

**Comment by gentryx** [comment]
PTAL

**Comment by hkaiser** [comment]
@gentry: @msimberg is the master of ceremonies for the upcoming release - he will decide whether this should go in or not.

**Comment by msimberg** [comment]
Thanks! Will add this to the release.

**Comment by gentryx** [comment]
Thanks! :-)

**Pull request merged**
