### PR TITLE
add a *destroy* trait for ParcelPort plugins

### LINKED ISSUE #4988: MPI is not finalized if running with only one locality
## Expected Behavior

MPI_Finalize() needs to be invoked if an HPX application using the MPI Parcelport is terminated, even if only one locality is being run.

## Actual Behavior

With one locality no MPI Parcelport will be instantiated, however, MPI_Init is still called (from the factory, I guess).

## Steps to Reproduce the Problem

  1. configure HPX with MPI support. e.g. ```cmake -DCMAKE_INSTALL_PREFIX=/home/gentryx/local_install/ -DCMAKE_CXX_COMPILER=g++-9.3.0  -DHPX_WITH_PARCELPORT_MPI=true -DHPX_WITH_PARCELPORT_TCP=true -DHPX_WITH_CXX14=true -DCMAKE_BUILD_TYPE=Release  -DHPX_WITH_TESTS_HEADERS=true -DHPX_WITH_BOOST_MPI=true```
  1. ```make 1d_stencil_8```
  1. ```mpirun -np 1 bin/1d_stencil_8 --hpx:bind=balanced --hpx:threads=1  -Ihpx.parcel.tcp.enable=0  -Ihpx.parcel.mpi.enable=1```

## Specifications

... Please describe your environment

  - HPX Version: HPX head (rev 18a2c734b4e87a0522571bfb17b2b8e3d42ef672)
  - Platform (compiler, OS): GCC 9.3.0 on Linux (Gentoo)

### PR DESCRIPTION
**Pull request by gentryx**
...so that MPI_Finalize() will always be called exactly once

Fixes #4988

### CODE REVIEW

**Comment by gentryx** [comment]
The 2 failing tests seem unrelated (build-and-test is failing for formatting errors which did not occur in the files I touched and jenkins/cscs/gcc-newest doesn't even show an error message IIUC).

**Comment by gentryx** [comment]
Are these known issues?

**Comment by hkaiser** [comment]
@the clang-format complaint looks like to be your issue, the failing test is a known problem you can ignore.

**Comment by gentryx** [comment]
Hey Hartmut! Alright, I just ran clang-format. I'm puzzled though because the diff it created is not correlated with the files I changed before. Anyway, hope this fixes it.

**Comment by hkaiser** [comment]
> Hey Hartmut! Alright, I just ran clang-format. I'm puzzled though because the diff it created is not correlated with the files I changed before. Anyway, hope this fixes it.

The files changed by that commit are not related to any of the changes. Could you please run clang-format on the file mpi_environment.cpp only (the one clang-format complains about)?

**Comment by gentryx** [comment]
Ugh, I was under the illusion that I had run clang-format for the whole source tree. Which I didn't. :-D Thanks for the hint!

**Comment by biddisco** [comment]
in case it helps for future reference, I tend to use
```git diff --name-only | grep -E ".hpp|.cpp" | xargs -n 1 clang-format -i```
or install the git commit hook in the hpx repo at ```tools/pre-commit``` (instructions inside the hook script)

**Review by hkaiser — DISMISSED** [review]
Except for the formatting only changes, this LGTM. Thanks!

**Comment by gentryx** [comment]
Never mind, found more files and re-ran clang-format. Tests are running.

**Review by hkaiser — DISMISSED** [review]
LGTM, thanks!

**Comment by hkaiser** [comment]
@gentryx not sure where this came from, but now inspect is complaining about lines being too long: https://223857-4455628-gh.circle-artifacts.com/0/hpx_inspect_report.html. Could you have a look, please?

**Comment by gentryx** [comment]
> @gentryx not sure where this came from, but now inspect is complaining about lines being too long: https://223857-4455628-gh.circle-artifacts.com/0/hpx_inspect_report.html. Could you have a look, please?

Huh, now we're running in circles :-P That came from running clang-format. So if I revert the change we'll have that format test failing again.

**Comment by hkaiser** [comment]
> Huh, now we're running in circles :-P That came from running clang-format. So if I revert the change we'll have that format test failing again.

@gentryx Generally, we have not applied clang-format consistently at this point (it's an ongoing process that we have aligned with our modularization effort). We currently require only for files in the `libs` subdirectory to be formatted. That explains why applying clang-format to the files outside of that directory caused issues. For now, please do not format any files outside of `libs`. Sorry for this, we should have mentioned it explicitly earlier.

**Comment by hkaiser** [comment]
> > Huh, now we're running in circles :-P That came from running clang-format. So if I revert the change we'll have that format test failing again.
> 
> @gentryx Generally, we have not applied clang-format consistently at this point (it's an ongoing process that we have aligned with our modularization effort). We currently require only for files in the `libs` subdirectory to be formatted. That explains why applying clang-format to the files outside of that directory caused issues. For now, please do not format any files outside of `libs`. Sorry for this, we should have mentioned it explicitly earlier.

@gentryx I missed telling you about this so I will fix things here to avoid you having to invest even more time.

**Comment by hkaiser** [comment]
@gentryx I have merged master into your branch and subsequently removed all unnecessary formatting changes from this patch to reduce the changes to a minimum. I hope you don't mind. Please feel free to remove my changes altogether.

**Comment by gentryx** [comment]
Hey Hartmut, thanks a ton! Anything left for me to do here?

**Comment by hkaiser** [comment]
> Hey Hartmut, thanks a ton! Anything left for me to do here?

Let's wait for the tests to cycle. That should be it.

**Comment by gentryx** [comment]
Thanks Hartmut! I'll do a better job WRT formatting next time!

**Pull request merged**
