### PR TITLE
Add is_invocable typedefs to top-level hpx namespace and public API list

### PR DESCRIPTION
**Pull request by msimberg**

### CODE REVIEW

**Review by hkaiser — COMMENTED** [review]
Shouldn't we do this the other way around, i.e. move the implementation into `namespace hpx` and add a (deprecated) using statement into `namespace hpx::traits`?

**Comment by msimberg** [comment]
> Shouldn't we do this the other way around, i.e. move the implementation into `namespace hpx` and add a (deprecated) using statement into `namespace hpx::traits`?

Yeah, I was being lazy... I'll update this to do that instead.

**Comment by msimberg** [comment]
This should now be ready to go.

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Review by aurianer — APPROVED** [review]
LGTM thanks!

**Pull request merged**
