### PR TITLE
Actions with ids cleanup

### PR DESCRIPTION
**Pull request by hkaiser**
This patch supersedes #1482: Actions with integer type ids. It implements identifying actions using unique integer ids instead of unique strings. This improves the performance of the serialization layer and decreases the size of the generated data streams.

### CODE REVIEW

**Comment by sithhell** [comment]
Do we have performance numbers? How does this solution scale?
Am 10.06.2015 8:53 nachm. schrieb "Hartmut Kaiser" <notifications@github.com

**Comment by hkaiser** [comment]
We don't have any performance numbers at this point. The statement that it this patch improves performance is purely based on common sense - but surprises are possible :/

**Comment by sithhell** [comment]
Running the serialization overhead benchmark or the osu_latency test should at least give us some ideas there. Measuring the startup time with a different number of localities too.

**Comment by sithhell** [comment]
I think this solution won't scale. All worker nodes send all their non-constant typenames to the root locality. Those typenames will be almost identical on all localities, this creates an overhead at startup. Having the root broadcasting it's registered typenames would help here. The workers would then be left to only register a small subset of still unregistered typenames (which will only happen when some have loaded different plugins than the root).

**Comment by hkaiser** [comment]
> All worker nodes send all their non-constant typenames to the root locality. Those typenames will be almost identical on all localities, this creates an overhead at startup. Having the root broadcasting it's registered typenames would help here. The workers would then be left to only register a small subset of still unregistered typenames (which will only happen when some have loaded different plugins than the root).

That's exactly what's implemented. All known HPX actions have predefined ids and only the names of actions without a predefined id will be communicated with the root locality. Also, the user can use his/her own predefined ids for application based actions. I don't see how broadcasting the ids for actions available on all localities from the root would improve the picture.

Also, at startup we already have a sequential communication from all localities with the root going on (and I don't see any other way of doing bootstrap at the moment), so additionally sending along those non-predefined action names will barely make a difference.

**Comment by sithhell** [comment]
Am 11.06.2015 12:35 vorm. schrieb "Hartmut Kaiser" <notifications@github.com
>:
>>
>> All worker nodes send all their non-constant typenames to the root
locality. Those typenames will be almost identical on all localities, this
creates an overhead at startup. Having the root broadcasting it's
registered typenames would help here. The workers would then be left to
only register a small subset of still unregistered typenames (which will
only happen when some have loaded different plugins than the root).
>
> That's exactly what's implemented. All known HPX actions have predefined
ids and only the names of actions without a predefined id will be
communicated with the root locality. Also, the user can use his/her own
predefined ids for application based actions. I don't see how broadcasting
the ids for actions available on all localities from the root would improve
the picture.

The difference is sending N bytes M times versus sending N bytes log(M)
times.

>
> Also, at startup we already have a sequential communication from all
localities with the root going on (and I don't see any other way of doing
bootstrap at the moment), so additionally sending along those
non-predefined action names will barely make a difference.

I'll do some testing to see how much this really effects us.

**Comment by hkaiser** [comment]
The last commit adds predefined ids for all `base_lco` and `base_lco_with_value` get and set actions. This reduces the number of communicated typenames for hello_world to five (2 from hello_world itself and 3 template actions which can't be assigned predefined ids). At the same time, 85 of the actions have predefined ids.

**Comment by hkaiser** [comment]
The last commit adds predefined ids for all  base_lco  and  base_lco_with_value  get and set actions. This reduces the number of communicated typenames for hello_world to five (2 from hello_world itself and 3 template actions which can't be assigned predefined ids). At the same time, 85 of the actions have predefined ids. This increases the parcel size for the first parcel to the root locality by about 150 bytes per locality (if compared to not sending those names), that's an increase of about 20%.

Changing the scheme to broadcasting the undefined typename/id mappings from the root to all localities would transmit less data (as you said), but it would do this by way of an additional networking operation (in addition the initial bootstrapping ping-pong).

**Comment by AntonBikineev** [comment]
@sithell when doing testing please make action name longer to avoid short string optimization

**Comment by hkaiser** [comment]
@sithhell have you had a chance to do the measurements? We should really go ahead and get these changes into master.

**Comment by sithhell** [comment]
Am 14.06.2015 5:46 nachm. schrieb "Hartmut Kaiser" <notifications@github.com
>:
>
> @sithhell have you had a chance to do the measurements? We should really
go ahead and get these changes into master.

I wasn't able to do those measurements yet and won't have time until next
week. I wouldn't like to these those optimizations in master without having
confirmation that those are really optimizations.

**Comment by sithhell** [comment]
After doing some measurements, I can see that the serialization of actions overall has been improved indeed. To my surprise, startup times haven't gotten worse! In fact, they got better as well, the trend so far shows that it even gets better the more nodes that are involved. I've run a simple application that does nothing but execute hpx_main and has two actions registered to up to 256 nodes so far (512 nodes is currently in the queue) as well as the serialization overhead benchmark. The data as well as graphs can be observed here:
https://goo.gl/TfpGBE

Nevertheless, the work here isn't done yet as it should be considered dangerous and unwanted that third party libraries or applications assign constant IDs to actions as there is no way to resolve conflicts there yet.

**Comment by hkaiser** [comment]
> Nevertheless, the work here isn't done yet as it should be considered dangerous and unwanted ...

I wouldn't classify this work as 'dangerous' and 'unwanted'. This patch massively improves the performance of our serialization layer, as such it is definitely 'wanted'. 

For the possible conflicts of ids I'd suggest to dynamically assign base-ids to all modules during bootstrap. This should allow to disambiguate things. I'd like to merge this now and open a ticket to remind us to resolve the possible id ambiguities (which may happen only if users start assigning ids to their actions - we don't have to advertise that at this point).

**Comment by sithhell** [comment]
>> Nevertheless, the work here isn't done yet as it should be considered dangerous and unwanted ...
> I wouldn't classify this work as 'dangerous' and 'unwanted'. This patch massively improves the performance of our serialization layer, as such it is definitely 'wanted'.

A little bit out of context. This comment was mainly meant for third party applications/libraries. The performance increase is out of question.

> For the possible conflicts of ids I'd suggest to dynamically assign base-ids to all modules during bootstrap. This should allow to disambiguate things.

Something like that sounds like a good idea, yes.

> I'd like to merge this now and open a ticket to remind us to resolve the possible id ambiguities (which may happen only if users start assigning ids to their actions - we don't have to advertise that at this point).

I absolutely agree. I just wanted to comment on the fact that it isn't ready for prime time yet, at least the constant ID assignment. Everything else looks solid and good.

**Pull request merged**
