### PR TITLE
Adding sync_wait_with_variant

### PR DESCRIPTION
**Pull request by hcq9102**
## Any background context you want to provide?
P2300R5: [sync_wait_with_variant](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2300r5.html#design-typed)
sync_wait_with_variant, which accepts any sender, but returns an optional whose value type is the variant of all the possible tuples sent by the input sender:
## Checklist

- [x] I have added a new feature and have added tests to go along with it.

### CODE REVIEW

**Review by hkaiser — CHANGES_REQUESTED** [review]
Very nice! Please add the new file here: https://github.com/STEllAR-GROUP/hpx/blob/master/libs/core/execution/CMakeLists.txt#L26, and add the new test to the build system (here: https://github.com/STEllAR-GROUP/hpx/blob/master/libs/core/execution/tests/unit/CMakeLists.txt#L19).

Also, now that you have a working version that duplicates 95% of the `sync_wait` code, would you see a way to combine the implementations of `sync_wait` and `sync_wait_with_variant` to reduce the amount of code repetition?

**Comment by hcq9102** [comment]
> Also, now that you have a working version that duplicates 95% of the `sync_wait` code, would you see a way to combine the implementations of `sync_wait` and `sync_wait_with_variant` to reduce the amount of code repetition?

Sure, will do.

**Comment by hkaiser** [comment]
@hcq9102 things should be fine now. Please note that I also have rebased this branch onto master.

**Comment by hkaiser** [comment]
This can be closed as it is subsumed by #6015

**Comment by hcq9102** [comment]
#6015 got merged. We don't need this one anymore.(sync_wait_with_variant integrating with sync_wait)

**Pull request closed without merging**
