### PR TITLE
Add more variations to future_overhead test

### PR DESCRIPTION
**Pull request by msimberg**
Adds a few more variations to the `future_overhead` test:
- Spawn tasks directly using `register_work` (overhead of executors)
- Spawn tasks directly on scheduler using `create_thread` (overhead of dispatching through applier, thread manager, thread pool)
- Spawn tasks hierarchically using `create_thread` with task placement (spawn one task per core which spawns all tasks for that core)
- Spawn tasks hierarchically using `apply` with task placement

Timings on Piz Daint (sorry about the ugly tables):
```
invoked 100000, futures      apply   limiting-Exec     default_executor in      0.071536 seconds        : 0.715361 us/future, queue  numa 0, threads 1, info none                                                              
invoked 100000, futures      apply   limiting-Exec    parallel_executor in      0.069927 seconds        : 0.699275 us/future, queue  numa 0, threads 1, info none                                                              
invoked 100000, futures     action        WaitEach          no-executor in      0.112674 seconds        : 1.126738 us/future, queue  numa 0, threads 1, info none                                                              
invoked 100000, futures     action         WaitAll          no-executor in      0.100595 seconds        : 1.005946 us/future, queue  numa 0, threads 1, info none                                                              
invoked 100000, futures      async        WaitEach     default_executor in      0.151116 seconds        : 1.511162 us/future, queue  numa 0, threads 1, info none                                                              
invoked 100000, futures      async        WaitEach    parallel_executor in      0.103295 seconds        : 1.032946 us/future, queue  numa 0, threads 1, info none                                                              
invoked 100000, futures      async         WaitAll     default_executor in      0.138836 seconds        : 1.388364 us/future, queue  numa 0, threads 1, info none                                                              
invoked 100000, futures      async         WaitAll    parallel_executor in      0.092037 seconds        : 0.920370 us/future, queue  numa 0, threads 1, info none                                                              
invoked 100000, futures      apply     ThreadCount     default_executor in      0.102927 seconds        : 1.029267 us/future, queue  numa 0, threads 1, info none                                                              
invoked 100000, futures      apply     ThreadCount    parallel_executor in      0.070489 seconds        : 0.704887 us/future, queue  numa 0, threads 1, info none                                                              
invoked 100000, futures      apply     Sliding-Sem     default_executor in      0.087901 seconds        : 0.879014 us/future, queue  numa 0, threads 1, info none                                                              
invoked 100000, futures      apply     Sliding-Sem    parallel_executor in      0.085327 seconds        : 0.853271 us/future, queue  numa 0, threads 1, info none                                                              
invoked 100000, futures register_work           latch                 none in   0.068932 seconds        : 0.689317 us/future, queue  numa 0, threads 1, info none                                                              
invoked 100000, futures create_thread           latch                 none in   0.064157 seconds        : 0.641567 us/future, queue  numa 0, threads 1, info none                                                              
invoked 100000, futures create_thread_hierarchical           latch                 none in      0.062903 seconds        : 0.629033 us/future, queue  numa 0, threads 1, info none                                              
invoked 100000, futures apply_hierarchical           latch     default_executor in      0.098540 seconds        : 0.985404 us/future, queue  numa 0, threads 1, info none
```

```
invoked 100000, futures      apply   limiting-Exec     default_executor in      0.045695 seconds        : 0.456949 us/future, queue  numa 0, threads 18, info none                                                             
invoked 100000, futures      apply   limiting-Exec    parallel_executor in      0.041699 seconds        : 0.416986 us/future, queue  numa 0, threads 18, info none                                                             
invoked 100000, futures     action        WaitEach          no-executor in      0.081346 seconds        : 0.813458 us/future, queue  numa 0, threads 18, info none                                                             
invoked 100000, futures     action         WaitAll          no-executor in      0.074717 seconds        : 0.747170 us/future, queue  numa 0, threads 18, info none                                                             
invoked 100000, futures      async        WaitEach     default_executor in      0.248704 seconds        : 2.487037 us/future, queue  numa 0, threads 18, info none                                                             
invoked 100000, futures      async        WaitEach    parallel_executor in      0.070782 seconds        : 0.707821 us/future, queue  numa 0, threads 18, info none                                                             
invoked 100000, futures      async         WaitAll     default_executor in      0.233087 seconds        : 2.330867 us/future, queue  numa 0, threads 18, info none                                                             
invoked 100000, futures      async         WaitAll    parallel_executor in      0.064412 seconds        : 0.644124 us/future, queue  numa 0, threads 18, info none                                                             
invoked 100000, futures      apply     ThreadCount     default_executor in      0.222897 seconds        : 2.228965 us/future, queue  numa 0, threads 18, info none                                                             
invoked 100000, futures      apply     ThreadCount    parallel_executor in      0.053388 seconds        : 0.533877 us/future, queue  numa 0, threads 18, info none                                                             
invoked 100000, futures      apply     Sliding-Sem     default_executor in      0.240655 seconds        : 2.406546 us/future, queue  numa 0, threads 18, info none                                                             
invoked 100000, futures      apply     Sliding-Sem    parallel_executor in      0.071160 seconds        : 0.711599 us/future, queue  numa 0, threads 18, info none                                                             
invoked 100000, futures register_work           latch                 none in   0.051454 seconds        : 0.514539 us/future, queue  numa 0, threads 18, info none                                                             
invoked 100000, futures create_thread           latch                 none in   0.046436 seconds        : 0.464356 us/future, queue  numa 0, threads 18, info none                                                             
invoked 100000, futures create_thread_hierarchical           latch                 none in      0.011537 seconds        : 0.115373 us/future, queue  numa 0, threads 18, info none                                             
invoked 100000, futures apply_hierarchical           latch     default_executor in      0.051020 seconds        : 0.510204 us/future, queue  numa 0, threads 18, info none
```

```
invoked 100000, futures      apply   limiting-Exec     default_executor in      0.098857 seconds        : 0.988569 us/future, queue  numa 0, threads 36, info none                                                             
invoked 100000, futures      apply   limiting-Exec    parallel_executor in      0.057570 seconds        : 0.575702 us/future, queue  numa 0, threads 36, info none                                                             
invoked 100000, futures     action        WaitEach          no-executor in      0.122239 seconds        : 1.222391 us/future, queue  numa 0, threads 36, info none                                                             
invoked 100000, futures     action         WaitAll          no-executor in      0.112463 seconds        : 1.124633 us/future, queue  numa 0, threads 36, info none                                                             
invoked 100000, futures      async        WaitEach     default_executor in      0.328070 seconds        : 3.280703 us/future, queue  numa 0, threads 36, info none                                                             
invoked 100000, futures      async        WaitEach    parallel_executor in      0.104692 seconds        : 1.046923 us/future, queue  numa 0, threads 36, info none                                                             
invoked 100000, futures      async         WaitAll     default_executor in      0.322980 seconds        : 3.229801 us/future, queue  numa 0, threads 36, info none                                                             
invoked 100000, futures      async         WaitAll    parallel_executor in      0.096391 seconds        : 0.963910 us/future, queue  numa 0, threads 36, info none                                                             
invoked 100000, futures      apply     ThreadCount     default_executor in      0.306251 seconds        : 3.062511 us/future, queue  numa 0, threads 36, info none                                                             
invoked 100000, futures      apply     ThreadCount    parallel_executor in      0.092758 seconds        : 0.927580 us/future, queue  numa 0, threads 36, info none                                                             
invoked 100000, futures      apply     Sliding-Sem     default_executor in      0.330664 seconds        : 3.306644 us/future, queue  numa 0, threads 36, info none                                                             
invoked 100000, futures      apply     Sliding-Sem    parallel_executor in      0.118773 seconds        : 1.187730 us/future, queue  numa 0, threads 36, info none                                                             
invoked 100000, futures register_work           latch                 none in   0.087652 seconds        : 0.876517 us/future, queue  numa 0, threads 36, info none                                                             
invoked 100000, futures create_thread           latch                 none in   0.079041 seconds        : 0.790408 us/future, queue  numa 0, threads 36, info none                                                             
invoked 100000, futures create_thread_hierarchical           latch                 none in      0.011673 seconds        : 0.116727 us/future, queue  numa 0, threads 36, info none                                             
invoked 100000, futures apply_hierarchical           latch     default_executor in      0.052060 seconds        : 0.520596 us/future, queue  numa 0, threads 36, info none
```

```
invoked 100000, futures      apply   limiting-Exec     default_executor in      0.044927 seconds        : 0.449273 us/future, queue  numa 0, threads 72, info none                                                             
invoked 100000, futures      apply   limiting-Exec    parallel_executor in      0.054969 seconds        : 0.549692 us/future, queue  numa 0, threads 72, info none                                                             
invoked 100000, futures     action        WaitEach          no-executor in      0.149016 seconds        : 1.490159 us/future, queue  numa 0, threads 72, info none                                                             
invoked 100000, futures     action         WaitAll          no-executor in      0.138322 seconds        : 1.383223 us/future, queue  numa 0, threads 72, info none                                                             
invoked 100000, futures      async        WaitEach     default_executor in      0.350506 seconds        : 3.505057 us/future, queue  numa 0, threads 72, info none                                                             
invoked 100000, futures      async        WaitEach    parallel_executor in      0.126604 seconds        : 1.266038 us/future, queue  numa 0, threads 72, info none                                                             
invoked 100000, futures      async         WaitAll     default_executor in      0.337756 seconds        : 3.377564 us/future, queue  numa 0, threads 72, info none                                                             
invoked 100000, futures      async         WaitAll    parallel_executor in      0.118260 seconds        : 1.182605 us/future, queue  numa 0, threads 72, info none                                                             
invoked 100000, futures      apply     ThreadCount     default_executor in      0.307390 seconds        : 3.073903 us/future, queue  numa 0, threads 72, info none                                                             
invoked 100000, futures      apply     ThreadCount    parallel_executor in      0.105353 seconds        : 1.053530 us/future, queue  numa 0, threads 72, info none                                                             
invoked 100000, futures      apply     Sliding-Sem     default_executor in      0.348388 seconds        : 3.483885 us/future, queue  numa 0, threads 72, info none                                                             
invoked 100000, futures      apply     Sliding-Sem    parallel_executor in      0.141513 seconds        : 1.415133 us/future, queue  numa 0, threads 72, info none                                                             
invoked 100000, futures register_work           latch                 none in   0.097532 seconds        : 0.975321 us/future, queue  numa 0, threads 72, info none                                                             
invoked 100000, futures create_thread           latch                 none in   0.089086 seconds        : 0.890856 us/future, queue  numa 0, threads 72, info none                                                             
invoked 100000, futures create_thread_hierarchical           latch                 none in      0.010706 seconds        : 0.107059 us/future, queue  numa 0, threads 72, info none                                             
invoked 100000, futures apply_hierarchical           latch     default_executor in      0.128711 seconds        : 1.287111 us/future, queue  numa 0, threads 72, info none
```

We're throwing away a bit of performance in the executors, but the difference isn't that big. The surprising part is just how much faster the hierarchical spawn with `create_thread` is. It doesn't improve much after 18 threads, but it doesn't get *worse* unlike all the other variations. I'm having a hard time believing this so I'd appreciate a pair of eyes (or more) to check that I'm not cheating in that test. If true it's very encouraging in the sense that we have a lot of room to improve in the executors and the way we spawn work, rather than in the queue backends. The `parallel_executor` is very close to doing this but I don't think it gets any of the benefits because it's still doing round robin scheduling.

### CODE REVIEW

**Comment by biddisco** [comment]
terrible formatting of the output. I'll clean it up

**Comment by msimberg** [comment]
I added another test that uses `for_loop` and a static chunk size of 1 to test the hierarchical scheduling of `parallel_executor` as well. This should be ready to go now as I'm not planning on changing how we schedule tasks in this PR, just testing how well different strategies work.

**Comment by hkaiser** [comment]
Why is the `default_executor` so terrible? Doesn't that at least mean we shouldn't use it as the `default`? ;-)

**Comment by biddisco** [comment]
The default executor is terrible, and it's the main reason that this test was enhanced back around the time of issue #3579 
Last time I looked at it, it seemed to be caused by some memory allocation issues. I still have not got around to pinning down the exact problem, but our continued experimentation with these overheads tests and different way of spawning tasks, is giving us a better idea of how to proceed.

**Comment by msimberg** [comment]
I thought (unsurprisingly) that the `default_executor` actually was the default executor, but it turns out that `apply/async` will use the `parallel_executor` if none is given. So things are not so bad. The use case that one actually still needs the `default_executor` for is when one wants to set priorities, stack sizes, and hints. None of the other executors support that.

So we should probably instead push to deprecate the `default_executor` and provide constructors for the `parallel_executor` and `sequenced_executor`? Or should the default executor just *be* `parallel_executor`? Or is it still worth it to wait for some sort of stabilization in the executor proposals?

**Pull request merged**
