### PR TITLE
Update EVE integration

### PR DESCRIPTION
**Pull request by srinivasyadav18**
## Proposed Changes

  - use new tag for eve fetch content : hpx-v1.9.0
  - delete FindEve.cmake, instead use `find_package(eve)`
  - replace alias `Eve::eve` with `eve::eve`
  - cleanup eve header inclusions

### CODE REVIEW

**Review by hkaiser — DISMISSED** [review]
LGTM, thanks!

**Comment by hkaiser** [comment]
@srinivasyadav18 could you please fix the clang-format issues?

**Comment by srinivasyadav18** [comment]
> @srinivasyadav18 could you please fix the clang-format issues?

This is fixed now ;-)!

**Comment by hkaiser** [comment]
bors merge

**Pull request merged**
