### PR TITLE
Set commit status from Jenkins also for special branches 

### PR DESCRIPTION
**Pull request by msimberg**
@hkaiser this is required if you decide to try to use bors more extensively. Otherwise it's not necessary and can be closed without merging.

### CODE REVIEW

**Comment by hkaiser** [comment]
> @hkaiser this is required if you decide to try to use bors more extensively. Otherwise it's not necessary and can be closed without merging.

I'd be more than happy to use bors. We might have to reduce the review requirements for this, however.

**Comment by hkaiser** [comment]
@khuck: while unrelated to this particular PR, APEX now seems to depend on zlib without checking if it's available (see: https://github.com/STEllAR-GROUP/hpx/runs/4838798276?check_suite_focus=true). Is that a known issue?

**Comment by hkaiser** [comment]
bors merge

**Comment by khuck** [comment]
> @khuck: while unrelated to this particular PR, APEX now seems to depend on zlib without checking if it's available (see: https://github.com/STEllAR-GROUP/hpx/runs/4838798276?check_suite_focus=true). Is that a known issue?
> 
> Edit: please see [UO-OACISS/apex#163](https://github.com/UO-OACISS/apex/issues/163) as well.

@hkaiser HPX / APEX _does_ check if zlib is available.  See https://github.com/UO-OACISS/apex/blob/develop/cmake/Modules/APEX_SetupZlib.cmake for the check, and `gzstream.hpp` should only get included if APEX_HAVE_ZLIB is set (https://github.com/UO-OACISS/apex/blob/b09eb7d94c9e329ce74aff29375ee9b7a384561b/src/apex/trace_event_listener.hpp#L15-L17).  Does the cmake `find_package(ZLIB)` step only check for the library, and not the development headers?

**Comment by hkaiser** [comment]
> > @khuck: while unrelated to this particular PR, APEX now seems to depend on zlib without checking if it's available (see: https://github.com/STEllAR-GROUP/hpx/runs/4838798276?check_suite_focus=true). Is that a known issue?
> > Edit: please see [UO-OACISS/apex#163](https://github.com/UO-OACISS/apex/issues/163) as well.
> 
> @hkaiser HPX / APEX _does_ check if zlib is available. See https://github.com/UO-OACISS/apex/blob/develop/cmake/Modules/APEX_SetupZlib.cmake for the check, and `gzstream.hpp` should only get included if APEX_HAVE_ZLIB is set (https://github.com/UO-OACISS/apex/blob/b09eb7d94c9e329ce74aff29375ee9b7a384561b/src/apex/trace_event_listener.hpp#L15-L17). Does the cmake `find_package(ZLIB)` step only check for the library, and not the development headers?

@khuck honestly, I don't know. But this would explain things.

**Pull request merged**
