### PR TITLE
Add support for mi-malloc

### LINKED ISSUE #4029: Add support for mimalloc
Add support for https://microsoft.github.io/mimalloc/ to the build system.

Bonus points: benchmark the allocators we support.

### PR DESCRIPTION
**Pull request by msimberg**
Fixes #4029.

Quick testing shows that it's consistenly faster than `tcmalloc` on some variations of the `future_overhead` benchmark and slower on others, so results will likely vary from application to application.

I don't know if this will work correctly on Windows.

### CODE REVIEW

**Comment by hkaiser** [comment]
I think, mimalloc on windows will a bit more work, similarly to what was needed for jemalloc. I can try looking into it.

**Comment by hkaiser** [comment]
Also, could you post your benchmarking results here, please?

**Comment by msimberg** [comment]
> Also, could you post your benchmarking results here, please?

Yeah, absolutely. Give me some time though. I don't want to do the same raw text dump I did last time. I'll get some plots going.

**Comment by msimberg** [comment]
Some of the results (sorry, I'll do more thorough plots, including comparing to jemalloc): 
[action](https://github.com/STEllAR-GROUP/hpx/files/3616883/awe.pdf)
[create_thread](https://github.com/STEllAR-GROUP/hpx/files/3616886/cth.pdf)
[for_loop](https://github.com/STEllAR-GROUP/hpx/files/3616887/for_loop.pdf)

I left the outliers in there. Each configuration is repeated 5 times and first iteration is typically worse. E.g. for the `for_loop` version the first iteration is typically much worse with `mimalloc` than it is with `tcmalloc`, but pretty much the same afterwards.

**Comment by hkaiser** [comment]
@msimberg I added support for MSVC/Windows here. I also rebased onto master (required force-pushing).

**Comment by msimberg** [comment]
Thanks @hkaiser!

**Pull request merged**
