### PR TITLE
Updating jenkins configuration for Rostam2.2

### PR DESCRIPTION
**Pull request by akheir**
Updated the Jenkins's setting on Rostam 

Libraries added:
- llvm/11 + boost/1.73
- llvm/12 + boost/1.75
- llvm/13 + boost/1.78
- gcc/9 + boost/1.75
- gcc/10 + boost/1.78
- rocm/4.5.2
- cuda/10.5

Libraries removed:
- gcc/8
- clang/9
- rocm/4.3.0
- cuda/10.4

### CODE REVIEW

**Review by hkaiser — DISMISSED** [review]
LGTM, thanks!

**Comment by msimberg** [comment]
Thanks @akheir for the updates!

It looks like all configurations (except HIP) have trouble executing the compilers:
```
CMake Warning (dev) at /usr/share/cmake/Modules/CMakeDetermineCompiler.cmake:70 (find_program):
  Policy CMP0109 is not set: find_program() requires permission to execute
  but not to read.  Run "cmake --help-policy CMP0109" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The file

    /opt/apps/llvm/11.1.0/bin/clang++

  is readable but not executable.  CMake is using it for compatibility.
Call Stack (most recent call first):
  /usr/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:64 (_cmake_find_compiler)
  CMakeLists.txt:44 (project)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The CXX compiler identification is unknown
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /opt/apps/llvm/11.1.0/bin/clang++
-- Check for working CXX compiler: /opt/apps/llvm/11.1.0/bin/clang++ - broken
CMake Error at /usr/share/cmake/Modules/CMakeTestCXXCompiler.cmake:59 (message):
  The C++ compiler

    "/opt/apps/llvm/11.1.0/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /work/jenkins/workspace/HPX/hpx/build/clang-11-debug/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/bin/ninja-build cmTC_bee84 && [1/2] Building CXX object CMakeFiles/cmTC_bee84.dir/testCXXCompiler.cxx.o
    FAILED: CMakeFiles/cmTC_bee84.dir/testCXXCompiler.cxx.o 
    /opt/apps/llvm/11.1.0/bin/clang++   -stdlib=libc++ -o CMakeFiles/cmTC_bee84.dir/testCXXCompiler.cxx.o -c testCXXCompiler.cxx
    /bin/sh: /opt/apps/llvm/11.1.0/bin/clang++: Permission denied
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:44 (project)


-- Configuring incomplete, errors occurred!
See also "/work/jenkins/workspace/HPX/hpx/build/clang-11-debug/CMakeFiles/CMakeOutput.log".
See also "/work/jenkins/workspace/HPX/hpx/build/clang-11-debug/CMakeFiles/CMakeError.log".
```

The HIP configurations are failing partly because of this issue: https://github.com/Kitware/CDash/issues/1196 which will go away once CDash is update at CSCS. There's an error following that which I think is being triggered by the fetch of Asio:
```
CMake Error at /usr/share/cmake/Modules/ExternalProject.cmake:2538 (message):
  error: git version 1.6.5 or later required for --recursive flag with 'git
  submodule ...': GIT_VERSION_STRING=''
Call Stack (most recent call first):
  /usr/share/cmake/Modules/ExternalProject.cmake:2637 (_ep_get_git_submodules_recurse)
  /usr/share/cmake/Modules/ExternalProject.cmake:3681 (_ep_add_download_command)
  CMakeLists.txt:22 (ExternalProject_Add)
```
Is it possible that it's for some reason picking up an old git version?

**Comment by akheir** [comment]
@msimberg thanks for the detailed error message,
I know what I did wrong, I forgot to set the proper rsync flag while distributing he libraries, I will fix it asap

**Comment by akheir** [comment]
@msimberg, I fixed and tested the permission issue on Rostam.

**Comment by msimberg** [comment]
retest lsu

**Comment by msimberg** [comment]
@akheir after #5578 there's now a conflict in the CI configuration files (a lot of the CMake options were changed). Let me know if you'd like me to resolve those conflicts.

**Comment by hkaiser** [comment]
It might actually be a good test to leave things as they are to see if our compatibility option propagation works correctly...

**Comment by hkaiser** [comment]
> @akheir after #5578 there's now a conflict in the CI configuration files (a lot of the CMake options were changed). Let me know if you'd like me to resolve those conflicts.

@msimberg @akheir is out for the rest of the year. I'd appreciate it if you had some time to fix this.

**Comment by hkaiser** [comment]
retest lsu

**Comment by hkaiser** [comment]
FWIW, the HIP build problems should be addressed by #5722

**Comment by hkaiser** [comment]
I think this is as good as it can get now. Merging.

**Pull request merged**
