### PR TITLE
Remove thread_pool_attached_executors as they are not used anywhere

### PR DESCRIPTION
**Pull request by biddisco**
This is partly for #3077
The thread_pool_attached_executor is not used in any code and has no obvious purpose. The pool_executor that works with the thread pools created by the resource manager supercedes it I believe.

### CODE REVIEW

**Comment by biddisco** [comment]
Note that I'm expecting some push back for this PR and I partly wanted to test if everything builds ok with this removed.

**Comment by sithhell** [comment]
The only place where it is used in `hpx::compute::block_executor`. One of the features this executor provides is the ability to schedule tasks to a given set of cores, while still allowing for the possibility of stealing. So my suggestion would be, instead of removing it, allow it to attach to a given thread pool configured using the resource partitioner.

**Comment by biddisco** [comment]
All one needs to do is create a pool with the cores you want to use and use a pool executor.

**Comment by sithhell** [comment]
Pools can't be created dynamically, and there is no stealing between pools.

**Comment by biddisco** [comment]
Dynamic pools will be supported in future. Feel free to create an issue requesting this.

The executor does not control stealing, it only tells the tasks which cores to run on - stealing is the job of the scheduler and this belongs to the pool.

**Comment by msimberg** [comment]
@biddisco do you think we can close this? I think the `thread_pool_attached_executor`s could be replaced by something better in the future, but at the moment they don't have a direct replacement and don't hurt anyone (or have they caused headaches for you while working on your executors?). In the end they're similar to a NUMA executor in that they let you schedule tasks on a subset of resources of a thread pool, without actually creating an actual thread pool.

**Comment by msimberg** [comment]
I'm going to close this for now. We can always reopen once we have a proper plan for what to do with all the executors.

**Pull request closed without merging**
