### PR TITLE
Attempt to fix CUDA related OctoTiger problems

### PR DESCRIPTION
**Pull request by hkaiser**
@diehlpk please check whether this helps with the CUDA issue you reported

### CODE REVIEW

**Comment by diehlpk** [comment]
@hkaiser The latest commit worked.

**Review by diehlpk — APPROVED** [review]
LGTM! However, I do not understand what the issue was with nvcc.

**Comment by diehlpk** [comment]
@hkaiser Lol, CUDA was updated to 11.5 and the fix does not work anymore.

**Comment by hkaiser** [comment]
> @hkaiser Lol, CUDA was updated to 11.5 and the fix does not work anymore.

Makes sense. I added the workaround for CUDA <= V11.3 only. I'll change this to include V11.5.

**Comment by hkaiser** [comment]
> > @hkaiser Lol, CUDA was updated to 11.5 and the fix does not work anymore.
> 
> Makes sense. I added the workaround for CUDA <= V11.4 only (see: https://github.com/STEllAR-GROUP/hpx/pull/5803/files#diff-3431f838361a40f09c861dad1c272c870011dbb42acecdcc1ce99dcba2773aa9R79). I'll change this to include V11.5.

See https://github.com/STEllAR-GROUP/hpx/pull/5813 for a possible fix.

**Pull request merged**
