### PR TITLE
Fixing HPX/APEX linking and dependencies for external projects like Phylanx

### PR DESCRIPTION
**Pull request by khuck**
Fixes linking problems with external executables. Fixes flatbed problems from apex dependencies.

### CODE REVIEW

**Comment by khuck** [comment]
The build-and-test CI failure has to do with documentation, I have no idea why that failed or whether it's relevant

**Comment by hkaiser** [comment]
> The build-and-test CI failure has to do with documentation, I have no idea why that failed or whether it's relevant

Yes, Auriane is currently working on fixing this (see also #4260).

**Comment by msimberg** [comment]
The pycicle builder seems to agree with this as well, which is good. It does not test that APEX actually works though (and we should try to think of a more thorough test for this; perhaps grepping stdout and otf2 files for keywords like correct task names etc.). @khuck I take it you checked that this works with e.g. Phylanx? Also, did you end up not needing to change anything related to rpath handling?

**Comment by khuck** [comment]
> The pycicle builder seems to agree with this as well, which is good. It does not test that APEX actually works though (and we should try to think of a more thorough test for this; perhaps grepping stdout and otf2 files for keywords like correct task names etc.). @khuck I take it you checked that this works with e.g. Phylanx? Also, did you end up not needing to change anything related to rpath handling?

Correct, the rpath handling is now fixed.  For testing, there is a tests/unit/apex directory, so running ctest -R tests.unit.apex should check whether the build was valid.  Although the only way to really test this change is to use HPX with another project, which is the Phylanx test.  I have a buildbot server that does just that, http://omega.nic.uoregon.edu:8020

**Pull request merged**
