### PR TITLE
Simplify execution CPOs

### PR DESCRIPTION
**Pull request by msimberg**
In P0443 member functions were given priority over free functions in the various CPOs. In P2300 tag_dispatch is the only way to implement various CPOs, i.e. member functions are not taken into account. This updates our execution CPOs to behave like P2300. This means that `schedule`, `set_value`, `set_error`, `set_done`, `start`, `connect` inherit `hpx::functional::tag`, not `hpx::functional::tag_priority`. This is slightly more verbose (`friend void tag_dispatch(start_t, ...)` instead of `void start(...)`) but is simpler to reason about. Additionally, the `thread_pool_scheduler` test compiles 10-15% faster with this change.

As a flyby I've:
- Removed the leftover scheduler is a sender functionality (i.e. one has to use `schedule(scheduler)` to get a sender; `thread_pool_scheduler` was previously a sender in itself)
- `just` is no longer a CPO (customization makes very little sense, this is aligned with P2300)
- `keep_future` is no longer a CPO (it only makes sense for futures)

Algorithms that have a reasonable default implementation still use `tag_fallback_dispatch` as before.

I think we should also revisit the `tag_dispatch`/`tag_invoke` question. The way we are now using `tag_dispatch` for the execution CPOs is really what `tag_invoke` is supposed to be. For the case of the segmented algorithms I believe we could put the dispatching one level down into the algorithm implementations as an internal implementation detail, but it should not use the "public" customization point.

### CODE REVIEW

**Comment by msimberg** [comment]
> That's exactly what we just removed. The goal was to completely separate the segmented implementations from the non-segmented (normal) ones. I think the base implementations shouldn't be aware of a possible segmented overload.

Right. I suppose the problem is that now the "odd" name `tag_dispatch` (there because we want to do dispatching for things like the segmented algorithms) leaks into things that are legitimately `tag_invoke`-y. One solution could be to have both `tag_dispatch` and `tag_invoke`. In any case, I'm not proposing to change that in this PR, it's just something that came up while doing these changes.

**Comment by hkaiser** [comment]
> > That's exactly what we just removed. The goal was to completely separate the segmented implementations from the non-segmented (normal) ones. I think the base implementations shouldn't be aware of a possible segmented overload.
> 
> Right. I suppose the problem is that now the "odd" name `tag_dispatch` (there because we want to do dispatching for things like the segmented algorithms) leaks into things that are legitimately `tag_invoke`-y. One solution could be to have both `tag_dispatch` and `tag_invoke`. In any case, I'm not proposing to change that in this PR, it's just something that came up while doing these changes.

I was thinking about possible interactions between our `tag_invoke`  and a potential `std::tag_invoke`. From what I see, even if we would name our facility `tag_invoke`, there wouldn't be any bad situations, where a `std::tag_invoke` could accidentally consider one of our APIs (the used tags would prevent that). That leaves us only with conceptual reasons to name our facilities `dispatch` instead of `invoke`.

I still think that `tag_dispatch` is much more than just `tag_invoke` as it provides convenient ways to manage overloading. We should consider all of our uses before starting to rename `tag_dispatch` back into `tag_invoke`.

**Comment by hkaiser** [comment]
Also: what about the algorithm overloads for Kokkos? Wouldn't that require `tag_fallback_dispatch` to function as well?

**Comment by msimberg** [comment]
Responded here https://github.com/STEllAR-GROUP/hpx/pull/5348#issuecomment-919174774, since the `tag_invoke/dispatch` discussion doesn't affect this PR.

**Review by aurianer — APPROVED** [review]
LGTM thanks!

**Pull request merged**
