### PR TITLE
Fix Public API main page

### PR DESCRIPTION
**Pull request by dimitraka**
Fixes #
- Add links to C++ standard
- Split algorithms
- Correct namespaces

### CODE REVIEW

**Review by NK-Nikunj — DISMISSED** [review]
LGTM, thanks!

**Comment by gonidelis** [comment]
Nice!

**Comment by gonidelis** [comment]
Nice!

**Comment by hkaiser** [comment]
@dimitraka Could you please rebase this PR onto master (and resolve the conflicts)?

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by hkaiser** [comment]
bors merge

**Pull request merged**
