### PR TITLE
Fixing compatibility header for pack.hpp

### PR DESCRIPTION
**Pull request by hkaiser**

### CODE REVIEW

**Comment by K-ballo** [comment]
The other pack compatibility header needs similar changes.

**Comment by hkaiser** [comment]
> The other pack compatibility header needs similar changes.

Which ones, @K-ballo?

**Comment by K-ballo** [comment]
> > The other pack compatibility header needs similar changes.
> 
> Which ones, @K-ballo?

The original compatibility header, from when it was moved into a module: https://github.com/STEllAR-GROUP/hpx/blob/master/libs/datastructures/include_compatibility/hpx/util/detail/pack.hpp

**Comment by hkaiser** [comment]
> The other pack compatibility header needs similar changes.
> 
> Which ones, @K-ballo?
> 
> The original compatibility header, from when it was moved into a module: https://github.com/STEllAR-GROUP/hpx/blob/master/libs/datastructures/include_compatibility/hpx/util/detail/pack.hpp

Done.

**Comment by hkaiser** [comment]
The test failures seem to be unrelated... I'll merge this now.

**Pull request merged**
