### PR TITLE
Fix a wrong #ifdef for IO/TIMER pools causing build errors

### PR DESCRIPTION
**Pull request by biddisco**
Jut a flyby fix that was causing build errors for me

### CODE REVIEW

**Comment by biddisco** [comment]
Although this fixes my build. I still have an error when applications try to access the IO pool but I can't see what's triggering it. Something is calling an action to sync the IO pool at shutdown time ....
```
Thread 7 "future_overhead" hit Catchpoint 1 (exception thrown), __cxxabiv1::__cxa_throw (obj=0x2aaab5f28080, tinfo=0x2aaaac72cb40 <typeinfo for hpx::detail::exception_with_info<hpx::exception>>, dest=0x2aaaabd032f8 <hpx::detail::exception_with_info<hpx::exception>::~exception_with_info()>) at ../../../../cray-gcc-8.3.0-201903122028.16ea96cb84a9a/libstdc++-v3/libsupc++/eh_throw.cc:80
80      ../../../../cray-gcc-8.3.0-201903122028.16ea96cb84a9a/libstdc++-v3/libsupc++/eh_throw.cc: No such file or directory.
gdb$ bt
#0  __cxxabiv1::__cxa_throw (obj=0x2aaab5f28080, tinfo=0x2aaaac72cb40 <typeinfo for hpx::detail::exception_with_info<hpx::exception>>, dest=0x2aaaabd032f8 <hpx::detail::exception_with_info<hpx::exception>::~exception_with_info()>) at ../../../../cray-gcc-8.3.0-201903122028.16ea96cb84a9a/libstdc++-v3/libsupc++/eh_throw.cc:80
#1  0x00002aaaabd033f8 in hpx::throw_with_info<hpx::exception const&> (e=..., xi=...) at /apps/daint/UES/biddisco/src/hpx/libs/errors/include/hpx/errors/exception_info.hpp:194
#2  0x00002aaaabd00ed5 in hpx::detail::construct_custom_exception<hpx::exception> (e=..., func=..., file=..., line=1620, auxinfo=...) at /apps/daint/UES/biddisco/src/hpx/libs/errors/src/exception.cpp:219
#3  0x00002aaaabcff399 in hpx::detail::get_exception<hpx::exception> (e=..., func=..., file=..., line=1620, auxinfo=...) at /apps/daint/UES/biddisco/src/hpx/libs/errors/src/exception.cpp:260
#4  0x00002aaaabcffb6d in hpx::detail::throw_exception<hpx::exception> (e=..., func=..., file=..., line=1620) at /apps/daint/UES/biddisco/src/hpx/libs/errors/src/exception.cpp:272
#5  0x00002aaaabd08a29 in hpx::detail::throw_exception (errcode=hpx::bad_parameter, msg=..., func=..., file=..., line=1620) at /apps/daint/UES/biddisco/src/hpx/libs/errors/src/throw_exception.cpp:23
#6  0x00002aaaabbe9f82 in hpx::runtime_distributed::get_thread_pool (this=0x2aaab240b000, name=0x2aab3a475a20 "io_pool") at /apps/daint/UES/biddisco/src/hpx/src/runtime_distributed.cpp:1618
#7  0x00002aaaabe8fd04 in hpx::get_thread_pool (name=0x2aaaab34dc28 "io_pool", name_suffix=0x2aaaab34d8f0 "") at /apps/daint/UES/biddisco/src/hpx/libs/runtime_local/src/runtime_local.cpp:1125
#8  0x00002aaaab31ce4d in hpx::iostreams::server::output_stream::write_sync (this=0x2aaab9023150, locality_id=0, count=0, buf_in=...) at /apps/daint/UES/biddisco/src/hpx/components/iostreams/src/server/output_stream.cpp:91
#9  0x00002aaaab33dd75 in hpx::actions::detail::component_invoke<hpx::iostreams::server::output_stream, void, void (unsigned int, unsigned long, hpx::iostreams::detail::buffer const&), unsigned int, unsigned long, hpx::iostreams::detail::buffer>(std::integral_constant<bool, false>, unsigned long, int, void (hpx::iostreams::server::output_stream::*)(unsigned int, unsigned long, hpx::iostreams::detail::buffer const&), unsigned int&&, unsigned long&&, hpx::iostreams::detail::buffer&&) (lva=46912736735568, f=(void (hpx::iostreams::server::output_stream::*)(hpx::iostreams::server::output_stream * const, unsigned int, unsigned long, const hpx::iostreams::detail::buffer &)) 0x2aaaab31cdf6 <hpx::iostreams::server::output_stream::write_sync(unsigned int, unsigned long, hpx::iostreams::detail::buffer const&)>, vs#0=@0x2aaab542c110: 0, vs#1=@0x2aaab542c118: 0, vs#2=...) at /apps/daint/UES/biddisco/src/hpx/hpx/runtime/actions/component_action.hpp:61
#10 0x00002aaaab33da3e in hpx::actions::action<void (hpx::iostreams::server::output_stream::*)(unsigned int, unsigned long, hpx::iostreams::detail::buffer const&), &hpx::iostreams::server::output_stream::write_sync, hpx::iostreams::server::output_stream::write_sync_action>::invoke<unsigned int, unsigned long, hpx::iostreams::detail::buffer> (lva=46912736735568, comptype=36, vs#0=@0x2aaab542c110: 0, vs#1=@0x2aaab542c118: 0, vs#2=...) at /apps/daint/UES/biddisco/src/hpx/hpx/runtime/actions/component_action.hpp:121
#11 0x00002aaaab33e329 in hpx::actions::detail::action_invoke<hpx::iostreams::server::output_stream::write_sync_action>::operator()<unsigned int, unsigned long, hpx::iostreams::detail::buffer> (this=0x2aab3a475df0) at /apps/daint/UES/biddisco/src/hpx/hpx/runtime/actions/basic_action.hpp:85
#12 hpx::util::detail::invoke_fused_impl<0ul, 1ul, 2ul, hpx::actions::detail::action_invoke<hpx::iostreams::server::output_stream::write_sync_action>, hpx::util::tuple<unsigned int, unsigned long, hpx::iostreams::detail::buffer> > (f=..., t=...) at /apps/daint/UES/biddisco/src/hpx/libs/functional/include/hpx/functional/invoke_fused.hpp:78
#13 0x00002aaaab33e1e7 in hpx::util::functional::invoke_fused::operator()<hpx::actions::detail::action_invoke<hpx::iostreams::server::output_stream::write_sync_action>, hpx::util::tuple<unsigned int, unsigned long, hpx::iostreams::detail::buffer> > (this=0x2aab3a475e0f, f=..., t=...) at /apps/daint/UES/biddisco/src/hpx/libs/functional/include/hpx/functional/invoke_fused.hpp:135
#14 0x00002aaaab33e1a1 in hpx::util::invoke<hpx::util::functional::invoke_fused, hpx::actions::detail::action_invoke<hpx::iostreams::server::output_stream::write_sync_action>, hpx::util::tuple<unsigned int, unsigned long, hpx::iostreams::detail::buffer> > (f=..., vs#0=..., vs#1=...) at /apps/daint/UES/biddisco/src/hpx/libs/functional/include/hpx/functional/invoke.hpp:135
#15 0x00002aaaab33e0d4 in hpx::actions::trigger<void, hpx::util::functional::invoke_fused, hpx::actions::detail::action_invoke<hpx::iostreams::server::output_stream::write_sync_action>, hpx::util::tuple<unsigned int, unsigned long, hpx::iostreams::detail::buffer> > (cont=..., f=..., vs#0=..., vs#1=...) at /apps/daint/UES/biddisco/src/hpx/hpx/runtime/actions/trigger.hpp:42
#16 0x00002aaaab33dff7 in hpx::actions::detail::continuation_thread_function<hpx::iostreams::server::output_stream::write_sync_action>::operator() (this=0x2aaab542c0a0) at /apps/daint/UES/biddisco/src/hpx/hpx/runtime/actions/basic_action.hpp:182
#17 0x00002aaaab33df5a in hpx::util::detail::callable_vtable<std::pair<hpx::threads::thread_state_enum, hpx::threads::thread_id> (hpx::threads::thread_state_ex_enum)>::_invoke<hpx::actions::detail::continuation_thread_function<hpx::iostreams::server::output_stream::write_sync_action> >(void*, hpx::threads::thread_state_ex_enum&&) (f=0x2aaab542c0a0, vs#0=@0x2aab3a475edc: hpx::threads::wait_signaled) at /apps/daint/UES/biddisco/src/hpx/libs/functional/include/hpx/functional/detail/vtable/callable_vtable.hpp:93
#18 0x00002aaaabcfb064 in hpx::util::detail::basic_function<std::pair<hpx::threads::thread_state_enum, hpx::threads::thread_id> (hpx::threads::thread_state_ex_enum), false, false>::operator()(hpx::threads::thread_state_ex_enum) const (vs#0=hpx::threads::wait_signaled, this=0x2aaab9188700) at /apps/daint/UES/biddisco/src/hpx/libs/functional/include/hpx/functional/detail/basic_function.hpp:228
#19 hpx::threads::coroutines::detail::coroutine_impl::operator() (this=0x2aaab9188690) at /apps/daint/UES/biddisco/src/hpx/libs/coroutines/src/detail/coroutine_impl.cpp:74
#20 0x00002aaaabcfab72 in hpx::threads::coroutines::detail::lx::trampoline<hpx::threads::coroutines::detail::coroutine_impl> (fun=0x2aaab9188690) at /apps/daint/UES/biddisco/src/hpx/libs/coroutines/include/hpx/coroutines/detail/context_linux_x86.hpp:92
#21 0x0000000000000000 in ?? ()
```

**Comment by msimberg** [comment]
> Although this fixes my build. I still have an error when applications try to access the IO pool but I can't see what's triggering it. Something is calling an action to sync the IO pool at shutdown time ....
> 
> ```
> Thread 7 "future_overhead" hit Catchpoint 1 (exception thrown), __cxxabiv1::__cxa_throw (obj=0x2aaab5f28080, tinfo=0x2aaaac72cb40 <typeinfo for hpx::detail::exception_with_info<hpx::exception>>, dest=0x2aaaabd032f8 <hpx::detail::exception_with_info<hpx::exception>::~exception_with_info()>) at ../../../../cray-gcc-8.3.0-201903122028.16ea96cb84a9a/libstdc++-v3/libsupc++/eh_throw.cc:80
> 80      ../../../../cray-gcc-8.3.0-201903122028.16ea96cb84a9a/libstdc++-v3/libsupc++/eh_throw.cc: No such file or directory.
> gdb$ bt
> #0  __cxxabiv1::__cxa_throw (obj=0x2aaab5f28080, tinfo=0x2aaaac72cb40 <typeinfo for hpx::detail::exception_with_info<hpx::exception>>, dest=0x2aaaabd032f8 <hpx::detail::exception_with_info<hpx::exception>::~exception_with_info()>) at ../../../../cray-gcc-8.3.0-201903122028.16ea96cb84a9a/libstdc++-v3/libsupc++/eh_throw.cc:80
> #1  0x00002aaaabd033f8 in hpx::throw_with_info<hpx::exception const&> (e=..., xi=...) at /apps/daint/UES/biddisco/src/hpx/libs/errors/include/hpx/errors/exception_info.hpp:194
> #2  0x00002aaaabd00ed5 in hpx::detail::construct_custom_exception<hpx::exception> (e=..., func=..., file=..., line=1620, auxinfo=...) at /apps/daint/UES/biddisco/src/hpx/libs/errors/src/exception.cpp:219
> #3  0x00002aaaabcff399 in hpx::detail::get_exception<hpx::exception> (e=..., func=..., file=..., line=1620, auxinfo=...) at /apps/daint/UES/biddisco/src/hpx/libs/errors/src/exception.cpp:260
> #4  0x00002aaaabcffb6d in hpx::detail::throw_exception<hpx::exception> (e=..., func=..., file=..., line=1620) at /apps/daint/UES/biddisco/src/hpx/libs/errors/src/exception.cpp:272
> #5  0x00002aaaabd08a29 in hpx::detail::throw_exception (errcode=hpx::bad_parameter, msg=..., func=..., file=..., line=1620) at /apps/daint/UES/biddisco/src/hpx/libs/errors/src/throw_exception.cpp:23
> #6  0x00002aaaabbe9f82 in hpx::runtime_distributed::get_thread_pool (this=0x2aaab240b000, name=0x2aab3a475a20 "io_pool") at /apps/daint/UES/biddisco/src/hpx/src/runtime_distributed.cpp:1618
> #7  0x00002aaaabe8fd04 in hpx::get_thread_pool (name=0x2aaaab34dc28 "io_pool", name_suffix=0x2aaaab34d8f0 "") at /apps/daint/UES/biddisco/src/hpx/libs/runtime_local/src/runtime_local.cpp:1125
> #8  0x00002aaaab31ce4d in hpx::iostreams::server::output_stream::write_sync (this=0x2aaab9023150, locality_id=0, count=0, buf_in=...) at /apps/daint/UES/biddisco/src/hpx/components/iostreams/src/server/output_stream.cpp:91
> #9  0x00002aaaab33dd75 in hpx::actions::detail::component_invoke<hpx::iostreams::server::output_stream, void, void (unsigned int, unsigned long, hpx::iostreams::detail::buffer const&), unsigned int, unsigned long, hpx::iostreams::detail::buffer>(std::integral_constant<bool, false>, unsigned long, int, void (hpx::iostreams::server::output_stream::*)(unsigned int, unsigned long, hpx::iostreams::detail::buffer const&), unsigned int&&, unsigned long&&, hpx::iostreams::detail::buffer&&) (lva=46912736735568, f=(void (hpx::iostreams::server::output_stream::*)(hpx::iostreams::server::output_stream * const, unsigned int, unsigned long, const hpx::iostreams::detail::buffer &)) 0x2aaaab31cdf6 <hpx::iostreams::server::output_stream::write_sync(unsigned int, unsigned long, hpx::iostreams::detail::buffer const&)>, vs#0=@0x2aaab542c110: 0, vs#1=@0x2aaab542c118: 0, vs#2=...) at /apps/daint/UES/biddisco/src/hpx/hpx/runtime/actions/component_action.hpp:61
> #10 0x00002aaaab33da3e in hpx::actions::action<void (hpx::iostreams::server::output_stream::*)(unsigned int, unsigned long, hpx::iostreams::detail::buffer const&), &hpx::iostreams::server::output_stream::write_sync, hpx::iostreams::server::output_stream::write_sync_action>::invoke<unsigned int, unsigned long, hpx::iostreams::detail::buffer> (lva=46912736735568, comptype=36, vs#0=@0x2aaab542c110: 0, vs#1=@0x2aaab542c118: 0, vs#2=...) at /apps/daint/UES/biddisco/src/hpx/hpx/runtime/actions/component_action.hpp:121
> #11 0x00002aaaab33e329 in hpx::actions::detail::action_invoke<hpx::iostreams::server::output_stream::write_sync_action>::operator()<unsigned int, unsigned long, hpx::iostreams::detail::buffer> (this=0x2aab3a475df0) at /apps/daint/UES/biddisco/src/hpx/hpx/runtime/actions/basic_action.hpp:85
> #12 hpx::util::detail::invoke_fused_impl<0ul, 1ul, 2ul, hpx::actions::detail::action_invoke<hpx::iostreams::server::output_stream::write_sync_action>, hpx::util::tuple<unsigned int, unsigned long, hpx::iostreams::detail::buffer> > (f=..., t=...) at /apps/daint/UES/biddisco/src/hpx/libs/functional/include/hpx/functional/invoke_fused.hpp:78
> #13 0x00002aaaab33e1e7 in hpx::util::functional::invoke_fused::operator()<hpx::actions::detail::action_invoke<hpx::iostreams::server::output_stream::write_sync_action>, hpx::util::tuple<unsigned int, unsigned long, hpx::iostreams::detail::buffer> > (this=0x2aab3a475e0f, f=..., t=...) at /apps/daint/UES/biddisco/src/hpx/libs/functional/include/hpx/functional/invoke_fused.hpp:135
> #14 0x00002aaaab33e1a1 in hpx::util::invoke<hpx::util::functional::invoke_fused, hpx::actions::detail::action_invoke<hpx::iostreams::server::output_stream::write_sync_action>, hpx::util::tuple<unsigned int, unsigned long, hpx::iostreams::detail::buffer> > (f=..., vs#0=..., vs#1=...) at /apps/daint/UES/biddisco/src/hpx/libs/functional/include/hpx/functional/invoke.hpp:135
> #15 0x00002aaaab33e0d4 in hpx::actions::trigger<void, hpx::util::functional::invoke_fused, hpx::actions::detail::action_invoke<hpx::iostreams::server::output_stream::write_sync_action>, hpx::util::tuple<unsigned int, unsigned long, hpx::iostreams::detail::buffer> > (cont=..., f=..., vs#0=..., vs#1=...) at /apps/daint/UES/biddisco/src/hpx/hpx/runtime/actions/trigger.hpp:42
> #16 0x00002aaaab33dff7 in hpx::actions::detail::continuation_thread_function<hpx::iostreams::server::output_stream::write_sync_action>::operator() (this=0x2aaab542c0a0) at /apps/daint/UES/biddisco/src/hpx/hpx/runtime/actions/basic_action.hpp:182
> #17 0x00002aaaab33df5a in hpx::util::detail::callable_vtable<std::pair<hpx::threads::thread_state_enum, hpx::threads::thread_id> (hpx::threads::thread_state_ex_enum)>::_invoke<hpx::actions::detail::continuation_thread_function<hpx::iostreams::server::output_stream::write_sync_action> >(void*, hpx::threads::thread_state_ex_enum&&) (f=0x2aaab542c0a0, vs#0=@0x2aab3a475edc: hpx::threads::wait_signaled) at /apps/daint/UES/biddisco/src/hpx/libs/functional/include/hpx/functional/detail/vtable/callable_vtable.hpp:93
> #18 0x00002aaaabcfb064 in hpx::util::detail::basic_function<std::pair<hpx::threads::thread_state_enum, hpx::threads::thread_id> (hpx::threads::thread_state_ex_enum), false, false>::operator()(hpx::threads::thread_state_ex_enum) const (vs#0=hpx::threads::wait_signaled, this=0x2aaab9188700) at /apps/daint/UES/biddisco/src/hpx/libs/functional/include/hpx/functional/detail/basic_function.hpp:228
> #19 hpx::threads::coroutines::detail::coroutine_impl::operator() (this=0x2aaab9188690) at /apps/daint/UES/biddisco/src/hpx/libs/coroutines/src/detail/coroutine_impl.cpp:74
> #20 0x00002aaaabcfab72 in hpx::threads::coroutines::detail::lx::trampoline<hpx::threads::coroutines::detail::coroutine_impl> (fun=0x2aaab9188690) at /apps/daint/UES/biddisco/src/hpx/libs/coroutines/include/hpx/coroutines/detail/context_linux_x86.hpp:92
> #21 0x0000000000000000 in ?? ()
> ```

Does inspecting the buffer in `write_sync` give you anything useful? I doubt our examples/tests were ever meant to run without the IO pool, so are you running those or a standalone app? `hpx::cout` is the obvious thing to look for...

**Comment by biddisco** [comment]
> Does inspecting the buffer in `write_sync` give you anything useful? I doubt our examples/tests were ever meant to run without the IO pool, so are you running those or a standalone app? `hpx::cout` is the obvious thing to look for...

No `hpx::cout` is not used anywhere I suspect some shutdown synchronization action but due to meetings, I didn't get any further. I'm hoping @hkaiser knows what might be calling it before termination.

**Comment by msimberg** [comment]
I'll merge this now as this still fixes the build. I've opened #4818 for the second issue. @biddisco could you please comment with your build settings on that other issue?

**Pull request merged**
