### PR TITLE
Splitting tests to avoid compiler OOM

### LINKED ISSUE #3272: CircleCI does not upload generated docker image any more
The new CircleCI V2 scripts do not upload the generated docker image anymore as some of the parallel algorithm tests fail to compile (OOM problems?). This causes all kind of problems for projects depending on the latest HPX master features.

Would it be possible to upload the docker file whenever the core libraries compile successfully (at least until the issue with the parallel algorithms has been resolved)?

### PR DESCRIPTION
**Pull request by hkaiser**
Fixes #3272

### CODE REVIEW

**Comment by hkaiser** [comment]
This also fixes #3053

**Comment by msimberg** [comment]
Very nice! Now the problem is the install step:

```
Concurrent upstream jobs persisted the same file(s) into the workspace:
  - tests/headers/CMakeFiles/runtime_runtime_mode_hpp_lib.dir/flags.make
  - tests/headers/CMakeFiles/runtime_parcelset_fwd_hpp_lib.dir/link.txt
  - tests/unit/parallel/algorithms/CMakeFiles/
...
```

This is because the test steps all attach to the same workspace, persist their workspaces, and the install step then tries to merge them. This should fail officially as well (according to [this](https://circleci.com/blog/deep-diving-into-circleci-workspaces/)). We could try deleting those files in all but one of the parallel steps... @sithhell have you encountered this problem with other projects? How badly do we want parallel builds?

**Comment by hkaiser** [comment]
@msimberg @sithhell could this be resolved with high priority please? We really need an updated docker image for our other project testing environment asap.

**Comment by msimberg** [comment]
@hkaiser in that case I will try to make everything sequential at least as a temporary solution (it *should* work, we'll see). Then we can play around again to make it run in parallel.

**Comment by msimberg** [comment]
But we still need this one so I will go ahead and merge this. Thanks!

**Comment by hkaiser** [comment]
@msimberg Wouldn't it be sufficient to single out one of the steps to run after everything has finished to do the installation?

**Comment by msimberg** [comment]
@hkaiser hmm, yes, it won't be a full install then but I suppose that's enough for you?

**Comment by hkaiser** [comment]
@msimberg I'd need a full install, but your suggestion sound like a possible solution.

**Comment by msimberg** [comment]
I need to think before I write on a Friday afternoon. `make install` depends on examples but not tests. Let's see what happens in #3275.

**Comment by sithhell** [comment]
The parallel workspace merge is certainly a problem. It is a little unclear to me why the failure happens, since only the examples persist files to the workspace (or should, at least)... I think in general, it is a good idea to only upload a new docker image once the tests pass. Keeps us motivated to fix the remaining spurious failures ;)

**Pull request merged**
