### PR TITLE
Use dynamic bitsets by default for CPU masks

### LINKED ISSUE #5661: HPX should detect the number of cores on the build machine
## Expected Behavior

HPX should build for the number of cores on the machine you're on by default

## Actual Behavior

It builds for 64 or less cores

### PR DESCRIPTION
**Pull request by msimberg**
Maybe fixes #5661.

Opening this as a draft only to see the performance test CI results.

### CODE REVIEW

**Comment by msimberg** [comment]
The first runs looks good both for `future_overhead` and `stream`. However, that's only with 4 threads. I'll try to get some more comprehensive runs in later.

**Comment by msimberg** [comment]
Below are some more thorough benchmarks. All them are with the default scheduler. I'd say the differences are within noise levels.

Future overhead benchmark with the `parallel_executor` (since it spawns more tasks):
future_overhead_static_dynamic

Stream benchmark:
stream_static_dynamic

**Comment by hkaiser** [comment]
> Below are some more thorough benchmarks. All them are with the default scheduler. I'd say the differences are within noise levels.

Ok, let's switch to dynamic bitsets, then.

**Comment by msimberg** [comment]
In yesterday's meeting we decided to use vectors in the `shared_priority_queue_scheduler` to make it work with dynamic bitsets. In my infinite wisdom I already made that change in #5171 (https://github.com/STEllAR-GROUP/hpx/blob/7ae910fcc1180b48d775791fb1941a74ab3be584/libs/core/schedulers/include/hpx/schedulers/shared_priority_queue_scheduler.hpp#L1362-L1368) and promptly forgot about it. It even uses arrays if `HPX_WITH_MAX_CPU_COUNT` is defined and falls back to vectors otherwise.

**Comment by msimberg** [comment]
bors merge

**Pull request merged**
