### PR TITLE
Rename 'module' symbols to avoid keyword conflict

### LINKED ISSUE #5148: runtime_support.hpp does not work with newer cling
## Expected Behavior

Code including this file should compile.

## Actual Behavior

An error is triggered. The compiler claims a ')' is needed after the identifier "module" on line 300.

Changing "module" to "module_" on lines 300 and 303 allows the code to compile.

### PR DESCRIPTION
**Pull request by hkaiser**
Fixes #5148

('module' is a keyword starting with C++20)

### CODE REVIEW

**Review by msimberg — APPROVED** [review]
Nasty... Thanks! How difficult would it be to add an inspect check for this? Let me know if you'd like me to add it.

**Review by aurianer — APPROVED** [review]
Thanks!

**Comment by hkaiser** [comment]
> Nasty... Thanks! How difficult would it be to add an inspect check for this? Let me know if you'd like me to add it.

If we had a C++20 builder then we wouldn't need an inspect check, I think.

**Comment by msimberg** [comment]
> > Nasty... Thanks! How difficult would it be to add an inspect check for this? Let me know if you'd like me to add it.
> 
> If we had a C++20 builder then we wouldn't need an inspect check, I think.

Good point! We can definitely add that.

**Pull request merged**
