### PR TITLE
Adding --hpx:bind=none to disable thread affinities

### PR DESCRIPTION
**Pull request by hkaiser**

### CODE REVIEW

**Comment by hkaiser** [comment]
@Finomnis: please try this to make sure it solves your problems on travis.

**Comment by hkaiser** [comment]
This is meant to fix #1432: Add command line flag to disable thread pinning

**Comment by pagrubel** [comment]
When would one use this?

On Mar 31, 2015, at 6:21 PM, Hartmut Kaiser <notifications@github.com<mailto:notifications@github.com>> wrote:


This is meant to fix #1432<https://github.com/STEllAR-GROUP/hpx/issues/1432>: Add command line flag to disable thread pinning

**Comment by sithhell** [comment]
@pagrubel this can be used when no pinning at all is desired. Some platforms potentially have problems with pinning the threads to cores.

**Comment by sithhell** [comment]
Thanks!

**Pull request merged**
