### PR TITLE
Modernize facilities related to hpx::sync

### PR DESCRIPTION
**Pull request by hkaiser**

### CODE REVIEW

**Comment by msimberg** [comment]
@hkaiser could you please summarize the changes? Is it `::type` to `_t`, `::value` to `_v`, `typedef` to `using`, and a few new helper type traits? Something else?

**Review by aurianer — APPROVED** [review]
LGTM thanks!

**Comment by hkaiser** [comment]
> @hkaiser could you please summarize the changes? Is it `::type` to `_t`, `::value` to `_v`, `typedef` to `using`, and a few new helper type traits? Something else?

Yes, this is mostly `_t`/`_v` changes and adding missing implementations for those. I have also replaced some explicitly calculated return types with a simple `auto`.

**Review by msimberg — APPROVED** [review]
Thanks!

**Comment by msimberg** [comment]
@hkaiser I've only formatted a file. Was this otherwise ready to go now?

**Comment by hkaiser** [comment]
> @hkaiser I've only formatted a file. Was this otherwise ready to go now?

Yes, thanks!

**Comment by hkaiser** [comment]
Thanks for taking care of this @msimberg !

**Pull request merged**
