### PR TITLE
Replaced tag_invoke with tag_fallback_invoke for adjacent_find algorithm

### PR DESCRIPTION
**Pull request by Jedi18**
Replaced tag_invoke with tag_fallback_invoke for adjacent_find algorithm as mentioned here https://github.com/STEllAR-GROUP/hpx/pull/5176#issuecomment-781142703 .

### CODE REVIEW

**Comment by hkaiser** [comment]
Could you add the corresponding changes to this file as well, please (just to keep the algorithms consistent)?

**Comment by msimberg** [comment]
retest

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by gonidelis** [comment]
@Jedi18  Thanks :)

**Comment by hkaiser** [comment]
The remaining errors are unrelated. @Jedi18 thank you again for contributing!

**Comment by Jedi18** [comment]
Thank you for merging and help with the PR!

**Pull request merged**
