### PR TITLE
HPX on ppc64le

### PR DESCRIPTION
**Pull request by KhalidHasanov**
HPX on ppc64le:
Based on {version}: V0.9.99-trunk (AGAS: V3.0), Git: 516da8e9c4
{platform}: linux
{compiler}: GNU C++ version 6.1.0
{stdlib}: GNU libstdc++ version 20160427

Build with boost-1.60, gcc-6.1, and hwloc-1.11.3.

### CODE REVIEW

**Comment by hkaiser** [comment]
@KhalidHasanov Thanks so much! How urgent is this patch? I'd be a bit hesitant to merge this into our upcoming release (planned for the end of this week), mainly as we have no way of testing this on short notice. Would it be sufficient for this patch to go into the master branch (targetting the next release, planned for October)?

**Comment by KhalidHasanov** [comment]
@hkaiser You are welcome! It is not that urgent actually, waiting for the October release should be fine.

**Comment by hkaiser** [comment]
@KhalidHasanov Great! I'll merge this to master, then.

**Comment by KhalidHasanov** [comment]
@hkaiser Thanks!

**Pull request merged**
