### PR TITLE
Adding simple average power consumption performance counter

### PR DESCRIPTION
**Pull request by hkaiser**
This adds an HPX performance counter `/runtime{locality#N/total}/average_power`. The power consumption is collected through the PWR library (http://powerapi.sandia.gov/).

The build system expects for the library to be installed, available through pkg_config, or found using the `HPX_PWR_ROOT` cmake variable.

### CODE REVIEW

**Comment by diehlpk** [comment]
@hkaiser The branch does not compile on Fugaku.

```
/vol0003/mdt0/data/hp210311/u10393/OctoTigerBuildChain/src/hpx/components/performance_counters/power/src/power_counter.cpp:8:10: fatal error: hpx/asssert.hpp: No such file or directory
    8 | #include <hpx/asssert.hpp>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [components/performance_counters/power/CMakeFiles/power_component.dir/build.make:90: components/performance_counters/power/CMakeFiles/power_component.dir/src/power_counter.cpp.o] Error 1
gmake[2]: Leaving directory '/vol0003/mdt0/data/hp210311/u10393/OctoTigerBuildChain/build/hpx/build'
gmake[1]: *** [CMakeFiles/Makefile2:10847: components/performance_counters/power/CMakeFiles/power_component.dir/all] Error 2
```

**Comment by hkaiser** [comment]
> @hkaiser The branch does not compile on Fugaku.
> 
> ```
> /vol0003/mdt0/data/hp210311/u10393/OctoTigerBuildChain/src/hpx/components/performance_counters/power/src/power_counter.cpp:8:10: fatal error: hpx/asssert.hpp: No such file or directory
>     8 | #include <hpx/asssert.hpp>
>       |          ^~~~~~~~~~~~~~~~~
> compilation terminated.
> gmake[2]: *** [components/performance_counters/power/CMakeFiles/power_component.dir/build.make:90: components/performance_counters/power/CMakeFiles/power_component.dir/src/power_counter.cpp.o] Error 1
> gmake[2]: Leaving directory '/vol0003/mdt0/data/hp210311/u10393/OctoTigerBuildChain/build/hpx/build'
> gmake[1]: *** [CMakeFiles/Makefile2:10847: components/performance_counters/power/CMakeFiles/power_component.dir/all] Error 2
> ```

Yes, this is an obvious typo. Will fix.

**Comment by diehlpk** [comment]
@hkaiser I added some commits to get things to compile. I have not yet tested the performance counter.

**Comment by diehlpk** [comment]
@hkaiser HPX segfaults with the counter enabled. I will have a look later.

```
(gdb) where
#0  _get_nobjs_has (topology=topology@entry=0x400020ff0000, obj=obj@entry=0x2, type=type@entry=HWLOC_OBJ_NUMANODE)
    at node_conf.c:236
#1  0x00004000214c3b84 in _get_nobjs_has (topology=topology@entry=0x400020ff0000, obj=obj@entry=0x400020b00300, 
    type=type@entry=HWLOC_OBJ_NUMANODE) at node_conf.c:244
#2  0x00004000214c45c0 in _get_nchips (topology=0x400020ff0000) at node_conf.c:261
#3  _get_chip_infos (infos=0x4000214f06c0 <_chip_infos>, conf=0x4000214f0688 <_node_conf>, topology=0x400020ff0000)
    at node_conf.c:468
#4  node_conf_init () at node_conf.c:776
#5  0x00004000214c360c in krm_init_locked () at lib.c:2481
#6  krm_init () at lib.c:2531
#7  0x0000400021494f00 in fj_pwr_krm_init (ops=0x400020b60070) at ./hpcpwr_fj_pwr_dev.c:1275
#8  0x00004000214925fc in pwr_arm64hpcdev_init (initstr=0x400007c7f2d0 "fj_pwr") at ./hpcpwr_main.c:36
#9  0x0000400002ce0f74 in PowerAPI::DistCntxt::initDevice(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) () from /lib64/libpwr.so.0
#10 0x0000400002ce2460 in PowerAPI::DistCntxt::traverse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, PWR_AttrName, std::vector<PowerAPI::Device*, std::allocator<PowerAPI::Device*> >&, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) () from /lib64/libpwr.so.0
#11 0x0000400002ce38bc in PowerAPI::DistCntxt::initAttr(PowerAPI::Object*, PWR_AttrName) () from /lib64/libpwr.so.0
#12 0x0000400002cd5dcc in PowerAPI::Object::Object(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, PWR_ObjType, PowerAPI::Cntxt*) () from /lib64/libpwr.so.0
#13 0x0000400002ce6210 in PowerAPI::DistObject::DistObject(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, PWR_ObjType, PowerAPI::Cntxt*) () from /lib64/libpwr.so.0
#14 0x0000400002cdfab0 in PowerAPI::DistCntxt::createObject(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, PWR_ObjType, PowerAPI::Cntxt*) () from /lib64/libpwr.so.0
#15 0x0000400002cd1b14 in PowerAPI::Cntxt::findObject(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int*) () from /lib64/libpwr.so.0
#16 0x0000400002ce1b28 in PowerAPI::DistCntxt::DistCntxt(int, PWR_Role, char const*) () from /lib64/libpwr.so.0
#17 0x0000400002ccc67c in PWR_CntxtInit () from /lib64/libpwr.so.0
#18 0x0000400002c89174 in hpx::performance_counters::power::power::init() ()
   from /vol0003/mdt0/data/hp210311/u10393/OctoTigerBuildChain/build/hpx/lib64/hpx/libhpx_power.so.1.8.0
--Type <RET> for more, q to quit, c to continue without paging--
#19 0x0000400000e5b1ac in hpx::components::server::runtime_support::call_startup_functions(bool) ()
   from /vol0003/mdt0/data/hp210311/u10393/OctoTigerBuildChain/build/hpx/lib64/libhpx.so.1
#20 0x0000400000e8adfc in hpx::lcos::local::detail::task_object<void, hpx::util::detail::deferred<hpx::detail::action_invoker<hpx::components::server::runtime_support::call_startup_functions_action>, hpx::util::pack_c<unsigned long, 0ul, 1ul, 2ul>, void*, int, bool>, void, hpx::lcos::detail::task_base<void> >::do_run() ()
   from /vol0003/mdt0/data/hp210311/u10393/OctoTigerBuildChain/build/hpx/lib64/libhpx.so.1
#21 0x0000400000d0d98c in std::pair<hpx::threads::thread_schedule_state, hpx::threads::thread_id> hpx::util::detail::callable_vtable<std::pair<hpx::threads::thread_schedule_state, hpx::threads::thread_id> (hpx::threads::thread_restart_state)>::_invoke<hpx::threads::detail::thread_function_nullary<hpx::util::detail::deferred<void (*)(hpx::intrusive_ptr<hpx::lcos::detail::task_base<void> >), hpx::util::pack_c<unsigned long, 0ul>, hpx::intrusive_ptr<hpx::lcos::detail::task_base<void> > > > >(void*, hpx::threads::thread_restart_state&&) ()
   from /vol0003/mdt0/data/hp210311/u10393/OctoTigerBuildChain/build/hpx/lib64/libhpx.so.1
#22 0x000040000106bf74 in hpx::threads::coroutines::detail::coroutine_impl::operator()() ()
   from /vol0003/mdt0/data/hp210311/u10393/OctoTigerBuildChain/build/hpx/lib64/libhpx_core.so
#23 0x000040000106b698 in void hpx::threads::coroutines::detail::generic_context::trampoline<hpx::threads::coroutines::detail::coroutine_impl>(boost::context::detail::transfer_t) ()
   from /vol0003/mdt0/data/hp210311/u10393/OctoTigerBuildChain/build/hpx/lib64/libhpx_core.so
#24 0x0000400001440b9c in make_fcontext ()
   from /vol0003/mdt0/data/hp210311/u10393/OctoTigerBuildChain/build/boost/lib/libboost_context.so.1.79.0
```

**Comment by hkaiser** [comment]
@diehlpk The stack back trace of your segfault seems to point to hwloc. Please make sure that HPX was built against the same version of hwloc as the power library is using.

**Comment by diehlpk** [comment]
@hkaiser using the correct hwloc and the power counter works.

**Review by diehlpk — DISMISSED** [review]
LGTM!

**Comment by hkaiser** [comment]
@diehlpk I would like for the power counters to be tested on the rostam CI instances. For that we need to fix the installation of that library there first. Once that's in place we will merge this PR.

**Comment by hkaiser** [comment]
bors merge

**Pull request merged**
