### PR TITLE
Test release and debug builds on Piz Daint

### PR DESCRIPTION
**Pull request by msimberg**

### CODE REVIEW

**Comment by msimberg** [comment]
retest cscs

**Comment by msimberg** [comment]
retest cscs

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

Just a question: why have you implemented this differently if compared to the LSU configuration

**Comment by msimberg** [comment]
> LGTM, thanks!
> 
> Just a question: why have you implemented this differently if compared to the LSU configuration

I have not, at least not intentionally. Where do you see differences?

The scripts could do with a bit of unification now, but they should do roughly the same thing. The only thing that I know is different is that on rostam we install HPX on `master` and `release`.

**Comment by hkaiser** [comment]
> The scripts could do with a bit of unification now, but they should do roughly the same thing. 

That's what I was referring to. On rostam the configuration scripts for the concrete CI directly refer to `${configuration_name}-${build_type}` while on PizDaint you use the combined `${configuration_name_with_build_type}`. No big deal, really...

**Comment by msimberg** [comment]
> That's what I was referring to. On rostam the configuration scripts for the concrete CI directly refer to `${configuration_name}-${build_type}` while on PizDaint you use the combined `${configuration_name_with_build_type}`. No big deal, really...

Could you link to it please? Both of them `export configuration_name_with_build_type="${configuration_name}-${build_type,,}"` and use that later on.

**Comment by hkaiser** [comment]
> > That's what I was referring to. On rostam the configuration scripts for the concrete CI directly refer to `${configuration_name}-${build_type}` while on PizDaint you use the combined `${configuration_name_with_build_type}`. No big deal, really...
> 
> Could you link to it please? Both of them `export configuration_name_with_build_type="${configuration_name}-${build_type,,}"` and use that later on.

You're right - I misremembered things. Please disregard my comment.

**Review by aurianer — APPROVED** [review]
LGTM thanks!

**Comment by msimberg** [comment]
Now it should *actually* use the build type. I didn't apply it earlier.

**Comment by msimberg** [comment]
Note: Piz Daint is in maintenance today... So no builds there at the moment.

**Comment by msimberg** [comment]
retest cscs

**Comment by msimberg** [comment]
I've disabled a GCC warning which seems to be bogus, and only appears with optimizations enabled in GCC 11. This wasn't there before since the gcc-newest configuration (which uses GCC 11 at the moment) was only built in debug mode.

**Pull request merged**
