### PR TITLE
Fixing use of for_loop with rebound execution policy (using `.with()`)

### PR DESCRIPTION
**Pull request by hkaiser**

### CODE REVIEW

**Comment by hkaiser** [comment]
From IRC:
```
[13:46]	Yorlik: hkaiser: Everything compiled. I can now work on ironing out minor
kinks in the entire system I think, like updating tests an other thinks. I just built the 
main application, but that's a great step now.
```

**Comment by gonidelis** [comment]
Should we merge this now?

**Comment by hkaiser** [comment]
retest

**Comment by hkaiser** [comment]
bors merge

**Pull request merged**
