### PR TITLE
Add unit test cases and fixes for the S/R versions of the parallel algorithms

### PR DESCRIPTION
**Pull request by zhekemist**
This PR has the goal of adding simple unit test cases for the S/R versions of HPX's parallel algorithms where they were previously missing, and to address the issues identified through these test. The fixes are currently based on NVIDIA's stdexec S/R implementation instead of HPX's own S/R implementation. (see [PR #6431](https://github.com/STEllAR-GROUP/hpx/pull/6431))

The algorithms addressed in this PR are tracked in [this document](https://docs.google.com/spreadsheets/d/1zbz88UZn912nLiBMbRaMTQTU2lT0vZRigui4jrcbIRA/edit?usp=sharing). Additionally, Issue #6535 was opened to track the algorithms not covered in this PR.

Note that the S/R unit tests for algorithms not yet fixed were removed to avoid cluttering the tests with unnecessary, guaranteed-to-fail test cases.  They were removed in commit [a20f1b4](https://github.com/STEllAR-GROUP/hpx/pull/6494/commits/a20f1b4da8e49de5d4380dd23a5c928525106768) and can be restored by reverting this commit if needed.

### CODE REVIEW

**Comment by hkaiser** [comment]
Wow... Just wow! Thanks a lot for your work on this!

**Comment by Pansysk75** [comment]
retest lsu

**Comment by isidorostsa** [comment]
@hkaiser could you enable testing?

**Comment by isidorostsa** [comment]
@zhekemist Should this be merged as is?

**Comment by hkaiser** [comment]
Yes, we can merge this. The CI problems are unrelated.

**Comment by hkaiser** [comment]
Thanks a  lot @zhekemist!

**Comment by isidorostsa** [comment]
Great work Tobias, thank you for this thorough and well documented contribution!

**Pull request merged**
