### PR TITLE
Segfault fix

### PR DESCRIPTION
**Pull request by ct-clmsn**
work to decrease false positive rate on SIGSEGV

### CODE REVIEW

**Comment by hkaiser** [comment]
This is related to #2987

**Comment by hkaiser** [comment]
@ct-clmsn now it's just inspect that is left unhappy: https://8895-4455628-gh.circle-artifacts.com/0/tmp/circle-artifacts.akV330g/hpx_inspect_report.html

**Comment by ct-clmsn** [comment]
@hkaiser for shame! thank you for the post! i've gone back and attempted to clean up all the formatting issues. hope to pass muster this go around.

**Comment by msimberg** [comment]
@ct-clmsn Thanks, looks good!

**Comment by ct-clmsn** [comment]
@msimberg Thanks, I hope this works and minimizes the false positive rate to something more reasonable. Are there other things that I should do for the pycicle-Build pycicle-Test failures?

**Comment by hkaiser** [comment]
@ct-clmsn I think those can be ignored for now as they are unrelated to your work and will be fixed independently.

**Pull request merged**
