### PR TITLE
Trivial relocation of c-v-ref-array types

### PR DESCRIPTION
**Pull request by isidorostsa**
This PR is an addition to the earlier https://github.com/STEllAR-GROUP/hpx/pull/6264

It allows peeling away type qualifiers to make sure that declaring type `T` as trivially relocatable will declare the following types too: 

`const T`, `volatile T`, `const volatile T`, `T&`, `T&&`, `T[]`, `T[n]`

### CODE REVIEW

**Review by hkaiser — DISMISSED** [review]
LGTM, thanks!

**Comment by isidorostsa** [comment]
> LGTM, thanks!

Thanks for reviewing, I am surprised there is not a simpler way to specialize all versions of a type at once

**Comment by hkaiser** [comment]
> > LGTM, thanks!
> 
> Thanks for reviewing, I am surprised there is not a simpler way to specialize all versions of a type at once

Well, there is, to some extent. You could write:
```
    namespace detail {

        template <typename T>
        struct is_trivially_relocatable<T> : std::is_trivially_copyable<T>
        {
        };
    }

    template <typename T>
    struct is_trivially_relocatable<T> : detail::is_trivially_relocatable<std::decay_t<T>>
    {
    };
```
In this case the user type specializations (the macros) would have to to map onto `hpx::detail::is_trivially_relocatable` instead of `hpx::is_trivially_relocatable`. However I'm not sure if this is a good idea.

**Comment by isidorostsa** [comment]
Oh that looks a lot cleaner, but I agree we could do without two `is_trivially_relocatable` traits :P 

Also just noting that `std::decay_t` would not work for this case because we want to transform `T[n] ->  T` instead of `T[n] -> T*`

**Comment by hkaiser** [comment]
@isidorostsa so let's go ahead with it as is, should we?

**Comment by isidorostsa** [comment]
Let me add some tests first and I think we are good

**Comment by hkaiser** [comment]
@isidorostsa once you fix the clang-format issues, this seems to be good to go.

**Comment by isidorostsa** [comment]
> @isidorostsa once you fix the clang-format issues, this seems to be good to go.

Will do, but let's discuss a bit on Thursday before merging

**Comment by hkaiser** [comment]
@isidorostsa there is still some clang-format problem, could you have a look, please?

**Comment by isidorostsa** [comment]
This will be integrated into #6314

**Pull request closed without merging**
