### PR TITLE
Refactoring async, apply, and dataflow APIs

### PR DESCRIPTION
**Pull request by hkaiser**
This is a stop-gap measure to workaround current issues on MSVC

### CODE REVIEW

**Comment by sithhell** [comment]
The changes look strange to me, but if they help for MSVC I have on objections.

**Comment by hkaiser** [comment]
> The changes look strange to me, but if they help for MSVC I have on objections.

Yes, @K-ballo said the same. The plan is to work on refactoring all of the `async` overloads to go through some kind of traits system which would allow to avoid the excessive use of SFINAE (same is true for `dataflow` and `future<>::then` as well - those are currently implemented using a similar SFINAE mess).

**Comment by sithhell** [comment]
Ok, do we have a ticket for that already?

**Comment by hkaiser** [comment]
> Ok, do we have a ticket for that already?

#1576

**Comment by hkaiser** [comment]
This PR is now ready for review and merging. It now fixes #1576 as discussed earlier.

**Comment by hkaiser** [comment]
After the last round of modifications the code compiles and runs fine on all platforms including MSVC. Please review now. The patch makes another two platforms in buildbot green.

**Pull request merged**
