### PR TITLE
Add Asio version check

### PR DESCRIPTION
**Pull request by msimberg**
Adds a version check for Asio. Sets the minimum to 1.12.0 which as far as I can tell should work. Before 1.12.0 `asio/io_context.hpp` didn't exist. I've also changed one of the CI configurations to use 1.12.0.

Flyby: Updated the list of required Boost libraries. This is a potential candidate for a 1.7.1 if we feel the need for it otherwise.

### CODE REVIEW

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by hkaiser** [comment]
> This is a potential candidate for a 1.7.1 if we feel the need for it otherwise.

Let's start collecting PRs that should potentially go into 1.7.1 here: https://github.com/STEllAR-GROUP/hpx/issues/5486

**Review by aurianer — APPROVED** [review]
LGTM thanks!

**Comment by msimberg** [comment]
I'll have to keep an eye on this: https://app.circleci.com/pipelines/github/STEllAR-GROUP/hpx/8417/workflows/12530766-565e-4890-9a35-a4838356e7bf/jobs/261330. It's for sure not from this PR, but I don't know yet if that's a regular failure or if the timeout just needs to be increased a bit. If someone happens to see anything relevant for this please let me know.

**Comment by msimberg** [comment]
The tag was wrong on the `gcc-8` config. I'd still like to wait for that to come back clean before merging this.

**Comment by msimberg** [comment]
retest cscs

**Comment by msimberg** [comment]
retest lsu

**Pull request merged**
