### PR TITLE
Enable migration of polymorphic components

### PR DESCRIPTION
**Pull request by hkaiser**

### CODE REVIEW

**Comment by hkaiser** [comment]
@bremerm31 Could you please verify whether this PR fixes your issues?

**Comment by bremerm31** [comment]
Has something changed in the build process recently? I'm not able to compile this branch. I've also attached the hpx cmake config output.
[hpx.config.txt](https://github.com/STEllAR-GROUP/hpx/files/3051870/hpx.config.txt)

```
[  0%] Building CXX object src/CMakeFiles/hpx.dir/exception.cpp.o
cd /work/02578/bremer/stampede2/dgswemv2_build_Debug_stampede2-skx/hpx/src && /opt/apps/gcc/7.1.0/bin/c++  -DDEBUG -DHPX_COMPONENT_NAME=hpx -DHPX_ENABLE_ASSERT_HANDLER -DHPX_EXPORTS -D_DEBUG -D_GNU_SOURCE -Dhpx_EXPORTS -I/work/02578/bremer/stampede2/hpx -isystem /opt/apps/gcc7_1/boost/1.64/include -I/work/02578/bremer/stampede2/dgswemv2_install_Debug_stampede2-skx/include -I/work/02578/bremer/stampede2/dgswemv2_build_Debug_stampede2-skx/hpx -I/opt/intel/compilers_and_libraries_2017.4.196/linux/mpi/intel64/include  -g -fPIC   -pthread -Wall -Wextra -Wno-unused-local-typedefs -Wno-strict-aliasing -Wno-sign-promo -Wno-attributes -Wno-cast-align -Wno-unused-parameter -Wformat=2 -Wno-format-nonliteral -Winit-self -Wdouble-promotion -Wcast-qual -Wcast-align -Werror=trampolines -Werror=parentheses -Werror=reorder -Werror=return-type -Werror=sequence-point -Werror=uninitialized -Werror=format -Werror=missing-braces -Werror=sign-compare -fdiagnostics-show-option -Werror=vla -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-maybe-uninitialized -Wno-sync-nand -Wno-delete-non-virtual-dtor -fvisibility=hidden -std=c++14 -o CMakeFiles/hpx.dir/exception.cpp.o -c /work/02578/bremer/stampede2/hpx/src/exception.cpp
In file included from /work/02578/bremer/stampede2/hpx/hpx/runtime/naming/name.hpp:12:0,
                 from /work/02578/bremer/stampede2/hpx/hpx/performance_counters/counters_fwd.hpp:12,
                 from /work/02578/bremer/stampede2/hpx/hpx/performance_counters/counters.hpp:10,
                 from /work/02578/bremer/stampede2/hpx/hpx/runtime.hpp:13,
                 from /work/02578/bremer/stampede2/hpx/src/exception.cpp:12:
/work/02578/bremer/stampede2/hpx/hpx/util/spinlock_pool.hpp:61:45: error: ‘HPX_HAVE_SPINLOCK_POOL_NUM’ was not declared in this scope
     template <typename Tag, std::size_t N = HPX_HAVE_SPINLOCK_POOL_NUM>
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
/work/02578/bremer/stampede2/hpx/hpx/util/spinlock_pool.hpp:61:45: note: suggested alternative: ‘HPX_HAVE_IO_POOL’
     template <typename Tag, std::size_t N = HPX_HAVE_SPINLOCK_POOL_NUM>
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                             HPX_HAVE_IO_POOL
In file included from /work/02578/bremer/stampede2/hpx/hpx/performance_counters/counters_fwd.hpp:12:0,
                 from /work/02578/bremer/stampede2/hpx/hpx/performance_counters/counters.hpp:10,
                 from /work/02578/bremer/stampede2/hpx/hpx/runtime.hpp:13,
                 from /work/02578/bremer/stampede2/hpx/src/exception.cpp:12:
/work/02578/bremer/stampede2/hpx/hpx/runtime/naming/name.hpp:378:40: error: template argument 2 is invalid
         typedef util::spinlock_pool<tag> internal_mutex_type;
                                        ^
/work/02578/bremer/stampede2/hpx/hpx/runtime/naming/name.hpp: In member function ‘bool hpx::naming::gid_type::acquire_lock()’:
/work/02578/bremer/stampede2/hpx/hpx/runtime/naming/name.hpp:383:46: error: qualified-id in declaration before ‘l’
             internal_mutex_type::scoped_lock l(this);
                                              ^
/work/02578/bremer/stampede2/hpx/hpx/runtime/naming/name.hpp: In member function ‘void hpx::naming::gid_type::relinquish_lock()’:
/work/02578/bremer/stampede2/hpx/hpx/runtime/naming/name.hpp:396:46: error: qualified-id in declaration before ‘l’
             internal_mutex_type::scoped_lock l(this);
                                              ^
make[2]: *** [src/CMakeFiles/hpx.dir/exception.cpp.o] Error 1
make[2]: Leaving directory `/work/02578/bremer/stampede2/dgswemv2_build_Debug_stampede2-skx/hpx'
make[1]: *** [src/CMakeFiles/hpx.dir/all] Error 2
make[1]: Leaving directory `/work/02578/bremer/stampede2/dgswemv2_build_Debug_stampede2-skx/hpx'
make: *** [all] Error 2
```

**Comment by hkaiser** [comment]
@bremerm31 This constant is defined here: https://github.com/STEllAR-GROUP/hpx/blob/master/CMakeLists.txt#L626-L630. You might want to delete your CMake cache file and try again.

**Comment by bremerm31** [comment]
Yup! Clearing out install directory fixed the compiler issue. This PR behaves as expected.

**Pull request merged**
