### PR TITLE
fix RPATH behaviour

### PR DESCRIPTION
**Pull request by neundorf**
Commit eaf73b9bd2c2e5ab04f3fc62e3bda2from Feb. 27th 2015 looks wrong.
It added the variable HPX_FULL_RPATH_DEFAULT, but did not make use of it.
This patch probably makes it behave as it was intended to behave, i.e.
different defaults on different platforms.

Alex

### CODE REVIEW

**Comment by sithhell** [comment]
Thanks, LGTM!

**Comment by neundorf** [comment]
Can this be merged ?

**Comment by neundorf** [comment]
my first hpx commit :-)

**Comment by hkaiser** [comment]
@neundorf that makes you eligible for a STE||AR-GROUP sticker! @aserio would be able to send you one (or two) if you got in contact with him.

**Comment by hkaiser** [comment]
@neundorf that makes you eligible for a STE||AR-GROUP sticker! @aserio would be able to send you one (or two) if you got in contact with him.

**Pull request merged**
