### PR TITLE
Adjust handling of CUDA/HIP options in CMake

### PR DESCRIPTION
**Pull request by msimberg**
Alternative to #5141. @biddisco could you check if the options behave the way you'd expect on this branch?

### CODE REVIEW

**Review by aurianer — APPROVED** [review]
Perfect thanks!

**Comment by aurianer** [comment]
Side note: there is an open PR to add hip-lang as a CMake module, this would allow to use `enable_language(HIP)` as it's already possible with CUDA

**Comment by msimberg** [comment]
> Side note: there is an open PR to add hip-lang as a CMake module, this would allow to use `enable_language(HIP)` as it's already possible with CUDA

Nice! Could you please link to that just for future reference?

Note I definitely missed a spot based on the CI results... I'll be pushing a fix for that soon.

**Comment by msimberg** [comment]
@biddisco did you get a chance to try this out/does it look reasonable to you?

**Review by biddisco — CHANGES_REQUESTED** [review]
```
cmake -DHPX_WITH_ASYNC_CUDA=ON -DHPX_WITH_CUDA_COMPUTE=OFF -DHPX_WITH_CUDA=OFF 
```
```
mak tests.unit.modules.async_cuda tests.performance.modules.async_cuda
ninja: error: unknown target 'tests.unit.modules.async_cuda'
```

**Comment by msimberg** [comment]
> ```
> cmake -DHPX_WITH_ASYNC_CUDA=ON -DHPX_WITH_CUDA_COMPUTE=OFF -DHPX_WITH_CUDA=OFF 
> ```
> 
> ```
> mak tests.unit.modules.async_cuda tests.performance.modules.async_cuda
> ninja: error: unknown target 'tests.unit.modules.async_cuda'
> ```

`HPX_WITH_CUDA=OFF` guards all CUDA functionality. You want `cmake -DHPX_WITH_CUDA=ON -DHPX_WITH_CUDA_COMPUTE=OFF`.

**Pull request merged**
