### PR TITLE
Add shift_left and shift_right algorithms

### LINKED ISSUE #3706: Add shift_left and shift_right algorithms
P0769 was accepted for C++20 (http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0769r2.pdf). This adds the `shift_left` and `shift_right` algorithms. We should implement those as part of our parallel algorithm module (see #1141).

See also for an exemplar (sequential) implementation of those here: https://github.com/danra/shift_proposal.

### PR DESCRIPTION
**Pull request by Jedi18**
Added shift_left and shift_right algorithms.

## Any background context you want to provide?
Closes #3706
Issue #4822

### CODE REVIEW

**Comment by hkaiser** [comment]
add to whitelist

**Review by hkaiser — DISMISSED** [review]
LGTM, thanks! Sorry this took so long.

**Comment by hkaiser** [comment]
@Jedi18 same here: could you please fix the conflict so we can go ahead and merge the PR?

**Comment by Jedi18** [comment]
Sorry dind't notice those. Fixed the formatting errors.

**Pull request merged**
