### PR TITLE
Barrier hang

### PR DESCRIPTION
**Pull request by sithhell**
This patch fixes a hang observed with certain usages of `hpx::lcos::barrier`.

Flybys:
 - Fixing one lock held during suspension error
 - Fixing race condition for pre caching localities

### CODE REVIEW

**Comment by atrantan** [comment]
Still got the issue. But to get this, multiple runs may be required (sometimes `barrier_hang.cpp` passes)

**Comment by hkaiser** [comment]
@atrantan how can we reproduce the issue? What compiler, Boost version, build type, etc.?

**Comment by atrantan** [comment]
Please find here the details related to the run : 
`{config}:
  HPX_HAVE_NATIVE_TLS=ON
  HPX_HAVE_STACKTRACES=ON
  HPX_HAVE_COMPRESSION_BZIP2=OFF
  HPX_HAVE_COMPRESSION_SNAPPY=OFF
  HPX_HAVE_COMPRESSION_ZLIB=OFF
  HPX_HAVE_PARCEL_COALESCING=ON
  HPX_HAVE_PARCELPORT_TCP=ON
  HPX_HAVE_PARCELPORT_MPI=ON (OpenMPI V1.6.5, MPI V2.1)
  HPX_HAVE_PARCELPORT_VERBS=OFF
  HPX_HAVE_VERIFY_LOCKS=OFF
  HPX_HAVE_HWLOC=ON
  HPX_HAVE_ITTNOTIFY=OFF
  HPX_HAVE_RUN_MAIN_EVERYWHERE=OFF
  HPX_PARCEL_MAX_CONNECTIONS=512
  HPX_PARCEL_MAX_CONNECTIONS_PER_LOCALITY=4
  HPX_AGAS_LOCAL_CACHE_SIZE=4096
  HPX_HAVE_MALLOC=tcmalloc
  HPX_PREFIX (configured)=/home/atrantan/hpx-fork/build-gcc
  HPX_PREFIX=/home/atrantan/hpx-fork/build-gcc
{version}: V1.1.0 (AGAS: V3.0), Git: ba8b2b15eb
{boost}: V1.59.0
{build-type}: release
{date}: May  1 2017 09:14:45
{platform}: linux
{compiler}: GNU C++ version 4.9.2
{stdlib}: GNU libstdc++ version 20141220
`

**Comment by sithhell** [comment]
How do you run it? How many localities, how many threads per localities?

Am 01.05.2017 4:22 nachm. schrieb "atrantan" <notifications@github.com>:

**Comment by atrantan** [comment]
@sithhell Obviously, one hpx-main, 4 localities, one thread per locality

**Comment by sithhell** [comment]
The hangs should be gone now.

**Pull request merged**
