### PR TITLE
Fix scheduler related configuration values

### PR DESCRIPTION
**Pull request by msimberg**
Fixes some very bad configuration values related to scheduler stealing etc. This was bad copy-pasting by me.

### CODE REVIEW

**Comment by msimberg** [comment]
@kordejong these are probably causing at least part your weird traces. These are also values you can play around with as I don't think we've put too much effort into finding optimal values (and they'll likely vary by application). You can change them with `--hpx:ini=hpx.thread_queue.<option_name>=X`.

**Comment by msimberg** [comment]
@hkaiser this is a clear regression since the last release, so this would be good to have in 1.4.0.

**Comment by msimberg** [comment]
This also revealed a problem in how agent storage was handled (i.e. not handled) in embedded schedulers. I think it's as simple as the fix I've proposed (reset the `context_storage` variable in the scheduling loop after the embedded scheduler has yielded to the parent scheduler). The previously failing tests now pass again, but I'll wait to see if this introduces other problems.

**Comment by msimberg** [comment]
> Interesting... I was not aware that the `context_storage` may change during execution of the callbacks...

It's the thread stealing. The faulty config values essentially prohibited thread stealing, and with that fixed the embedded scheduler worker threads can get stolen while suspended. When they wake up they use the storage of the wrong OS thread.

**Comment by hkaiser** [comment]
Nice catch!

**Pull request merged**
