### PR TITLE
[hpx::execution] Added forwarding_scheduler_query

### PR DESCRIPTION
**Pull request by SAtacker**
Signed-off-by: Shreyas Atre <shreyasatre16@gmail.com>

## Proposed Changes

- [X] [forwarding_scheduler_query](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2300r4.html#spec-execution.schedulers.queries.forwarding_scheduler_query)
- [x] [get_forward_progress_guarantee](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2300r4.html#spec-execution.schedulers.queries.get_forward_progress_guarantee)
- [x] [this_thread::execute_may_block_caller](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2300r4.html#spec-execution.schedulers.queries.execute_may_block_caller)

## Checklist

- [X] Unit test - forwarding_scheduler_query
- [x] Unit test - get_forward_progress_guarantee
- [x] Unit test - execute_may_block_caller

### CODE REVIEW

**Comment by hkaiser** [comment]
Please ignore the clang 14 builder problems, those are unrelated

**Comment by hkaiser** [comment]
@SAtacker could you please fix the issues reported by inspect:

/libs/core/execution/include/hpx/execution/queries/get_scheduler.hpp: *Line length limit*: [64](https://github.com/STEllAR-GROUP/hpx/blob/3a77b2da29e933a3da2a47cf51fb2ef2e590c985/libs/core/execution/include/hpx/execution/queries/get_scheduler.hpp#L64)
/libs/core/execution_base/include/hpx/execution_base/this_thread.hpp: *Line length limit*: [75](https://github.com/STEllAR-GROUP/hpx/blob/3a77b2da29e933a3da2a47cf51fb2ef2e590c985/libs/core/execution_base/include/hpx/execution_base/this_thread.hpp#L75), [84](https://github.com/STEllAR-GROUP/hpx/blob/3a77b2da29e933a3da2a47cf51fb2ef2e590c985/libs/core/execution_base/include/hpx/execution_base/this_thread.hpp#L84), [90](https://github.com/STEllAR-GROUP/hpx/blob/3a77b2da29e933a3da2a47cf51fb2ef2e590c985/libs/core/execution_base/include/hpx/execution_base/this_thread.hpp#L90)

?

**Comment by SAtacker** [comment]
> @SAtacker could you please fix the issues reported by inspect:
> 
> /libs/core/execution/include/hpx/execution/queries/get_scheduler.hpp: _Line length limit_: [64](https://github.com/STEllAR-GROUP/hpx/blob/3a77b2da29e933a3da2a47cf51fb2ef2e590c985/libs/core/execution/include/hpx/execution/queries/get_scheduler.hpp#L64) /libs/core/execution_base/include/hpx/execution_base/this_thread.hpp: _Line length limit_: [75](https://github.com/STEllAR-GROUP/hpx/blob/3a77b2da29e933a3da2a47cf51fb2ef2e590c985/libs/core/execution_base/include/hpx/execution_base/this_thread.hpp#L75), [84](https://github.com/STEllAR-GROUP/hpx/blob/3a77b2da29e933a3da2a47cf51fb2ef2e590c985/libs/core/execution_base/include/hpx/execution_base/this_thread.hpp#L84), [90](https://github.com/STEllAR-GROUP/hpx/blob/3a77b2da29e933a3da2a47cf51fb2ef2e590c985/libs/core/execution_base/include/hpx/execution_base/this_thread.hpp#L90)
> 
> ?

Thanks. This should be done in clang-format right? I have it as a commit hook as well as I did it manually but it doesn't change.

**Comment by hkaiser** [comment]
> Thanks. This should be done in clang-format right? I have it as a commit hook as well as I did it manually but it doesn't change.

clang-format doesn't touch comments (see: https://github.com/STEllAR-GROUP/hpx/blob/master/.clang-format#L107), you will have to handle this manually.

**Comment by hkaiser** [comment]
@msimberg all of the CSCS builders seem to fail. Has something changed in the setup?

**Comment by msimberg** [comment]
> @msimberg all of the CSCS builders seem to fail. Has something changed in the setup?

Nothing that I'm aware of. The logs seem to say that the jobs timed out, which smells a bit like a transient slurm problem. Other jobs that were launched around the same time (and later) seem to have been started and run just fine.

**Comment by msimberg** [comment]
retest cscs

**Review by hkaiser — APPROVED** [review]
The CSCS builders are fine now. 
LGTM, thanks!

**Comment by hkaiser** [comment]
The failure that prevented bors from merging is a known one. Merging manually...

**Comment by SAtacker** [comment]
> The failure that prevented bors from merging is a known one. Merging manually...

Thanks for reviewing.

**Pull request merged**
