### PR TITLE
Fixing build if HPX_WITH_PARCELPORT_ACTION_COUNTERS=On

### LINKED ISSUE #4950: Build with `HPX_WITH_PARCELPORT_ACTION_COUNTERS` `ON` fails
## Expected Behavior

Build succeeds.

## Actual Behavior

Build fails: [build.txt](https://github.com/STEllAR-GROUP/hpx/files/5187178/build.txt)

## Steps to Reproduce the Problem

I built HPX with the following settings:
````
HPX_WITH_PARCELPORT_ACTION_COUNTERS ON                                                                     
HPX_WITH_THREAD_IDLE_RATES ON                                                                              
HPX_WITH_APEX ON                                                                                           
HPX_WITH_PAPI ON                                                                                               
HPX_WITH_MALLOC "tcmalloc"                                                                                     
HPX_WITH_HWLOC ON                                                                                              
HPX_WITH_GOOGLE_PERFTOOLS ON                                                                                   
HPX_WITH_MAX_CPU_COUNT "96"                                                                                    
HPX_WITH_PARCELPORT_TCP ON                                                                                     
HPX_WITH_PARCELPORT_MPI ON                                                                                     
HPX_WITH_PARCELPORT_MPI_MULTITHREADED ON                                                                       
APEX_WITH_OTF2 ON                                                                                              
APEX_WITH_PAPI ON
````

When turning `HPX_WITH_PARCELPORT_ACTION_COUNTERS OFF`, the build succeeds.

## Specifications

  - HPX Version: 1.5.0
  - Platform (compiler, OS): Linux, gcc-10, openmpi 4.0.4

### PR DESCRIPTION
**Pull request by hkaiser**
Fixes #4950

@kordejong this should fix the problem you reported.

@msimberg could you suggest one of the builders we could use to enable `HPX_WITH_PARCELPORT_ACTION_COUNTERS` to avoid similar issues in the future?

### CODE REVIEW

**Comment by msimberg** [comment]
Thanks @hkaiser! E.g. `gcc-oldest` or `clang-newest` (on daint at least) would work well (`gcc-newest` has the distributed runtime off, `clang-oldest` networking off). Any on rostam as well, but since that still needs some work we should stick to daint. Are there other optional counters that should be turned on for CI?

**Comment by hkaiser** [comment]
> Thanks @hkaiser! E.g. `gcc-oldest` or `clang-newest` (on daint at least) would work well (`gcc-newest` has the distributed runtime off, `clang-oldest` networking off). Any on rostam as well, but since that still needs some work we should stick to daint. 

Ok, I'll go with `clang-newest`, then.

> Are there other optional counters that should be turned on for CI?

There is `HPX_WITH_THREAD_IDLE_RATES`, `HPX_WITH_THREAD_CREATION_AND_CLEANUP_RATES`, `HPX_WITH_THREAD_CUMULATIVE_COUNTS` (I think this one is `ON` by default), and `HPX_WITH_THREAD_STEALING_COUNTS`. I'll enable those as well on the same builder.

**Comment by hkaiser** [comment]
FWIW, there is also `HPX_WITH_COROUTINE_COUNTERS`.

**Comment by hkaiser** [comment]
@msimberg I have rebased this onto master, let's see how it goes. I think we should be able to merge this.

**Comment by msimberg** [comment]
Thanks @hkaiser, did a rebase here as well to get the fix for the rostam builders. There a two more member functions that needed an `override`. Let's merge if this is clean after this.

**Comment by hkaiser** [comment]
> Thanks @hkaiser, did a rebase here as well to get the fix for the rostam builders. There a two more member functions that needed an `override`. Let's merge if this is clean after this.

Done. Thanks!

**Pull request merged**
