### PR TITLE
Fixing #1748

### LINKED ISSUE #1748: All public HPX headers need to be self contained
This is to finish the work in #1710

### PR DESCRIPTION
**Pull request by sithhell**
This PR fixes #1748 by making all public headers self contained. In addition, the non-used value_logger facility has been removed.

### CODE REVIEW

**Comment by hkaiser** [comment]
LGTM, thanks. Can we enable the header tests on one or two of the buildbot builders now?

**Comment by sithhell** [comment]
On 10/28/2015 06:39 PM, Hartmut Kaiser wrote:
> LGTM, thanks. Can we enable the header tests on one or two of the
> buildbot builders now?

They are enabled by default now with this changeset.

**Comment by hkaiser** [comment]
> They are enabled by default now with this changeset.

Should we really build those with every builder? That easily doubles the build times...

**Comment by sithhell** [comment]
We should at least have it enabled on circle ci. But you are right... it should probably only enabled on a few testers.

**Comment by hkaiser** [comment]
@sithhell agreed, let's enable it for circelci, that should be sufficient

**Comment by sithhell** [comment]
The remaining failures should be gone now.

**Comment by sithhell** [comment]
Can we merge this now?

**Comment by hkaiser** [comment]
Please go ahead merging this.

**Pull request merged**
