### PR TITLE
Renaming vector

### PR DESCRIPTION
**Pull request by hkaiser**
This is  renaming hpx::vector to hpx::deque

- the rationale is that this data structure does not store its elements sequentially
  in memory, but in non-contiguous segments

### CODE REVIEW

**Comment by hkaiser** [comment]
Another new name which was suggested for the current `hpx::vector` would be `hpx::distributed_array`. I'm open to suggestions here.

**Comment by dcbdan** [comment]
What about `hpx::distributed_vector`? Do operations on the container have the same complexity as `std::deque`?

**Comment by hkaiser** [comment]
@dcbdan Well, the point is that vectors manage contiguous memory, `hpx::vector` does not. Wouldn't it be misleading if we called it `hpx::distributed_vector`?

**Comment by dcbdan** [comment]
In a sense, `hpx::distributed_vector` would be an oxymoron. But if each local part manages contiguous memory, the name seems explanatory. What operations are best supported for the container to be named and could that help naming it?

**Comment by hkaiser** [comment]
@dcbdan: good points! However, I'm thinking that `hpx::segmented_vector` or `hpx::partitioned_vector` would be more fitting. The partitions don't have to be distributed after all.

**Comment by biddisco** [comment]
+1 for

hpx::partitioned_vector

(or even

hpx::partitioned::vector)

**Comment by sithhell** [comment]
Am 21.08.2015 10:29 vorm. schrieb "John Biddiscombe" <
notifications@github.com>:
>
> +1 for
>
> hpx::partitioned_vector

I like that name. The only disadvantage with that name I could currently
imagine that people might get the impression that it's resizable, though
iiuc, that's planned to be implemented sooner or later.

**Comment by hkaiser** [comment]
Ok, `hpx::partitioned_vector` it is. And yes we plan to make it resizable.

**Pull request merged**
