### PR TITLE
Update exception_list.hpp

### PR DESCRIPTION
**Pull request by aksl4**
This update refines the exception_list class in the HPX namespace by addressing threading and copy/move semantics. The class acts as a container for std::exception_ptr objects, allowing parallel algorithms to store and manage exceptions encountered during execution.

Proposed Changes
Updated mutex_type to use hpx::util::detail::spinlock for thread-safe access.
Added explicit base class copy constructor call in the exception_list copy constructor to avoid clang-tidy warnings and ensure correct initialization.
Retained comments for clarity, explaining the purpose of each function and threading concerns.
Added thread-safe copy and move constructors and assignment operators to safely handle the exception_list in parallel contexts.
Any background context you want to provide?
The changes ensure that exception_list is compatible with HPX's threading requirements and avoids issues with clang-tidy by correctly calling the base class copy constructor. These modifications make the class more robust for use in concurrent environments where exceptions from parallel algorithms need to be collected and managed reliably.

Checklist
 I have added a new feature and have added tests to go along with it.
 I have fixed a bug and have added a regression test.
 I have run clang-format to ensure consistent code style.
 I have checked that all functions have thread-safe access, where applicable.
 I have reviewed the CI output to ensure there are no clang-tidy or clang warnings.
 I have documented my code, where needed, for clarity and maintenance.

### CODE REVIEW

**Comment by aksl4** [comment]
Hii,
Just want to know how to test this on local machine

**Comment by hkaiser** [comment]
> Hii, Just want to know how to test this on local machine

Build HPX locally and run the tests you're interested in locally as well.

**Comment by aksl4** [comment]
> > Hii, Just want to know how to test this on local machine
> 
> Build HPX locally and run the tests you're interested in locally as well.

so i got this in my local machine, just wanted to know what's the command to run them or please help me find the documentation on running this tests locally

**Comment by hkaiser** [comment]
> > > Hii, Just want to know how to test this on local machine
> > 
> > 
> > Build HPX locally and run the tests you're interested in locally as well.
> 
> so i got this in my local machine, just wanted to know what's the command to run them or please help me find the documentation on running this tests locally

All tests are located in your `<build>/bin` directory (or if you install HPX -- which I wouldn't suggest while debugging things -- in `<installdir>/bin`). Simply start them as you see fit.

**Pull request closed without merging**
