### PR TITLE
Avoid holding a lock during agas::incref while doing a credit split

### PR DESCRIPTION
**Pull request by sithhell**

### CODE REVIEW

**Comment by hkaiser** [comment]
Do all tests pass for this?

**Comment by sithhell** [comment]
Yes, all tests pass.

**Comment by hkaiser** [comment]
I'm still not convinced that competing `incref` requests do not lead to out of order `decref` requests, especially when several localities are involved. I'm hesitant to agree to merging this.

**Comment by sithhell** [comment]
I am. I successfully ran `hello_world` on several numbers of localities: 2, 4, 8, 16, 32, 64, 128, 256 and 512. Hello world ran successfully ten times on each number of localities. Note that `hello_world` requires credit splitting with 16 localities and up. I didn't have a single failure. How do you think out of order decrefs might happen?

**Comment by hkaiser** [comment]
Ok, I'm not able to think of anything bad at this point. Let's go ahead and merge this. I'll keep an eye open, though.

**Pull request merged**
