### PR TITLE
Adding performance test Jenkins builder at LSU

### PR DESCRIPTION
**Pull request by hkaiser**

### CODE REVIEW

**Comment by hkaiser** [comment]
@Pansysk75 perfect! This seems to work as expected now! Thanks a lot!

**Comment by Pansysk75** [comment]
> @Pansysk75 perfect! This seems to work as expected now! Thanks a lot!

I think the above StellarBot comment was from the Daint cluster and not from Rostam. The Rostam Jenkins has't picked up on it yet, maybe it needs a " retest "?

**Comment by Pansysk75** [comment]
retest

**Comment by Pansysk75** [comment]
retest lsu

**Comment by Pansysk75** [comment]
@hkaiser 
Ok, it seems to work all the way through. The report results seem a bit off, I'll need to check whether that's due to general inconsistency or due to a bad performance reference.

**Comment by hkaiser** [comment]
> Ok, it seems to work all the way through. 

Great!

> The report results seem a bit off, I'll need to check whether that's due to general inconsistency or due to a bad performance reference.

The current reference contained in this PR was copied from the Daint performance tests. We need to create a new reference set based on the data collected on Rostam.

**Comment by hkaiser** [comment]
@Pansysk75 also, please let me know once you think that this can be merged.

**Comment by hkaiser** [comment]
Let's merge this now. It might need more work, however.

**Comment by hkaiser** [comment]
bors merge

**Pull request merged**
