### PR TITLE
Update ROCm to 4.0.1 on Rostam

### PR DESCRIPTION
**Pull request by aurianer**
I compiled fine locally on Rostam, let's see what CI says

### CODE REVIEW

**Review by hkaiser — DISMISSED** [review]

**Comment by aurianer** [comment]
retest

**Comment by aurianer** [comment]
There is still one failing test for hipcc-debug but I think we can merge this since it improves a lot master (cf the [build failures](https://cdash.cscs.ch/buildSummary.php?buildid=149408))

**Comment by msimberg** [comment]
retest lsu

**Comment by msimberg** [comment]
There was a temporary timeout on one of the CUDA/HIP tests on this PR that did not repeat when this was retriggered. Let's go ahead with this since neither @aurianer or I could reproduce it, but let's keep an eye out for timeouts like that on master. Thanks @aurianer for updating this!

**Pull request merged**
