### PR TITLE
Adding missing #includes to fix gcc V10 linker problems

### LINKED ISSUE #4320: HPX 1.4.0 does not compile with gcc 10
## Expected Behavior

HPX 1.4.0 should compile with gcc 10

## Actual Behavior

https://koji.fedoraproject.org/koji/getfile?taskID=40822717&volume=DEFAULT&name=build.log

## Steps to Reproduce the Problem

  1. Build HPX 1.4.0 using gcc 10

## Specifications

... Please describe your environment

  - HPX Version: 1.4.1
  - Platform (compiler, OS): Fedora rawhide, gcc 10

### PR DESCRIPTION
**Pull request by hkaiser**
- flyby: clean up -fPIC option

Fixes #4320

### CODE REVIEW

**Comment by hkaiser** [comment]
@msimberg once this is confirmed to fix the Fedora32/gcc10 issue we can go ahead with the V1.4.1 point release, I think.

**Comment by diehlpk** [comment]
Patch build on Fedora https://koji.fedoraproject.org/koji/taskinfo?taskID=41304526

**Comment by hkaiser** [comment]
@diehlpk I confirm the issue - working on a fix as we speak.

**Comment by diehlpk** [comment]
[ 67%] Linking CXX executable ../../../bin/async_customization
cd /builddir/build/BUILD/hpx-1.4.0/serial/libs/resource_partitioner/examples && /usr/bin/cmake -E cmake_link_script CMakeFiles/async_customization.dir/link.txt --verbose=1
/usr/bin/c++  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DNDEBUG  -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-z,defs -fvisibility=hidden CMakeFiles/async_customization.dir/async_customization.cpp.o  -o ../../../bin/async_customization  -Wl,-rpath,/builddir/build/BUILD/hpx-1.4.0/serial/lib: ../../../lib/libhpx_init.a ../../../lib/libhpx_wrap.a ../../../lib/libhpx.so.1.4.0 /usr/lib64/libboost_system.so -lpthread /usr/lib64/libboost_program_options.so /usr/lib64/libtcmalloc_minimal.so /usr/lib64/libhwloc.so -latomic -ldl -lrt -Wl,-wrap=main 
make[2]: Leaving directory '/builddir/build/BUILD/hpx-1.4.0/serial'
/usr/bin/ld: ../../../lib/libhpx.so.1.4.0: undefined reference to `bool hpx::detail::apply_impl<hpx::lcos::base_lco_with_value<hpx::naming::id_type, hpx::naming::gid_type, hpx::traits::detail::component_tag>::set_value_action, hpx::naming::gid_type>(hpx::naming::id_type const&, hpx::naming::address&&, hpx::threads::thread_priority, hpx::naming::gid_type&&)'
/usr/bin/ld: ../../../lib/libhpx.so.1.4.0: undefined reference to `bool hpx::detail::apply_impl<hpx::lcos::base_lco_with_value<unsigned int, unsigned int, hpx::traits::detail::managed_component_tag>::set_value_action, unsigned int>(hpx::naming::id_type const&, hpx::naming::address&&, hpx::threads::thread_priority, unsigned int&&)'
/usr/bin/ld: ../../../lib/libhpx.so.1.4.0: undefined reference to `bool hpx::detail::apply_impl<hpx::lcos::base_lco_with_value<std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, hpx::parcelset::locality, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, hpx::parcelset::locality> > >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, hpx::parcelset::locality, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, hpx::parcelset::locality> > >, hpx::traits::detail::component_tag>::set_value_action, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, hpx::parcelset::locality, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, hpx::parcelset::locality> > > >(hpx::naming::id_type const&, hpx::naming::address&&, hpx::threads::thread_priority, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, hpx::parcelset::locality, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, hpx::parcelset::locality> > >&&)'
/usr/bin/ld: ../../../lib/libhpx.so.1.4.0: undefined reference to `bool hpx::detail::apply_impl<hpx::lcos::base_lco_with_value<std::vector<unsigned int, std::allocator<unsigned int> >, std::vector<unsigned int, std::allocator<unsigned int> >, hpx::traits::detail::managed_component_tag>::set_value_action, std::vector<unsigned int, std::allocator<unsigned int> > >(hpx::naming::id_type const&, hpx::naming::address&&, hpx::threads::thread_priority, std::vector<unsigned int, std::allocator<unsigned int> >&&)'
/usr/bin/ld: ../../../lib/libhpx.so.1.4.0: undefined reference to `bool hpx::detail::apply_impl<hpx::lcos::base_lco_with_value<unsigned int, unsigned int, hpx::traits::detail::component_tag>::set_value_action, unsigned int>(hpx::naming::id_type const&, hpx::naming::address&&, hpx::threads::thread_priority, unsigned int&&)'
/usr/bin/ld: ../../../lib/libhpx.so.1.4.0: undefined reference to `bool hpx::detail::apply_impl<hpx::lcos::base_lco_with_value<std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, hpx::parcelset::locality, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, hpx::parcelset::locality> > >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, hpx::parcelset::locality, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, hpx::parcelset::locality> > >, hpx::traits::detail::managed_component_tag>::set_value_action, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, hpx::parcelset::locality, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, hpx::parcelset::locality> > > >(hpx::naming::id_type const&, hpx::naming::address&&, hpx::threads::thread_priority, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, hpx::parcelset::locality, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, hpx::parcelset::locality> > >&&)'
```
/usr/bin/ld: ../../../lib/libhpx.so.1.4.0: undefined reference to `bool hpx::detail::apply_impl<hpx::lcos::base_lco_with_value<hpx::naming::id_type, hpx::naming::gid_type, hpx::traits::detail::managed_component_tag>::set_value_action, hpx::naming::gid_type>(hpx::naming::id_type const&, hpx::naming::address&&, hpx::threads::thread_priority, hpx::naming::gid_type&&)'
/usr/bin/ld: ../../../lib/libhpx.so.1.4.0: undefined reference to `bool hpx::detail::apply_impl<hpx::lcos::base_lco_with_value<std::vector<unsigned int, std::allocator<unsigned int> >, std::vector<unsigned int, std::allocator<unsigned int> >, hpx::traits::detail::component_tag>::set_value_action, std::vector<unsigned int, std::allocator<unsigned int> > >(hpx::naming::id_type const&, hpx::naming::address&&, hpx::threads::thread_priority, std::vector<unsigned int, std::allocator<unsigned int> >&&)'
collect2: error: ld returned 1 exit status
```

**Comment by hkaiser** [comment]
> https://koji.fedoraproject.org/koji/taskinfo?taskID=41313384
> @hkaiser Your latest commit results in this linking error

Hmmm. Those are the errors that I believed to have fixed. The missing symbols are the same as the ones that were missing for the other failing tests before.

**Comment by diehlpk** [comment]
> > https://koji.fedoraproject.org/koji/taskinfo?taskID=41313384
> > @hkaiser Your latest commit results in this linking error
> 
> Hmmm. Those are the errors that I believed to have fixed. The missing symbols are the same as the ones that were missing for the other failing tests before.

@hkaiser I did a new build and now the gcc build succeeded on x86 and we have to wait for the openmpi and mpich builds. I do not know why, but now the latest patch was applied. 

https://koji.fedoraproject.org/koji/taskinfo?taskID=41313541

**Comment by diehlpk** [comment]
@hkaiser Latest build was successfully and the commit can be merge into master

**Pull request merged**
