### PR TITLE
Fixing for local executions of actions to properly set task names

### PR DESCRIPTION
**Pull request by hkaiser**

### CODE REVIEW

**Review by msimberg — APPROVED** [review]
Looks good, thanks!

**Comment by msimberg** [comment]
I suppose the `apex_action_count` test might need updating after this fix: https://cdash.cscs.ch/testDetails.php?test=51364877&build=180058?

**Comment by hkaiser** [comment]
> I suppose the `apex_action_count` test might need updating after this fix: https://cdash.cscs.ch/testDetails.php?test=51364877&build=180058?

Uhhh, would you be able to do that? I have no APEX setup available easily. Thanks for noticing.

**Comment by msimberg** [comment]
@hkaiser I've just updated the count in the test. I suppose the fix here was part of the "some reason" (https://github.com/STEllAR-GROUP/hpx/blob/30f47ed5ea8622bf526ee0080d276f73142f2be2/tests/unit/apex/apex_action_count.cpp#L108) for the count being off. It's still off by one, so is it possible that some other action names aren't being set?

**Comment by hkaiser** [comment]
> @hkaiser I've just updated the count in the test. I suppose the fix here was part of the "some reason" (
> 
> https://github.com/STEllAR-GROUP/hpx/blob/30f47ed5ea8622bf526ee0080d276f73142f2be2/tests/unit/apex/apex_action_count.cpp#L108
> 
> ) for the count being off. It's still off by one, so is it possible that some other action names aren't being set?

Not sure why, I'll try to have a look.

**Comment by msimberg** [comment]
We decided to leave the final missing task name for a future investigation. This is already an improvement so merging.

**Pull request merged**
