### PR TITLE
Moving is_relocatable to namespace hpx

### PR DESCRIPTION
**Pull request by hkaiser**
Fixes compilation problems on master

### CODE REVIEW

**Comment by hkaiser** [comment]
@isidorostsa please verify that this is ok.

**Comment by isidorostsa** [comment]
It looks good to me! Should I also change the unit test to look for hpx::traits::is_relocatable<>?

**Comment by hkaiser** [comment]
> It looks good to me! Should I also change the unit test to look for hpx::traits::is_relocatable<>?

I think we should keep the trait as `hpx::is_relocatable` for compatibility with the standard.

**Comment by isidorostsa** [comment]
> > It looks good to me! Should I also change the unit test to look for hpx::traits::is_relocatable<>?
> 
> I think we should keep the trait as `hpx::is_relocatable` for compatibility with the standard.

I completely agree with that

**Comment by hkaiser** [comment]
bors merge

**Pull request merged**
