### PR TITLE
Investigate the failure of the LCI parcelport.

### PR DESCRIPTION
**Pull request by JiakunYan**

### CODE REVIEW

**Comment by JiakunYan** [comment]
@hkaiser I think I have fixed the LCI parcelport.

**Comment by hkaiser** [comment]
@JiakunYan very nice, thanks! What was the issue?

**Comment by JiakunYan** [comment]
@hkaiser A problem on the LCI side. A dumb bug. When you asked me to fix the compilation error "non-void function doesn't have return value", I fixed it in the wrong way. It leads to some function calls being skipped when compilation. The reason it took me so long to reproduce the bug is it only went wrong when LCI_DEBUG=OFF.

**Comment by hkaiser** [comment]
> @hkaiser A problem on the LCI side. A dumb bug. When you asked me to fix the compilation error "non-void function doesn't have return value", I fixed it in the wrong way. It leads to some function calls being skipped when compilation. The reason it took me so long to reproduce the bug is it only went wrong when LCI_DEBUG=OFF.

I'm glad you caught it!

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by hkaiser** [comment]
bors merge

**Pull request merged**
