### PR TITLE
Fix HPX-APEX cmake integration

### PR DESCRIPTION
**Pull request by srinivasyadav18**
Existing apex cmake integration does not work for external Apex installation.

This fix seperates the git fetch installation using HPX_WITH_FETCH_APEX and external installation using Apex_ROOT, cmake variables respectively.

### CODE REVIEW

**Review by hkaiser — DISMISSED** [review]
LGTM, thanks!

**Comment by hkaiser** [comment]
This makes some of the builders fail: 

- https://github.com/STEllAR-GROUP/hpx/actions/runs/6065900150/job/16455889171?pr=6342
- https://app.circleci.com/pipelines/github/STEllAR-GROUP/hpx/15729/workflows/5b3db204-05da-4776-b9c2-814f42beb9c7/jobs/361491

**Comment by srinivasyadav18** [comment]
> Details



> This makes some of the builders fail:
> 
> * https://github.com/STEllAR-GROUP/hpx/actions/runs/6065900150/job/16455889171?pr=6342
> * https://app.circleci.com/pipelines/github/STEllAR-GROUP/hpx/15729/workflows/5b3db204-05da-4776-b9c2-814f42beb9c7/jobs/361491

@hkaiser I have fixed the issues. I think it is now ready to be merged. Please review it. Thank you!

**Comment by srinivasyadav18** [comment]
> @srinivasyadav18 the cmake formatting needs some touching up, still

I have just rebased the branch. That fixed the issue. Thanks!

**Comment by hkaiser** [comment]
bors merge

**Pull request merged**
