### PR TITLE
Parallel heap algorithm implementations WIP

### PR DESCRIPTION
**Pull request by Syntaf**
Implementation moving forward from #1888 , still WIP so this PR is for code review and inspect.

To-Do:
- [ ] Write `is_heap`, `is_heap_until`
- [ ] Benchmark algorithms to test performance
- [ ] Determine how chunk size should interact within these algorithms, as the chunk size is not guaranteed in [level based parallelism](http://drobilla.net/papers/Parallel_C++_STL_Heap_Building.pdf)
- [ ] Decide whether to create practitioners for these algorithms, or leave the implementation within the algorithm itself. 

Currently:
- `make_heap` algorithm is implemented and all tests pass

### CODE REVIEW

**Comment by hkaiser** [comment]
@Syntaf: what's the status of this work?

**Comment by Syntaf** [comment]
@hkaiser All of the tests pass and the algorithms work, but I ran out of time to benchmark them and refine their implementation. A couple things to note

* I don't believe settings the chunk size via executor works, it currently splits it events among partitions and additionally divides it by 2. I chose to divide by some constant because an evenly partitioned set with the amount of cores would almost all be run sequentially in the heap algorithms. 
* If the amount of items in a level is less than the chunk size, it is run sequentially 
* I had to overload the `parallel` function in both `is_heap` and `make_heap` to account for throwing exceptions within futures, other than that their implementation is identical. 

I created two functions inside of `parallel/util/detail/chunk_size.hpp` , `get_bottomup_heap_bulk_iteration_shape` and `get_topdown_heap_bulk_iteration_shape`. Both of these functions return a *shape* vector as the other chunk_size functions do, and runs any sequential work (if the level is less than the chunk_size). The difference is that they do not partition the level, they only return what levels **can** be parallelized. So inside `parallel` I loop through the shape and chunk/execute the items, this is because each element in *shape* must synchronize before moving on to the next element.

**Comment by sithhell** [comment]
What's the status here? Can we close the PR and you open it again once everything is done?

**Comment by hkaiser** [comment]
@sithhell I'm working on this ...

**Comment by hkaiser** [comment]
@taeguk Before I close this PR without merging, does this contain anything you might be of value for your work?

**Comment by taeguk** [comment]
@hkaiser I don't refer the implementation in this PR.

**Comment by hkaiser** [comment]
Closing this unmerged as similar work is being done independently.

**Pull request closed without merging**
