### PR TITLE
Some fixes around hpx compute

### PR DESCRIPTION
**Pull request by atrantan**
This patch :
- Properly compiles the new cuda example `cublas_matmult`
- Fixes issue when `for_each` is used in Cuda code

### CODE REVIEW

**Comment by atrantan** [comment]
Got the error `fatal error: cuda_runtime.h: No such file or directory`. To keep it in c++ file. I suggest to call `include_directories` with `CUDA_INCLUDE_DIRS` (variable defined after using FindCuda in cmake)

**Comment by hkaiser** [comment]
@biddisco Are you happy with this patch?

**Comment by biddisco** [comment]
If you mean the patch from @atrantan, then no not really.  I didn't have time to look at what might cause the compilation problem and make the fix suggested, but I don't believe that using nvcc to compile is what we want here (or at least it's not what I wanted).

**Comment by atrantan** [comment]
@biddisco Is the patch now ok for you?

**Pull request merged**
