### PR TITLE
Adds a tool for inspect that checks for character limits

### PR DESCRIPTION
**Pull request by Bcorde5**
The first test is to see how circle tests handles the build, if successful, then I will fix the mistakes.  Comments and criticisms are welcome.

### CODE REVIEW

**Comment by K-ballo** [comment]
Would it be possible to except `#error` directives from this check?

**Comment by Bcorde5** [comment]
I suppose, let me work on it, and as long as that is the preferred result it could work.

**Comment by sithhell** [comment]
I think it would be a good idea to exclude these items:
 - CMakeLists.txt
 - docs
 - external source code

I am also not a big fan of a strict 80 characters line limit. I'd rather prefer to escape this limit occasionally. It's sometimes odd to just break a line because you are a few characters over the limit.

**Comment by hkaiser** [comment]
> I am also not a big fan of a strict 80 characters line limit. I'd rather prefer to escape this limit occasionally. It's sometimes odd to just break a line because you are a few characters over the limit.

Agreed. We settled on a hard 90 character limit for now (with 80 characters being a 'soft' limit as before). The main incentive for this rule is to ensure readability in any contexts (i.e. in diff-views on github, etc.)

**Comment by hkaiser** [comment]
> I think it would be a good idea to exclude these items:
> - CMakeLists.txt
> - docs
> - external source code

Sure, that can be done. Even if I think that files under our control should be slowly fixed to conform to this rule as it simplifies online reading, etc. For external code inspect can be disabled by simply placing a file named `hpx-no-inspect` into the base directory of the sub-tree which should not be checked.

**Comment by Bcorde5** [comment]
Yeah, the name of the branch was made before we agreed on the limit, the actual limit is set upon launch, with the default being 90.

**Comment by Bcorde5** [comment]
There seems to be a problem with giving circleci the option to choose the length of the limit, so for not it is going to be set at 90, only configurable in the inspect tool.  Please let me know if you still want to prompt circleci to set the limit.

**Comment by hkaiser** [comment]
> There seems to be a problem with giving circleci the option to choose the length of the limit, ...

@Bcorde5 Sorry, I don't understand what you mean by 'there seems to be a problem'.

**Comment by Bcorde5** [comment]
Disregard that last statement, I believe I have found a solution to the problem.

**Comment by Bcorde5** [comment]
I am going to make an exception for #define right now, if this seems troublesome, please let me know soon.  However, I have been running into some trouble trying to edit #define.

**Comment by hkaiser** [comment]
> I am going to make an exception for #define and #if right now, if this seems troublesome

Preprocessor directives have to be one a single line. However, you can use a single `\` at the end of the line to introduce line breaks into those:

    #define FOO \
        'this is what FOO expands to'

**Comment by Bcorde5** [comment]
Now that I have the grasp of how to use \, I can fix #define and #if, so only #error will be an exception, thank you.

**Comment by Bcorde5** [comment]
It has been decided that url links will be ignored by this check, as it would be too confusing if they were edited.

**Comment by Bcorde5** [comment]
Does anyone know what is causing the error?

**Comment by hkaiser** [comment]
@Bcorde5 just look at the circleci log here: https://circleci.com/gh/STEllAR-GROUP/hpx/1318

**Comment by hkaiser** [comment]
Thanks!

**Pull request merged**
