### PR TITLE
Remove indirection layer in at_index_impl

### PR DESCRIPTION
**Pull request by K-ballo**
Remove indirection layer in at_index_impl

### CODE REVIEW

**Review by aurianer — APPROVED** [review]
Thanks a lot!

**Review by hkaiser — APPROVED** [review]
Nice, thanks!

**Comment by msimberg** [comment]
Sigh... I'm really sorry @K-ballo. I've merged the wrong PR (meant to merge https://github.com/STEllAR-GROUP/hpx/pull/4972). This one still had some build issues on some of the GCC's. I've reverted the merge. Would you mind reopening this?

**Comment by msimberg** [comment]
@K-ballo I've opened #4976 with the branch `pack-tweaks-2` to save you the trouble of reopening this. Sorry again, I'm a dumbass.

**Pull request merged**
