### PR TITLE
Counter shortnames

### PR DESCRIPTION
**Pull request by devangb**
Adds flag hpx:print-counter-format with options: normal,csv,csv-short and flag hpx:no-csv-header

### CODE REVIEW

**Comment by hkaiser** [comment]
@devangb Our compliance checker is not happy with changes to two of the files: https://circle-artifacts.com/gh/STEllAR-GROUP/hpx/1063/artifacts/0/tmp/circle-artifacts.KWEuvY4/hpx_inspect_report.html. That is why your build is failing..

**Comment by devangb** [comment]
@hkaiser I am unable to get the error, turns out the lines it is pointing to for endline whitespaces are untouched by me, even lines around them.

**Comment by hkaiser** [comment]
@devangb You probably branched off your branch a long time ago (before we started to inspect our code for certain guidelines). You might want to rebase your branch against our master branch.

**Comment by hkaiser** [comment]
@devangb Thanks for your fixes. There is still one problem left inspect is complaining about: https://circle-artifacts.com/gh/STEllAR-GROUP/hpx/1076/artifacts/0/tmp/circle-artifacts.LzPMiAl/hpx_inspect_report.html. Once this has been corrected we can go ahead and merge your contributions to master.

**Comment by devangb** [comment]
@hkaiser fixed

**Comment by pagrubel** [comment]
Documentation should be added to the manual

**Comment by devangb** [comment]
@pagrubel I have added the documentation

**Comment by hkaiser** [comment]
LGTM!

**Comment by pagrubel** [comment]
I tested the functionality and it works fine. Read the source file of the document, but didn't build that. LGTM too

**Pull request merged**
