### PR TITLE
Variadic templates support for runtime_support and components

### PR DESCRIPTION
**Pull request by K-ballo**
Variadic templates support for runtime_support and components.

### CODE REVIEW

**Comment by sithhell** [comment]
Please readd the action_serialization_data constructors.

**Comment by sithhell** [comment]
transfer_action is tuplyfied again.

**Comment by sithhell** [comment]
I think the PR needs to be brought in line with latest master first.

**Comment by K-ballo** [comment]
Rebased, with no conflicts. Running tests again.

**Comment by sithhell** [comment]
functional::new_ is a little confusing. I was expecting it to call components::new_, not regular new. What do others think?

**Comment by sithhell** [comment]
Looks good otherwise!

**Comment by hkaiser** [comment]
> functional::new_ is a little confusing. I was expecting it to call components::new_, not 
> regular new. What do others think?

Letting it call the API instead of an internal function is the right thing to do, I believe.

**Pull request merged**
